### ISSUE TITLE
Generate docs for the core SDK

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#10]
Building docs for the core SDK might be different from generating docs for a random package. We should ensure that this tool works for internal and external docs.

**Comment by sethladd** [comment]
Should we close this?

**Comment by keertip** [comment]
fixed in #110

**Comment by alan-knight** [comment]
What does this do for e.g. dart:html. I was noticing that it's suppressed for analyzer tests because it gives errors. Or are the errors not enough to prevent analysis for doc generation purposes?
