### ISSUE TITLE
Ensure: two linked names in a doc comment are linked correctly

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#100]
Was: https://code.google.com/p/dart/issues/detail?id=16440

Docs: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:async.StreamSink

Source: https://github.com/dart-lang/bleeding_edge/blob/7cf5e8497e1cdad03213f8d46b6c99582fbb7eb1/dart/sdk/lib/async/stream.dart#L1466

Actual:

![screen shot 2015-01-12 at 2 17 37 pm](https://cloud.githubusercontent.com/assets/5479/5712278/c404e8ae-9a65-11e4-9bfa-fc3bb1c03fd0.png)

Expected:  done and Future are linked correctly.

**Comment by keertip** [comment]
Verified that done and Future link correctly.
