### ISSUE TITLE
For package docs: show the path to the documented library

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1000]
For instance, `shelf.io` is at `package:shelf/shelf_io.dart`, etc

While we'd like for folks to align the the library files and library names, there is no enforcement.

**Comment by sethladd** [comment]
dart: libraries have the same problem. the library name for dart:io is actually dart_io. Talk about confusing.

**Comment by jcollins-g** [comment]
So, for each library, show how to import it automatically as part of the library's docs?  Or do you want this data on the package page?

**Comment by kevmoo** [comment]
See
https://webdev.dartlang.org/angular/api/angular2.platform.common/angular2.platform.common-library

![screen shot 2017-05-15 at 7 53 47 pm](https://cloud.githubusercontent.com/assets/17034/26087837/3a3eda82-39a8-11e7-8e05-36d4290a7488.png)

I think we should list the library as "platform/common.dart" – which is the URI folks use after "package:angular2"

And here https://webdev.dartlang.org/angular/api/angular2.platform.common/HashLocationStrategy-class

![screen shot 2017-05-15 at 7 52 05 pm](https://cloud.githubusercontent.com/assets/17034/26087818/11202c5a-39a8-11e7-8f19-241e5ee46c2c.png)

angular2 -> platform/common.dart -> HashLocationStrategy

Seems a better idea.

Sound okay?

**Comment by devoncarew** [comment]
+1 to de-emphasizing or removing the library name, and instead using the path where the symbol is being defined in or exported from.
