### ISSUE TITLE
Sorting of members: Sort embedded numbers numerically.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dartdoc#1002]
See https://api.dartlang.org/1.12.2/dart-typed_data/dart-typed_data-library.html
The order is: `Uint16List`, `Uint32List`, `Uint64List`, `Uint8List`.
If names contain an embedded number, it's probably always better to sort the names so that embedded numbers counts as one "letter" which is sorted numerically. This will give the logical progression that the user expects.

**Comment by sethladd** [comment]
That would be a cool feature. Patches definitely welcome.

(you'd be surprised how much discussion there was around sorting of names)

**Comment by sethladd** [comment]
CL from @lrhn is up! https://codereview.chromium.org/1419553004/

**Comment by lrhn** [comment]
Fix landed.
