### ISSUE TITLE
"Library not documented" printed for libraries that are definitely documented

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#1004]
e.g. everything in Intl, test, or polymer. There are definitely doc comments on some of those libraries. What is it that it's looking for as documentation? And even if there weren't a library comment, it makes it look like there's no documentation at all, so people might ignore the hundreds of doc comments inside it.

**Comment by keertip** [comment]
thanks @alan-knight for the report! 

dupe #1005
