### ISSUE TITLE
Support searching for "Class.method"

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#1006]
Right now if you search for a member of the form `Class.method` (for example `List.add`), you get no results. It should instead give you the corresponding member, if one exists. This would be a really efficient way to get at the documentation for a member (like `add`) that has a lot of different implementations across a library.

**Comment by sethladd** [comment]
Hm, this should work in the latest dartdoc. (and the dev channel SDK)

![screen shot 2015-10-29 at 1 08 10 pm](https://cloud.githubusercontent.com/assets/5479/10830668/25ced77c-7e3e-11e5-9551-977656e097e2.png)

Please reopen if this isn't what you meant.

**Comment by nex3** [comment]
I was using the old SDK's docs but for the new ones this does work.
