### ISSUE TITLE
Table of contents should link to inherited members

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#1007]
Currently, there are no links in the table of contents for inhereted members (for example, [`Directory.exists`](https://api.dartlang.org/1.12.2/dart-io/Directory-class.html)). But it's still useful to be able to easily navigate to their documentation, regardless of where it is. It would be nice for the table of contents for these members to either navigate to the members on the page, or to link to the original definition in the superclass.

**Comment by keertip** [comment]
This has been fixed, but docs have not been regenerated. tracking it https://github.com/dart-lang/api.dartlang.org/issues/51
