### ISSUE TITLE
Missing what a class's superclass is

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1009]
For example: https://api.dartlang.org/1.13.0-dev.7.4/dart-io/File-class.html

I'd love to see what File extends.

Thanks!

**Comment by kevmoo** [comment]
It implements `FileSystemEntity` – this is just buried at the end of the dartdoc comment.

Is something else missing?
Or would you the super class info above the doc comment content?

**Comment by sethladd** [comment]
Ah ha! You're right. Happy to try alternatives, but not a big deal. Thanks for the help!

**Comment by sethladd** [comment]
Not intending to take action on this. But open to ideas for improvements.
