### ISSUE TITLE
link to `dart:` libaries

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1011]
Link to `dart:` libraries when they're referenced in the generated docs (using the https://api.dartlang.org address).

**Comment by sethladd** [comment]
Classes? methods? Just the libraries?

**Comment by devoncarew** [comment]
Classes and methods, in the same places we'd link to classes and methods from the package we're generating docs for.

**Comment by keertip** [comment]
dupe of #739
