### ISSUE TITLE
@Deprecated annotation shows up as raw HTML for static method

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1012]
https://api.dartlang.org/1.13.0-dev.7.6/dart-html/Element/internalCreateElement.html
![screen shot 2015-11-02 at 9 55 04 am](https://cloud.githubusercontent.com/assets/17034/10884764/d939638e-8147-11e5-9e2b-8c1e6ff99949.png)

**Comment by sethladd** [comment]
Good catch, thanks!

**Comment by kevmoo** [comment]
Just on the SDK with be4e3c5 and I still see this

![screen shot 2015-11-06 at 2 29 58 pm](https://cloud.githubusercontent.com/assets/17034/11010333/0a3d229c-8493-11e5-855e-b08d4f702c1c.png)

**Comment by keertip** [comment]
@kevmoo , the fix has to be published and added to sdk. tracking it #1024

**Comment by kevmoo** [comment]
That screen shot was from my machine running the latest bits with `--sdk-docs`.

@keertip Did you verify the issue is fixed when generating the SDK docs?

**Comment by kevmoo** [comment]
Woo hoo! Can we get a build out with these change? And then an update to DEPS in the SDK? Then a stable merge request? And then a pony. :smiley:
