### ISSUE TITLE
Ensure: Utf8Codec.fuse shows more specific parameterized type

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#102]
Was: https://code.google.com/p/dart/issues/detail?id=16113

Type hierarchy: Utf8Codec --> Encoding --> Codec<String, List<int>>  -->  Codec<S, T>

1) encode
Expected: List<int> encode(String input)
Actual: List<int> encode(S input)

2) fuse
Expected: Codec<String, dynamic> fuse(Codec<List<int>, dynamic> other)
Actual: Codec<String, dynamic> fuse (Codec<dynamic, dynamic> other)

Code: https://github.com/dart-lang/bleeding_edge/blob/7cf5e8497e1cdad03213f8d46b6c99582fbb7eb1/dart/sdk/lib/convert/utf.dart

API docs: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:convert.Utf8Codec

**Comment by keertip** [comment]
Verified. 

![screen shot 2015-05-05 at 5 27 58 pm](https://cloud.githubusercontent.com/assets/2192312/7485533/1c19401e-f34c-11e4-87f6-60ef3d07ca65.png)
