### ISSUE TITLE
Syntax highlight READMEs

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#1021]
Currently code blocks in package READMEs are not syntax highlighted, even when they are on GitHub and pub.dartlang.org (see the glob README on [dartdocs.org](https://www.dartdocs.org/documentation/glob/1.0.5/index.html) versus [GitHub](https://github.com/dart-lang/glob)).

**Comment by srawlins** [comment]
Some research, in terms of highlighting in the browser with JavaScript:

* I think that Google's [Prettify](https://github.com/google/code-prettify) is pretty popular. Probably used all over developer.google.com, etc.
* [Rainbows](https://craig.is/making/rainbows) is newer, I think, and pretty neat, but I don't think its yet popular.
* [Highlight.js](https://highlightjs.org/) is also very popular.

Aside from that, Pygments (Python) and Albino (Ruby) are the popular back-end tools (GitHub uses them).

**Comment by sethladd** [comment]
We use prettifier in dartdoc. Maybe you can use that?

**Comment by kevmoo** [comment]
Dupe of https://github.com/dart-lang/dartdoc/issues/1021

**Comment by kevmoo** [comment]
Er, https://github.com/dart-lang/dartdoc/issues/1016
