### ISSUE TITLE
"Extends" for generic types isn't shown.

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dartdoc#1027]
Take https://api.dartlang.org/stable/dart-collection/LinkedList-class.html
The generic type `E` must extend `LinkedListEntry`. However that is not shown in the documentation.
In fact the LinkedList-signature is:
`class LinkedList<E extends LinkedListEntry<E>> ...`

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by keertip** [comment]
@floitschG , the info about the generics is shown in the title.
![Uploading Screen Shot 2015-12-09 at 11.19.21 AM.png…]()

**Comment by floitschG** [comment]
Might be that the output changed, but it's not really great yet.

When I look for a constructor, I don't see the title anymore (I tried with my neighbor and he only found the generic type when I pointed out that the class is generic).
Also, the inheritance chain says that `Object > Iterable<E> > LinkedList` giving the impression that LinkedList isn't generic.
Finally, the title doesn't allow to click on the "LinkedListEntry". In fact the only place where "LinkedListEntry" is clickable is in the user-supplied dartdoc.

**Comment by keertip** [comment]
Would adding this information to the inheritance chain be sufficient?

**Comment by floitschG** [comment]
Probably sufficient, but you really want to see it with the constructors too. That's when you have to provide the generic type.
At the moment, the constructor doesn't show at all that there is a "hidden" additional argument.

**Comment by sethladd** [comment]
Apologies, I'm not fully understanding what the recommended fix is here.

I see that part of the solution is to change `Object > Iterable<E> > LinkedList` to `Object > Iterable<E> > LinkedList<E extends LinkedListEntry>`

**Comment by floitschG** [comment]
Yes. that would be a good start.

As a second step, we should improve the documentation for constructors:.
For example, https://api.dartlang.org/stable/1.22.1/dart-collection/LinkedList/LinkedList.html
There is no way to know that this constructor is on a class that takes a generic argument. We have 5 mentions of "LinkedList", but none shows "LinkedList<E extends ...>

**Comment by jcollins-g** [comment]
The navigation bar at the top displays the correct entry as of 0.14.1.

**Comment by jcollins-g** [comment]
Some screenshots for a proposed solution are in PR #1556.
