### ISSUE TITLE
Release 0.8.1

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1036]

**Comment by keertip** [comment]
https://codereview.chromium.org/1464883002/

**Comment by keertip** [comment]
Had to revert change due to build failures. Will look into it.

**Comment by kevmoo** [comment]
This *is* closed. We shipped 0.8.1. I think we're tracking this - https://github.com/dart-lang/sdk/issues/24996

**Comment by keertip** [comment]
Thanks! Reopened the wrong one.
