### ISSUE TITLE
Latest Dartdoc release has a bad type assertion

### ISSUE THREAD

**Issue by alxhub** [dart-lang/dartdoc#1039]
The problematic line: https://github.com/dart-lang/dartdoc/blob/master/lib/src/model.dart#L415
Log from Angular CI build showing the problem: https://travis-ci.org/angular/angular/jobs/92373133#L843

**Comment by keertip** [comment]
dupe of https://github.com/dart-lang/sdk/issues/25016. Angular is using dartdoc from the sdk
