### ISSUE TITLE
Ensure: Comparable's doc comments with [double.compareTo] is linked correctly

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#104]
Was https://code.google.com/p/dart/issues/detail?id=16181

Docs: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.Comparable

Source: https://github.com/dart-lang/bleeding_edge/blob/80988a506bdf74d2e87bf0d7e1211d035c2e5624/dart/sdk/lib/core/comparable.dart

Expected:

I should be able to type `The operators differ from [double.compareTo] on -0.0 and NaN.` and get it linked correctly.

**Comment by keertip** [comment]
Verified, can link to double.compareTo

![screen shot 2015-05-05 at 2 31 29 pm](https://cloud.githubusercontent.com/assets/2192312/7483396/81e64cb6-f333-11e4-841a-7418802a0d11.png)
