### ISSUE TITLE
generated dartdocs can't be cleanly unzipped on a Mac

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1045]
_From @skybrian on November 28, 2015 3:31_

To reproduce, download the 1.13.0 API docs from: https://www.dartlang.org/downloads/archive/

Unzip from the command line using "unzip".

The zip file contains files that differ only in case. On a Mac filesystem, this means you can't cleanly unzip the archive. It will complain about having to overwrite files:

replace gen-dartdocs/dart-web_gl/RenderingContext/VIEWPORT.html?
replace gen-dartdocs/dart-html/Window/defaultstatus.html? [y]es, [n]o, [A]ll, [N]one, [r]ename:
replace gen-dartdocs/dart-io/HttpHeaders/EXPIRES.html? [y]es, [n]o, [A]ll, [N]one, [r]ename: 
replace gen-dartdocs/dart-io/HttpHeaders/DATE.html? [y]es, [n]o, [A]ll, [N]one, [r]ename
replace gen-dartdocs/dart-io/HttpHeaders/host.html? [y]es, [n]o, [A]ll, [N]one, [r]ename:

_Copied from original issue: dart-lang/sdk#25056_

**Comment by kevmoo** [comment]
_From @sebe on November 29, 2015 11:30_

Just passing, interesting issue, I had no idea that Mac file system default was case insensitive or it could be an alias on your unzip command, like unzip -C .

I Can see the issue, using date as example in dart-io/HttpHeaders, when I go to the website I can see both html files with chrome.
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/DATE.html
Dart SDK dart:io HttpHeaders DATE CONSTANT DATE
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/date.html
Dart SDK dart:io HttpHeaders date PROPERTY date

A solution could be to put all the constants in a constant/constants directory
 dart-io/HttpHeaders/constants/DATE.html ,
dart-io/HttpHeaders/constants/date.html  or
dart-io/HttpHeaders/constant_date.html 

Don't know what effect this would have on tools if any.

**Comment by kevmoo** [comment]
@sebe It's not quite that simple. Dart allows any members to vary only by case. The fact that consts vs variables in this case is the issue doesn't generalize, sadly.

**Comment by sethladd** [comment]
When I originally looked at this question (how to scope names in a directory layout, and what effect case sensitivity has), I tried javadoc. That tool can also generate docs that overwrite themselves, when used on case-insensitive file systems.

**Comment by sebe** [comment]
As a linux user this is not an issue for me.
Seems to me, unless the api docs are restructured, offline access to api docs requires a case-sensitive file system.  

What is the practise in Google,
is it recommend/enforced that all software development be done on a case-sensitive file system?

Looking around android dev on mac os "we recommend that you always work with the AOSP source files on a case-sensitive filesystem" due to problems with git.
https://source.android.com/source/initializing.html#setting-up-a-mac-os-x-build-environment

**Comment by skybrian** [comment]
Hi, the original bug I filed isn't about fixing the general case. It's just about fixing the dartdocs packaged with the Dart SDK so that Mac users don't have a poor out-of-the-box experience.

Using a different filename for constants is enough to fix all the conflicts we have right now in the SDK, and makes future conflicts unlikely too.

**Comment by sebe** [comment]
There are only 2 occurrences for each, using .htm for the duplicate would make a unique case insensitive file name.
Mounting the zip archive as is a cool way to view offline, wonder if this is a solution for the mac.
" archivemount is known to work under both linux and Mac OS X (via MacFUSE)."
http://manpages.ubuntu.com/manpages/natty/man1/archivemount.1.html

Details of the duplicates.
find gen-dartdocs_v1.13.0 -name '*.html' | sort |tr '[:upper:]' '[:lower:]'| uniq -d -c
      2 gen-dartdocs_v1.13.0/dart-html/window/defaultstatus.html
      2 gen-dartdocs_v1.13.0/dart-io/httpheaders/date.html
      2 gen-dartdocs_v1.13.0/dart-io/httpheaders/expires.html
      2 gen-dartdocs_v1.13.0/dart-io/httpheaders/host.html
      2 gen-dartdocs_v1.13.0/dart-web_gl/renderingcontext/viewport.html

defaultstatus and defaultStatus are both PROPERTY which are Deprecated.
https://api.dartlang.org/1.13.0/dart-html/Window/defaultstatus.html
https://api.dartlang.org/1.13.0/dart-html/Window/defaultStatus.html

date, expires and host have a PROPERTY and a CONSTANT
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/date.html
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/DATE.html

https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/expires.html
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/EXPIRES.html

https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/host.html
https://api.dartlang.org/1.13.0/dart-io/HttpHeaders/HOST.html

viewport has a  METHOD and a CONSTANT
https://api.dartlang.org/1.13.0/dart-web_gl/RenderingContext/viewport.html
https://api.dartlang.org/1.13.0/dart-web_gl/RenderingContext/VIEWPORT.html

**Comment by keertip** [comment]
We should get this fixed for Mac users. Using a different file name for constants, as @skybrian  suggested, would work.

**Comment by sebe** [comment]
This won't help with

**Comment by sebe** [comment]
Cool, there will still be an issue with defaultstatus and defaultStatus, until at least one is removed.
defaultstatus and defaultStatus are both PROPERTY which are Deprecated.
https://api.dartlang.org/1.13.0/dart-html/Window/defaultstatus.html
https://api.dartlang.org/1.13.0/dart-html/Window/defaultStatus.html

**Comment by keertip** [comment]
Yes, it will not fix that. Hopefully since they are deprecated the problem will be resolved on its own soon :)

**Comment by sebe** [comment]
Hey @skybrian if you check out 1.14.0-dev.4.0 you see that html file names for constants are now like
gen-dartdocs/dart-io/HttpHeaders/DATE-constant.html
The only issue you will have is with defaultstatus and defaultStatus, both are deprecated, so you will get one error, until at least one is removed. Thanks dart team.

**Comment by skybrian** [comment]
Yes, good enough for me.
