### ISSUE TITLE
Ensure: link to a member that isn't in the class but is in an "interface" that it implements we can link to that instead.

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#105]
Was: https://code.google.com/p/dart/issues/detail?id=16712

For example in the File class, I'm trying to link to [parent] but it doesn't show up in the output as a link. Parent is inherited from  FileSystemEntity.

**Comment by keertip** [comment]
In dartdoc, parent shows up as a link, but the link is not correct. It should be a link to a method, and not a ref in the page FileSystemEntity.html#parent

**Comment by sethladd** [comment]
Looks like this is fixed!

Go to https://new-dartdocs-dot-dartlang-api.appspot.com/132549/dart-io/File-class.html

click "using the getter parent"

Goes to https://new-dartdocs-dot-dartlang-api.appspot.com/132549/dart-io/FileSystemEntity/parent.html

@keertip can you just triple check?
