### ISSUE TITLE
the committed generated sample is too large

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1052]
Related to https://github.com/dart-lang/dartdoc/pull/1051; It makes changes harder to review. We should instead commit a smaller generated sample.

**Comment by sethladd** [comment]
Are we going to change the generated sample? If not, we can close this. I agree with the suggestion, but not sure there's a concrete alternative.

cc @kevmoo

**Comment by kevmoo** [comment]
Here's the thing: it's really easy to add an example of feature "x" to the sample to validate it doesn't accidentally regress.

If we feel a feature is covered too many times, we can remove bit incrementally.
