### ISSUE TITLE
Ensure: All links are rendered in TransformerGroup

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#106]
Was: https://code.google.com/p/dart/issues/detail?id=17447

Docs: http://www.dartdocs.org/documentation/barback/0.15.2+2/index.html#barback/barback.TransformerGroup

Source: https://github.com/dart-lang/barback/blob/master/lib/src/transformer/transformer_group.dart

Expected: The doc comment `However, from the perspective of someone using a TransformerGroup, it works just like a Transformer.` should have the word Transformer linked.

Actual: The word Transformer is not linked in the rendered output.

**Comment by keertip** [comment]
See the same issue in dartdoc.

**Comment by keertip** [comment]
This is not a bug in dartdoc. Even though the class `Transformer` is included in the public api for barback, it is not imported into the library for class `TransformerGroup` and so cannot be linked to from this class.
