### ISSUE TITLE
Speed up dartdoc

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#1061]
Profiling dartdoc, a lot of time is taken by file io. This can be reduced by adding caching to dartdoc.

**Comment by sethladd** [comment]
Curious, what I/O does dartdoc do, that isn't through the analyzer?  (other than, of course, writing the files)

**Comment by keertip** [comment]
It is through the analyzer.  Analyzer reads the file every time dartdoc asks for doc comments (maybe source too), and this means multiple reads on the same file for the different elements in the file. dartdoc can do the io and cache the files, and use the source ranges from the analyzer to get to the element comments/source etc as needed, thus reducing io.

Also, adding the `<nodoc>` option meant processing the comment twice.

**Comment by sethladd** [comment]
wow, good analysis! Glad you tracked this one down.

Curious why reading doc comments doesn't go through the analyzer's cache.

**Comment by keertip** [comment]
The next version of the analyzer (> 0.27.1)  will cache the documentation comments, thus reducing io. dartdoc should upgrade to it once it is published.

**Comment by keertip** [comment]
Upgraded to analyzer which caches doc comments.
