### ISSUE TITLE
option to override the favicon

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1063]
Flutter would like a different favicon. Could we add an option to override it?

**Comment by sethladd** [comment]
cc @eseidel

**Comment by eseidel** [comment]
Presumably this is already possible using --header? I haven't tried.

**Comment by sethladd** [comment]
Header inserts a block of code into `<head>` but it doesn't override `<head>`. The favicon is already set, and it's hard coded. So, we'll need a graceful way to override that.

**Comment by keertip** [comment]
One more option :). Yes, we could add an option to override the favicon.

**Comment by eseidel** [comment]
We can also pretty easily post process the output directory to replace the
image. Not sure how common the need is or how much otber post processing
were going to need to do. Just depends on if we want to have a "flutter
docs" wrapper around dartdoc or not.

**Comment by sethladd** [comment]
Ideally, dartdoc is a tool that is customizable by frameworks. It's in scope to allow customization of favicon, imo.

**Comment by eseidelGoogle** [comment]
Presumably flutter (http://docs.flutter.io/flutter/) can now change:
https://github.com/flutter/flutter/blob/master/dev/dartdoc.dart#L45
to include favicon from https://github.com/flutter/website/blob/master/favicon.ico and our docs should look right. :D  Thanks @devoncarew!
