### ISSUE TITLE
Find libraries listed in _embedder.yaml for doc generation

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1067]
The Flutter engine (or sky_engine) package will provide dart: libraries, listed in the _embedder.yaml.  (See also https://github.com/dart-lang/sdk/issues/25011)

It would be really great if the dartdoc tool could find those libraries and generate docs for them, just like any other lib in the lib/ directory.

This is (probably?) blocking https://github.com/flutter/flutter/issues/998

Thanks!

**Comment by sethladd** [comment]
cc @pq

**Comment by pq** [comment]
Happy to help with this @keertip.  Just let me know!

**Comment by pq** [comment]
The corresponding bits landed in CLI in https://github.com/dart-lang/sdk/commit/3d3c9c5af46ffed91786672872006cba8581f533.  Crib-away! :smile:

**Comment by sethladd** [comment]
Yay! thanks for the head's up. This should make it easy for us to generate API docs for all dart: libraries provided by Flutter, to publish on docs.flutter.io.

**Comment by keertip** [comment]
Thanks @pq!
