### ISSUE TITLE
Properties aren't grayed/italicized in body, like they are in right nav

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1068]
Not sure if this is a bug or feature?

From http://docs.flutter.io/flutter/widgets/Padding-class.html

![screen shot 2015-12-19 at 10 14 31 am](https://cloud.githubusercontent.com/assets/5479/11914549/6bd1286a-a639-11e5-8376-e915ef6ad073.png)

![screen shot 2015-12-19 at 10 14 28 am](https://cloud.githubusercontent.com/assets/5479/11914552/6ffc813c-a639-11e5-9017-150db0af2dda.png)

**Comment by kevmoo** [comment]
In the body, we see "inherited" as text. On the right, faded/italic is the hint.

It is a "feature" – although happy to discuss.

**Comment by sethladd** [comment]
I'd be happy to see the names in the body italicized or grayed, fwiw.
