### ISSUE TITLE
'lib/src' excluded

### ISSUE THREAD

**Issue by d2m** [dart-lang/dartdoc#107]
A few questions to better understand your directions:

- is there a reason why files in ```lib/src``` are ignored
  https://github.com/dart-lang/dartdoc/blob/master/lib/src/io_utils.dart#L81

- which existing doc generator (any language) is similar to the dartdoc output

- how do you plan to organize links between different packages

thanks!

**Comment by a14n** [comment]
From [Pub Package Layout Conventions - Implementation files](https://www.dartlang.org/tools/pub/package-layout.html#implementation-files):

>You are free to import libraries that live in lib/src from within other Dart code in the same package (like other libraries in lib, scripts in bin, and tests) but you should never import from another package’s lib/src directory. **Those files are not part of the package’s public API**, and they might change in ways that could break your code.

**Comment by d2m** [comment]
@a14n thanks!

**Comment by keertip** [comment]
As @a14n pointed out, lib/src are internal to the package and will not be included in docs. So they are excluded by intention.

We are still working on the format of the docs, changes coming soon.  The linking between different packages also needs to be addressed.
