### ISSUE TITLE
Not linking to class in "implements" list

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1070]
http://docs.flutter.io/flutter/animation/ElasticOutCurve-class.html

![screen shot 2015-12-20 at 11 37 56 am](https://cloud.githubusercontent.com/assets/5479/11919686/2e6409e0-a70e-11e5-83b6-cebbd5b0f237.png)

**Comment by sethladd** [comment]
I think this is from dartdoc 0.8.4

**Comment by devoncarew** [comment]
Looks fixed, from looking at this page: http://docs.flutter.io/flutter/dart-core/List-class.html.

**Comment by devoncarew** [comment]
<img width="402" alt="screen shot 2016-07-20 at 10 08 39 am" src="https://cloud.githubusercontent.com/assets/1269969/16995585/f871590e-4e61-11e6-8402-44ed7884f665.png">

Looks like this has since been fixed.
