### ISSUE TITLE
Missing version in source of output

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1071]
Makes it harder to file bugs, can't refer to a specific version.

Check out view-source:http://docs.flutter.io/flutter/animation/CurvedPerformance-class.html

**Comment by kevmoo** [comment]
Check out the root of the package - view-source:http://docs.flutter.io/flutter/index.html

We did this to avoid crazy churn in every file when we generate docs

**Comment by sethladd** [comment]
OK, thanks for the tip.
