### ISSUE TITLE
Cannot generate docs for pkg/analyzer

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1072]
See
https://www.dartdocs.org/documentation/analyzer/0.27.1/log.txt
https://www.dartdocs.org/documentation/analyzer/0.27.1+1/log.txt

Seems related to `MultiplyInheritedPropertyAccessorElementImpl`

**Comment by kevmoo** [comment]
@keertip Is there any way to add a regression test?

**Comment by keertip** [comment]
yes, we can. opened #1076

**Comment by kevmoo** [comment]
Was that the issue that caused the crash?
