### ISSUE TITLE
Incorrect HTML escaping for const expressions

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1084]
For example:

![screen shot 2016-01-19 at 9 30 13 am](https://cloud.githubusercontent.com/assets/5479/12429673/650f4992-bea0-11e5-99d1-b8c647886b84.png)

From http://docs.flutter.io/flutter/material/material-library.html

Probably should be `const <int, List<BoxShadow>> {1 : const <BoxShadow> [` ...

**Comment by sethladd** [comment]
From dartdoc 0.8.4

**Comment by Hixie** [comment]
You can see this with kMaterialEdges now (same page).

**Comment by keertip** [comment]
Looks like `kMaterialEdges` is missing type information after the `const`. Is that it? Don't see the `const >` as in the screenshot by Seth.

**Comment by Hixie** [comment]
If you look at the HTML source you'll see there's unescaped HTML:
```html
          <div>
            <span class="signature"><code>const <MaterialType, double> {MaterialType.canvas : null, MaterialType.card : 2.0, MaterialType.circle : null, MaterialType.button : 2.0, MaterialType.transparency : null}</code></span>
          </div>
```

**Comment by eseidel** [comment]
This is presumably the line:
https://github.com/dart-lang/dartdoc/blob/master/lib/templates/_constant.html#L8
Unclear why it uses {{{ instead of {{, the 3 { makes it unescaped according to the mustache manual:
https://mustache.github.io/mustache.5.html

**Comment by devoncarew** [comment]
I think it needs to use the unescaped braces there because the constant string might have hyperlinks for some of the types referenced in it (`const Foo<double>()`).
