### ISSUE TITLE
Clipping text in header

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1086]
![screen shot 2016-01-15 at 10 11 53 am](https://cloud.githubusercontent.com/assets/5479/12430080/7a763bc2-bea2-11e5-93a5-1f7aff68c069.png)

Notice how the bottom of the `g` is clipped in the word "widgets".

**Comment by devoncarew** [comment]
Fixed here: https://github.com/flutter/flutter/pull/3196; we overrode the default styles for dartdoc, which I think caused this clipping issue.
