### ISSUE TITLE
reference to operators doesn't seem to be supported

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dartdoc#1087]
```dart
/// Class [MyClass]
/// constructor [new MyClass], 
/// operators don't seem to be supported  [MyClass.==], [operator ==], [==]
class MyClass {
  MyClass();

  bool operator ==(dynamic other) {
    return false;
  }
}
```

Are there any docs about Dart code comments?

See also http://stackoverflow.com/questions/34907717/how-to-refer-to-constructors-and-operators-in-dartdoc

**Comment by keertip** [comment]
Yes, it is https://www.dartlang.org/effective-dart/documentation/

**Comment by sethladd** [comment]
"operators don't seem to be supported" -- thanks for trying this out! Sounds like a bug.

I believe we get these references from the analyzer? I wonder if the issue is with analyzer or dartdoc.

**Comment by devoncarew** [comment]
Likely blocked by (and resolved by) https://github.com/dart-lang/sdk/issues/26929.

**Comment by devoncarew** [comment]
(assigning to myself for now)
