### ISSUE TITLE
don't link to exported name if original location is public and inside same package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1090]
Consider this layout:

```
lib/
  a.dart (which exports b.dart)
  b.dart
```

We would like the names from b.dart, which appear as part of a.dart, to linked to from b.dart (instead of appearing as they come from a.dart).

Today, the names from b.dart appear (in the URL) as if they are part of a.dart. Which is mostly true, because a.dart exports b.dart. But this is confusing to developers when a.dart's export of b.dart is simply a convenience for developers.

**Comment by sethladd** [comment]
I'm taking a look at this.

**Comment by sethladd** [comment]
Update: made a lot of progress on this over the weekend.

**Comment by Hixie** [comment]
This would be moot if we fixed https://github.com/dart-lang/dartdoc/issues/1158.
