### ISSUE TITLE
Export class from src library is not linked

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1091]
false alarm

**Comment by sethladd** [comment]
cc @kevmoo @keertip to confirm assumption here.

**Comment by keertip** [comment]
Yes, it should be documented if it is exported.

**Comment by keertip** [comment]
@sethladd, are you looking into this one too? If not, I can take a look.

**Comment by sethladd** [comment]
Yes, I'm taking a look. I might need to call for assistance :)

**Comment by keertip** [comment]
Thank you :)

**Comment by kevmoo** [comment]
Closed as not an issue? Or fixed?

**Comment by sethladd** [comment]
was a bug/me not understanding. Closed as "nothing to see here" :)
