### ISSUE TITLE
Document markup syntax

### ISSUE THREAD

**Issue by krisgiesing** [dart-lang/dartdoc#1098]
The main documentation doesn't mention what the markup syntax is.  I assume it's markdown, but what flavor?

**Comment by sethladd** [comment]
Good point! When you say "main documentation", where did you look? We need to fix all those places.

**Comment by krisgiesing** [comment]
https://github.com/dart-lang/dartdoc/blob/master/README.md or https://pub.dartlang.org/packages/dartdoc (I assume they're the same).

**Comment by krisgiesing** [comment]
I guess I missed the markdown section in https://www.dartlang.org/effective-dart/documentation/.

**Comment by sethladd** [comment]
I'll add a note about formatting to dartdoc's README. Thanks for pointing that out.

**Comment by sethladd** [comment]
Closed by https://github.com/dart-lang/dartdoc/commit/6b5a9949281956c3c80c8335d00959628221865a
