### ISSUE TITLE
[dev]: dartdoc error on analyzer-clean code

### ISSUE THREAD

**Issue by kegluneq** [dart-lang/dartdoc#1099]
Steps to repro:

1. Download [ng2dart_c7261c2.zip](https://github.com/dart-lang/dartdoc/files/126950/ng2dart_c7261c2.zip)
2. `mkdir repro && cd repro`
3. `unzip ng2dart_c7261c2.zip`
4. `pub get`
5. `dart --version        # should return 1.15.0-dev.2.0, otherwise adjust PATH`
6. `dartdoc --input=. --output=docs`

Result:
```bash
[error] 'const' variables must be constant value at <path>/lib/platform/testing/browser.dart, line 13.
[error] 'const' lists must have all constant values at <path>/lib/platform/testing/browser.dart, line 13.
[error] 'const' variables must be constant value at <path>/lib/platform/testing/browser.dart, line 20.
[error] 'const' lists must have all constant values at <path>/lib/platform/testing/browser.dart, line 20.
```

Some interesting notes:
* The analyzer reports hints about TODOs, deprecations, and unused vars, but nothing else.
* If line 6 is changed to omit `--input=.` i.e. `dartdoc --output=docs`, the operation succeeds

**Comment by keertip** [comment]
@kegluneq , the next dev release of the sdk will have the fixed dartdoc.
