### ISSUE TITLE
Display source code for methods or functions

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#11]
A developer should be able to view the source code for a method or function, in order to learn how the method or function is implemented.

We need to do something smart with abstract classes (like List).

**Comment by sethladd** [comment]
I've been looking at this. We can get the source code with `_method.computeNode().toSource()`, but there are at least three issues:

* we'll need to format it
* "native" or "external" functions are not clearly marked, so sometimes you see what looks like an empty method. For example:

![screen shot 2015-07-21 at 11 26 37 am](https://cloud.githubusercontent.com/assets/5479/8809114/5c723874-2f9b-11e5-9286-8af160f81905.png)


* the source code can contain implementation details that are not otherwise visible. For example:

![screen shot 2015-07-21 at 11 26 22 am](https://cloud.githubusercontent.com/assets/5479/8809107/53dc8eee-2f9b-11e5-9e13-cca5cfb5a621.png)

**Comment by sethladd** [comment]
Making progress:

![screen shot 2015-07-21 at 3 22 14 pm](https://cloud.githubusercontent.com/assets/5479/8813981/87aac9d6-2fbc-11e5-80ef-bd4c41a66c77.png)

**Comment by sethladd** [comment]
Little better:

![screen shot 2015-07-21 at 3 28 04 pm](https://cloud.githubusercontent.com/assets/5479/8814043/1b244e6c-2fbd-11e5-8f82-542e7a4968c3.png)

**Comment by devoncarew** [comment]
What about having the `source` section title styled the same as the other section headers? Classes, Libraries, Methods, ...

It would also be nice to try the source code left aligned with the title, rather than indented.

**Comment by sethladd** [comment]
> What about having the source section title styled the same as the other section headers? Classes, Libraries, Methods, ...

If you think they are of the same "type", then sure, we can do that.

> It would also be nice to try the source code left aligned with the title, rather than indented.

I agree, but I thought you wanted source code blocks to be indented? +1 for not indented here.

**Comment by sethladd** [comment]
source code is now aligned to the left.

**Comment by devoncarew** [comment]
I like the indenting for in-line code snippets. I do think we want some style difference between in-line snippets and method source. The indentation difference may be enough -

**Comment by sethladd** [comment]
Source is now displayed for functions and methods.
