### ISSUE TITLE
word "abstract" isn't showing on abstract method

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1104]
We might want to say "abstract" in the listing of methods, as well as the detail page. It's hard to know what we need to implement if I extend this class.

![screen shot 2016-02-24 at 4 53 57 pm](https://cloud.githubusercontent.com/assets/5479/13306283/446d19f6-db17-11e5-9918-0ec6d172ddbf.png)
![screen shot 2016-02-24 at 4 53 11 pm](https://cloud.githubusercontent.com/assets/5479/13306284/4470982e-db17-11e5-9de3-cd0fc441e55d.png)

**Comment by Hixie** [comment]
http://docs.flutter.io/flutter/material/RenderObjectWidget/createRenderObject.html is the link to what is shown above
