### ISSUE TITLE
Provide a way to reference a sample code

### ISSUE THREAD

**Issue by luisvt** [dart-lang/dartdoc#1105]
It would be cool if we have a way to reference sample code similarly to what is been achieved in angular2 docs using jade.

I think they use something like this:

```
:makeExample('url/to/sample/file', 'name-of-block')
```

it would be cool if we could add something like that to docs and then the html get autogenerated with sample code.

**Comment by sethladd** [comment]
Neat idea!

**Comment by keertip** [comment]
Angular2 uses the `@example` tag to indicate sample code that should be injected into the documentation.

dartdoc should provide support for recognizing  
<code>
@example core/pipes/ts/lowerupper_pipe/lowerupper_pipe_example.ts region='LowerUpperPipe'
</code>

and adding the sample code referenced to the documentation.

**Comment by keertip** [comment]
@sanfordredlich

**Comment by sanfordredlich** [comment]
Thanks, it would be great to also have it create a log of @example entries it was not able to find on the file system, so we can ensure that they are created. This will make creating the documentation much more efficient.

**Comment by chalin** [comment]
@keertip et all: FYI, I'll soon be looking into completing the implementation of this feature. Let me know if there are any objections and/or words of advice.

**Comment by keertip** [comment]
@chalin , sounds good! 
Currently dartdoc has support for finding `@example` tags and looking for the files associated with it, and prints out a message if it is not found. The reading and injecting the example is what needs to be implemented.
