### ISSUE TITLE
embedder_libs is now embedding_libs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1106]
In https://github.com/dart-lang/dartdoc/blob/master/test_package_embedder_yaml/lib/_embedder.yaml

The key is now "embedded_libs".

**Comment by sethladd** [comment]
(marked as P1 because this blocks flutter from generating docs)

cc @johnmccutchan @keertip @kevmoo

**Comment by keertip** [comment]
So how urgent is this? The last dev roll for 1.15 is early next week.

**Comment by sethladd** [comment]
We can install a random version of dartdoc on our Travis CI bots. We'd like this fixed immediately, and pushed to pub. But you don't need to get into 1.15 unless you want to. Thanks!

**Comment by sethladd** [comment]
Fixing this may fix https://github.com/dart-lang/dartdoc/issues/1107

**Comment by johnmccutchan** [comment]
I don't think it will fix #1107

**Comment by johnmccutchan** [comment]
Also, I think this issue will be fixed by using a newer version of the analyzer package.

**Comment by sethladd** [comment]
We still need to change the key name, though?

**Comment by johnmccutchan** [comment]
Yes, just the name in the test.

**Comment by keertip** [comment]
@johnmccutchan , the analyzer version to be used is ^0.27.2.

**Comment by johnmccutchan** [comment]
To clear up confusion:

1) The analyzer version is fine. 
2) The test package `test_package_embedder_yaml` is using the old key "embedder_libs" it should be using "embedded_libs".

The fact that the test has been passing suggests it is a buggy test.

**Comment by sethladd** [comment]
Thanks! Can you let us know when you publish 0.9.1 to pub? We need to update our build scripts to use the newest version.

**Comment by keertip** [comment]
Will do. Looks like @johnmccutchan  has a fix for #1107, waiting for that.

**Comment by johnmccutchan** [comment]
https://github.com/dart-lang/dartdoc/pull/1109 is ready

**Comment by keertip** [comment]
0.9.1 has been published.

**Comment by sethladd** [comment]
Thanks so much! I'll file an issue to use this version when generating docs for Flutter.
