### ISSUE TITLE
You must run 'pub get' before generating docs for sky_engine

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/dartdoc#1110]
If you just download the sky_engine package directly and run dartdoc you get no documentation. If you first run `pub get` and then run dartdoc documentation is generated.

**Comment by keertip** [comment]
dartdoc will not run pub get, it does not know whether the there is a .packages file etc. It just looks for one. The user/build script should setup the package.

**Comment by sethladd** [comment]
Maybe we could print something if dartdoc determines it can't generate docs ? Or, is that not something it could determine?

**Comment by johnmccutchan** [comment]
@keertip The issue is what kind of behaviour dartdoc should have if there is no .packages file. For example, we could let the user know.

**Comment by keertip** [comment]
We could print out a message if no resolver can be setup up for package: uris.

**Comment by sethladd** [comment]
I ran into this, too. No errors or warnings, just telling me zero libraries. Wasn't clear how to diagnose or debug.

```
~/Code/flutter/bin/cache/pkg/sky_engine[master] $ dartdoc
Generating documentation for 'sky_engine' into /Users/sethladd/Code/flutter/bin/cache/pkg/sky_engine/doc/api/

Parsed 0 files in 0.2 seconds.

documenting sky_engine
Documented 0 libraries in 0.4 seconds.

Success! Docs generated into /Users/sethladd/Code/flutter/bin/cache/pkg/sky_engine/doc/api
```
