### ISSUE TITLE
dartdoc shouldn't care about missing dart:_internal or dart:nativewrappers

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/dartdoc#1111]
These are VM private libraries with no SDK definition. dartdoc dies if you don't include dummy versions:

```yaml
embedded_libs:
  "dart:_internal": "empty.dart"
  "dart:nativewrappers": "empty.dart"
```

**Comment by keertip** [comment]
Is there an exception?

**Comment by johnmccutchan** [comment]
@keertip These libraries are purely private and have no SDK interface but are included by SDK interface sources. Without the `dart:_internal` and `dart:nativewrappers` entries in `embedded_libs` import errors are generated because dartdoc can't find the two libraries. What I'm suggesting here is that dartdoc do the following:

1) Insert empty libraries for 'dart:_internal' and 'dart:nativewrappers'.
2) Not to generate documentation for 'dart:_internal' or 'dart:nativewrappers'.

**Comment by keertip** [comment]
@johnmccutchan , could you add steps to repro?

In the case of the SDK, dartdoc gets all the library info from the analyzer, and it is clearly defined which ones are public/private etc. Maybe the analyzer has information that dartdoc can use when the core libraries are defined in the _embedder.yaml. Will need to take a look.

**Comment by johnmccutchan** [comment]
reproduction steps:

- check out flutter/engine
- build dist
- remove lines for 'dart:_internal' and 'dart:nativewrappers' 
- run dartdoc in the built engine package.

**Comment by keertip** [comment]
Unfortunately, not much dartdoc can do here. It is the analyzer that fails if there are no definitions for dart:_internal and dart:nativewrappers. These libraries are accessed in dart:ui and maybe other flutter libraries, so analysis fails if they are not defined.

And without analysis, docs cannot be generated.
