### ISSUE TITLE
Subclass property incorrectly reported as write-only

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#1116]
In the following code:

``` dart
class Super {
  get foo {}
  set foo(_) {}
}

class Sub extends Super {
  set foo(_) {}
}
```

The documentation for `Sub` claims that `foo` is write-only, despite it extending `Super` and thus supporting `Super.foo` as a readable property.

This has comes up in practice with the [`LineScanner`](https://www.dartdocs.org/documentation/string_scanner/0.1.4+1/string_scanner/LineScanner-class.html) class, whose `position` field is documented as write-only despite extending `SpanScanner`. It's also worth noting that `LineScanner.position` fails to inherit the documentation for `SpanScanner.position`, although this is probably just the same issue.

**Comment by jcollins-g** [comment]
This is now fixed with #1466.
