### ISSUE TITLE
String scanner documentation pages fail to load

### ISSUE THREAD

**Issue by kg** [dart-lang/dartdoc#1117]
Visiting https://www.dartdocs.org/documentation/string_scanner/latest/string_scanner/SpanScanner-class.html in Firefox or Edge on my machine yields a blank white page with no title. The same is true for every other link in the package I've tried, including the top level - https://www.dartdocs.org/documentation/string_scanner/latest/index.html .

Other packages appear to have working documentation and the main top level site works.

The blank response in this case appears to be a HTTP 200 with a mostly empty body (374 bytes, looks like just some script).

**Comment by sethladd** [comment]
Hi, thanks for contacting us.

Do other docs work for you?

Does this page work for you? https://www.dartdocs.org/documentation/string_scanner/0.1.4+1/index.html

Do the docs load in Chrome for you?

**Comment by kg** [comment]
Hi Seth,

The other things I tried worked. Browsed around the top-level briefly and picked a random package and clicked through and it seemed fine.

That versioned URL (0.1.4+1) works here in Firefox.

In Chrome, ```https://www.dartdocs.org/documentation/string_scanner/latest/string_scanner/SpanScanner-class.html``` appears to redirect to ```https://www.dartdocs.org/documentation/string_scanner/0.1.4+1/string_scanner/SpanScanner-class.html```. Not sure why the redirect doesn't work in other browsers... just tried it again in FF and it's still not working. :/

**Comment by keertip** [comment]
I am seeing the same - the redirect is not working in FF. 

@sethladd , any ideas?

**Comment by sethladd** [comment]
I think @kevmoo and @nex3 diagnosed it in another issue?

**Comment by kevmoo** [comment]
This issue is specific to dartdocs.org - https://github.com/astashov/dartdocs.org/issues/28
