### ISSUE TITLE
Can't refer to identifiers that aren't imported

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1124]
This document:
   http://docs.flutter.io/flutter/rendering/rendering-library.html
...mentions a bunch of classes in the text at the top which are listed in the sidebar but for some reason there are no links.

(I can't just import the relevant files because then the analyzer would complain about unused imports.)

**Comment by pq** [comment]
May be best filed as an analyzer bug since it has to do with how we calculate unused imports.

cc @scheglov @bwilkerson

**Comment by scheglov** [comment]
https://codereview.chromium.org/1850813002

**Comment by scheglov** [comment]
https://github.com/dart-lang/sdk/commit/498c77ef510963a9de6e27c1db1f22987dcdf4c0

**Comment by Hixie** [comment]
So the fix on our side now is to just import the things we're mentioning?

**Comment by Hixie** [comment]
Thanks!

**Comment by scheglov** [comment]
@Hixie Yes, I think you can add new imports now.
I don't know for sure how `dartdoc` works, maybe @keertip can clarify whether references in comments are supported.
