### ISSUE TITLE
Support searching via URL

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#1126]
I'd like to set up a Chrome search handler to search the Dart core library APIs, but currently this isn't possible because there's no way to construct a URL for a search query. It would be great to support something like this.

One possibility for an easy implementation that avoids the need for a search results page:

* When a DartDoc page first loads, check for the presence of a query parameter named "search".
* If such a parameter exists, find the first autocomplete result that would be chosen if the search string were typed in the search bar.
* If there is such a result, navigate to its page.

**Comment by sethladd** [comment]
Sounds great!
