### ISSUE TITLE
dartdoc garbles the signature of methods that take callbacks

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1137]
Consider e.g. <http://docs.flutter.io/flutter/animation/CurvedAnimation-class.html>:

```
addListener(VoidCallback listener()) → void
Calls the listener every time the value of the animation changes.
inherited
```

This implies that `addListener` takes a no-argument method that returns a `VoidCallback`. This is false. It takes a `VoidCallback`, which is a typedef that has no arguments and returns void.

Similarly:

```
addStatusListener(AnimationStatusListener listener(AnimationStatus status)) → void
Calls listener every time the status of the animation changes.
inherited
```

...is wrong, because that's not at all the signature of that method. It takes an `AnimationStatusListener`, not a method that returns `AnimationStatusListener`.

**Comment by eseidel** [comment]
I believe this is the codepath:
https://github.com/dart-lang/dartdoc/blob/b2f61f7ed68657f2da441d1eaf7b543d00efd2a9/lib/src/model.dart#L1498

**Comment by eseidel** [comment]
Yeah, I think this part is just wrong for typedef args:
https://github.com/dart-lang/dartdoc/blob/b2f61f7ed68657f2da441d1eaf7b543d00efd2a9/lib/src/model.dart#L1509
and should be skipped.  I'd need to write a unittest and fiddle to see.
