### ISSUE TITLE
[Feature] Fuzzy search

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#114]
_From @vicb on January 28, 2014 12:39_

[DevDocs.io](http://devdocs.io/help) support fuzzy search, ie if you type `tls`, `tols`, `tlstr` ..you'll see `toLocaleString()` show up in the auto-complete.

Once again I can contribute this feature **IF** I get some feedback.

_Copied from original issue: dart-lang/dartdoc-viewer#16_

**Comment by keertip** [comment]
Not planned for now
