### ISSUE TITLE
Formatting issue of code blocks with newlines in HttpRequest docs

### ISSUE THREAD

**Issue by DanTup** [dart-lang/dartdoc#1148]
I don't know if this is a dartdoc issue, but figured if not you can point where it should go...

On the docs page for [HttpRequest](https://api.dartlang.org/1.12.0/dart-io/HttpHeaders-class.html) the formatting of code for setting the `CACHE_CONTROL` header (which has a linebreak in the source) comes out incorrectly (`pre` tag is closed on first line).

Not sure if the error is the source code (the second line doesn't start with a `*`) or dartdoc.

![screenshot 2016-04-13 at 19 37 41](https://cloud.githubusercontent.com/assets/1078012/14505088/8c9993d0-01af-11e6-8f2d-86d2801d8a4a.png)

**Comment by devoncarew** [comment]
Hey! Sorry for the delay. This looks like an issue with the source file itself - perhaps open an PR against the https://github.com/dart-lang/sdk repo? Thanks for the report!

**Comment by DanTup** [comment]
[Done](https://github.com/dart-lang/sdk/pull/26937)!
