### ISSUE TITLE
source code shown for methods but not getters or constructors

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dartdoc#1150]
It would be nice if the dartdoc more consistently showed the source code.

Example with source:
https://www.dartdocs.org/documentation/source_span/1.2.2/source_span/SourceSpanMixin/message.html

Examples without source:
https://www.dartdocs.org/documentation/source_span/1.2.2/source_span/FileSpan/FileSpan.html
https://www.dartdocs.org/documentation/source_span/1.2.2/source_span/FileSpan/file.html

**Comment by Hixie** [comment]
I've noticed this on the Flutter docs too. Seeing the source is sometimes really useful, so the more we could show the better.
