### ISSUE TITLE
For Flutter docs, be more aggressive about including dependencies

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1159]
Right now we don't export all of vector_math in the Flutter docs, but we do export Matrix4. This results in Matrix4 being documented, but the types that _it_ uses not being documented.

We should, IMHO, have a way to tell dartdoc that we want to include the documents for _all_ our dependencies, with dartdoc automatically following the imports to find everything that's mentioned and documenting them all.

See also:
- https://github.com/dart-lang/dartdoc/issues/1158 (about not including reexported types twice)

cc @devoncarew

**Comment by astashov** [comment]
I will look at it

**Comment by astashov** [comment]
So, how will it look like? We provide additional argument to the `dartdoc` script, like `dartdoc --include-all-dependencies`, and it will first go through all the dependencies we tell it to document (i.e. libs of the current package + all the `--include-external`s), and if it finds some symbols from some libraries are undocumented, it will add those libraries to the list of documentable libs? Something like that?

**Comment by Hixie** [comment]
Sounds good to me.
