### ISSUE TITLE
Improve page titles

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#116]
_From @kwalrath on April 4, 2014 1:2_

I'm very happy that we now have dynamic page titles, but I think we can improve them. (I originally wrote this as a comment on #22, so you might experience deja vu.)

The title (of https://api.dartlang.org/apidocs/channels/stable/#dart-core.Expando, for example) is a little odd:
dart-core.Expando API Docs

I'd like something like this:
**Expando (dart:core) API Reference**

The most important info is on the left (where it's more likely to be visible in the tab), and there's a : instead of a - after "dart".

Here's an example of a more deeply nested API: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/html5lib/dom_parsing.CodeMarkupVisitor

The title is now:
html5lib/dom_parsing.CodeMarkupVisitor API Docs

It might be more helpful as:
**CodeMarkupVisitor (html5lib/dom_parsing) API Reference**

(I'm not sure about `/` vs `.` as a separator. Also, "Reference" is a little more informative than "Docs", but perhaps not worth the extra characters.)

_Copied from original issue: dart-lang/dartdoc-viewer#24_

**Comment by sethladd** [comment]
_From @caffinatedmonkey on April 4, 2014 13:41_

I don't see the point of using **API Reference** or **API Docs**. Where else would the page title look like `Expando (dart:core)`? I think the whole **API Reference/Docs** is unnecessary.

**Comment by sethladd** [comment]
_From @kwalrath on April 4, 2014 14:41_

The point would be to differentiate between auto-generated API reference docs and other web pages/sites. Remember, you might see these page titles in a tab or in Google+ or in a list of bookmarks. Although the tabs will show only the first few letters, the others have more space, so it doesn't hurt to add clarification so readers get more context. 

For example, various Zone docs might look like this:

**dart-async.Zone** (api.dartlang.org now)
**Zone (dart:async) | Dart API Reference** (api.dartlang.org in the future?)
**Zones | Dart: Structured web apps** (article at https://www.dartlang.org/articles/zones/)

pub.dartlang.org is also relevant, and it has titles like this:

**barback 0.12.0 | Pub Package Manager**

Of course, everything following the API name should be configurable. In the Zone case, the "Zone (dart:async)" would be auto-generated (although perhaps configurable somehow), and the " | Dart API Reference" would be set using a docgen option (and perhaps blank if not set).

**Comment by sethladd** [comment]
_From @caffinatedmonkey on April 4, 2014 14:55_

Great idea :D

**Comment by sethladd** [comment]
_From @kwalrath on April 4, 2014 14:56_

:)

**Comment by sethladd** [comment]
Dupe of https://github.com/dart-lang/dartdoc/issues/118 ?

**Comment by sethladd** [comment]
Suggest a strategy of Most specific -- Less specific.

e.g.

`Method - Class - Library - Package | Dart API docs`

**Comment by kwalrath** [comment]
That makes sense to me.

**Comment by sethladd** [comment]
Closing. We have "most specific" to "least specific" titles, with names and type (package, library, method), etc.

Certainly reopen if we can tweak further.
