### ISSUE TITLE
Embeded HTML templates from Angular2 components are not escaped

### ISSUE THREAD

**Issue by Tomucha** [dart-lang/dartdoc#1162]
This is my source code (fragment):

```
@Component(
    selector: 'form-file-input',
    template: r'''
<div class="row">
    <div class="file-field input-field col s11">
      <div class="btn">
        <span>{{label}}</span>
       ... truncated ...
</div>
''')
class FormFileInput implements OnInit, AfterViewInit {
  static int counter = 0;
  ... etc 

```

And this is the result:
![image](https://cloud.githubusercontent.com/assets/2655576/15384916/48ab1116-1d9e-11e6-83cd-f2434930231d.png)

Probably similar (duplicate?) to https://github.com/dart-lang/dartdoc/issues/1084
dartdoc version: 0.9.0

**Comment by jcollins-g** [comment]
That's epically ungood, but should be easy enough to correct.

**Comment by jcollins-g** [comment]
[This branch](https://github.com/dart-lang/dartdoc/tree/1268-display-annotations-on-field) has been updated with a fix for this, waiting on an analyzer release.
