### ISSUE TITLE
No doc generated. (Linux)

### ISSUE THREAD

**Issue by Songbird0** [dart-lang/dartdoc#1166]
Hi !

While some hours, I'm trying to generate my project doc, but it don't work... (0 parsed files)
My pubspec.yaml:
name: random
dependencies:
  js: ^0.3.0
  intl: ^0.12.4
environment:
  sdk: ">=1.16.0"

Do you know where is my error ? Or it's a bug ?

Thanks for advance !

Songbird.
![screenshot - 27052016 - 10 12 06](https://cloud.githubusercontent.com/assets/13397428/15602093/7ff8ea16-23f3-11e6-9e76-c211698ab9dd.png)

**Comment by keertip** [comment]
Hi! Were you able to generate the docs?

**Comment by Songbird0** [comment]
Hello,
My topic has been moved [here](https://github.com/dart-lang/sdk/issues/26566).

Thanks for your answer ! :)
