### ISSUE TITLE
Generation failed: Class '_HashMap<Folder, YamlMap>'

### ISSUE THREAD

**Issue by rayk** [dart-lang/dartdoc#1168]
Consistently having this problem. 

**Environment** 
Dart VM version: 1.17.0-dev.6.0 (Thu May 26 12:22:23 2016) on "macos_x64"

Generation failed: Class '_HashMap<Folder, YamlMap>' has no instance getter 'urlMappings'.

NoSuchMethodError: method not found: 'urlMappings'
Receiver: Instance of '_HashMap<Folder, YamlMap>'
Arguments: []
dart:core                                                                               Object.noSuchMethod
package:analyzer/source/embedder.dart 222                                               EmbedderUriResolver.length
package:dartdoc/dartdoc.dart 148                                                        DartDoc._parseLibraries
package:dartdoc/dartdoc.dart 88                                                         DartDoc.generateDocs.<async>
===== asynchronous gap ===========================
dart:async                                                                              _Completer.completeError
package:dartdoc/dartdoc.dart 129                                                        DartDoc.generateDocs.<async>
===== asynchronous gap ===========================
dart:async                                                                              Future.Future.microtask
package:dartdoc/dartdoc.dart                                                            DartDoc.generateDocs
/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 130  main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                                                     Chain.capture
/b/build/slave/dart-sdk-mac-dev/build/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart 129  main.<async>
dart:async                                                                              _SyncCompleter.complete
package:dartdoc/dartdoc.dart 49                                                         initGenerators.<async>
dart:async                                                                              _SyncCompleter.complete
package:dartdoc/src/html/html_generator.dart 62                                         HtmlGenerator.create.<async>
dart:async                                                                              _SyncCompleter.complete
package:dartdoc/src/html/templates.dart 108                                             Templates.create.<async>
dart:async                                                                              _SyncCompleter.complete
package:dartdoc/src/html/templates.dart 91                                              Templates.create.<async>._loadTemplate.<async>
dart:async                                                                              _SyncCompleter.complete
package:dartdoc/src/html/resource_loader.dart 22                                        loadAsString.<async>
dart:async                                                                              _SyncCompleter.complete
package:dartdoc/src/html/resource_loader.dart 33                                        loadAsBytes.<async>

**Comment by devoncarew** [comment]
Thanks for the report! This is fixed in the latest (not yet released) dev SDK.
