### ISSUE TITLE
Can't see the complete docs of an enum's values

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1169]
Consider for instance:
http://docs.flutter.io/flutter/dart-ui/BlurStyle-class.html

How do I see the complete docs for `normal`?

**Comment by sethladd** [comment]
Thanks, good catch!

**Comment by devoncarew** [comment]
fixed by https://github.com/dart-lang/dartdoc/pull/1181

**Comment by Hixie** [comment]
Does that fix also work for multi-line descriptions? e.g.:
https://github.com/flutter/engine/blob/master/flutter/lib/ui/painting.dart#L169
http://docs.flutter.io/flutter/dart-ui/FilterQuality-class.html

Right now, clicking on the enum values doesn't take you to a per-identifier doc like clicking on a method or property normally would.

**Comment by devoncarew** [comment]
It doesn't; I considered that but though that multi markdown paragraph descriptions of enums would be unlikely :)

I'll open another issue.

**Comment by Hixie** [comment]
We don't mess around with our documentation. :-D

I have plans to have entire diagrams for some of the enum values. :-)
