### ISSUE TITLE
inheritance structure seems inaccurate

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#117]
_From @sethladd on September 4, 2014 0:10_

From ccala...@google.com on June 22, 2014 02:11:31

URL: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/analyzer/analyzer.NodeList#id_any Issue:
for NodeList, it says "extends Object".
but then, for various methods and fields, e.g. "any" and "iterator", it says "inherited from analyzer".
that makes no sense. analyzer isn't a class, so you can't inherit from it.
furthermore, i think NodeList inherits from ListMixin, so why don't i get to see that in the docs?

i have a feeling this is a bug in the doc generator.

Original issue: http://code.google.com/p/dart/issues/detail?id=19600

_Copied from original issue: dart-lang/dartdoc-viewer#32_

**Comment by sethladd** [comment]
See https://github.com/dart-lang/www.dartlang.org/issues/899

**Comment by keertip** [comment]
Verified. dartdoc shows mixin and no extends.
