### ISSUE TITLE
Show the full documentation for enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1186]
Related to https://github.com/dart-lang/dartdoc/issues/1169, we need to show the full doc for enums, not the first-line summary.

**Comment by eseidelGoogle** [comment]
The fix may be as simple as changing:
https://github.com/dart-lang/dartdoc/blob/master/lib/templates/_constant.html#L6
from {{ oneLineDoc }} to {{ documentation }}. I haven't checked all the places where {{<constant}} is referenced yet to know if that would be OK though.
