### ISSUE TITLE
Where can I find dartdoc contribution instructions?

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/dartdoc#1191]
I'm interested in making changes to dartdoc, but would like to do them correctly.

I learned from @devoncarew's recent PR: https://github.com/dart-lang/dartdoc/commit/8e7d638aacd30dd73df047f9d318812fffa3eb96 that there is a changelog to update as well as some sort of baseline tests to regenerate?

Are these instructions documented?  I couldn't find them in README.md or CONTRIBUTING.md or the wiki, but I may not have looked in the right places.  Thanks!

@keertip

**Comment by devoncarew** [comment]
We should update https://github.com/dart-lang/dartdoc/blob/master/CONTRIBUTING.md, but the short answer is:
- when a change is user-facing, we should add a new entry to the changelog
- you can run the tests via `dart test/all.dart`
- to re-gen the test library docs run `grind update-test-package-docs` (the grind tool can be installed by `pub global activate grinder`; other options can be discovered by `grind -h`)
- travis will complain if your code doesn't match the dartfmt output; you should `dartfmt -w` any changed files (or whole directories)

**Comment by eseidelGoogle** [comment]
Thank you very much. :)
