### ISSUE TITLE
Make `dartdoc` strong-mode clean.

### ISSUE THREAD

**Issue by pq** [dart-lang/dartdoc#1205]

**Comment by pq** [comment]
A challenge here is the following idiom:

```
class Field extends ModelElement
    with GetterSetterCombo
```

where ModelElement defines a bunch of fields that are *overridden* by getters in the `GetterSetterCombo` mixin.  I don't see a neat way to address this without some significant refactoring.

Curious how folks have navigated this elsewhere...  @leafpetersen, @jmesserly  ?

**Comment by jmesserly** [comment]
make it a getter and/or setter in the base class (ModelElement). I couldn't tell which field was overridden in a quick glance, but depending on the field, you may also be able to restructure the code to avoid an orphaned storage slot.

(it's a lot like what you would do in Java/C#, where fields cannot be overridden.)

**Comment by pq** [comment]
> make it a getter and/or setter in the base class 

Hey, you know, that might just work. 👍   Thanks!

**Comment by jmesserly** [comment]
🎉
