### ISSUE TITLE
Search results referable by URL to enable custom search engine from Chrome

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#121]
Was: https://github.com/dart-lang/dartdoc-viewer/issues/65

Look into becoming a custom search engine for Chrome. We think this starts by having a URL that refers to a specific search.

See also #7

**Comment by sethladd** [comment]
Not planned anymore. May return to this.

**Comment by Levi-Lesches** [comment]
I know this is an old thread, but Flutter and Flutter have this: 
```
https://api.flutter.dev/?search=SearchTerm
https://api.dart.dev/stable/2.7.2/index.html?search=SearchTerm
```

Is this built-in to DartDoc or did they do something special?
