### ISSUE TITLE
Logo in footer incorrectly links to dartlang.org

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1226]
Looks like dartdoc is hard-coding the logo to static-assets/favicon.png, and then using `alt="Dart"`, and linking to dartlang.org.

For Flutter, the favicon.png is the flutter logo.

Can dartdoc not link to dartlang.org from the logo in the footer, and not have a hard-coded alt attribute?

**Comment by srawlins** [comment]
No more logos in the footer. [Flutter](https://docs.flutter.io/flutter/material/AboutDialog-class.html). [Pub](https://pub.dartlang.org/documentation/analyzer/latest/analyzer.dart.ast.ast/analyzer.dart.ast.ast-library.html). [Dartlang](https://api.dartlang.org/dev/2.0.0-dev.64.0/dart-io/HttpServer/bind.html).
