### ISSUE TITLE
Incorrect output printed at end of generation

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1227]
I see this message when dartdoc is finished: "Success! Docs generated into /Users/sethladd/Code/flutter/dev/docs/doc/api"

However, the docs were generated into "dev/docs/doc"

Looks like we have an assumption built into the "Success!" message?

**Comment by jcollins-g** [comment]
I think this behavior is likely as intended.

dartdoc resolves to an absolute path for displaying its messages, which is why you see "/Users/sethladd..." prepended.  The subdirectory "api" is added by default if you don't specify an output directory with --output_dir.

How are you invoking dartdoc?

**Comment by jcollins-g** [comment]
Closing due to perceived lack of interest.
