### ISSUE TITLE
Ensure: generics on typedefs are displayed

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#123]
Was https://github.com/dart-lang/dartdoc-viewer/issues/35

**Comment by keertip** [comment]
Verified.

**Comment by chalin** [comment]
The generic parameters are not showing up for Comparator: e.g., see here, https://api.dartlang.org/133421/dart-core/Comparator.html. (Should a separate issue be filed?)

**Comment by sethladd** [comment]
Thanks for the report!
