### ISSUE TITLE
dart:math is listed twice on api.dartlang.org

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dartdoc#1230]
_From @kmillikin on August 16, 2016 12:21_

When I look at api.dartlang.org I see dart:math listed twice on the left-hand side.

_Copied from original issue: dart-lang/sdk#27083_

**Comment by mit-mit** [comment]
_From @kmillikin on August 16, 2016 13:21_

I just noticed that it's also listed twice in the body of the page.

**Comment by devoncarew** [comment]
@keertip, could you take a look?

**Comment by devoncarew** [comment]
This is fixed in the latest version of dartdoc: https://api.dartlang.org/dev/1.20.0-dev.1.0/index.html.
