### ISSUE TITLE
ScrollableBlock isn't linked from Block API docs for Flutter

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1238]
From https://docs.flutter.io/flutter/material/Block-class.html and https://docs.flutter.io/flutter/widgets/Block-class.html

Notice how LazyBlock isn't linked. That dartdoc comment is here: https://github.com/flutter/flutter/blob/c76decb84276486468c90a0c2a90df0b9d4895f2/packages/flutter/lib/src/widgets/scrollable.dart#L946

Can we link to ScrollableBlock from the doc comments in this page?

Thanks!

**Comment by sethladd** [comment]
cc @devoncarew @keertip

**Comment by sethladd** [comment]
Also note that Icon isn't linked from https://docs.flutter.io/flutter/material/Icons-class.html

**Comment by keertip** [comment]
looks like a dupe asking for  #1153

**Comment by astashov** [comment]
If it's dupe, should it be closed?

**Comment by devoncarew** [comment]
Closing as a dupe; @astashov has a PR for #1153 in progress.
