### ISSUE TITLE
Self-referential links on dartdoc pages are not obvious, broken links for inherited methods

### ISSUE THREAD

**Issue by ghost** [dart-lang/dartdoc#1239]
(1) Links provided in https://angular.io/docs/dart/latest/api/angular2.platform.browser/TemplateSecurityContext-class.html are redirecting to it self.Try clicking on  TemplateSecurityContext .It is no point of redirecting to the page it self by providing a link.

(2) links provided on page such as toString and noSuchMethod ( https://angular.io/docs/dart/latest/api/angular2.platform.browser/TemplateSecurityContext-class.html ) giving 404 not found.

**Comment by devoncarew** [comment]
@kwalrath - I'm not sure how those docs are generated, and if this is a dartdoc regression or not.

**Comment by kwalrath** [comment]
@chalin, what's your take on this?

**Comment by chalin** [comment]
- (1) WAI: if a link to a type Foo is made within the API docs of class Foo, then they will be self-referential. 
- (2) Corresponds to https://github.com/dart-lang/dartdoc/issues/1232.

**Comment by kwalrath** [comment]
Re (1): It seems silly to have a page link to itself. In this case, couldn't dartdoc detect the link and do something smarter?

**Comment by chalin** [comment]
Well, that could be open to debate. It does offer visual uniformity for all references.

I'm more concerned about situations where I see a type and that it is not linked. That is the case, for example, with dart:core types -- i.e., they are not being linked. As a reader I'd want to follow a link to, e.g., the **Map** type sometimes.

**Comment by jcollins-g** [comment]
This is related (and may be a duplicate depending on how you look at it) to #721.

**Comment by chalin** [comment]
I'd say that this issue is distinct enough from #721, in that it refers to in-page links rather than side-nav links to the current page.

**Comment by jcollins-g** [comment]
Part one of ghost's comment is working as intended from dartdoc's perspective (if you don't want a self-referential link in your dartdoc, don't write one in the comment).  Part two is a real problem with enums that is fixed in #1390.

**Comment by jcollins-g** [comment]
Since the first part is WAI and #1390 addressed the second part, closing.
