### ISSUE TITLE
Ensure: SourceSpans in html5lib comment is properly linked

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#124]
Was: https://github.com/dart-lang/dartdoc-viewer/issues/72

Go to http://www.dartdocs.org/documentation/html5lib/0.12.0/index.html#html5lib/parser#id_parse

See the comment:

```
Set generateSpans if you want to generate html5lib/source_span-span.SourceSpans, otherwise the sourceSpan property will be null. When using generateSpans you can additionally pass sourceUrl to indicate where the input was extracted from.
```

Expected: SourceSpans is linked correctly.

Actual: SourceSpans is not linked.

**Comment by keertip** [comment]
Works as expected. dartdoc does not create links for types in lib/src which are considered private, unless explicitly exported.
