### ISSUE TITLE
Documentation issue on api.dartlang.org > dart-core-library page

### ISSUE THREAD

**Issue by aravindame** [dart-lang/dartdoc#1241]
Link that provided in the https://api.dartlang.org/stable/1.19.0/dart-core/dart-core-library.html to redirect to the dart:collection library is broken. Link is redirecting to a broken link https://api.dartlang.org/stable/1.19.0/#dart-collection .

**Comment by devoncarew** [comment]
This issue was moved to dart-lang/sdk#27217
