### ISSUE TITLE
Markdown 0.11.0 requires a test expectation change in dartdoc

### ISSUE THREAD

**Issue by whesse** [dart-lang/dartdoc#1246]
Markdown 0.11.0 has been released, and using it in dartdoc changes the indentation in some output, so a test fails.

Please update the test and dependency version to markdown 0.11, and tag and release the new dartdoc version on pub.

This is not high priority.  When it is done, you can update the markdown and dartdoc version in sdk/DEPS.

**Comment by whesse** [comment]
It is important to give this a version number, and tag and release it on pub, so that it can be used in sdk/DEPS.

**Comment by devoncarew** [comment]
Hi, yup, see https://github.com/dart-lang/dartdoc/pull/1249 for the version rev.

**Comment by devoncarew** [comment]
tagged as `v0.9.7+4`
