### ISSUE TITLE
Ensure: identityHashCode links to correct identical function

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#125]
_From @IssuesMigrator on September 29, 2014 17:44_

_From [michael....@gmail.com](https://code.google.com/u/108931164613660994654/) on May 21, 2014 10:56:09_

https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart-core#id_identityHashCode int identityHashCode(Object object)

      Returns the identity hash code of object.

      Returns the same value as object.hashCode if object has not overridden hashCode. Returns the value that hashCode would return on this object, even if hashCode has been overridden.

      This hash code is compatible with **identical**.

In the last paragraph **identical** links to https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart-core.identical instead of https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart-core#id_identical

_Original issue: http://code.google.com/p/dart/issues/detail?id=18934_

_Copied from original issue: dart-lang/dartdoc-viewer#89_

**Comment by sethladd** [comment]
_From @IssuesMigrator on September 29, 2014 17:44_

_From @lrhn on May 21, 2014 03:03:30_

**Status:** Triaged  
  **Labels:** Area-DartDocViewer

**Comment by keertip** [comment]
dartdoc generates pages for methods too, so linking the _indentical_ to the method page for _identical_ works.
