### ISSUE TITLE
Show the appropriate import statement on each library page

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dartdoc#1251]
For example, visit this page:

https://www.dartdocs.org/documentation/analyzer/0.28.1/analyzer.dart.ast.ast/analyzer.dart.ast.ast-library.html

It's not obvious what import statement you should use to import this library. In this case it seems to be:

  import "package:analyzer/dart/ast/ast.dart";

Perhaps we could put the import statement at the top of each library page, to make it easy to copy and paste?

**Comment by sethladd** [comment]
I think we did that manually for the Dart SDK.

**Comment by eseidelGoogle** [comment]
Flutter got a request for this to, linked above.

**Comment by kwalrath** [comment]
I want this, too, for the angular docs. See dart-lang/site-webdev#787 for context.
