### ISSUE TITLE
Best practices for dart-doc?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dartdoc#1261]
I'm always stumped as a library author the best way to format my markdown to get nice output.

For example, should I be writing:

``` dart
/// Does a great, great thing.
///
/// ## Example
///     doThing() => 'GREEEEEEAAAAAAT'
String doThing() => ...
```

Or just using `**bold**` for the `Example` line, etc.

Do we have any sort of style guide or formatting suggestion guide?

**Comment by devoncarew** [comment]
Not sure; @kwalrath, @Sfshaza?

**Comment by devoncarew** [comment]
It looks like we do have a guide here: https://www.dartlang.org/guides/language/effective-dart/documentation (and we're ilnking to it from dartdoc's readme).

**Comment by kwalrath** [comment]
We do have that guide, but it could have more... guidance. Plus, we can have API-specific conventions.
