### ISSUE TITLE
ValueChanged<T> callbacks don't document the T

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1263]
(from https://github.com/flutter/flutter/issues/6475)

The doc generated for a ValueChanged valued callback doesn't reveal the type of its parameter.

For example see onChanged here: https://docs.flutter.io/flutter/material/Checkbox-class.html

**Comment by sethladd** [comment]
cc @hansmuller

**Comment by astashov** [comment]
Looking into it
