### ISSUE TITLE
Ability to insert predefined blobs of text into dartdocs

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1264]
This PR has a lot of duplication in the dartdocs:
https://github.com/flutter/flutter/pull/6473/files

It's very error-prone and likely to bit-rot. I wish we had a better way to do this.

We want the docs to include this information based on our experience in usability studies.

**Comment by Hixie** [comment]
In #1161 there is a proposal for fixing this. It seems fine, though I guess I don't really understand where we would store these macros. Would it just be in any Dart file in a /// comment that isn't associated with a specific identifier somehow?

**Comment by astashov** [comment]
We go through all the files while gathering all the classes, methods, etc for a library, so we can build an index of those macros while we are doing that. So yeah, it could be in any Dart file in any `/// comment`, even could be a part of some class/method docs.

**Comment by astashov** [comment]
Actually, we already have quite close functionality, with the syntax like `{@example dog/food}` (to add examples). The only difference - those examples should live in separate files, which may be not very convenient for the https://github.com/dart-lang/dartdoc/issues/1161 use case. We could use similar syntax though, like `{@macro: foobar}`

**Comment by Hixie** [comment]
Oh I don't know about @example, interesting. Can you point me to docs about it?

**Comment by astashov** [comment]
It was added like 10 days ago :) I dunno about the docs, but there's a PR for it: https://github.com/dart-lang/dartdoc/pull/1295

**Comment by devoncarew** [comment]
@astashov, re: generalized macros, I can see how they'd be referred to - `{@macro foobar}`; have you given any thought to how they'd be defined? How you'd have created the definition for `foobar` in the first place?

**Comment by astashov** [comment]
Well, it should either be some centralized place, like a separate file, similar to `@example`, or we can actually put it inline, right in other comments, like:

```dart
/// Docs for the class
/// {@template foobar}
/// This is the template contents
/// {@endtemplate}
class FooBar {
  ...
}
```

And we'll use it like:

```dart
/// {@macro foobar}
class FooBar2 {
}
```

and it will result in

```dart
/// This is the template contents
class FooBar2 {
}
```

That will require 2 passes through the docs though, first to build the index of macros, second - to render them.

**Comment by astashov** [comment]
What do you think?

**Comment by devoncarew** [comment]
It's tricky; for inline docs you'd have to import a file just for the purposes of defining macros. A package specific separate file would mean that we'd need to traverse package dirs in dartdoc, something we currently don't do (we just rely on the analyzer). @keertip, thoughts?

**Comment by keertip** [comment]
If all the macros used in a package are defined in the same package, then having the definitions in a separate file would work. But if the macro definition is in a different package, then looking through the package directories for the file is not something we want to do. As flutter is more than one package,  dartdoc would have to navigate through the various packages to find the macro definitions.

If the macros are defined in the comments, yes, it would take two passes. But dartdoc  does look at the comment contents in a couple of different places, [here](https://github.com/dart-lang/dartdoc/blob/master/lib/src/model_utils.dart#L75) to check if the element should be included and later to process the `@example` tag. So we could piggyback on the first check to build the index. 

Prefer the second option, though note that the macro name should be unique across packages in order to disambiguate as flutter has elements with the same name in different libraries/packages.

**Comment by astashov** [comment]
> Prefer the second option, though note that the macro name should be unique across packages in order to disambiguate as flutter has elements with the same name in different libraries/packages.

Since we gonna go through all the comments anyway while building an index, we can give warnings in case of ambiguous macro names.

So, proceed with the second option - keep them just in comments, do 2 passes? Everyone is agree?

**Comment by keertip** [comment]
yes, sounds good.

**Comment by chalin** [comment]
@astashov @sethladd et all: do we have an example of how this `@macro` feature is currently used?

cc @kwalrath

**Comment by astashov** [comment]
It was going to be used by the Flutter team, don't know whether they started to use it or not.

**Comment by kwalrath** [comment]
I'll ask the Flutter people about it today.

**Comment by sethladd** [comment]
@astashov did this get documented anywhere? how do we learn how to use it? :)

**Comment by astashov** [comment]
@sethladd here - https://github.com/dart-lang/dartdoc#macros

**Comment by sethladd** [comment]
Ah, gotcha. Thanks!

**Comment by kwalrath** [comment]
Also: https://github.com/dart-lang/dartdoc/blob/master/testing/test_package/lib/example.dart#L262

I don't know if the `@template` can be in a different file from the `@macro`, but that might be something you'd want to avoid anyway (for source code readability).

**Comment by astashov** [comment]
Yes it can be in a different file

**Comment by b-strauss** [comment]
Do IDEs somehow handle this feature? It would be a bit cumbersome to search for macros across the whole codebase when reading documentation.

**Comment by kwalrath** [comment]
@jwren making sure you see the question from @b-strauss.

**Comment by jwren** [comment]
@b-strauss 

I don't think we would want such features built into the IDE specifically for this case.  I'm not sure what it would look like either.  Already IJ supports find and replace, and multiple cursors.

For some annotations, `@macro` or `@template` in this case, perhaps a Dart Lint that would come along and point out the missed Copy & Paste errors...?

**Comment by b-strauss** [comment]
@jwren 

I might not have expressed myself properly.

I was thinking about a developer reading the documentation for a class. Until now all the important stuff was in one place, with some references to other symbols as follow up info.

With this feature, the documentation for something might be scattered across the whole codebase. I can imagine it might be a bit annoying to jump from one place to the other to read the whole thing. Maybe IDEs can help with that somehow.

**Comment by kwalrath** [comment]
I'm picturing it like this. You're looking at the code in DartPad or WebStorm or IntelliJ or whatever, and you see `/// {@macro consider_using_a_theme}`. It'd be nice if you could click that to see (in a dialog perhaps, with an option to go to) the template definition, which would be something like this:

```
/// {@template consider_using_a_theme}
/// Instead of using an absolute color from these palettes, consider using
/// [Theme.of] to obtain the local [ThemeData] structure, which exposes the
/// colors selected for the current theme, such as [ThemeData.primaryColor] and
/// [ThemeData.accentColor] (among many others).
/// {@endtemplate}
```

**Comment by chalin** [comment]
An alternative would be to imitate the way the `{@source}` directive is used and processed --- for an explanation of that see https://github.com/dart-lang/dartdoc/issues/1312#issuecomment-282409669.

To take @kwalrath's example. The API docs would contain:
```
/// {@macro consider_using_a_theme}
/// Instead of using an absolute color from these palettes, consider using
/// [Theme.of] to obtain the local [ThemeData] structure, which exposes the
/// colors selected for the current theme, such as [ThemeData.primaryColor] and
/// [ThemeData.accentColor] (among many others).
/// {@endmacro}
```
This way no special processing would be necessary (in any IDE/editor/environment) to see what the macro body is.

A separate tool would be run offline to ensure that all macro bodies were in sync with the macro definition.

**Comment by kwalrath** [comment]
I'd be happy with @chalin's solution. @Hixie, what do you think?

**Comment by Hixie** [comment]
I'm not really a big fan of duplicating the text. In general I'm not a huge fan of encouraging people to be reading the dartdocs in their source form. For example, as we start introducing more graphics, those won't be visible in the source. I think the solution is to encourage IDEs to actually render the dartdocs properly, inline, in some manner.

**Comment by kwalrath** [comment]
@Hixie I'm not a fan of encouraging reading the source, either, but that's what IDEs tend to encourage, so it's a very common use case.

**Comment by sethladd** [comment]
Just want to echo what we see over and over: "Jump to definition" is a very useful tool. We saw it in Atom, in VS Code, and in IntelliJ. This is a power of Flutter: the code for Flutter is right there in Dart, so developers can easily jump around and learn the framework. Which is why it's so cool that Flutter team values API docs so much :)

**Comment by kwalrath** [comment]
To @Hixie's point, we _should_ encourage IDEs to render the dartdocs.

But making the source code readable is also important.
