### ISSUE TITLE
ThemeData.hashCode has no documentation

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1266]
I don't understand why this is blank:
https://docs.flutter.io/flutter/material/ThemeData/hashCode.html

Shouldn't it inherit it from Object.hashCode?
https://docs.flutter.io/flutter/dart-core/Object/hashCode.html

**Comment by astashov** [comment]
Inheriting docs seems to be only working for methods, not for accessors. Do we want that functionality for accessors too?

**Comment by astashov** [comment]
It doesn't seem hard to add that, actually, I can add it.

**Comment by devoncarew** [comment]
I think we would want it. Are we implementing inherited docs in dartdoc or do we get that functionality from the analyzer?

**Comment by astashov** [comment]
It's in dartdoc
