### ISSUE TITLE
Display annotations on fields in dartdoc

### ISSUE THREAD

**Issue by rkj** [dart-lang/dartdoc#1268]
This can be very useful for code using framework like Angular that annotate fields with @Input and @Output to tell semantic of given code.

For example the just published Material widgets:
https://www.dartdocs.org/documentation/angular2_components/0.1.1/angular2_components/GlyphComponent-class.html
there is no way to tell which are actual input fields (the most important piece of API) from regular fields that are used internally by a component.

**Comment by Tomucha** [comment]
+1, pretty please :-)

**Comment by jcollins-g** [comment]
Surprising that this wasn't fixed with #1265 but apparently it wasn't.  Looking into it.

**Comment by jcollins-g** [comment]
In some cases, the list of annotations isn't where the dartdoc code expected it to be for certain nodes of the AST.   I've figured out how to navigate the tree sufficiently to get some cases, and [analyzer issue #28631](https://github.com/dart-lang/sdk/issues/28631) covers the rest of them, I hope.

Attached is a screenshot.  Is this along the lines of what you were looking for?

![screenshot from 2017-02-23 13 30 57](https://cloud.githubusercontent.com/assets/14116827/23280169/024e80a2-f9cd-11e6-8857-fe341ca1aa01.png)

**Comment by keertip** [comment]
Yes, do see the asked for info. Not sure if this is the best way to show it, but lets go with this for now.

**Comment by jcollins-g** [comment]
https://github.com/dart-lang/dartdoc/tree/1268-display-annotations-on-field

Not usable yet as it depends on https://codereview.chromium.org/2704933002 for analyzer.

Here are a couple more screenshots showing more complex examples from Angular:

![screenshot from 2017-02-24 16 37 01](https://cloud.githubusercontent.com/assets/14116827/23326390/e6ffa638-fab1-11e6-91e1-51270e88b855.png)
![screenshot from 2017-02-24 16 48 36](https://cloud.githubusercontent.com/assets/14116827/23326392/e8d607c2-fab1-11e6-91dc-3dc167cbe882.png)

**Comment by devoncarew** [comment]
Awesome!

We may want to render the annotations with a leading `@`, in order to help users know what they are when scanning the list of fields and methods.

**Comment by jcollins-g** [comment]
Currently, other annotations have the @ intentionally stripped (protected, deprecated, etc).  I don't know whether it is clearer to have them or not (I'm actually for adding the @), but I'd like to be consistent.

I will modify this to return the @ in front of all annotations unless there is a strong objection, then.

Also, this change fixes minor bugs in the prior fix for #1265 , including the appearance of spurious @ symbols in place of parameter annotations in constructor documentation.

**Comment by jcollins-g** [comment]
[Branch](https://github.com/dart-lang/dartdoc/tree/1268-display-annotations-on-field) now has cleaned up code and tests, but waiting for analyzer 0.29 change to land and be released before mailing as a PR.

**Comment by jcollins-g** [comment]
Obligatory screenshot, now with extra @ symbols:

![screenshot from 2017-02-27 16 23 00](https://cloud.githubusercontent.com/assets/14116827/23386053/17d669fa-fd09-11e6-9819-6601ecd1cbc8.png)

**Comment by devoncarew** [comment]
+1 to the `@` symbols :)

**Comment by keertip** [comment]
Looks good!

**Comment by Tomucha** [comment]
@jcollins-g  since you are in this part of the dartdoc code, please have look on this:
https://github.com/dart-lang/dartdoc/issues/1162

It's very annoying and possibly dangerous. Thank you!!!

**Comment by jcollins-g** [comment]
This refactoring of how annotations are handled will fix #1081, #1162 and issues not quite covered in the fix to #1265.
