### ISSUE TITLE
Ensure: DartDoc has incorrect signature for function parameters.

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#127]
_From @IssuesMigrator on September 29, 2014 17:44_

_From @lrhn on June 06, 2014 18:35:01_

The signature of num.parse is given as:
  static num parse(String input, [Function num onError(String input)])
The "Function" should not be there. https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.num#id_parse

_Original issue: http://code.google.com/p/dart/issues/detail?id=19283_

_Copied from original issue: dart-lang/dartdoc-viewer#94_

**Comment by sethladd** [comment]
Here's a good one to check :)

**Comment by keertip** [comment]
verified

![screen shot 2015-03-17 at 2 56 10 pm](https://cloud.githubusercontent.com/assets/2192312/6698430/dc03d474-ccb5-11e4-8103-6c5786792b4f.png)

**Comment by sethladd** [comment]
We should probably open a new issue for the space after `[`

Also, what is `onError` ? Hard to tell... can you open a new issue for that?
