### ISSUE TITLE
Sidebar isn't opaque, draws text on text

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1270]
For docs.flutter.io:

![screenshot_20161108-121215](https://cloud.githubusercontent.com/assets/5479/20115425/11b3cba2-a5ad-11e6-82c6-51f301893f82.png)

**Comment by sethladd** [comment]
Hm, this might be an issue specific to Flutter. The api.dartlang.org site looks good.

**Comment by sethladd** [comment]
We'll use a newer version of dartdoc on docs.flutter.io. If the problem persists, I'll reopen.

**Comment by sethladd** [comment]
For those following along, this was a bug in the styles for docs.flutter.io

**Comment by devoncarew** [comment]
If I recall, there are a bunch of styles that should be rolled back from flutter.io, from a commit of some bootstrap css a while ago.

**Comment by sethladd** [comment]
sorry, what does "should be rolled back" mean? unclear in which direction I should rollback?

**Comment by devoncarew** [comment]
The css committed was intended to add a sidebar or left-nac, but impacted a lot of other things, like page fonts and (likely) the mobile rendering.
