### ISSUE TITLE
styles.css: FormatException: Expecting '='

### ISSUE THREAD

**Issue by chalin** [dart-lang/dartdoc#1276]
- Setup using: `pub global activate linkcheck`
- Then running `linkcheck` on a site containing the dartdoc styles.css results in:
```
.../static-assets/styles.css
Unhandled exception:
FormatException: Expecting '=' (at character 24)
data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='16' ...
                       ^
```

Conext: we're using the dartdoc generated pages for https://github.com/dart-lang/angular2 via https://github.com/dart-lang/site-webdev. Running `linkcheck` over the resulting webdev site resulted in the error above.

cc @kwalrath @ericjim @keertip @kevmoo

**Comment by devoncarew** [comment]
@chalin, that's finding the data url from here: https://github.com/dart-lang/dartdoc/blob/master/lib/resources/styles.css#L391. I believe that's a valid data url; perhaps file a bug with the `linkcheck` tool?

**Comment by chalin** [comment]
You're right, it does seem to be a valid data URL. Moving this issue to https://github.com/filiph/linkcheck/issues/1 so that @filiph can take a look at it.
