### ISSUE TITLE
dartdoc html causes user to lose context when navigating

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dartdoc#1288]
### Steps to reproduce

- Visit https://docs.flutter.io/flutter/material/material-library.html
- Scroll down to the `ThemeData` class in the right-hand-side class navigation
- Click on the class
- Go to click on one of other classes you were just browsing, like `TextSpan`

### Expected behavior

You expect to keep your navigation context as a visual anchor of where you are in the site.

### Actual behavior

Since the page doesn't use frames, the whole page is reloaded.  Further, the constants, typedefs, and classes now like on the left side of the page, where they were on the right before. I'm no usability expert, but I find this totally jarring as a user (still to this day, even after having used Dartdoc for over a year).

### Suggestion

We should take a page from Javadoc, which I think got this one right.  The listing of your packages should stay in a constant location, as should the listing of your constants-typedefs-classes-etc.  I think html iframes is probably the way to go with this, but there may be others.

**Comment by sethladd** [comment]
Thanks. Can you reword the title to be more about the problem, less about
the solution?
