### ISSUE TITLE
Generate test output into temp directory

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#130]
Should not dirty project directory with `docs` during tests

**Comment by sethladd** [comment]
Where should it go?

**Comment by kevmoo** [comment]
`Directory.systemTemp.createTemp` something

An example: 
https://github.com/dart-lang/source_gen/blob/master/test/test_utils.dart#L23

Make best effort to clean it up when you're done. But if not, the system generally cleans this up after reboot, etc

**Comment by sethladd** [comment]
dartdoc can now output to a directory specified on the command line. Try `dartdoc --out=some_dir`

**Comment by kevmoo** [comment]
Sure. But the *tests* shouldn't leave turds in the project directory.

See my comment – dump to temp and cleanup afterwards.

**Comment by keertip** [comment]
#438
