### ISSUE TITLE
Crash when building Angular docs

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dartdoc#1315]
For details, see https://github.com/dart-lang/site-webdev/issues/296.

**Comment by devoncarew** [comment]
@astashov, see the exception near the end of https://s3.amazonaws.com/archive.travis-ci.org/jobs/188681711/log.txt

I think this was caused by https://github.com/dart-lang/dartdoc/pull/1313; do you mind taking a look?

**Comment by astashov** [comment]
Sure!

**Comment by kwalrath** [comment]
Thanks for the quick fix!
