### ISSUE TITLE
add some integration testing of major libraries

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1317]
We should shard the dartdoc bots:

- [x] have one run the dartdoc tests (likely against the dev sdk)
- [x] generate docs for the dart sdk (and validate the results)
- [x] have one clone the angular repo, generate docs for it, and run some validations #1393
- [x] have one clone the flutter repo, generate docs for it, and run some validations

This would prevent (or at least give us early warning) of regressions generating docs for angular and flutter.

**Comment by jcollins-g** [comment]
Angular docs are run regularly via the bots for a while now.  Closing.
