### ISSUE TITLE
Implement `covariant` marker in dartdoc

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/dartdoc#1322]
This is the dartdoc issue for https://github.com/dart-lang/sdk/issues/27486.

**Comment by devoncarew** [comment]
@keertip, this is still is scope for 1.22

**Comment by devoncarew** [comment]
(will need https://github.com/dart-lang/sdk/issues/28167 to land first)

**Comment by mit-mit** [comment]
Looks like https://github.com/dart-lang/sdk/issues/28167 landed!

**Comment by keertip** [comment]
Looking at the covariant spec, at this point there is nothing to be done in dartdoc wrt this.
