### ISSUE TITLE
Change the order of groups on dartdoc pages

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1323]
The order right now is a bit weird (especially that typedefs come so early on the library page).

Here are the suggested new orders:

- Top-level page: flutter, dart core, flutter_markdown, flutter_test, flutter_driver.
- Library pages: classes, constants, properties, functions, enums, typedefs, exceptions.
- Enum pages: constants, properties, functions, operators.
- Class pages: constructors, properties, methods, operators, static methods, constants.

cc @sethladd

**Comment by sethladd** [comment]
This list is approved. Go forth and make it awesome.

**Comment by sethladd** [comment]
cc @astashov if you're looking for one P2, this one is an easy one :)

**Comment by jcollins-g** [comment]
This has two parts influencing it: the script that constructs the "package" that dartdoc actually documents for flutter, and the dartdoc internal category sorting.  Starting work on the latter, first.

**Comment by jcollins-g** [comment]
@Hixie / @sethladd : it would be easier to do this automatically with flutter_driver before flutter_markdown and flutter_test.  Would that be acceptable?  I'll have to add a flag to specify ordering otherwise.

**Comment by Hixie** [comment]
It's probably fine, but it's definitely suboptimal. We ideally want flutter_test (unit tests) above flutter_driver (integration tests, more complicated), and ideally want flutter_markdown (a flutter runtime package) before the test packages.

Might be worth just giving us explicit control (maybe default to the order on the command line, say), that way you never have to worry about it again. :-)

**Comment by jcollins-g** [comment]
Sounds good.  I'll still improve the automatic categorizing but give you control on the command line to override it.

**Comment by Hixie** [comment]
Also any improvement is an improvement, we're happy to take things bit by bit if that's more tractable than going all the way to space in one step. :-)

**Comment by jcollins-g** [comment]
Static properties weren't mentioned under classes in the order above, so moving them to before static methods.

**Comment by jcollins-g** [comment]
Can't fix this without touching the code for #1225, so fixing that too.

**Comment by jcollins-g** [comment]
Done, cleaned up and has tests, but stuck behind #1368.  Some examples below from Flutter.

Top level, with new --category-order flag set to:
`"flutter,Dart Core,flutter_markdown,flutter_test,flutter_driver"`:

![screenshot from 2017-04-12 11 11 21](https://cloud.githubusercontent.com/assets/14116827/24974870/86efeeb0-1f78-11e7-91be-b012df9e5683.png)

Library:
![screenshot from 2017-04-12 12 10 25](https://cloud.githubusercontent.com/assets/14116827/24975059/3a124cfe-1f79-11e7-82eb-3bbbd432c49a.png)

Class:
![screenshot from 2017-04-12 12 23 57](https://cloud.githubusercontent.com/assets/14116827/24975570/013c111a-1f7b-11e7-9a97-fa12588c350e.png)

Enum:
![screenshot from 2017-04-12 12 11 19](https://cloud.githubusercontent.com/assets/14116827/24975084/544655d4-1f79-11e7-9671-a13fd4840a15.png)

**Comment by Hixie** [comment]
That is gorgeous.

**Comment by Hixie** [comment]
It looks like the order of groups on library, enum, and class pages hasn't changed. Should I file a separate bug to track those?

**Comment by jcollins-g** [comment]
This is fixed in head as screenshots indicate, but until #1390 lands to correct the many broken links from doc references introduced in #1368 it's not really usable yet.
