### ISSUE TITLE
We see ambiguous references when we think we shouldn't

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1328]
From https://travis-ci.org/flutter/flutter/builds/191793939 (a Travis build for Flutter), using dartdoc 0.9.9

```
Ambiguous reference to [Flexible.fit] in 'widgets.Column' (/home/travis/build/flutter/flutter/packages/flutter/lib/src/widgets/basic.dart:2206). We found matches to the following elements: 'material.Flexible.fit', 'widgets.Flexible.fit'
Ambiguous reference to [Flexible.fit] in 'widgets.Column' (/home/travis/build/flutter/flutter/packages/flutter/lib/src/widgets/basic.dart:2206). We found matches to the following elements: 'material.Flexible.fit', 'widgets.Flexible.fit'
```

We would expect to not see these warnings, because `Flexible.fit` really comes from `widgets.Flexible.fit`

**Comment by sethladd** [comment]
cc @Hixie 

cc @astashov I think you worked on something very related to this. Did those patches intent to address this case, too?

**Comment by astashov** [comment]
We could use stuff I've added at those patches to address these issues. I've added a way to find "canonical" model elements, so we only need to use the canonical model elements when searching for ambiguous references.
