### ISSUE TITLE
Search box doesn't always show me what I click on

### ISSUE THREAD

**Issue by abarth** [dart-lang/dartdoc#1330]
1. Go to <https://docs.flutter.io/> and type "BoxPainter" in the search box
2. Press the down arrow three times.  You should have the "paint" method selected.
3. Now press "enter".

Notice that you don't go to the paint method but instead you go to the BoxPainter class.

**Comment by eseidelGoogle** [comment]
Is this a regression from a previous dartdoc revision?

**Comment by abarth** [comment]
Yes.  I suspect it's relating to deduping reexports.

**Comment by Hixie** [comment]
I have bumped this bug to P0 to underscore it's importance. :-)

**Comment by sethladd** [comment]
@Hixie do we need to roll back our version of dartdoc in the meantime?

**Comment by abarth** [comment]
Probably, unfortunately.
