### ISSUE TITLE
Add media styles so printed dartdoc is cleaner

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dartdoc#1338]
The printed API doc has lots of stuff you don't expect:  sidebars, subnav, and link details. (See screenshot below.)

Adding this CSS solves the problem:

```
@media print {
  .subnav, .sidebar {
    display:none;
  }

  a[href]:after {
   content:"" !important;
  }
}
```

The following picture shows the before and after for the [Angular Directive class API docs](https://webdev.dartlang.org/angular/api/angular2.core/Directive-class).

![image](https://cloud.githubusercontent.com/assets/2164483/22613821/6cc1a13c-ea30-11e6-9ae0-be81936ca2e2.png)

**Comment by devoncarew** [comment]
Looks great! Our styles are here: https://github.com/dart-lang/dartdoc/blob/master/lib/resources/styles.css, if you'd like to put together a PR.

**Comment by kwalrath** [comment]
OK, I'll do that.
