### ISSUE TITLE
We have duplicate docs still in some cases

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1341]
For example:
* https://docs.flutter.io/flutter/widgets/ScrollPosition/ensureVisible.html
* https://docs.flutter.io/flutter/material/ScrollPosition/ensureVisible.html

Only the first of these should exist.

**Comment by eseidelGoogle** [comment]
Presumably this is just a small incompleteness from https://github.com/dart-lang/dartdoc/issues/1158
