### ISSUE TITLE
drop @example or rename it to @insert or @include

### ISSUE THREAD

**Issue by chalin** [dart-lang/dartdoc#1347]
See https://github.com/dart-lang/dartdoc/issues/1312#issuecomment-282359789 for the original thread of discussion:
> We now have two very similar mechanisms for adding code fragments to API docs: `@source` and `@example`. The former is handled outside of dartdoc.
> 
> I'd suggest that we drop support for `@example` in favor of `@source`.

cc @sethladd @kwalrath

**Comment by chalin** [comment]
@jcollins-g: just wanted to ensure that this issue was on your radar. IMHO @example should be dropped, or at least replaced by a more general mechanism of just plain text/markdown fragment insertion.

I know that @sethladd had some comments about this, though it wasn't clear to me if he was implying that `@example` was being used by flutter (but I think not).

**Comment by srawlins** [comment]
This directive is being removed. See https://github.com/dart-lang/dartdoc/commit/0e1a6d94a6cb5dd487a19ebb68980e34ac6154ba for the deprecation.
