### ISSUE TITLE
rev version to 1.0.0

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1358]
To indicate general stability.

/cc @jcollins-g @keertip

**Comment by jcollins-g** [comment]
Blocked by #1361.

**Comment by jcollins-g** [comment]
Removing block; #1361 was introduced prior to the last release so it shouldn't block this one.

**Comment by srawlins** [comment]
There are actually a lot of fields and methods that are public which I think could be made private. I'd love to deprecate the publicity of such code, and say the public members may be removed as early as 1.0.0.

**Comment by srawlins** [comment]
Complete.
