### ISSUE TITLE
add a facelift to dartdoc

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1372]
We should borrow some of the new css look from dartlang.org.

**Comment by devoncarew** [comment]
@jcollins-g, here's the current look - the header's now a fixed size:

<img width="1428" alt="screen shot 2017-05-12 at 12 56 46 pm" src="https://cloud.githubusercontent.com/assets/1269969/26014707/a304eb58-3712-11e7-82d4-7d67f1810b0d.png">

you can compare with a page like https://www.dartlang.org/community.

**Comment by jcollins-g** [comment]
looks very good!

**Comment by devoncarew** [comment]
The last bit left of this issue is to re-do the columns to be more similar to dartlang.org; this will improve the scrolling and nav behavior.
