### ISSUE TITLE
dartdoc should not use computeNode()

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1375]
@scheglov Konstantin, can you explain more about why using computeNode() is a bad idea?  Dartdoc's instances of it seemed fairly benign at first glance to me.

**Comment by scheglov** [comment]
I don't remember the clincher, but here are some idea.
@bwilkerson might remember more ideas.

1. There is no way for `computeNode()` to guarantee that it will read the same content of a file as the one which was used to create the element.

2. When you call `computeNode()`, it has to perform full resolution, even if the client does not care about resolution of the full file, with method bodies.

3. It's a bad API - it mixes elements and AST nodes.

**Comment by srawlins** [comment]
Yay `computeNode` is no longer referenced or overridden.
