### ISSUE TITLE
Future needs a method that returns void and catches all results

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1379]
I wish there was an equivalent to "then" or "whenComplete" and so forth that represented the "end" of the Future chain.

That is, this method would return `void`, and would count as catching any error thrown by the future.

Something like:
```dart
finishWith(T value, dynamic error, StackTrace stack);
```

...(where `error == null` indicates the future completed).

For example:

```dart
   Future<String> foo = fetchValueFromNetwork();
   Future<int> bar = foo.then<int>(convertValueToData);
   bar.finishWith((int value, dynamic error, StackTrace stack) {
     if (error != null) {
       print('Failed: $error');
     } else {
       print('Got $value!');
     }
   });
```

This would make working with Futures much more satisfying. The current model is problematic because whatever you do with a Future, you always end up spawning another Future that itself needs to be dealt with and the chain never really ends.

**Comment by devoncarew** [comment]
@hixie, did you mean to file this on the dartdoc repo?

**Comment by Hixie** [comment]
oops nope. Sorry. Refiled at https://github.com/dart-lang/sdk/issues/29361
