### ISSUE TITLE
Many broken links in flutter post 0.10.0

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1380]
Wrote a link checker for flutter's doc bot script and discovered that most links inside comments are broken.

example:  flutter_driver's DriverError constructor has links to message, originalError, and originalStackTrace, but they all are pointing to the parent class versions rather than DriverError's versions.

This bug will track fixing all broken links introduced in 0.10.0.

**Comment by chalin** [comment]
There are a lot of broken links for the [angular2](https://github.com/dart-lang/angular2) docs as well:
- See [this Travis log](https://travis-ci.org/dart-lang/site-webdev/jobs/222934881) for errors reported by the linkchecker when the doc are generated by dartdoc 0.10.0.
- [This is a the log](https://travis-ci.org/dart-lang/site-webdev/jobs/222420458) for when dartdoc 0.9.x was used.

cc @kwalrath @kevmoo

**Comment by jcollins-g** [comment]
Yep.  I'm integrating a link checker into dartdoc & flutter generation shortly so it won't generate broken docs ever without warning (which is how some of this got by me), enabling by default all warnings, and Devon is working on getting the bots running dartdoc on flutter and angular.

**Comment by jcollins-g** [comment]
@chalin what was the last good version for you?  I'm particularly interested if 0.9.11 worked well for you or not.

**Comment by chalin** [comment]
v0.9.13 works fine.
Would you also like for me to test v0.9.14-dev?

**Comment by jcollins-g** [comment]
0.9.14-dev is likely to work alright, but it is a SDK-only release.

This then is further consequences of the canonicalization rationalization I
hadn't seen yet.

**Comment by jcollins-g** [comment]
Flutter is down to a handful of busted links again in my canonicalization overhaul part two, roughly similar to 0.9.11.   Going to be a few days writing tests and integrating link checking into dartdoc.

**Comment by jcollins-g** [comment]
This issue is three-fold:

1) Canonicalization overhaul (#1368) had a couple of bugs, that accounts for about 1/3 of the broken links.
2) Canonicalization overhaul exposed inconsistencies in doc reference handling with respect to canonicalization, creating more broken links.  I found this while doing last-minute checks with flutter, but it should have been sooner.
3) Canonicalization overhaul resulted in silently dropping a substantially larger number of doc references.  (While there is a warning message that you can enable, it resulted in so many false-positive warnings the new ones hid in the swarm).

The first was quick to fix.  The last two were intertwined; I couldn't reasonably fix the actual problems with canonicalization without having reliable error reporting.   So, adding link checking, rewrote most of the doc comment handling, and now generating warnings for doc references only when appropriate.

**Comment by jcollins-g** [comment]
Canonicalization overhaul part two is shaping up.  Will include useful warnings about inability to link doc references, a built in link checker, and many changes to doc reference handling to make it more intuitive to use and correct in the canonicalized world.  Working on tests for it now.

**Comment by jcollins-g** [comment]
#1390 includes a built in link checker that verifies zero broken links in angular2, and ten broken links (created by invalid markdown, not dartdoc) in flutter.
