### ISSUE TITLE
Make it more obvious that there's further information behind a property

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1388]
For example, look at this page:
https://docs.flutter.io/flutter/material/AppBar-class.html
...it's not at all obvious that if you click "actions" you'll get a lot more information including sample code.

**Comment by jcollins-g** [comment]
We could dynamically add a link to the one-liner for a property or method if we detect a block code comment that says "Sample Code" or something along those lines?

**Comment by Hixie** [comment]
The problem occurs even if there's just two paragraphs. For example, look at "alwaysNeedsCompositing" on https://docs.flutter.io/flutter/rendering/RenderObject-class.html.

**Comment by jcollins-g** [comment]
Hmm.  We could produce a [...] link or something if dartdoc detects the one line doc is not all there is?

So the doc would look like:

Whether this render object always needs compositing.  [[...]](https://docs.flutter.io/flutter/rendering/RenderObject/alwaysNeedsCompositing.html)

Open to suggestions as to what the link would look like so it is at the same time obvious, but not intrusive and repetitive looking when there are many of them on a page.

**Comment by Hixie** [comment]
Worth a try. Anything is better than what we have now, which is that people have no idea there's more text to read. :-)

**Comment by devoncarew** [comment]
We did used to use ellipses when there was more content. It didn't read great when the doc summary ended with a period (which, most do). I like the `[...]` idea above, is seems to work well.

**Comment by jcollins-g** [comment]
OK, I'll try and fit this in, but carefully.  If there's one thing I know about changing dartdoc, it is that yes, things could be worse than what we have now. :-)

**Comment by Hixie** [comment]
Fair enough! :-)

**Comment by jcollins-g** [comment]
Promoting to P1 as IIRC user studies have indicated this is important.

**Comment by jcollins-g** [comment]
A sample of the new links, displayed only on items which actually have more useful docs.

![screenshot from 2017-06-01 13 45 21](https://cloud.githubusercontent.com/assets/14116827/26700008/a91bcbce-46d0-11e7-911d-d0bf06efa0d5.png)
