### ISSUE TITLE
publish new dartdoc with analyzer 0.30

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1389]
@jcollins-g, we've been blocked on publishing a fully generic function syntax compliant dartdoc until a stable 0.3.0 of package:analyzer is available. But we have a pre-release available w/ all the APIs we need. We could pin to that version and publish using the alpha release (`0.30.0-alpha.3`). WDYT?

**Comment by jcollins-g** [comment]
As long as package test doesn't conflict with it, that's the major issue.

After trying to pin dartdoc's version, with:  
```
diff --git a/pubspec.yaml b/pubspec.yaml
index 9a163c58..aef1c604 100644
--- a/pubspec.yaml
+++ b/pubspec.yaml
@@ -7,7 +7,7 @@ homepage: https://github.com/dart-lang/dartdoc
 environment:
   sdk: '>=1.14.0 <2.0.0'
 dependencies:
-  analyzer: ^0.29.8
+  analyzer: 0.30.0-alpha.3
   args: ^0.13.0
   collection: ^1.2.0
   html: '>=0.12.1 <0.14.0'
```
I get:
```
~/dart/clean/dartdoc
$ pub get
Resolving dependencies... (1.7s)
Package test has no versions that match >=0.12.0 <0.13.0 derived from:
- dartdoc depends on version ^0.12.0
~/dart/clean/dartdoc
$
```

**Comment by devoncarew** [comment]
:(

We can try to use version overrides here - https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

**Comment by jcollins-g** [comment]
that works, sort of:

~/dart/clean/dartdoc
$ pub get
Resolving dependencies... (1.0s)
+ front_end 0.1.0-alpha.2
+ kernel 0.2.0
Warning: You are using these overridden dependencies:
! analyzer 0.30.0-alpha.3
Downloading analyzer 0.30.0-alpha.3...
Downloading kernel 0.2.0...
Downloading front_end 0.1.0-alpha.2...
Changed 3 dependencies!
Precompiling executables... 
Precompiled grinder:init.
Precompiled grinder:grinder.
Precompiled markdown:markdown.
Precompiled test:test.
~/dart/clean/dartdoc
$

However, version overrides like that are probably not a wise thing to have in a published version of a package, right?

I think the right thing to do is have test declare that at least some 0.30 versions are OK.

**Comment by devoncarew** [comment]
> However, version overrides like that are probably not a wise thing to have in a published version of a package, right?

It's not a great practice, no.

Do you mind opening an issue on package:test?

**Comment by jcollins-g** [comment]
Done.

**Comment by micahbeeman-wf** [comment]
Now that analyzer 0.30.0 has been released, can dartdoc be updated to support it? The current version restraint is analyzer: ^0.29.8

**Comment by jcollins-g** [comment]
blocked on #1403
