### ISSUE TITLE
Generate index for SDK

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#139]
Going to api.dartlang.org should display a nice index/overview page for the SDK docs.

For packages, we use the package's README.

For the SDK, what do we use?

**Comment by kaendfinger** [comment]
If I get more information, I'll see what I can do on this.

**Comment by sethladd** [comment]
@keertip might have some research.

I believe we're going to have to do something unique for our SDK docs. Perhaps a command-line flag for dartdoc that takes a path to an "index" markdown file ?

**Comment by sethladd** [comment]
Dupe of https://github.com/dart-lang/dartdoc/issues/275
