### ISSUE TITLE
DragGestureRecognizer.onDown not hyperlinked on DragDownDetails docs

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1391]
On this page: https://docs.flutter.io/flutter/gestures/DragDownDetails-class.html
...the link to `DragGestureRecognizer.onDown` isn't hyperlinked.

**Comment by jcollins-g** [comment]
Addressed in #1390.
![screenshot from 2017-05-02 07 44 07](https://cloud.githubusercontent.com/assets/14116827/25623093/31994c0c-2f0b-11e7-83b0-9421892aa129.png)
