### ISSUE TITLE
have a travis bot build and verify the docs for AngularDart per commit

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1393]
We'd like to have a bot build and test the angulardart docs on every commit. We have something like this for Flutter already (https://github.com/dart-lang/dartdoc/blob/master/.travis.yml#L9, https://github.com/dart-lang/dartdoc/blob/master/tool/travis.sh#L22), but would like the same for AngularDart so we know when it breaks.

@chalin, is this something you could help with? I'm not clear how how best to gen the docs for angular. For flutter, we clone their repo and run their doc gen script (which also contains some validation code).

**Comment by chalin** [comment]
I'd be glad to help.
> how best to gen the docs for angular. For flutter, we clone their repo and run their doc gen script (which also contains some validation code).

Might you want to use a variant of the [webdev `.travis.yml`](https://github.com/dart-lang/site-webdev/blob/master/.travis.yml)? The [**build** task (line 18)](https://github.com/dart-lang/site-webdev/blob/master/.travis.yml#L18), is used to build and [validate the docs (line 53)](https://github.com/dart-lang/site-webdev/blob/master/.travis.yml#L53).

The build task builds:
- angular2 API docs (using dartdoc)
- angular_component API docs (using dartdoc), and finally
- the webdev site

The `get-ng-repo.sh` script ([invoked at line 41](https://github.com/dart-lang/site-webdev/blob/master/.travis.yml#L41)), fetches the other repos as necessary.

cc @kwalrath

**Comment by srawlins** [comment]
This has been de-prioritized.
