### ISSUE TITLE
Please add support for analyzer 0.30.0 

### ISSUE THREAD

**Issue by micahbeeman-wf** [dart-lang/dartdoc#1403]
Analyzer version 0.30.0 has been released, and dartdoc is pinned to ^0.29.8. I'm unable to consume the latest version of dartdoc until analyzer 0.30.0 is supported.

**Comment by devoncarew** [comment]
You're using dartdoc as a package? I'm curious, for what?

Until we publish, you can use dependeny_overrides to pin to specific versions of analyzer (and whatever use is consuming it, likely `test`).

**Comment by micahbeeman-wf** [comment]
We use it in dart_dev (https://github.com/Workiva/dart_dev/blob/master/pubspec.yaml#L20). During my build process I run dartdoc and zip it up to post to our documentation site

**Comment by jcollins-g** [comment]
@devoncarew I get the feeling that most serious users of dartdoc use it as a package to be able to control the version independently.  I know I would if I was putting it in a build process.

**Comment by jcollins-g** [comment]
@micahbeeman-wf  We will be publishing a version for analyzer 0.30.0 soon, there are some other things that need to happen first though.

**Comment by jcollins-g** [comment]
Introducing analyzer 0.30 seems to introduce some small regressions which I'm now working on.

**Comment by jcollins-g** [comment]
analyzer 0.30 is now supported at head and will go out with the next publish.

**Comment by jcollins-g** [comment]
This is done in 0.12.0.
