### ISSUE TITLE
Recently published Flutter plugins do not build

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dartdoc#1408]
For example:

- https://www.dartdocs.org/documentation/shared_preferences/0.1.1/
- https://www.dartdocs.org/documentation/url_launcher/0.4.1/

I'm assuming this is because of some language features or flags that are not on the dartdoc server?

/cc @filiph @sethladd

**Comment by devoncarew** [comment]
Looks like they fail at the `pub get` stage: https://www.dartdocs.org/documentation/shared_preferences/0.1.1/log.txt.

**Comment by devoncarew** [comment]
This issue was moved to astashov/dartdocs.org#47

**Comment by matanlurey** [comment]
Ah good catch!
