### ISSUE TITLE
dartdoc needs a better defined namespace lookup

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1414]
Part of #1412 and other odd behaviors of dartdoc in some edge cases is because dartdoc currently has a very hacky way of looking up names for the global namespace.    #1390 basically refined the hack and made it actually work in a majority of cases so we could ship something functional with canonicalization, but there are still edge cases where it doesn't work.  Particularly, it doesn't work for FQNs based on imports where libraries are renamed, there are bugs with inheritance and documentation inheritance, etc.

Dartdoc should have a lookup method in ModelElement where we can pass strings in, and have that traverse Dartdoc's structure to determine what object is relevant directly.  Then we can jettison the table building/searching hack and behavior will be more consistent.

**Comment by srawlins** [comment]
We're removing the global namespace lookup, switching to use `@docImport` via analyzer. CC @kallentu
