### ISSUE TITLE
roll dartdoc into the sdk

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1423]
We should update the version of dartdoc that's used by the sdk. Among other things, this generates the hosted api docs for dartlang.

Looks like cherry-pick season starts Wednesday 5/17.

/cc @jcollins-g

**Comment by jcollins-g** [comment]
analyzer 0.30 update needs to be merged first, and so does the branch with the generic type information change.

**Comment by jcollins-g** [comment]
blocked by #1403

**Comment by jcollins-g** [comment]
now blocked on an infrastructure issue in chromium, need a new repo added to the github mirror.

https://bugs.chromium.org/p/chromium/issues/detail?id=725662

**Comment by jcollins-g** [comment]
This is now complete.
