### ISSUE TITLE
Output generated for @covariant parameters is not correct

### ISSUE THREAD

**Issue by HansMuller** [dart-lang/dartdoc#1424]
For example see:
https://docs.flutter.io/flutter/widgets/RenderObjectElement/insertChildRenderObject.html
```
@protected
void insertChildRenderObject(
    RenderObject,
    child,
    dynamic,
    slot
)
```
Which is defined here:
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L3981

**Comment by jcollins-g** [comment]
Yep, we're not displaying that each of these types was modified with the covariant keyword, but we should.

**Comment by jcollins-g** [comment]
Oh, and even worse: we claim that some things are additional parameters when in fact they're part of the same parameter.
