### ISSUE TITLE
flutter docs don't work well with updated style

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1425]
As discussed offline, we will need to fix the css for flutter post #1372.  I'd like to have this done before the next time we publish so we can have a dartdoc that works for everyone once more -- sdk, flutter, pub packages, etc.

example from head-ish:

![screenshot from 2017-05-16 10 47 25](https://cloud.githubusercontent.com/assets/14116827/26120372/57e76c98-3a25-11e7-839a-63119968c65b.png)
![screenshot from 2017-05-16 10 50 04](https://cloud.githubusercontent.com/assets/14116827/26120390/721d0848-3a25-11e7-8602-86dbabfcfbd1.png)

**Comment by devoncarew** [comment]
Makes sense - I think this will be a small-ish patch.
