### ISSUE TITLE
macro implementation doesn't guarantee detection of templates before attempting to apply them

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1429]
Even the line here: https://github.com/dart-lang/dartdoc/blob/master/lib/dartdoc.dart#L180 only changes the order in which things are loaded.  The unfortunately named `_rawDocs` are cached by `ModelElement`'s documentation so after this initial pass we'll never see the templates again.

This has always been a problem, but the canonicalization overhaul made this worse because before #1368 we usually recreated `ModelElement`s frequently enough to cloak this (which caused its own problems).  Fix with multiple passes or changing how templates work to make them no longer inline (but sourced from a separate file).

Lower priority only because macros don't seem to be in heavy use yet.

**Comment by jcollins-g** [comment]
Moving to P2 because AFAICT there isn't even a warning when this happens; can demote to P3 if we at least warn on macros not being found.

**Comment by srawlins** [comment]
Closing this as stale. At least flutter has a good system for warning on un-replaced macros.
