### ISSUE TITLE
Emphasise required arguments

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1432]
Consider this documentation:
https://docs.flutter.io/flutter/material/PopupMenuButton/PopupMenuButton.html

It's not at all clear from the top part that `itemBuilder` is required, whereas the others are optional.

From https://github.com/flutter/flutter/issues/10170.

**Comment by jcollins-g** [comment]
adding @required to the top section would probably solve this.

As an aside, I'm also a little weirded out by the inclusion of something that is the source but isn't, and by something that is the actual source in our dartdocs.    It seems to me that having two different sections here is only useful in case the first one is misleading or broken -- I'd like to try to fix that.

**Comment by Hixie** [comment]
The main thing I want from the top block is the types of each argument, which aren't necessarily obvious from the source itself. What would be really cool would be if the top one, rather than being a source-like blob, was a pretty table that listed each argument, whether it was a named argument or positional or optional or required or whatever, its type, its default value, and ideally any dartdocs from the relevant field in the case of the argument being a `this.foo`-style argument.

But that's probably something for another bug. :-)

**Comment by jcollins-g** [comment]
There are a couple references to this issue now, suggesting it's pretty important to the developer experience for Flutter.  Raising to P1.

**Comment by jcollins-g** [comment]
There was a TODO where I special-cased attributes out of parameters deliberately to be bug-for-bug compatible when I enhanced the annotation support, but I wasn't sure whether that was a good idea.

Apparently it wasn't.  Screenshot below:

![screenshot from 2017-06-01 14 37 35](https://cloud.githubusercontent.com/assets/14116827/26701979/ee80c460-46d7-11e7-9e0f-e8652da44c50.png)

**Comment by Hixie** [comment]
Yay!

(I'll fork out my suggestion for a table to a separate P3 bug.)

**Comment by Hixie** [comment]
(Filed https://github.com/dart-lang/dartdoc/issues/1451)
