### ISSUE TITLE
mixin member linked to wrong mixin in generated ACX API docs

### ISSUE THREAD

**Issue by chalin** [dart-lang/dartdoc#1434]
- Visit the ACX [MaterialDropdownSelectComponent](https://webdev.dartlang.org/components/api/angular_components/MaterialDropdownSelectComponent-class) API page on webdev.
- Search for, say, `handleHomeKey`:

    > [handleHomeKey](https://webdev.dartlang.org/components/api/angular_components/ActivateItemOnKeyPressMixin/handleHomeKey.html)(KeyboardEvent event) → void
    > inherited
- Click on the link, and you'll get a 404.

The `handleHomeKey` is linked to https://webdev.dartlang.org/components/api/angular_components/ActivateItemOnKeyPressMixin/handleHomeKey.html but the [ActivateItemOnKeyPressMixin](https://github.com/dart-lang/angular_components/blob/master/lib/src/components/material_select/material_dropdown_select.dart#L379) doesn't define `handleHomeKey`. It is defined in [KeyboardHandlerMixin](https://github.com/dart-lang/angular_components/blob/master/lib/src/model/a11y/keyboard_handler_mixin.dart).

Note that if you look at the "Mixes-in" list towards the top of the  [API entry for MaterialDropdownSelectComponent](https://webdev.dartlang.org/components/api/angular_components/MaterialDropdownSelectComponent-class), the `KeyboardHandlerMixin` entry isn't hyperlinked:
> ![screen shot 2017-05-20 at 6 24 03 am](https://cloud.githubusercontent.com/assets/4140793/26275011/0bdc8682-3d25-11e7-9f89-c64d75839f59.png)

The API docs linked to above were generated using dartdoc 0.11.x.

cc @kwalrath @nshahan

**Comment by jcollins-g** [comment]
This suggests some sort of canonicalization problem.

**Comment by jcollins-g** [comment]
As part of fixing this, the links in index.json should be added to the link checker.

**Comment by kwalrath** [comment]
This probably explains a bunch of 404s in the doc analytics.

I was just thinking that we should have a complete list of all bad links. @chalin?

**Comment by jcollins-g** [comment]
I'm very interested in tracking that on my side too -- our built-in link checker covers most things now but clearly not everything.

**Comment by chalin** [comment]
> I was just thinking that we should have a complete list of all bad links.

@kwalrath, well, in a way, we've encoded that here in the link checker skip list: https://github.com/dart-lang/site-webdev/blob/master/scripts/config/linkcheck-skip-list.txt#L23-L26

**Comment by kwalrath** [comment]
Those don't match the 404s I'm seeing:

/angular/api/angular2.platform.browser/BrowserDomAdapter/getElementsByClassName
/angular/guide/testing/component/component/page-objects
/angular/api/angular2.platform.common_dom/DomAdapter/getElementsByTagName
/angular/api/angular2.platform.common_dom/DomAdapter/querySelectorAll
/angular/api/angular2.core/Stream/listen
/angular/api/angular2.platform.browser_static/BrowserDomAdapter/getComputedStyle
/angular/api/angular2.platform.browser/BrowserDomAdapter/BrowserDomAdapter
/angular/api/angular2.platform.browser/BrowserDomAdapter/classList

(That said, I don't know where these URLs are coming from. Some might be dart:html APIs that something is treating as angular2 ones. Some might be TS APIs that don't exist in Dart.)

**Comment by jcollins-g** [comment]
As for the mixin that isn't linked, that is an indication that dartdoc (rightly or wrongly) believes that it is referred to by the public interface (in this case, referenced from a class in the public interface) but isn't actually exported itself.  I'll verify that this determination is correct; if it is correct, the way to fix the missing link is to solve the warning.

The broken links look like they are gone now with 0.12.0.

**Comment by jcollins-g** [comment]
Never mind on the broken links -- we still have them in 0.12.0, looking into that.

**Comment by chalin** [comment]
Ok, thanks.

**Comment by jcollins-g** [comment]
Ah, I see what's going on here.  dartdoc is treating mixins too similarly to other things in the inheritance chain.  They aren't though, and so it isn't appropriate to redirect to other mixins if one can't be documented.

**Comment by jcollins-g** [comment]
Fixed with the combination of #1440 and #1442, will go out in the next release.
