### ISSUE TITLE
When a numbered list has linebreaks in it, there's no space inserted between the words

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1435]
When a numbered list has linebreaks in it, there's no space inserted between the words.

For example, see https://docs.flutter.io/flutter/widgets/WidgetsBinding/drawFrame.html and search for "objectdirty" or "havetheir".

**Comment by jcollins-g** [comment]
I don't think this really qualifies as P1?

**Comment by Hixie** [comment]
It makes reading those docs horrible and is embarrassing to the project, but if P2 is still considered "very important" then I'm fine with calling it P2. :-)

**Comment by jcollins-g** [comment]
P1 is the things I work on first.  P2 are things I'm actively trying to get to but are less important than other P1 things.  P3 are things I have no active plans to work on.

**Comment by jcollins-g** [comment]
This looks like it got fixed at some point.  No more missing spaces on line breaks.
