### ISSUE TITLE
Configure any redirects on api.dartlang.org required for moving to new URL structure

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#144]
In the python code

**Comment by sethladd** [comment]
@keertip are you working on the app engine app?

**Comment by keertip** [comment]
@sethladd  yes, started on it.

**Comment by sethladd** [comment]
I think we did this. Yay!

**Comment by keertip** [comment]
Keep this open until we switch over?

**Comment by sethladd** [comment]
We can keep another issue open, titled "turn on new docs for api.dartlang.org", but you're done with the code for this, AFAIK.

**Comment by keertip** [comment]
Yes, the code is in there.
