### ISSUE TITLE
New styles on Flutter dartdocs are too subdued

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1441]
The new styles are a bit disorienting because the name of the member you're looking at is so subdued.

e.g. https://docs.flutter.io/flutter/rendering/MainAxisAlignment-class.html

The most important thing on that page is the word "center" as far as I can tell, maybe "Constants". It should be "enum MainAxisAlignment", which is there twice but one of them is tiny and one of them is off on the right and grayed out. Actually even better would be for the header to be "MainAxisAlignment enum".

https://docs.flutter.io/flutter/painting/BorderRadius-class.html is another example

The first thing i read is "An immutable set of radii for each corner of a rectangle", which if i'd just landed there (e.g. following a link) would be confusing. When switching through my tabs, I need to know that that is the "BorderRadius class".

I think the solution is to move the `<h5>` from the right hand column into the first `<section>` of the main column, change it to an `<h1>`, and put the identifier before the keyword. The current styles already make that work pretty well. Maybe they could be tweaked a little but I'm not the right person for that.

cc @devoncarew @sethladd

**Comment by jcollins-g** [comment]
dartdocs outside of flutter also have this general layout, so it is applicable for more than flutter.

**Comment by devoncarew** [comment]
From some noodling up here:

<img width="1486" alt="screen shot 2017-05-25 at 1 22 04 pm" src="https://cloud.githubusercontent.com/assets/1269969/26468967/3eba7eac-414d-11e7-9b6c-0ca1e8a136c4.png">

**Comment by jcollins-g** [comment]
The "<T>" is just a sample of course, MaterialButton doesn't have type parameters.  (And if it did they would be in the nav above too.

Some other options we talked about include reintroducing the small headers on both side columns to make it clear what they are for.  Also, we can change the emphasis or lack of same on various parts of the navigation on the top bar, with a mind to not varying too much from flutter.io style.

**Comment by sethladd** [comment]
FWIW I found the source code sections to be hard to read. I didn't realize I could hover over the source code to make it easier to read. On windows chrome, due to something (??), the source code is a bit blurry even when I hover over it.

**Comment by Hixie** [comment]
It's intentional because some people were considering them to be sample code. I'm open to better ways to remove the emphasis without outright removing or hiding it behind a speed bump. :-)

**Comment by devoncarew** [comment]
We could change the title of that section from `Source` to `Implementation:`?

**Comment by Hixie** [comment]
@jcollins-g If you could point me to the file where I would make this change, I'd be happy to do it.

**Comment by jcollins-g** [comment]
https://github.com/dart-lang/dartdoc/blob/master/lib/templates/_source_code.html#L3

I believe this is the right place.  "Implementation" sounds fine to me if you think it would be less confusing.

**Comment by Hixie** [comment]
I believe the "source code" section is a separate bug, this specific bug is about the title at the top.

**Comment by jcollins-g** [comment]
Oh, I thought you were asking about the separate bug.  Which of the proposals above do you actually want to see implemented?

I think we're mostly waiting on a "yes, do the thing" confirmation here and we can do it for you, too.

**Comment by Hixie** [comment]
If you want my vote, I vote for what I originally proposed, which is what devon showed in the screenshot above, but with the heading using English grammer (name-category, e.g. "Foo<T> class", "VoidCallback typedef", etc, rather than category-name).

**Comment by Hixie** [comment]
I'm moving this to P1 based on the number of reports we get of this.
