### ISSUE TITLE
The values for each value of the `BoxFit` enum all say they are `const BoxFit(null)`

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1445]
The values for each value of the `BoxFit` enum all say they are `const BoxFit(null)`:

https://docs.flutter.io/flutter/painting/BoxFit-class.html

**Comment by jcollins-g** [comment]
This doesn't seem to be widespread, but no immediate idea what's gone wrong here.

**Comment by jcollins-g** [comment]
Code references trigger construction of enum members in a way the class doesn't expect, creating this bug.

**Comment by jcollins-g** [comment]
Also broken:
https://docs.flutter.io/flutter/rendering/AxisDirection-class.html
https://docs.flutter.io/flutter/widgets/BannerLocation-class.html
https://docs.flutter.io/flutter/painting/BorderStyle-class.html
https://docs.flutter.io/flutter/dart-ui/BlurStyle-class.html
https://docs.flutter.io/flutter/widgets/CrossFadeState-class.html
...
and apparently, quite a few more.  This may be getting worse than when it was initially reported as more code references are added.
