### ISSUE TITLE
Annotations should link to their reference

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dartdoc#1447]
For example, for the [`FirebaseAuth` class][auth]:

[auth]: https://www.dartdocs.org/documentation/angular_fire/0.2.0/angular_fire/FirebaseAuth-class.html

```
Annotations:            @Injectable()
```

I would have loved to be able to click on `@Injectable()` and jump to the reference on crossdart.

**Comment by jcollins-g** [comment]
Links to annotations should at least warn when they can't be created, similar to other linking problems.

**Comment by jcollins-g** [comment]
External linking fixed this.
