### ISSUE TITLE
Support for table markdown syntax

### ISSUE THREAD

**Issue by chalin** [dart-lang/dartdoc#1453]
Some API pages like the one for [DatePipe](https://webdev.dartlang.org/angular/api/angular2.common/DatePipe-class) contain embedded tables, which [displays nicely on the TS-side of the docs](https://aio-staging.firebaseapp.com/api/common/DatePipe). Can we get support for tables in Dart API docs too?

This is the table from the [DatePipe](https://webdev.dartlang.org/angular/api/angular2.common/DatePipe-class) API page:

```
| Component | Symbol | Short Form   | Long Form         | Numeric   | 2-digit   |
|-----------|:------:|--------------|-------------------|-----------|-----------|
| era       |   G    | G (AD)       | GGGG (Anno Domini)| -         | -         |
| year      |   y    | -            | -                 | y (2015)  | yy (15)   |
| month     |   M    | MMM (Sep)    | MMMM (September)  | M (9)     | MM (09)   |
| day       |   d    | -            | -                 | d (3)     | dd (03)   |
| weekday   |   E    | EEE (Sun)    | EEEE (Sunday)     | -         | -         |
| hour      |   j    | -            | -                 | j (13)    | jj (13)   |
| hour12    |   h    | -            | -                 | h (1 PM)  | hh (01 PM)|
| hour24    |   H    | -            | -                 | H (13)    | HH (13)   |
| minute    |   m    | -            | -                 | m (5)     | mm (05)   |
| second    |   s    | -            | -                 | s (9)     | ss (09)   |
| timezone  |   z    | -            | z (Pacific Standard Time)| -  | -         |
| timezone  |   Z    | Z (GMT-8:00) | -                 | -         | -         |
```
which, in GFM is rendered quite nicely as:

| Component | Symbol | Short Form   | Long Form         | Numeric   | 2-digit   |
|-----------|:------:|--------------|-------------------|-----------|-----------|
| era       |   G    | G (AD)       | GGGG (Anno Domini)| -         | -         |
| year      |   y    | -            | -                 | y (2015)  | yy (15)   |
| month     |   M    | MMM (Sep)    | MMMM (September)  | M (9)     | MM (09)   |
| day       |   d    | -            | -                 | d (3)     | dd (03)   |
| weekday   |   E    | EEE (Sun)    | EEEE (Sunday)     | -         | -         |
| hour      |   j    | -            | -                 | j (13)    | jj (13)   |
| hour12    |   h    | -            | -                 | h (1 PM)  | hh (01 PM)|
| hour24    |   H    | -            | -                 | H (13)    | HH (13)   |
| minute    |   m    | -            | -                 | m (5)     | mm (05)   |
| second    |   s    | -            | -                 | s (9)     | ss (09)   |
| timezone  |   z    | -            | z (Pacific Standard Time)| -  | -         |
| timezone  |   Z    | Z (GMT-8:00) | -                 | -         | -         |

cc @kwalrath

**Comment by kwalrath** [comment]
Yes, please.

**Comment by jcollins-g** [comment]
If this is an issue on a large number of places (or if you're perceiving people are frequently avoiding creating tables because of this bug), elevate to P1.

**Comment by srawlins** [comment]
The Dart Markdown package supports GFM tables.

**Comment by mit-mit** [comment]
We are also seeing this for Flutter packages. e.g. https://www.dartdocs.org/documentation/url_launcher/latest/

@jcollins-g  @devoncarew I suggest we raise this to P1. WDYT?

**Comment by jcollins-g** [comment]
Raised to P1 as while this is a not-common problem/feature request, it seems to be high impact.
