### ISSUE TITLE
Would like to be able to link from DartDocs back to source files.

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/dartdoc#1454]
Lots of reasons this could be useful, e.g.
1.  Pointing users to where the docs were generated from so they can edit them.
2.  Pointing users to the implementations of the classes in question so they can read them.

a. came up from @inmatrix wanting to be able to encourage our users to improve our docs.
b.  Occurred to me this morning when wanting to get to the source of "TabBar" but not wanting to go have to search github when I had already found the docs:
https://docs.flutter.io/flutter/material/TabBar-class.html

Maybe the --cross-dart option already does something like this?  FYI @Hixie

**Comment by jcollins-g** [comment]
Crossdart does do something like this, but I don't know much about it.

Dartdoc does know internally what lines and files inside a package each symbol comes from, it's at least theoretically possible to add that information to external links.  I'm a little worried about correctness issues though.

If I had the opportunity to design it from scratch, I might have a dartdoc config file in the package indicate the repository where the package comes from, and use git commit IDs from the local repo (or tags) to link to the exact version of the source dartdoc is documenting on github, directly.

**Comment by jcollins-g** [comment]
Prioritizing as P3 since crossdart already implements some of this.

**Comment by jcollins-g** [comment]
If what we want is links to github, crossdart doesn't do that.  It links to copies of the code based on published packages, probably to get around some of the correctness and other issues that make this problem harder to solve.

**Comment by jcollins-g** [comment]
A discussion in Flutter suggests that this could be used for a "edit source" link to github.

This is coming up more often in discussions -- increasing priority.

**Comment by InMatrix** [comment]
Here is some evidence that lacking a link to the source code from the API doc is hindering contribution: https://github.com/flutter/flutter/issues/21136#issuecomment-417652018
