### ISSUE TITLE
We'd like to link from API docs back to the product homepage

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1460]
Currently, the dartdoc output puts the package/product name into the upper left of the page. Which is cool. Except, we won't think we have an easy way to link that name to somewhere relevant.

We can post-process the docs, but would be cool if I could ask dartdoc to link the title in the upper-left of the page.

**Comment by jcollins-g** [comment]
The obvious thing to try here is adding support for the homepage: link in pubspec.yaml and link this field to that when it is present.  I'll try that and see how well it works.

**Comment by sethladd** [comment]
Ah, good idea!

**Comment by jcollins-g** [comment]
This seems to work alright, but given that the package name is already in use to return readers of other API pages to the index, #1463 only changes this for the package index page.

**Comment by sethladd** [comment]
Thanks!
