### ISSUE TITLE
No automatic hyperlinking in HTML fragments

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1467]
The table in the following snippet fails to hyperlink the contents of the cells:

https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/Element/updateChild.html

(I think our ideal solution would be to have some way to mark tables up in markdown instead of using HTML, for what it's worth.)

**Comment by srawlins** [comment]
The dartdoc package uses package:markdown, which mostly supports GitHub-flavored Markdown tables. Are these enabled in dartdocs?

**Comment by srawlins** [comment]
@Hixie , I don't understand. I don't see a `#` fragment in your URL that you link...

**Comment by Hixie** [comment]
@srawlins I literally meant "HTML fragment", as in, a fragment of HTML, not URL fragment identifiers.
The source for the above is at: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/framework.dart#L2557

**Comment by srawlins** [comment]
Oh sorry. That's not part of the Markdown spec. You'll notice the backticks aren't converted to `<code>` either.

If you use the GFM markdown syntax, it might work.

**Comment by Hixie** [comment]
What does that mean? :-)

**Comment by Hixie** [comment]
Also, what markdown spec?

**Comment by srawlins** [comment]
The markdown package tries to follow the [CommonMark spec](http://spec.commonmark.org/), or, if you use [`ExtensionSet.gitHub`](https://github.com/dart-lang/markdown#extension-sets) (which I think dartdocs does... or at least should), the [GFM spec](https://github.github.com/gfm/).

In this case, using GFM tables:

```markdown
|                 | `newWidget == null` | `newWidget != null`
|-----------------|---------------------|-----------------------
| `child == null` | Returns null.       | Returns new [Element].
| `child != null` | Old child is removed, returns null. | Old child updated if possible, returns child or new [Element]. |

**Comment by Hixie** [comment]
Pretty sure I tried that and it didn't work, and when I complained, I was told to use `<table>` markup. :-)
There is a bug about supporting that: https://github.com/dart-lang/dartdoc/issues/1453

BTW, dartdoc definitely doesn't follow that spec, at least not exclusively. In particular, hyperlinks to members aren't a syntax covered by that spec as far as I can tell. Nor are macros.

**Comment by srawlins** [comment]
OK good, so there is a known issue.

Yeah I guess custom link resolvers are a customization. We just allow [shortcut reference links](http://spec.commonmark.org/0.27/#shortcut-reference-link) without a [link reference definition](http://spec.commonmark.org/0.27/#link-reference-definition), which then gets sent to a link resolver to answer "this might be a link. do you think it's a link? where should it point to?"
