### ISSUE TITLE
docs.flutter.io difficult to use on mobile

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#1469]
From @goderbauer

Just visited docs.flutter.io on my iPhone (Safari on iOS 10) to quickly look up an API. It is very difficult to use on mobile:
* there is no search field to quickly search for something (<--- main problem)
* the actual information is embedded in a strangely scrolling div
* vertical scrolling is enabled even though there is no need for it
* when scrolling through the hamburger menu, the page below it scrolls as well when the end of the hamburger menu is reached.

**Comment by jcollins-g** [comment]
#1348 is related

**Comment by jcollins-g** [comment]
flutter/flutter#19987 is related
