### ISSUE TITLE
Package meta docs seem out of date?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dartdoc#1477]
Not sure where to file this exactly, but the pub page for `package:meta`

https://pub.dartlang.org/packages/meta

points to this dartdoc page for documentation:

https://www.dartdocs.org/documentation/meta/1.1.1/

which doesn't exist.

**Comment by devoncarew** [comment]
Should likely file at dartdocs.org; I do see this build failure:

https://www.dartdocs.org/documentation/meta/1.1.1/log.txt

So perhaps 1.1.1 didn't get published or published properly?

**Comment by leafpetersen** [comment]
Ok, filing there.
