### ISSUE TITLE
FutureOr<T> gets interpreted as "dynamic"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dartdoc#1482]
Example:
https://www.dartdocs.org/documentation/io/0.2.0/io/isExecutable.html

**Comment by devoncarew** [comment]
Thanks for the report! Note that those docs were generated using dartdoc `0.12.0` - released circa late May.

**Comment by matanlurey** [comment]
Is it possible for me to opt-in to a newer version of dartdoc? If not it
doesn't really help 😖

**Comment by devoncarew** [comment]
> Is it possible for me to opt-in to a newer version of dartdoc?

On dartdocs.org? I'm not familiar enough with it to know. My guess would be no.

My note was more for @jcollins-g, so she didn't spend too much time tracking down something that may no longer be an issue in a current version of dartdoc.

I believe @kevmoo has a plan to support dartdocs.org, or something with similar functionality, in the not too distant future.

**Comment by kevmoo** [comment]
> I believe @kevmoo has a plan to support dartdocs.org, or something with similar functionality, in the not too distant future.

Well, hopefully this year...

**Comment by matanlurey** [comment]
I tried it out `@HEAD`, and it still prints `dynamic`:

<img width="377" alt="screen shot 2017-09-28 at 9 05 53 pm" src="https://user-images.githubusercontent.com/168174/31000503-d9bc86c4-a490-11e7-982e-00d91fbe4a1c.png">

I'm going to take a shot fixing it if it is trivial 😈

**Comment by matanlurey** [comment]
Must be some sort of analyzer bug or misconfiguration of the analysis engine/driver/context - the raw `DartType` and `Element` are both `dynamic`, and even return `false` for `DartType.isDartAsyncFutureOr`.

... wait, aha!

```dart
var options = new AnalysisOptionsImpl()
      ..enableAssertInitializer = true;
```

... I thought maybe it was a lack of `strongMode = true`, but doesn't look like that either.

**Comment by matanlurey** [comment]
Or... maybe it is? I do [see this in `analyzer`](https://github.com/dart-lang/sdk/blob/d4dec4e1a4b6b9743f299428890c18446f1c2b6b/pkg/analyzer/lib/src/generated/resolver.dart#L8050):

```dart
// In non-strong mode `FutureOr<T>` is treated as `dynamic`
if (!typeSystem.isStrong && type.isDartAsyncFutureOr) {
```

... so I'll keep digging.

**Comment by matanlurey** [comment]
Yup, there are two places `AnalysisContext` is created, and one wasn't strong mode!

This looks much better:

<img width="700" alt="screen shot 2017-09-28 at 9 52 28 pm" src="https://user-images.githubusercontent.com/168174/31001261-5ac190d8-a497-11e7-860f-96b725bf01f9.png">

**Comment by matanlurey** [comment]
Looks like this is getting fixed by https://github.com/dart-lang/dartdoc/pull/1611!
