### ISSUE TITLE
background color clashing with pre code and pre.prettyprint

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1487]
See

<img width="703" alt="screen shot 2017-08-30 at 4 23 11 pm" src="https://user-images.githubusercontent.com/17034/29899344-b6b648e8-8d9f-11e7-99ed-f98355adc241.png">

**Comment by devoncarew** [comment]
Kevin, can you provide a showing the issue? I don't see any problems w/ the hosted docs; https://api.dartlang.org/stable/1.24.2/dart-async/dart-async-library.html.

**Comment by kevmoo** [comment]
See latest:
https://api.dartlang.org/dev/1.25.0-dev.15.0/dart-async/dart-async-library.html

**Comment by devoncarew** [comment]
Thanks for the fix! I'm surprised this made it through my css update - seems like something I would have noticed.
