### ISSUE TITLE
Feature to show if hashCode and operator== are overridden

### ISSUE THREAD

**Issue by bergwerf** [dart-lang/dartdoc#1496]
For me it would be useful to be able to determine from the documentation if I can use a certain type as a Map key rather than finding out by trial and error (e.g. by comparing two instances manually). This also includes classes in the API docs. Of course this doesn't have a high priority but I would really appreciate it if such a feature could be implemented along the line. Or is it already there and am I missing it?

**Comment by jcollins-g** [comment]
In general, methods, operators, and fields will display "inherited" if they are inherited, and nothing if they are defined in the class you are looking at.  Can you give a particular example?

**Comment by bergwerf** [comment]
Ah, you are completely right. I overlooked this. When you click on it in the right side bar it will take you to the definition in Object (e.g. https://api.dartlang.org/stable/1.24.2/dart-core/Object/hashCode.html), unlike in package documentations (https://www.dartdocs.org/documentation/vector_math/2.0.4/vector_math/Vector2/hashCode.html). I am fine with the current behavior now I know to look for this text in the getters description. Of course it could be made more explicit somehow, but this is a very fine detail.
