### ISSUE TITLE
Error in dartdoc blocking Dart roll in Flutter

### ISSUE THREAD

**Issue by anders-sandholm** [dart-lang/dartdoc#1510]
_From @rmacnak-google on October 4, 2017 21:1_

dartdoc:stderr: Generation failed: Unknown type GenericFunctionTypeElementImpl
https://travis-ci.org/flutter/flutter/jobs/283373111

@jcollins-g @aam

_Copied from original issue: dart-lang/sdk#31008_

**Comment by anders-sandholm** [comment]
_From @rmacnak-google on October 4, 2017 21:9_

This type seems to come from the analyzer.
@bwilkerson @scheglov

**Comment by anders-sandholm** [comment]
_From @aam on October 4, 2017 21:12_

I found that upgrading to dartdoc to 0.13.0+3 worked in the past: https://github.com/flutter/flutter/commit/f6fe8dc7e3e961c067432e74f8a5fc089d7559b7#diff-a1ec403951c0ee8a36a3b4d2bc1fa797

**Comment by anders-sandholm** [comment]
_From @bwilkerson on October 4, 2017 21:20_

@jcollins-g

**Comment by anders-sandholm** [comment]
_From @jcollins-g on October 4, 2017 21:28_

Yes, you need >=0.13.0+3.

**Comment by anders-sandholm** [comment]
_From @jcollins-g on October 4, 2017 21:31_

The longer version is that 0.13.0+3 eliminates that fatal error, but in order to generate docs somewhat correctly you also need a release with dart-lang/dartdoc#1506 and dart-lang/dartdoc#1509.  I'll be releasing a version with that soon, hopefully tomorrow.

**Comment by jcollins-g** [comment]
0.13.0+3 is already at head (hence P1 priority).  Will use this to track rolling a newer version.
