### ISSUE TITLE
package.flushWarnings should be called rather than referenced as a Closure in package._withAutoIncludedDependencies

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1517]
https://github.com/dart-lang/dartdoc/blob/693fd88bc9ad21edcdbb7bc3cb48eaaab75c2d85/lib/src/model.dart#L3900

**Comment by devoncarew** [comment]
We should have a github label for `'oops'`.

**Comment by jcollins-g** [comment]
Yes.

**Comment by srawlins** [comment]
There is no longer any reference to flushWarnings.
