### ISSUE TITLE
Code blocks in markdown are too wide

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1522]
Code blocks stretch. Paragraphs are limited to 700px. The result looks weird-ish.

<img width="1425" alt="screen shot 2017-10-17 at 10 45 29 pm" src="https://user-images.githubusercontent.com/17034/31703265-bc2cb7a0-b390-11e7-8591-417cc2e0f55b.png">

**Comment by jcollins-g** [comment]
marking P2 - (minor display warts not impeding navigation, not widespread but not an edge case either)
