### ISSUE TITLE
Bizarre mid-word hyperlinking issue

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1535]
On the [SystemChannels.platform] page, there's a link to "OptionalMessageChannel", at least there should be, but somehow it's becoming a link to "MessageChannel", with only half the word hyperlinked???￼

https://master-docs-flutter-io.firebaseapp.com/flutter/services/SystemChannels/platform-constant.html

**Comment by jcollins-g** [comment]
I just ran into this by accident yesterday in my branch and have a patch coming with #1524.  This sort of thing happens with any constant due to a bug in how they're rendered.  It does some blind string substitution without paying attention to word boundaries, and misses escapes on types ala #1529.

**Comment by jcollins-g** [comment]
Also, the generated string (with hyperlinks!) is occasionally truncated on the enclosing element's page, creating ugly and invalid HTML.
