### ISSUE TITLE
Display branch name in addition to git hash

### ISSUE THREAD

**Issue by InMatrix** [dart-lang/dartdoc#1542]
This issue was raised in the context of using the Master branch of Flutter, but it might apply to other situations too. It's often not obvious to the user that the docs they're looking at did not match the version they were on. This has occurred to several users of Flutter who were on the Master branch but found the docs on Alpha. The Flutter Dart Doc already includes a Git hash in its footer, but it's too hard to notice and it's too much to expect users to remember the git hash of their reversion. 

Can we consider including the branch name of the code from which docs were generated in a more prominent place (e.g., the header)? Thanks!

**Comment by Hixie** [comment]
SGTM. Fixing this is just a matter of updating: https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart#L141

**Comment by Hixie** [comment]
(that is, this isn't a feature request for dartdoc, it's just something we can do ourselves in flutter land)
