### ISSUE TITLE
Allow fold out sections for more detailed/advanced docs

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1552]
From an [old dartdoc discussion](https://docs.google.com/document/d/1tndhthlM9jFls1kA5YvPj-LMiaNhp1uSAnRStpxB370/edit?ts=5a134f5e#heading=h.4tkns0pv6mna):

---snip---
We should also use sections inside member comments. I'm proposing that dartdoc recognizes Advanced sections and folds them by default. That is, a markdown section Advanced in a normal dartdoc comment is not visible by default, but can only be looked at by clicking on a '+' button.

```
/// Converts a double to its decimal string-representation.
///
/// # Advanced
/// The conversion algorithm must be accurate and follow the internal identity
/// requirement as specified in [Steele](http:// …).
///
/// If the output number requires more than 5 digits, it is expressed as an
/// exponential number.
/// ....String toString() { … }
```
---snip---

**Comment by srawlins** [comment]
Closing this in favor of https://github.com/dart-lang/dartdoc/issues/1876, a near duplicate.
