### ISSUE TITLE
Switching to strong mode creates broken link in Flutter, SDK

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1561]
@bwilkerson 

I attempted to revive #1507 and got it mostly working.  However, it currently causes dartdoc to generate an error that is too low priority to be worth the time investigating further at the moment.  To recap where I got:

Enabling strong mode results in this new warning from Flutter:
```
new: dartdoc:stdout: Validating docs...
new: dartdoc:stderr:   warning: dartdoc generated a broken link to: package-collection_collection/CombinedMapView/operator_put.html
new: dartdoc:stderr:     to element collection.CombinedMapView.[]=: (file:///usr/local/google/home/jcollins/dart/flutter/bin/cache/pkg/sky_engine/lib/collection/maps.dart:159:17)
new: dartdoc:stderr:     linked to from collection.CombinedMapView: (file:///usr/local/google/home/jcollins/.pub-cache/hosted/pub.dartlang.org/collection-1.14.3/lib/src/combined_wrappers/combined_map.dart:20:7)
```

Debugging this shows that the inheritance manager for the `CombinedMapView`'s superclass `UnmodifiableBase` fails to generate a `MultiplyInheritedExecutableElement` for the operator and gives the wrong element to dartdoc, causing dartdoc to generate the bad link.   We need to get the element for _UnmodifiableMapMixin's version of the operator to link correctly.   It's possible for this sort of thing to be invisible in other situations (where it happens to generate a link to a documented file), and I expect that to be the common case.  So until there's time to dig in here, I think strong mode should be avoided in dartdoc.  I'll see about adding an assert to catch this problem.

Screenshot of debugger when things are working (strongMode = false):

![success](https://user-images.githubusercontent.com/14116827/33672342-dd6129a2-da5e-11e7-9bc6-98868f4d5c90.png)

Screenshot of debugger when things are not working (strongMode = true):

![failing](https://user-images.githubusercontent.com/14116827/33672367-ec035ab6-da5e-11e7-9c1b-292fd082c7be.png)

**Comment by kevmoo** [comment]
Looking across a number of packages, the quality of the docs generated when strong-mode is enabled is SOOO much higher.

Any way we could look back into this?

**Comment by jcollins-g** [comment]
It's pretty inevitable that we'll have to -- we may just have to accept some broken or wrong links.  While I haven't given it a lot of thought, my gut says this is probably next up after the analysis driver.

**Comment by kevmoo** [comment]
Another curious ping 😄

**Comment by jcollins-g** [comment]
Switching on strong mode now _only_ results in this problem -- all other tests pass and docs generally look better.   I'll try to figure out why this bug happens.

**Comment by jcollins-g** [comment]
Have dug in more deeply and it looks like the analyzer is doing something more correct in strong mode: it is no longer marking inherited elements from classes as also coming from interfaces in some rare cases.  Dartdoc expected the old behavior, resulting in this rare bug.  This looks likely to be fixable without analyzer changes -- working on that now.

**Comment by kevmoo** [comment]
![](https://media.giphy.com/media/nKG86WRlokFfW/giphy.gif)

**Comment by jcollins-g** [comment]
(this is P1 as non-strong mode will not be supported post Dart 2.0)

**Comment by kevmoo** [comment]
Agreed!
