### ISSUE TITLE
Some lists are getting collapsed

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1587]
Some, but not all, markdown lists are getting turned into run-on paragraphs.

Cases I noticed are broken:

https://master-docs-flutter-io.firebaseapp.com/flutter/flutter_test/hasAGoodToStringDeep-constant.html (last paragraph)
https://master-docs-flutter-io.firebaseapp.com/flutter/flutter_test/throwsAssertionError.html (last paragraph)
https://master-docs-flutter-io.firebaseapp.com/flutter/flutter_test/WidgetTester/hasRunningAnimations.html

Cases where it still works:

https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/StatefulWidget-class.html
https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/Widget-class.html

From what I can tell, lists in `flutter_test` don't work, lists in `flutter` do.

**Comment by jcollins-g** [comment]
This was fixed by #1612.
