### ISSUE TITLE
Add option to ignore analyzer errors - or at least CompileTimeErrorCode.URI_HAS_NOT_BEEN_GENERATED

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1595]
https://github.com/dart-lang/dartdoc/blob/4a009a036165574ec8681b058e9d7a6aebaaf743/lib/dartdoc.dart#L139

In the case of https://github.com/dart-lang/angular_components/issues/207, the error is `CompileTimeErrorCode.URI_HAS_NOT_BEEN_GENERATED`

We could just ignore these errors – or treat them as warnings to see if anything else fails

Or we could just add a flag to ignore errors.

**Comment by devoncarew** [comment]
I think we should rely on the analysis_options.yaml file here, and just make sure dartdoc respects it. Should be fixed as part of https://github.com/dart-lang/dartdoc/issues/1586.

**Comment by jcollins-g** [comment]
I'll be working on #1586 first thing after dartconf, but if that takes too long we might consider the intermediate step Kevin suggested in a patch release (if this blocks angular?)

**Comment by jcollins-g** [comment]
Migrating to the new analysis driver is not enough in and of itself to fix analysis_option handling.  More details written up in #1586.  However, the workaround is simple enough and I'll work on making that happen instead.
