### ISSUE TITLE
flutter docs generated from head don't know about Dart Core

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1601]
Since the analysis driver transition in #1598 it looks like Flutter docs call Dart "Sky Engine" instead of recognizing those libraries are the dart SDK.   Probably something wrong with how we're doing embedded SDKs again -- that was it last time this happened (#1107).

**Comment by jcollins-g** [comment]
This was found thanks to the development of #1600, woo.

**Comment by scheglov** [comment]
The driver gets already created `SourceFactory`, with SDK and packages configured.

I see that we handle `_embedder.yaml` in [ContextBuilder](https://github.com/dart-lang/sdk/blob/30fa9c93afd960ae0695e0b1d6cb427cf7a2cbbf/pkg/analyzer/lib/src/context/builder.dart#L370).

**Comment by jcollins-g** [comment]
We do something similar in dartdoc too, but apparently what we needed to do changed subtly (and because I didn't have #1600 yet I didn't notice it right away).

**Comment by jcollins-g** [comment]
Changing to P0, because this also impacts navigation as canonicalization loses its mind when it doesn't have an SDK.  Dartdoc emits hundreds of warnings and mislinks things due to canonicalization errors.  Fortunately, we haven't shipped a release with the driver change yet.
