### ISSUE TITLE
Allow running from Dart code.

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1609]
For the `dartdocs.org` site, it would be better if we could run `dartdoc` without executing a new process. The current `bin/dartdoc.dart` does a lot of heavy lifting, and also one-off environment setup, and copying that is not straightforward.

Is there a way to simply call a method to run `dartdoc` repeatedly from the Dart code?

**Comment by jcollins-g** [comment]
Not possible at the moment; dartdoc has too many things depending on command line arguments that are assumed to be global.

**Comment by jcollins-g** [comment]
#1676 fixes this.  With that PR I think it's at least feasible to run dartdoc without fork and exec.  Issues with doing so should be filed as separate bugs after that lands.
