### ISSUE TITLE
Match GitHub fonts for pretty print

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1644]
The current font makes certain table lines too long.

- GitHub: https://github.com/desktop-dart/text_table
- Dartdoc: https://www.dartdocs.org/documentation/text_table/2.5.3/

GitHub uses `font-family: "SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace;` which the pub site will match. I'm happy to create a PR here too, just wanted to check if there is any preference of one font over the other.

**Comment by jcollins-g** [comment]
I have no preference; please go ahead and file a PR preferably with screenshot(s).
