### ISSUE TITLE
Encourage use of `ignore` instead of `ignore_for_file`

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/dartdoc#1649]
In TOH examples, Use of `ignore_for_file` is encouraged instead of `ignore`

Less robust :
```dart
// ignore_for_file: uri_has_not_been_generated
import 'heroes_component.template.dart' as hct;
```

More robust : 
```dart
// ignore: uri_has_not_been_generated
import 'heroes_component.template.dart' as hct;
```

A new user reading TOH docs will not be familiar with how import paths work, in this situation globally disabling linting rules is not good. 

Also in git repositories of examples, `uri_has_not_been_generated` linting rule is globally disabled.

**Comment by kwalrath** [comment]
@chalin can you comment? (Not sure why this is in dartdoc instead of site-webdev.)

**Comment by chalin** [comment]
@dineshbhosale - are you suggesting that the analyzer understands a directive named `ignore`? As far as I know it does not. If you still think that this is a real issue, please **reopen this issue over site-webdev**.

**Comment by dineshbhosale** [comment]
I opened this in wrong place, I'm new to angular dart , sorry.

**Comment by kwalrath** [comment]
Thanks for letting us know when you find issues, @dineshbhosale. It's very good for us to see what new users encounter.
