### ISSUE TITLE
library references should be URIs, not the library name

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1658]
See
https://pub.dartlang.org/documentation/angular/5.0.0-alpha+9/index.html

![screen shot 2018-04-02 at 10 39 52 am](https://user-images.githubusercontent.com/17034/38207312-352bcaac-3662-11e8-8136-d03c447954b5.png)

Doesn't help

Should be

```
angular.dart
builder.dart
core.dart
di.dart
experimental.dart
security.dart
```

These are the actual files I'd import.

...and more painfully
https://pub.dartlang.org/documentation/angular_components/0.9.0-alpha+9/index.html

In this case, there are many libraries named `module` – no way to tell them apart.

Better to have long URIs than ambiguous names...

**Comment by jcollins-g** [comment]
Yeah, that's a problem.

We should remove all usages of library names in dartdoc.   I think this is likely the main thing blocking dart-lang/sdk#32738; most other pieces of the ecosystem either don't care about the library name at all or don't use it for important things.

**Comment by kevmoo** [comment]
So I went through googleapis and got rid of pointless `library XYZ;` names - https://github.com/google/googleapis.dart/commit/a4e0b03a8c912609fec5b43cdb73dec5c56ede02 – cool 2.19 feature @srawlins !

Guess what?

Before: 
![image](https://user-images.githubusercontent.com/17034/226449024-f561b37a-ed67-4675-baab-5084d343dd53.png)

After:
![image](https://user-images.githubusercontent.com/17034/226449104-9b73dfe4-d482-4850-80e3-dfcda461f13b.png)

We should really fix this!

**Comment by kevmoo** [comment]
FYI: all of those `v1` things map to `compute/v1.dart`, `ml/v1.dart` etc etc

**Comment by srawlins** [comment]
Whoa. Mega cringe.

**Comment by jcollins-g** [comment]
What if the import URIs were available via mouseover and on the library pages themselves, and we started warning for duplicate library names in the same package?   No matter what compressed form we choose for the left sidebar there are going to be cases where the user will want to override that -- and there already is a way to do that, the `library foo;` statement.   It's true that it has been deemphasized but I doubt it's going to go away entirely as long as part files exist.    We might as well make use of it for its ability to label libraries.

**Comment by natebosch** [comment]
> but I doubt it's going to go away entirely as long as part files exist.

We also prefer that part files refer to the library they are part of by URI and not library name.
https://dart.dev/guides/language/effective-dart/usage#do-use-strings-in-part-of-directives

**Comment by srawlins** [comment]
@kevmoo I have a WIP that looks like this, WDYT?

<img width="473" alt="Screenshot 2023-10-20 at 8 43 51 AM" src="https://github.com/dart-lang/dartdoc/assets/103167/6098bc5c-d435-4bc4-b9f3-b50f36e74b42">

<img width="957" alt="Screenshot 2023-10-20 at 8 44 08 AM" src="https://github.com/dart-lang/dartdoc/assets/103167/9d0ed1a7-7f0d-45af-8902-34f4868122f5">

This does cause some library names to be truncated with a `...`, but I can fix that as well by making the left panel horizontally scrollable, for https://github.com/dart-lang/dartdoc/issues/1043. (I think making the names wrap lines would make it an unreadable mess.)

**Comment by natebosch** [comment]
> I can fix that as well by making the left panel horizontally scrollable

Good plan. How about we also save a few characters of space and strip the `.dart`?

> I think making the names wrap lines would make it an unreadable mess.

+1

**Comment by srawlins** [comment]
I guess I'm conflating two issues, but adding ".dart" solves https://github.com/dart-lang/dartdoc/issues/1000 as well.

I could use, for example, `v1/admob` in the sidebar, and `v1/admob.dart` in the heading?

**Comment by srawlins** [comment]
Yeah a tooltip is a good idea too. Probably better UX.

**Comment by natebosch** [comment]
> I could use, for example, `v1/admob` in the sidebar, and `v1/admob.dart` in the heading?

I think that could work. It would also be OK to retain the `.dart` in the sidebar - but the repetition is somewhat distracting IMO.

**Comment by kevmoo** [comment]
Since EVERY import will end in `.dart` dropping it SGTM!

Maybe include it in the tooltip?
