### ISSUE TITLE
Dartdoc does not run under --preview-dart-2

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1668]
A number of (mostly runtime) exceptions occur within dartdoc and mustache4dart, the templating package dartdoc uses.

This is distinct from dartdoc understanding dart 2 code; it does this already.

- [x] Analyzer must support running under --preview-dart-2
- [x] Dartdoc unit tests must pass under --preview-dart-2
- [x] Dartdoc smoke test (self-document) must pass under --preview-dart-2
- [x] Dartdoc must generate valid SDK docs under --preview-dart-2
- [x] Dartdoc must generate valid flutter docs under --preview-dart-2.
- [x] SDK bug must be fixed: https://github.com/dart-lang/sdk/issues/32901

**Comment by devoncarew** [comment]
Note: mustache4dart has not been updated in 10 months https://github.com/valotas/mustache4dart

**Comment by devoncarew** [comment]
https://github.com/valotas/mustache4dart/pull/70

**Comment by jcollins-g** [comment]
@devoncarew I have some changes to mustache4dart on deck.  I'll upload a PR once I have a steel thread through dartdoc.

**Comment by jcollins-g** [comment]
With #1669, this is almost ready to go.  But we're blocked on pub run support, an analyzer package, and dart-lang/sdk#32901.

**Comment by jcollins-g** [comment]
Attempting this end to end has uncovered more things we need to tweak in library dependencies.

**Comment by jcollins-g** [comment]
Analyzer publish has happened; once test package is updated we can move to the new analyzer with preview-dart-2 support.

**Comment by jcollins-g** [comment]
Tests pass with the bleeding edge SDK.  Will switch snapshots in the SDK immediately, then follow up with a new dartdoc release.

**Comment by jcollins-g** [comment]
Building a snapshot seems to have stronger requirements than running with --preview-dart-2.  This error had never shown up in previous testing.

```
[1/1] Regenerating ninja files
[5/13] ACTION //utils/dartdoc:dartdoc(//build/toolchain/linux:clang_x64)
FAILED: gen/dartdoc.dart.snapshot 
python ../../build/gn_run_binary.py compiled_action dart --deterministic --packages=/usr/local/google/home/jcollins/dart/sdk/sdk/.packages --snapshot=gen/dartdoc.dart.snapshot --snapshot-depfile=/usr/local/google/home/jcollins/dart/sdk/sdk/out/ReleaseX64/gen/dartdoc.dart.snapshot.d --preview-dart-2 --snapshot-kind=app-jit /usr/local/google/home/jcollins/dart/sdk/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart --help
Command failed: ./dart --deterministic --packages=/usr/local/google/home/jcollins/dart/sdk/sdk/.packages --snapshot=gen/dartdoc.dart.snapshot --snapshot-depfile=/usr/local/google/home/jcollins/dart/sdk/sdk/out/ReleaseX64/gen/dartdoc.dart.snapshot.d --preview-dart-2 --snapshot-kind=app-jit /usr/local/google/home/jcollins/dart/sdk/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart --help
output: Generate HTML documentation for Dart libraries.

Usage: dartdoc [OPTIONS]

Unhandled exception:
Failed assertion: boolean expression must not be null
#0      Usage.calculateColumnWidths (package:args/src/usage.dart)
#1      Usage.generate (package:args/src/usage.dart:61:5)
#2      ArgParser.usage (package:args/src/arg_parser.dart:318:56)
#3      _printUsageAndExit (file:///usr/local/google/home/jcollins/dart/sdk/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:103:16)
#4      _printHelpAndExit (file:///usr/local/google/home/jcollins/dart/sdk/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:97:3)
#5      main (file:///usr/local/google/home/jcollins/dart/sdk/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:60:5)
<asynchronous suspension>
#6      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

ninja: build stopped: subcommand failed.
BUILD FAILED
~/dart/sdk/sdk
$ 
```
