### ISSUE TITLE
dartdoc does not obey analysis_options files

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1672]
#1586 initially assumed that porting over to the analysis driver would make dartdoc obey analysis_options files.  This turned out not to be the case, but a new bug was not filed to make it clear that dartdoc does not do that.

**Comment by jcollins-g** [comment]
This is blocked on the new analyzer API.

**Comment by srawlins** [comment]
I don't see anything in analysis_options.yaml that should be particularly followed by dartdoc. We can re-open with an example.
