### ISSUE TITLE
how to run dartdoc as a package?

### ISSUE THREAD

**Issue by wendux** [dart-lang/dartdoc#1679]
I want to change the html templates in source code to custom my website.  I add the package dependences in` pubspec.yml`
```yml
  dartdoc:
    git:
      url: "https://github.com/dart-lang/dartdoc.git"
```
and then, I run `pub run dart doc`, but get the errors as follows:
```
Unhandled exception:
NoSuchMethodError: Class 'ArgParser' has no instance method 'addMultiOption'.
Receiver: Instance of 'ArgParser'
Tried calling: addMultiOption("hosted", abbr: null, defaultsTo: Instance(length:1) of '_GrowableList', help: "Specify URLs for hosted pub packages", hide: null, splitCommas: null)
#0      Object.noSuchMethod (dart:core-patch/dart:core/object_patch.dart:46)
#1      DartdocOption&&_DartdocArgOption._onAdd (package:dartdoc/src/dartdoc_optio
```

**Comment by jcollins-g** [comment]
Hi @wendux,

I suggest not using git for your package dependencies, as you may get unstable code that way.  The typical way to run dartdoc from a package is:

```sh
pub global activate dartdoc
pub global run dartdoc
```

**Comment by wendux** [comment]
Thanks, because I want to change  html templates in source code to custom my website style , so I fork the repo and custom the style ,  and  depend this my branch   .

**Comment by jcollins-g** [comment]
What version of dart are you using, and can you share the complete contents of your pubspec.yaml?  (At least, any parts of pubspec.yaml that refer to public packages).

**Comment by jcollins-g** [comment]
Closing, please reopen if you have more information.
