### ISSUE TITLE
Support categories for member APIs

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#1681]
For packages with many different APIs of a given type, it's useful to divide those APIs into categories rather than having them all sorted alphabetically. For example, in [`test`'s docs](https://www.dartdocs.org/documentation/test/latest/test/test-library.html), there are so many matcher functions that it's hard for users to notice non-matcher functions like `pumpEventQueue()`. It would be very useful to be able to put the matchers in their own sub-section beneath "Functions" to keep everything organized. It would be similarly useful to be able to group classes, fields, and so on.

This is possible today with [the `{@category}` annotation](https://github.com/dart-lang/dartdoc/blob/master/README.md#categories), but that only works for libraries. I'd love to see it generalized.

**Comment by devoncarew** [comment]
The docs for atom.io do something similar - even for classes w/o a lot of methods, they break up the API into semantic categories:

https://atom.io/docs/api/v1.26.1/NotificationManager

**Comment by jcollins-g** [comment]
I have generic categorization support in a local branch.  It's coming.

**Comment by jcollins-g** [comment]
Categorization support is shaping up nicely and will be displayed as "api" and "APIs" in dartdoc generated pages.  I'm working on the style bits and category page generation now.

**Comment by nex3** [comment]
How long does it take for a change like this to percolate out into pub.dartlang.org/documentation?

**Comment by jcollins-g** [comment]
I am planning to publish this week, tomorrow if I can.  Afterwards the pub site maintainers have to pick it up, but they typically do that within a few days.

**Comment by nex3** [comment]
I'm guessing this is live now? Is there any way to tell for sure?

**Comment by nex3** [comment]
It doesn't seem to be working locally for https://github.com/sass/dart-sass/commit/cf2e4167e6b1a02df248189e8fd3a1c87ec9417c with 0.21.1. The class list looks the same as ever.

**Comment by jcollins-g** [comment]
It's not clear enough in the docs.   I forgot to mention that if the categories are not declared in dartdoc_options.yaml, they're otherwise invisible in the generated docs.

See examples [here](https://github.com/dart-lang/dartdoc/blob/master/README.md#dartdoc_optionsyaml) and [here](https://github.com/dart-lang/dartdoc/blob/master/testing/test_package/dartdoc_options.yaml).

**Comment by nex3** [comment]
I've definitely got DartDoc recognizing the categories now, but it's still not using them to sort either the right-hand column or the main member list.

![sass-categories](https://user-images.githubusercontent.com/188/45977902-ba6be900-bfff-11e8-95aa-8f382b2afb1c.png)

**Comment by jcollins-g** [comment]
This is currently working as intended.  To get a sorted list of importers, you click on "importers" and then only importers are displayed.  Same with "values".

Admittedly this is a bit different than the way categories were handled for libraries, previously.  I take it you'd like it do this?  It wasn't clear to me that that was a win, but we can do that.

**Comment by nex3** [comment]
I would like that. I'd actually prefer it to having an alphabetical list of tagged classes.

**Comment by jcollins-g** [comment]
@nex3 I'll poll the other stakeholders and if I can get some broad agreement there, I'll implement it.

**Comment by virgule-xyz** [comment]
categories: they are displayed under a Topics section on the left. To be displayed you need to create a markdown file where the content is the description of the topic.

![Capture d’écran 2020-03-23 à 15 14 53](https://user-images.githubusercontent.com/7458151/77325980-65568380-6d19-11ea-8dec-5c9e4dd84365.png)
