### ISSUE TITLE
dartdoc ignores analysis errors outside of a package's public library files

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1695]
Analysis errors outside the package's public library files can still impact document generation by making it impossible to link to outside packages with --link-to-remote.  Also, we might generate docs for packages like pana that are incomplete without warning the user, because the only thing the public library files do in that package is reexport private libraries.

Workaround is to make sure that the package analyzes correctly outside dartdoc.

**Comment by srawlins** [comment]
I don't believe this has been an issue for some time. Closing for now.
