### ISSUE TITLE
Left library sections

### ISSUE THREAD

**Issue by marcguilera** [dart-lang/dartdoc#1706]
I'm probably misunderstanding how dartdoc generates docs but here is what I do:

<img width="181" alt="screen shot 2018-06-03 at 12 13 35 am" src="https://user-images.githubusercontent.com/7732696/40881432-c404e4a4-66c6-11e8-919e-f03dc6e8c290.png">

I don't understand how LIB.CORE is properly being bundled generated when the code I use to document is similar in the other libraries:

```
/// Models, entities and data access.
library lib.core.data;
```

```
/// The library for the redux store.
library lib.client.core.redux;
```

Ideally, I would like the LIBARY title to be LIB.CLIENT.CORE. I have tried playing with the `@category` tag with little success. For bonus points I would prefer LIB.CORE to be at the top an LIB.CLIENT.CORE to be at the bottom.

**Comment by jcollins-g** [comment]
"LIBRARIES" is the name of the category containing all libraries not tagged with the category tag.  If you wish it to go away and be replaced by something else, you can tag those libraries with a `@category LIB.CLIENT` tag.  The categoryOrder field in dartdoc_options.yaml (see README) can change the order in which the categories appear -- just specify a different order there.

**Comment by jcollins-g** [comment]
Hi @marcguilera , were you able to resolve your issue?

**Comment by jcollins-g** [comment]
Please reopen if you are still having trouble.
