### ISSUE TITLE
Adding anchors to headings in API docs

### ISSUE THREAD

**Issue by InMatrix** [dart-lang/dartdoc#1720]
This is feedback from a study participant:

> Another thing I've noticed when helping people online with Flutter is that I would like to link them to a specific heading. For instance, If I want to link to "Dynamically determining the children during the build phase" on https://docs.flutter.io/flutter/widgets/RenderObjectElement-class.html the site doesn't produce anchor tags and I can no easy "link ux" to grab a link to send to someone.

I thought it's a good idea, since some of Flutter's API docs are quite long.

**Comment by slightfoot** [comment]
@InMatrix thanks for reposting

**Comment by jcollins-g** [comment]
duplicate of #1710
