### ISSUE TITLE
List markdown not rendered as an HTML list

### ISSUE THREAD

**Issue by chalin** [dart-lang/dartdoc#1722]
See https://github.com/dart-lang/sdk/blob/5b5e36f0be3994c7c889848cf0f5b210456afc59/pkg/meta/lib/meta.dart#L176-L189:

```dart
/// Used to annotate a named parameter `p` in a method or function `f`.
/// Indicates that every invocation of `f` must include an argument
/// corresponding to `p`, despite the fact that `p` would otherwise be an
/// optional parameter.
///
/// Tools, such as the analyzer, can provide feedback if
///
/// * the annotation is associated with anything other than a named parameter,
/// * the annotation is associated with a named parameter in a method `m1` that
///   overrides a method `m0` and `m0` defines a named parameter with the same
///   name that does not have this annotation, or
/// * an invocation of a method or function does not include an argument
///   corresponding to a named parameter that has this annotation.
const Required required = const Required();
```

This is rendered as follows (see https://pub.dartlang.org/documentation/meta/latest/meta/required-constant.html):

> Used to annotate a named parameter p in a method or function f. Indicates that every invocation of f must include an argument corresponding to p, despite the fact that p would otherwise be an optional parameter.
> 
> Tools, such as the analyzer, can provide feedback if
> 
> the annotation is associated with anything other than a named parameter, the annotation is associated with a named parameter in a method m1 that overrides a method m0 and m0 defines a named parameter with the same name that does not have this annotation, or an invocation of a method or function does not include an argument corresponding to a named parameter that has this annotation.

cc @kwalrath @Sfshaza

**Comment by kwalrath** [comment]
And yet it's working in https://api.dartlang.org/be (the homepage has bullets). What's the difference?

**Comment by jcollins-g** [comment]
Homepage is rendered via a different path.

The whitespace / comment character stripping has been a cause of bugs like this before.

**Comment by Sfshaza** [comment]
I was wondering if it didn't work because of the 3-slashes - did you try 2?

I tried all sorts of things and couldn't get this to work properly on flutter.io.

**Comment by kwalrath** [comment]
2 slashes wouldn't show up in the doc comment at all. This is just a bug, but a fairly serious one.

@jcollins-g can we please get a P1?

**Comment by jcollins-g** [comment]
Elevating as bullet points not showing up correctly is a more widespread problem
