### ISSUE TITLE
Lingering type parameters in API of X implements List<int>

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#1725]
Take [Uint8List](https://api.dartlang.org/dev/2.0.0-dev.68.0/dart-typed_data/Uint8List-class.html), which `implements List<int>`. In this class there is no `<E>` type parameter (that's the `int` in `List<int>`). But E's continue to show up in the documentation. Scroll down that main page to see:

* `any(bool test(E element)) → bool`
* `expand<T>(Iterable<T> f(E element)) → Iterable<T>`
* `map<T>(T f(E e)) → Iterable<T>`
* `reduce(int combine(E value, E element)) → int`

etc. Note that `int` is found in a few places though:

* `addAll(Iterable<int> iterable) → void`
* `asMap() → Map<int, int>`
* `firstWhere(bool test(E element), { int orElse() }) → int`

**Comment by jcollins-g** [comment]
Looks like type resolution is incomplete here for methods inherited from Iterable (which is where the E seems to be coming from).  I believe there's enough information in the analyzer for us to know better.

**Comment by srawlins** [comment]
This looks to have been fixed at some point, woohoo! https://api.dart.dev/stable/2.9.3/dart-typed_data/Uint8List-class.html
