### ISSUE TITLE
Avoid @pragma in documentation

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dartdoc#1726]
The VM is adding `@pragma` annotations to the SDK source (https://dart-review.googlesource.com/c/sdk/+/65545). These must not show up in the API documentation. Pragma annotations are, by definition, only intended for specific tools, not for users, and there is only negative value in exposing them.

**Comment by jcollins-g** [comment]
This is another "special" object we need to cloak and provide more generic support in Dartdoc for this.

**Comment by jcollins-g** [comment]
Special object handling was made more generic in #1729 so this should be a little easier now.

**Comment by jcollins-g** [comment]
`@pragma`s are popping up in more places and breaking Dartdoc internal tests without either a fix for this or the tests.

https://travis-ci.org/dart-lang/dartdoc/jobs/415682622
