### ISSUE TITLE
CONTRIBUTING.md links to broken "dartdoc API" page

### ISSUE THREAD

**Issue by athomas** [dart-lang/dartdoc#1731]
> This page: https://github.com/dart-lang/dartdoc/blob/master/CONTRIBUTING.md
> 
> with the text "dartdoc API" links to this: https://dartdoc.firebaseapp.com/
> 
> which gives a page with this message (among other information): 
> 
> "Project Import Required
> This Firebase project is out of date and requires import into Google Cloud Platform to resume service."
> 
> Hope this is helpful.
> 
> Joshua

**Comment by jcollins-g** [comment]
This should link to the package docs hosted on pub.
