### ISSUE TITLE
support the new super mixins

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1752]
The overall tracking issue is here: https://github.com/dart-lang/language/issues/12.

This is the dartdoc specific issue for supporting the new super mixins feature.

**Comment by jcollins-g** [comment]
Marking as blocked until at least some level of support in analyzer (dart-lang/sdk#34164) is available.

**Comment by jcollins-g** [comment]
Still blocked for completion (will require a version of build to be published that supports the new analyzer as well).  However, I have wired this up enough now to know that the new analyzer support works well enough to treat the new mixin declarations as ordinary classes.

I think the right thing to do here is to treat these similarly to how we treat enums; as a special type of class with different labeling.

**Comment by jcollins-g** [comment]
Landing this, and a dartdoc publish is blocked on this: https://github.com/dart-lang/build/pull/1873  and a new analyzer publish which should happen in the next day or so.

**Comment by jcollins-g** [comment]
As pointed out in dart-lang/build#1873, there is a workaround available for us to publish without new build versions, so we're really only blocked for certain on a new analyzer publish.
