### ISSUE TITLE
Request: get all subclasses for a class

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#176]
We'll need this for the Class page.

**Comment by keertip** [comment]
This information is not contained in the analyzer model. Dartdoc would have to compute this info.

**Comment by sethladd** [comment]
Understood. Is it possible to wire something up to use in the template?

**Comment by keertip** [comment]
in #213

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
Hi Keerti, how does #213 provide "given a class, get all of its subclasses" ?

I see "get all of its implementors".

I'm looking for a way to say: "given a class, tell me everyone that extends it" and "given a class, tell me everyone that implements it"

**Comment by sethladd** [comment]
So maybe the question is, does this distinction actually matter?

**Comment by sethladd** [comment]
I think the distinction for "show my subclasses" and "show what implements me" is a worthwhile distinction.

it's the distinction between "is-a" and "acts-like"

**Comment by sethladd** [comment]
Discussed this with @keertip and we're going to test a flat list of all "implementors".
