### ISSUE TITLE
Fix English language errors on captions for related objects to classes

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1766]
Currently, class documentation includes several lists of objects related to them and they have captions, as you can see  here for "Inheritance" and "Mixes-in".

![screenshot from 2018-09-27 15-15-59](https://user-images.githubusercontent.com/14116827/46178255-f0f96c00-c26a-11e8-8b5d-ac396c83c1e4.png)

The complete current list:

* "Inheritance" shows the chain of superclasses starting at this object.
* "Implements" shows any classes listed in the "implements" clause of the class/mixin declaration.
* "Mixes-in" shows any classes or mixins listed in the "with" clause of the class declaration.
* "Implemented by" shows any classes or mixins listing this class in their "implements" clause.
* "Annotations" shows any annotations declared with `@annotation` prior to the class declaration.

These are inconsistent at best.  @kwalrath, what is your opinion on replacement phrases?

**Comment by kwalrath** [comment]
If we did all verb phrases, we'd have something like this:
* Inherits from
* Implements
* Mixes in
* Implemented by (implicit "Is")
* (but what to do for Annotations?)

If we did all noun phrases, it might be something like this:
* Inheritance
* Implemented types
* Mixed in types
* Implementers
* Annotations

Noun phrases seems more doable.
