### ISSUE TITLE
remove the use of the older super mixins

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1772]
As part of supporting the new super mixins, the runtime implementations will remove support for the older style super mixins. The dartdoc codebase is one client that uses the older style super mixins, so it should either move to the new super mixins, or move off super mixins.

@jcollins-g

**Comment by devoncarew** [comment]
https://github.com/dart-lang/dartdoc/blob/master/analysis_options.yaml#L3

**Comment by jcollins-g** [comment]
This will require some refactoring once the new mixin support is in place.
