### ISSUE TITLE
Remove dependencies on package:front_end implementation details.

### ISSUE THREAD

**Issue by peter-ahe-google** [dart-lang/dartdoc#1775]
Please update the following imports to use package:analyzer instead:

```
lib/src/model.dart:import 'package:front_end/src/byte_store/byte_store.dart';
lib/src/model.dart:import 'package:front_end/src/base/performance_logger.dart';
```

These imports can be used instead:

```
package:analyzer/src/dart/analysis/byte_store.dart
package:analyzer/src/dart/analysis/performance_logger.dart
```

Files in /src/ by convention are  implementation details and shouldn't be relied on, so I encourage coordinating with the analyzer team to find a stable public API that can replace these implementation details.

**Comment by peter-ahe-google** [comment]
FYI: These imports are blocking:

* https://dart-review.googlesource.com/c/sdk/+/77760
* https://dart-review.googlesource.com/c/sdk/+/77761

**Comment by jcollins-g** [comment]
Yes, a more stable public API is a long term goal for analyzer.  Setting as P1 as it looks like this is blocking some moderately important CLs.

**Comment by peter-ahe-google** [comment]
@jcollins-g Thank you for giving this a high priority.

**Comment by jcollins-g** [comment]
@peter-ahe-google There's a lot of high priority stuff flying around, but I'll do what I can to get this rolled into the SDK ASAP.

**Comment by peter-ahe-google** [comment]
Thanks again.
