### ISSUE TITLE
Search box broken for this one weird page in analyzer docs

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1776]
_From @srawlins on September 19, 2018 16:49_

Steps:

1. Load https://pub.dartlang.org/documentation/analyzer/latest/dart_element_element/LibraryElement-class.html

Expected results:

Search bar should be enabled, but it's disabled, with placeholder "Loading search...". Console has following:

```
Uncaught ReferenceError: module is not defined
    at typeahead.bundle.min.js:7
    at typeahead.bundle.min.js:7
highlight.pack.js:2 Uncaught ReferenceError: hljs is not defined
    at highlight.pack.js:2
URI.js:3 Uncaught ReferenceError: module is not defined
    at URI.js:3
    at URI.js:3
script.js:196 Uncaught ReferenceError: hljs is not defined
    at HTMLDocument.<anonymous> (script.js:196)
```

I tried CTRL+SHIFT+R, Incognito mode, no luck. This is with Chrome 69.0.3497.81 (Official Build) (64-bit) on Linux. Search seems to work for other pages, like https://pub.dartlang.org/documentation/analyzer/latest/dart_element_element/ClassElement-class.html.

_Copied from original issue: dart-lang/pub-dartlang-dart#1633_

**Comment by isoos** [comment]
This seems to be a network (or datastore bucket) issue:
- after generating the dartdoc content: it works
- after applying pub-site-related customization: it works (verified by downloading the `package.tar.gz` archive and hosting it locally
- ~20 minutes ago the bug was present as the original description (I was able to see the same JS error), but as of now it works.

**Comment by isoos** [comment]
_From @srawlins on September 20, 2018 12:31_

Phew, that makes sense; I can't imagine why else only _that_ page would be broken. Thanks @isoos !

**Comment by isoos** [comment]
_From @sortie on September 20, 2018 12:45_

It doesn't work for me. I see Javascript errors in the console.

```
[Deprecation] Using unescaped '#' characters in a data URI body is deprecated and will be removed in M71, around December 2018. Please use '%23' instead. See https://www.chromestatus.com/features/5656049583390720 for more details.
LibraryElement-class.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/sourcesanspro/v11/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7l.woff2
LibraryElement-class.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/sourcecodepro/v7/HI_SiYsKILxRpg3hIP6sJ7fM7PqlPevW.woff2
LibraryElement-class.html:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdu.woff2
typeahead.bundle.min.js:7 Uncaught ReferenceError: module is not defined
    at typeahead.bundle.min.js:7
    at typeahead.bundle.min.js:7
highlight.pack.js:2 Uncaught ReferenceError: hljs is not defined
    at highlight.pack.js:2
URI.js:3 Uncaught ReferenceError: module is not defined
    at URI.js:3
    at URI.js:3
script.js:196 Uncaught ReferenceError: hljs is not defined
    at HTMLDocument.<anonymous> (script.js:196)
```

**Comment by jcollins-g** [comment]
Setting to P3 (very rare problem with workaround).

**Comment by parlough** [comment]
This should be fixed by https://github.com/dart-lang/dartdoc/pull/2486
