### ISSUE TITLE
method arguments with typedefs don't render correctly in dartdocs

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1778]
e.g. the onError argument in https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/precacheImage.html renders as "void onError" instead of saying "ImageErrorListener", as per https://master-docs-flutter-io.firebaseapp.com/flutter/painting/ImageErrorListener.html.

cc @gspencergoog

**Comment by jcollins-g** [comment]
This is a subcase of one of the issues fixed in #1765 and so will be fixed when that lands.  Tested with it to verify.
