### ISSUE TITLE
Overriding getter with member variable causes docs to get lost

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dartdoc#1779]
Consider the following:

```dart
library foo;

/// Base class docs
class Base {
  /// Great, thorough documentation
  bool get foo => true;
}

/// Subclass docs
class Sub extends Base {
  @override
  final bool foo = false;
}
```

When I look up the dartdocs for `Sub.foo`, I expect to see "Great, thorough documentation".  Yet there are no docs for `Sub.foo`.

**Comment by jcollins-g** [comment]
This is another case that was fixed in as part of cleanups for #1765 and will be fixed when this lands.  #1781 adds a specific test for this case.
