### ISSUE TITLE
Enhance dartdoc to detect fuchsia-style "packages"

### ISSUE THREAD

**Issue by zanderso** [dart-lang/dartdoc#1783]
From the downstream bug:

> We do not maintain pubspec.yaml files in the Fuchsia tree and instead generate .packages files from our build files. It should not be too hard to teach dartdoc to look at the latter when looking for package references.

/cc @jcollins-g

**Comment by jcollins-g** [comment]
This is #1746.

**Comment by jcollins-g** [comment]
I closed this out, but I want to be certain this is a duplicate.  Are you saying that you have another way of generating a .packages file (which is how I heard that), or that you have an alternative way of defining groups of code that would otherwise be called "packages".

If there is an alternative way we should be using to detect bundles of Dart code that map to packages within dartdoc, this is a separate bug.

@zanderso

**Comment by zanderso** [comment]
Right, there are apps and libraries in the Fuchsia tree that don't have a pubspec.yaml file. Instead of pub generating a .packages file, the Fuchsia GN build generates a .packages file. IIUC, the request is for dartdoc to use those generated .packages files instead of a pubspec.yaml file. The downstream issue is DNO-299.

**Comment by jcollins-g** [comment]
Refined title to more clearly express the difference between this and #1746.

**Comment by jcollins-g** [comment]
Increasing priority to P2 based on offline discussion, as we're now sure this is a good idea.

**Comment by sethladd** [comment]
Hi! I'm wondering if there's a workaround for this issue, in the meantime? We can generate API docs for other languages, we'd like to also generate for Dart :)

**Comment by juliehockett** [comment]
Are there any updates on this/is any work for it planned?

**Comment by devoncarew** [comment]
@keertip is the best person to liaison with here.

For comparison, dartdoc doesn't work with the flutter repo or the angulardart one out of the box. They both have pretty specific use cases and customization. Both frameworks have a build step to build their docs, involving generating synthetic packages and passing custom flags and config into dartdoc. Depending on the exact use case, the same thing may apply here.

**Comment by keertip** [comment]
@juliehockett , the flutter script is here - https://github.com/flutter/flutter/blob/master/dev/tools/dartdoc.dart. It sets up the packages for doc generation - pubspecs, main library file etc and then calls dartdoc.

Fuchsia would need to do something on these lines to get dartdoc to run over the packages to be documented.

**Comment by juliehockett** [comment]
I've circled back to this from last year, and it appears that we've made sufficient changes to the structure of our dart code to allow using this (albeit with some manipulation, but it does the job). Thank you!

**Comment by keertip** [comment]
Good to hear that! Thanks for the update.
