### ISSUE TITLE
{@template} docs not showing up in base class

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dartdoc#1812]
Flutter's [`WidgetsApp.localizationsDelegates`](https://github.com/flutter/flutter/blob/0f34f526204d180e117d2fc296084155651cf8da/packages/flutter/lib/src/widgets/app.dart#L417-L422) uses `{@template}` to set up a reusable documentation block for subclasses:

```dart
  /// {@template flutter.widgets.widgetsApp.localizationsDelegates}
  /// The delegates for this app's [Localizations] widget.
  ///
  /// The delegates collectively define all of the localized resources
  /// for this application's [Localizations] widget.
  /// {@endtemplate}
  final Iterable<LocalizationsDelegate<dynamic>> localizationsDelegates;
```

The documentation that's produced for the base class is empty: https://docs.flutter.io/flutter/widgets/WidgetsApp/localizationsDelegates.html.  Note that subclasses that use the `{@macro}` _do_ get the correct documentation inserted.

It seems that `{@template}` documentation blocks should still show in the generated documentation.

/cc @jcollins-g

**Comment by jcollins-g** [comment]
This has been WAI but is very counterintuitive, and I don't like the idea of having to repeat a macro declaration to work around it.
