### ISSUE TITLE
dartdoc renders property setters in a nonsensical manner

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dartdoc#1846]
https://docs.flutter.io/flutter/rendering/RendererBinding/renderView.html has:

![image](https://user-images.githubusercontent.com/17391434/48820627-a1836980-ed0a-11e8-8e56-8716bc026bf5.png)

I don't know where that `void renderView= (` bit came from.  The corresponding code from [flutter/lib/src/rendering/binding.dart](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/rendering/binding.dart) is:

```dart
  /// The render tree that's attached to the output surface.
  RenderView get renderView => _pipelineOwner.rootNode;
  /// Sets the given [RenderView] object (which must not be null), and its tree, to
  /// be the new render tree to display. The previous tree, if any, is detached.
  set renderView(RenderView value) {
    assert(value != null);
    _pipelineOwner.rootNode = value;
  }
```

https://docs.flutter.io/flutter/rendering/RenderBox/size.html and https://docs.flutter.io/flutter/rendering/TextureBox/textureId.html are some other pages that exhibit this problem.  I have not done an exhaustive search.

I assume that (at least some?) property setters are not being handled properly by dartdoc.

**Comment by jcollins-g** [comment]
This is from the linkedReturnType rendering in dartdoc, which doesn't look very dart-y in a large number of cases probably because we're exposing some pretty low level names for these bits (like 'foo=').  Re-rendering these in a nicer manner would be good.

**Comment by zoechi** [comment]
Just encountered this as well https://docs.flutter.io/flutter/widgets/TextEditingController/text.html

**Comment by srawlins** [comment]
Still an issue; e.g. see https://pub.dev/documentation/collection/1.19.0/collection/DelegatingList/length.html
