### ISSUE TITLE
lost...

### ISSUE THREAD

**Issue by pedromorgan** [dart-lang/dartdoc#1874]
I was here...
https://pub.dartlang.org/packages/markdown
and had to skwint to see the little API-Reference.... expected at top

and then i RTFM ing and 
many while later after closing many tabs
https://pub.dartlang.org/documentation/flutter_markdown/latest/

am trying to find the api link, and git and version info etc 

its not very user friendly atmo, imho ;-)
but probably easily solvable for geriatrics..

**Comment by jcollins-g** [comment]
Hi, this is the project for API documentation generation.  If you'd like to make suggestions for the pub site, check out https://github.com/dart-lang/pub-dartlang-dart.
