### ISSUE TITLE
Can't search API docs on mobile (docs.flutter.io, api.dartlang.org)

### ISSUE THREAD

**Issue by sfshaza2** [dart-lang/dartdoc#1914]
It's currently not possible to search on the docs.flutter.io or api.dartlang.org sites on a mobile device, unless you are in landscape mode. (Not in portrait mode.)

Please see:
https://github.com/flutter/website/issues/2071

**Comment by zoechi** [comment]
Dup of #1348

**Comment by jcollins-g** [comment]
docs.flutter.io needs to be rebuilt with the latest version of dartdoc.  I do not know how to do this short of releasing a new version of flutter as publishing the docs there is part of the release process.  You can check what it will look like on the staging at https://master-docs-flutter-io.firebaseapp.com/ .

api.dartlang.org should work for the latest dev build: https://api.dartlang.org/dev/2.1.1-dev.3.2/index.html

The newer dartdoc puts the search box on the hamburger menu.
