### ISSUE TITLE
Going back in the dartdocs loses your scroll position

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dartdoc#1915]
Moved from https://github.com/flutter/flutter/issues/10984
Original author @Hixie

This used to be fine. I think it broken when we added scrolling in the left and right columns.

Steps:
1. Go to https://master-docs-flutter-io.firebaseapp.com/flutter/rendering/ContainerRenderObjectMixin-class.html
2. Open "add".
3. Nope, that was the wrong one. Go back.
4. Open "addAll".
5. Nope, that was the wrong one. Go back.
6. Get frustrated that you had to scroll after step 3 and have to scroll again now.

**Comment by jcollins-g** [comment]
Original bug was from 2017, I do think this is broken by our webkit scrolling.  Other related issues, some of which are straight dupes:

#1288 #1372 #1267 #779 #1870
