### ISSUE TITLE
Tool output not being substituted sometimes.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/dartdoc#1930]
After some recent changes it appears that tool directives are not always being run, or at least the results of their run aren't being interpolated into the HTML.

An example is in [Chip.onDeleted](https://master-docs.flutter.io/flutter/material/Chip/onDeleted.html) in the Flutter docs.

The snippet code there is being generated, so I think the tool is being run, but for some reason the output isn't being put back into the HTML.

**Comment by jcollins-g** [comment]
Marking as P1 esp since it's not clear to me how common this is yet.

**Comment by gspencergoog** [comment]
It definitely doesn't happen all the time: most of the other examples I've looked at are correct, so maybe it's somethig odd with this one, but if so, it's not obvious: the dartdoc looks right to me.

**Comment by jcollins-g** [comment]
This seems to be a problem with how we are deciding to skip precaching for elements that will never be documented.  Sometimes we are apparently guessing wrong.

**Comment by jcollins-g** [comment]
Narrowed this down further.  In precacheLocalDocs we are missing a case where a documented canonical element inherits its documentation from an element that is not documented via any other means.

**Comment by jcollins-g** [comment]
I have a fix, working on tests for it now.

**Comment by jcollins-g** [comment]
The fix corrects 247 instances where we are not correctly executing tools.

**Comment by jcollins-g** [comment]
The problem has to do with Dartdoc's documentation inheritance.  An `@override` member of a class without documentation will pick up documentation from the parent and/or interface classes.  But the tooling code skipped any element whose documentationComment was null without making sure that the documentation inherited had tool strings substituted in.

**Comment by gspencergoog** [comment]
Ahh.  Sorry, I wasn't aware I needed to check that.

**Comment by jcollins-g** [comment]
@gspencergoog I think your code at least ran things once on everything. I think I introduced this when I tried to filter out duplicate or unnecessary runs.
