### ISSUE TITLE
Add documentation style guidance for inline code

### ISSUE THREAD

**Issue by camsteffen** [dart-lang/dartdoc#1936]
The Effective Dart: Documentation page has a [section for code blocks](https://www.dartlang.org/guides/language/effective-dart/documentation#prefer-backtick-fences-for-code-blocks) but there is no guideline for inline code. Issue https://github.com/dart-lang/dartdoc/issues/303 seems to suggest that the `[:code:]` style is the old way.

Should we add a section like the following?

> Note: You may see some docs with inline code written as `[:code:]`. This is the old way of formatting inline code. This style is still supported, but you should prefer using standard markdown style with backticks like `` `code` ``.

**Comment by jcollins-g** [comment]
@kwalrath Where should issues like this go?

**Comment by kwalrath** [comment]
In the dart-lang/site-www repo. The ideal way is probably to go to the page and click the bug icon at the top right, but it's also fine to just transfer this bug there.

**Comment by kwalrath** [comment]
This issue was moved to dart-lang/site-www#1351
