### ISSUE TITLE
Flutter - No horizontal scroll in documentation sample code

### ISSUE THREAD

**Issue by shihaohong** [dart-lang/dartdoc#1942]
When looking at code samples on the Flutter documentation, one has to scroll to the bottom of the sample before being able to scroll horizontally. I think it'd be a better experience to be able to scroll horizontally before reaching the bottom of the code sample.

Following example is taken from [TabController](https://docs.flutter.io/flutter/material/TabController-class.html)

Before reaching the bottom, horizontal scrollbar hidden:
![before_reaching_bottom](https://user-images.githubusercontent.com/27032613/54314029-cf313e80-4597-11e9-88e0-4bfd0793cb38.png)

After reaching bottom, horizontal scrollbar shows:
![after_reaching_bottom](https://user-images.githubusercontent.com/27032613/54314034-d0626b80-4597-11e9-9190-ebd6f6b90a3f.png)

**Comment by srawlins** [comment]
It seems like the right solution is to limit the height of the sample code. Something like... the height of the window? Just under this?

**Comment by guidezpl** [comment]
I think this is fixed, scrolling always works for me.

**Comment by keertip** [comment]
This has been fixed.
