### ISSUE TITLE
Macros don't expand dartdoc directives injected by tools

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/dartdoc#1945]
In [this page ](https://master-api.flutter.dev/flutter/foundation/BindingBase/registerServiceExtension.html), there are `{@inject-html}` tags still present in the output.  These examples are generated by the snippets tool, but they are part of a template, and it's not happening elsewhere, so I assume that this is because templates don't get a second pass when they are instantiated to expand dartdoc directives.

Related to https://github.com/flutter/flutter/issues/29919

**Comment by srawlins** [comment]
Should be fixed with a bump to dartdoc 0.32.3, which I have not released yet.
