### ISSUE TITLE
Flutter Dartdocs Improper Syntax Highlighting

### ISSUE THREAD

**Issue by shihaohong** [dart-lang/dartdoc#1948]
Currently, the ExpansionPanelList documentation is incorrectly highlighting a huge chunk of the code in `red` as a String. I feel that this may be partly because the string interpolation is happening at the end of the string. 

<img width="709" alt="Screen Shot 2019-04-04 at 11 21 25 AM" src="https://user-images.githubusercontent.com/27032613/55578881-cda4f300-56cb-11e9-809a-5db79d079e52.png">

See [ExpansionPanelList.radio](https://master-api.flutter.dev/flutter/material/ExpansionPanelList/ExpansionPanelList.radio.html) for complete dartdoc sample.

**Comment by devoncarew** [comment]
@shihaohong, thanks for the report!

@kevmoo, do you know what syntax highlighter we're using for dartdoc? I see `hljs-comment` css classes in the html code. I think at some point we standardized on one language highlighter (for dartdoc, and for the pub site?).

**Comment by kevmoo** [comment]
Yup! https://highlightjs.org/

The best thing you could do would be to file/fix issues in Dart support there.

Could also be an issue w/ our markdown parsing. Would be good to investigate!

**Comment by Piinks** [comment]
Found another example of this: 
https://api.dartlang.org/stable/2.2.0/dart-io/Process-class.html

![Screen Shot 2019-04-04 at 3 52 05 PM](https://user-images.githubusercontent.com/16964204/55593877-60588880-56f2-11e9-9394-fa5942764a45.png)
