### ISSUE TITLE
Filename collision on case-preserving file systems: 

### ISSUE THREAD

**Issue by fayaz07** [dart-lang/dartdoc#1957]
dartdoc generates lot of files with similar file name but with uppercase, as it is causing difficulties to upload the flutter package. An example 

Looks great! Are you ready to upload your package (y/n)? y
Uploading...
Filename collision on case-preserving file systems: doc/api/dart-io/FileSystemEntityType/link-constant.html..
pub finished with exit code 1

**Comment by JDVila** [comment]
Any update on this one? I'm getting a similar error:

```
Looks great! Are you ready to upload your package (y/n)? y
Uploading...
Filename collision on case-preserving file systems: doc/api/dart-core/Map/map.html..
pub finished with exit code 1
```

**Comment by JDVila** [comment]
@fayaz07 I just solved the issue for myself - looks like I created a docs directory at one point, and since flutter made dart docs locally, when I tried to push to the Pub site, it saw this as a collision. Check your repo to see if you might have that similar issue. Good luck!

**Comment by fayaz07** [comment]
Thanks @JDVila I will try it

**Comment by jcollins-g** [comment]
As a general rule, you don't need to upload docs to the pub site; pub will generate documentation for your package itself.  The larger problem of case-preserving filesystem name collisions are owned by issue #1196.
