### ISSUE TITLE
Constructors that set instance members should show documentation for those members

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dartdoc#1958]
Consider the following class:

```dart
class Foo {
  /// Constructs a new `Foo`.
  Foo({this.bar, this.baz});

  /// Value indicating how much nonsense we can document without
  /// sounding too nonsensical.
  final int bar;
  
  /// String to display to the [Qux], explaining the purpose of this field.
  final String baz;
}
```

When you generate dardoc for this class, the constructor documentation looks like this:

---

![wpvJ5ue9hSy](https://user-images.githubusercontent.com/15253456/57174071-6e7eef00-6ded-11e9-8398-ea805872db7b.png)

---

As a reader, I immediately want to know what the docs are on `bar` and `baz` in that constructor - and I wonder why the documentation author didn't mention them at all.  Meanwhile, the documentation author is patting themselves on the back for writing such thorough documentation on `bar` and `baz` in the class.

I see this mismatch all over the place in almost every package I look at, including the Flutter framework.

It seems like we should inline the documentation on any member variables that are set from the constructor.

**Comment by srawlins** [comment]
I think this makes really great sense for "field formal" parameters (`this.foo`), like your example. Great idea.

**Comment by srawlins** [comment]
Closing in favor of the newer issue: https://github.com/dart-lang/dartdoc/issues/2617
