### ISSUE TITLE
[Class.method] reference linked to the wrong page

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dartdoc#1965]
I don't know if there are other examples, but I noticed that the generated documentation for [`ImageStreamCompleter.reportError`](https://api.flutter.dev/flutter/painting/ImageStreamCompleter/reportError.html) has multiple references to `FlutterError.reportError`, but those links all point to  `ImageStreamCompleter.reportError` instead. (The `FlutterError` class should definitely be in scope.)

**Comment by jamesderlin** [comment]
Another example: [`ImageCache.evict`](https://api.flutter.dev/flutter/painting/ImageCache/evict.html) tries to link to `ImageProvider.evict`, but the generated hyperlink instead goes to the current `ImageCache.evict` page.

**Comment by jcollins-g** [comment]
At some point over the last year, this seems to have been fixed -- the examples given here seem to go to the right places now.
