### ISSUE TITLE
Travis failing for a week - failed assert

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1980]
See https://travis-ci.org/dart-lang/dartdoc/builds

CC @devoncarew

**Comment by devoncarew** [comment]
Thanks! From talking locally, we think this is a change in the Flutter framework (that's breaking our flutter integration test).

cc @keertip

**Comment by keertip** [comment]
Yes, am looking into it.

**Comment by keertip** [comment]
This change in flutter is what caused the breakage - https://github.com/flutter/flutter/commit/90500a5dc4.

**Comment by kevmoo** [comment]
Ah! Wonder if DartDoc is not happy w/ conditional imports.

**Comment by keertip** [comment]
Yes, the conditional imports look to be the issue. The doc generation is working for the flutter folks at head, no complaints there. It's just the test. The test uses a sync method to build docs and has an assert to check for certain conditions - which are now failing.

Now that there is a likely reason, can work with a test case.
