### ISSUE TITLE
disallow enabling --allow-tools from the analysis_options.yaml file

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1987]
We now prefer that users explicitly enable dartdoc tools from the command line (via `--allow-tools`). We should disallow enabling --allow-tools from the dartdoc_options.yaml file; see https://github.com/dart-lang/dartdoc/issues/1940#issuecomment-505117236 for more context.

When making this change, we may also want to warn on the cli (and fail the dartdoc run?) if we do find a use of enabling via the dartdoc_options.yaml file.

**Comment by keertip** [comment]
The --allow-tools flag cannot be used from dartdoc_options.yaml file, is it defined as only a command line option.
