### ISSUE TITLE
DartDoc accepts Github emojis

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dartdoc#1991]
In https://github.com/dart-lang/sdk/issues/37547, it turns out that DartDoc supports GitHub emoji sequences like `:100:` (:100:).
That was a surprise. 

I don't see any urgent need for emojis in code documentation, but they can occur accidentlally, however unlikely it might seem.
Could we consider not enabing all GitHub extensions in our extension set.

Where is the supported DartDoc syntax documented?
The DartDoc readme.md (same doc as https://pub.dev/packages/dartdoc) doesn't mention anything, and the linked Effective Dart page does not treat syntax.

**Comment by devoncarew** [comment]
This is likely coming from `package:markdown` (https://pub.dev/packages/markdown).

I'm surprised we're getting emoji support ( 😮 ); we're configuring it here: https://github.com/dart-lang/dartdoc/blob/master/lib/src/markdown_processor.dart#L142.

cc @kevmoo @srawlins

**Comment by srawlins** [comment]
This is correct. I think dartdoc uses the [gitHubWeb](https://pub.dev/documentation/markdown/latest/markdown/ExtensionSet/gitHubWeb.html) extension set (tries to match GitHub parsing of READMEs, comments, etc. But there is also [gitHubFlavored](https://pub.dev/documentation/markdown/latest/markdown/ExtensionSet/gitHubFlavored.html), which is a smaller set of extensions, which might be more appropriate for DartDoc comments...

**Comment by RedBrogdon** [comment]
Any chance we could consider this a feature? 😄 

![image](https://user-images.githubusercontent.com/969662/61389442-c4e8bf00-a86d-11e9-8cc5-6516a1996a04.png)

**Comment by dnfield** [comment]
We can always just directly put emoji's in the doc comment if we want to - rather than getting surprised later that an IP address turned into an emoji.

**Comment by DanTup** [comment]
We should also consider that the web isn't the only place the Dartdocs ends up - they're shown in editor tooltips etc. too. Unless all the markdown renderers for those support the same things, things may creep into the docs that don't render nicely there (Flutter already has a lot of these, like the icon images and macros).

Using the emoji directly in the source would work more universally (assuming all parts are handling the encodings correctly 😄).
