### ISSUE TITLE
Abstract factory not linked

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/dartdoc#2008]
I have two classes: `NoteTime` (abstract), and `Note`, which has a `final NoteTime time` property. 

The `Note` constructor looks like this: 
```dart
/// Returns a new [Note] from a JSON object.
/// 
/// Uses `json ["message"]` for the message and passes `json["time"]` to [NoteTime.fromJson]
factory Note.fromJson(Map<String, dynamic> json) => Note (
	message: json ["message"],
	time: NoteTime.fromJson(json ["time"]),
);
```

Clicking on `NoteTime.fromJson` in the docs leads back to the `Note` constructor... any clue why?

Here's my `NoteTime.fromJson`: 
```dart
/// Initializes a new instace from JSON.
/// 
/// Mainly looks at `json ["type"]` to choose which type of 
/// [NoteTime] it should instantiate, and then leaves the 
/// work to that subclasses `.fromJson` method. 
/// 
/// Example JSON: 
/// ```
/// {
/// 	"type": "period",
/// 	"repeats": false,
/// 	"period": "9",
/// 	"letter": "M",
/// }
/// ```
factory NoteTime.fromJson(Map<String, dynamic> json) {
	switch (stringToNoteTime [json ["type"]]) {
		case NoteTimeType.period: return PeriodNoteTime.fromJson(json);
		case NoteTimeType.subject: return SubjectNoteTime.fromJson(json);
		default: throw JsonUnsupportedObjectError(
			json,
			cause: "Invalid time for note: $json"
		);
	}
}
```

**Comment by Levi-Lesches** [comment]
If it helps, `NoteTime.fromJson` has a page in the docs.

**Comment by keertip** [comment]
@Levi-Lesches , can you try generating the docs with 0.28.5 and see if this is still an issue. This looks like #1994.

**Comment by Levi-Lesches** [comment]
Just tried it, after deleting the original directory, upgrading `dartdoc`, and verifying using `dartdoc --version`, this is still an issue. 

Do you think it would come up in the logs?

**Comment by Levi-Lesches** [comment]
Also this can't be related to that issue since `NoteTime` is not at all related to `Note`.
