### ISSUE TITLE
Incorrect dartdoc cross reference in ProcessResult

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/dartdoc#2013]
In the current documentation for `ProcessResult.exitCode`

https://api.dartlang.org/stable/2.4.1/dart-io/ProcessResult/exitCode.html

There is a cross link of the form

See [Process.exitCode](https://api.dartlang.org/stable/2.4.1/dart-io/ProcessResult/exitCode.html) for more information in the exit code value.

Note that the cross link target is "https://api.dartlang.org/stable/2.4.1/dart-io/ProcessResult/exitCode.html", which is the source page (ProcessResult.exitCode), instead of what is indicated by the text (Process.exitCode).  

The promised "more information" is indeed present on the Process.exitCode page, but the link doesn't get you there.

cc @keertip

**Comment by keertip** [comment]
This has been fixed by #1994 . The Dart SDK needs to be updated to use the new version of dartdoc.

**Comment by keertip** [comment]
0.28.5 has rolled into the sdk, verified with bleeding edge docs, this has been fixed.
