### ISSUE TITLE
assets are missing after generating the documentation

### ISSUE THREAD

**Issue by tvw** [dart-lang/dartdoc#2019]
After running

```sh
$ dartdoc
```
all assets are missing so the generated output does not look very helpful.

dartdoc version: 0.28.5

**Comment by keertip** [comment]
@tvw , did you run it inside the package you want to generate docs for? What do you see in the `doc/api` folder?

**Comment by tvw** [comment]
Yes, I did run it inside the package. In ```doc/api``` I see ```index.html```, ```__404error.html``` and folders which contain the documentation of my source code. But no ```static-assets```.

**Comment by tvw** [comment]
I tried dartdoc in another, new package. Here dartdoc runs as expected. So it seems only to be a problem within this single package. I have no clue, where the problem is, but I will find out.

**Comment by nachiketingle** [comment]
@tvw I'm having the same problem. Were you able to resolve it?
