### ISSUE TITLE
Could you provide a tutorial please ?

### ISSUE THREAD

**Issue by maxime-aubry** [dart-lang/dartdoc#2024]
Hello.
I try to use your library.
Could you provide a full tutorial to help me to learn how to use this tool please ?
Thanks.

**Comment by keertip** [comment]
@maxime-aubry, are you looking to generate docs for your package? Did you look at the instructions in [README.md](https://github.com/dart-lang/dartdoc/blob/master/README.md).

**Comment by jcollins-g** [comment]
The latest version of dartdoc includes links to existing production uses of dartdoc  in a new [example/README.md](https://github.com/dart-lang/dartdoc/blob/v0.29.2/example/README.md).  I'll close this out for now in the hope that this answers most questions on how to use the tool, but please reopen if you have a specific idea for what a dartdoc tutorial would look like.
