### ISSUE TITLE
Exported extensions don't show up in the docs for a library

### ISSUE THREAD

**Issue by natebosch** [dart-lang/dartdoc#2032]
I'm working on https://github.com/dart-lang/stream_transform/pull/83

When I generate docs I see all the deprecated top level methods that are exported from the "main" library, but none of the extensions. If I add an extension directly I do see it in the docs.

**Comment by keertip** [comment]
@jcollins-g , could you take a look? Thanks!

**Comment by mkustermann** [comment]
@jcollins-g This might be a blocker for D26, since all our tools need to support extension methods and the core libraries, `dart:ffi` in particular, are using extension methods now.

**Comment by jcollins-g** [comment]
Getting this correct is turning out to be more of a pain than I realized.  Some discovery support is best implemented as analyzer code and I've got the beginnings of that working now.

**Comment by jcollins-g** [comment]
This has improved, but there are still significant bugs, see #2047.
