### ISSUE TITLE
Commas missing from named parameters with default values

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#2052]
See the constructor for KeybaordEvent: https://api.dartlang.org/dev/2.6.0-dev.8.2/dart-html/KeyboardEvent/KeyboardEvent.html

It's not terribly unreadable in that page, but look at the summary on the class page:

https://api.dartlang.org/dev/2.6.0-dev.8.2/dart-html/KeyboardEvent-class.html

**Comment by lrhn** [comment]
Just noticed the same thing on https://api.dartlang.org/stable/2.6.1/dart-core/RegExp-class.html.

**Comment by srawlins** [comment]
Fixed. https://api.dart.dev/stable/2.9.0/dart-html/KeyboardEvent/KeyboardEvent.html
