### ISSUE TITLE
Extension methods should appear on extended type

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2073]
It would be neat if specialized extensions appeared on the extended type as well. For example, consider dart:ffi's Pointer:

https://api.dartlang.org/stable/2.6.1/dart-ffi/Pointer-class.html

It doesn't list any extensions, but it would be useful for it to explicitly list DoublePointer et al. Currently there doesn't seem to be any way to discover those extensions.

In addition, it would be even better if it could actually list the extension members themselves. For example, Pointer could include the various `value`, `operator []`, etc, members that are defined on each extension.

**Comment by Hixie** [comment]
https://github.com/dart-lang/dartdoc/issues/2021 suggests something similar.

**Comment by jcollins-g** [comment]
The partial fix for #2021 that landed with #2053 does this.  See:

 https://api.dartlang.org/be/168069/dart-ffi/Pointer-class.html

**Comment by jcollins-g** [comment]
Listing the extension members themselves will eventually come with a more complete fix for #2021, but NNBD is currently occupying my time.
