### ISSUE TITLE
Inheritance doesn't match Implementors for ErrorDescription/DiagnosticsProperty (probably due to generics?)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2094]
https://api.flutter.dev/flutter/foundation/ErrorDescription-class.html says it inherits from "DiagnosticsProperty", but https://api.flutter.dev/flutter/foundation/DiagnosticsProperty-class.html does not list "ErrorDescription" in its list of implementors. The lack of symmetry is confusing.

**Comment by srawlins** [comment]
Another possibility is that ErrorDescription actually `extends _ErrorDiagnostic`, which `extends DiagnosticsProperty<List<Object>>`. It's possible that the undocumented class in the middle is preventing the symmetry.

**Comment by srawlins** [comment]
Likely the same as #1623, but I'm happy to keep both open. #1623 has details about the private link.
