### ISSUE TITLE
Unhandled exception: type 'FunctionTypeImpl' is not a subtype of type 'InterfaceType'

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2101]
The following exception happened while running `dartdoc 0.29.1` on `plexus 4.0.0+5` on `pub.dev`:

````
documenting plexus
Generating docs for library expose from package:plexus/expose.dart...

STDERR:
Documenting plexus...
  warning: expose has no library level documentation comments, from expose: (file:///tmp/pub-dartlang-dartdocGFHAYO/pkg/lib/expose.dart:1:9)
Unhandled exception:
type 'FunctionTypeImpl' is not a subtype of type 'InterfaceType'
#0      DefinedElementType.interfaceType (package:dartdoc/src/element_type.dart:324:38)
#1      DefinedElementType.instantiatedType (package:dartdoc/src/element_type.dart:331:12)
#2      Extension._couldApplyTo (package:dartdoc/src/model.dart:1350:47)
#3      Extension.couldApplyTo (package:dartdoc/src/model.dart:1346:33)
#4      Class.potentiallyApplicableExtensions.<anonymous closure> (package:dartdoc/src/model.dart:805:27)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:440:11)
````

- plexus sources: https://github.com/pfaffdev/plexus
- original bug report: https://github.com/dart-lang/pub-dev/issues/3196

**Comment by mpfaff** [comment]
Here's the contents of `expose.dart` if it helps

```dart
library expose;

export 'package:plexus/src/expose/list.dart';
export 'package:plexus/src/expose/maps.dart';

```

**Comment by mpfaff** [comment]
So it seems the issue is that `dartdoc` doesn't correctly handle `library expose;` not having documentation comments.

**Comment by jcollins-g** [comment]
The warning on library expose is a red herring; the exception is in some later processing loop.  It looks like a mismatch of expectations between dartdoc and the analyzer for some reason, though I'm having difficulty reproducing this at head.  Still investigating.

**Comment by jcollins-g** [comment]
Crash reproduced; the crash only occurs with the `--link-to-remote` flag (used by pub and most modern users of dartdoc now).

**Comment by jcollins-g** [comment]
code snippet below (inspired by the dartx package) will reproduce:

```
typedef R Function1<A, R>(A a);
typedef R Function2<A, B, R>(A a, B b);

extension DoSomething2X<A, B, R> on Function1<A, Function1<B, R>> {
  Function2<A, B, R> something() => (A first, B second) => this(first)(second);
}
```

**Comment by jcollins-g** [comment]
root cause identified.   Dartdoc does not understand much about extensions on function types (filed as  #2107) and what support we had got broken by an analyzer change.

Until this issue is fixed, any package that includes an extension on a function type in its transitive dependencies will crash if being documented with --link-to-remote, or will crash if it itself uses them.
