### ISSUE TITLE
Ensure that references to types with generics work

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#211]
I don't know if this is an issue with dartdoc, but copying over from a dartdocgen issue to make sure it's considered ( https://code.google.com/p/dart/issues/detail?id=22456 )

Summary is that, `[List<int>]` in a comment doesn't correctly resolve as a reference to the List docs.

which says
--------------------
Document references to parameterized types show incorrectly. For example, this  doc:

https://github.com/dart-lang/html5lib/blob/eaca2abbf149ab4d280ae94cb6e67480db421c0e/lib/parser.dart#L48

which says:

```dart
/// Parse the [input] html5 document fragment into a tree. The [input] can be
/// a [String], [List<int>] of bytes or an [HtmlTokenizer].
```

Comes up as:

```
Parse the input html5 document into a tree. The input can be a String, dart:core<dart:core> of bytes or an html5lib/tokenizer.HtmlTokenizer.
```

**Comment by keertip** [comment]
Fixed, verified 

![screen shot 2015-03-23 at 3 58 36 pm](https://cloud.githubusercontent.com/assets/2192312/6792455/8778b068-d175-11e4-93df-da25c84d92b6.png)
