### ISSUE TITLE
Unhandled exceptions with --link-to-remote (type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType')

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2113]
Similar to #2101, I've found another exception that is triggered when running dartdoc with `--link-to-remote`:

https://pub.dev/packages/aws_sns_api

On pub.dev:
https://pub.dev/documentation/aws_sns_api/latest/log.txt
````
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeParameterElementType.interfaceType (package:dartdoc/src/element_type.dart:261:38)
#1      DefinedElementType.instantiatedType (package:dartdoc/src/element_type.dart:331:12)
#2      Extension._couldApplyTo (package:dartdoc/src/model.dart:1350:47)
#3      Extension.couldApplyTo (package:dartdoc/src/model.dart:1346:33)
#4      Class.potentiallyApplicableExtensions.<anonymous closure> (package:dartdoc/src/model.dart:805:27)
````

The fix to #2101 may have been fixed this one too, please double-check...

**Comment by jcollins-g** [comment]
Yes, this is a similar bug and already fixed.

**Comment by isoos** [comment]
Reopening this, as it was not fixed with `dartdoc 0.30.0+1`, example package:
- `bird_flutter 0.0.3`
- https://pub.dev/packages/bird_flutter
- https://pub.dev/documentation/bird_flutter/latest/log.txt

The stacktrace differs in some of the lines from the previous one:

````
Unhandled exception:
type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
#0      TypeParameterElementType._interfaceType (package:dartdoc/src/element_type.dart:213:39)
#1      DefinedElementType.instantiatedType (package:dartdoc/src/element_type.dart:284:12)
#2      Extension._couldApplyTo (package:dartdoc/src/model/extension.dart:41:49)
#3      Extension.couldApplyTo (package:dartdoc/src/model/extension.dart:31:7)
#4      ExtensionTarget.potentiallyApplicableExtensions.<anonymous closure> (package:dartdoc/src/model/extension_target.dart:26:27)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:442:11)
````

**Comment by isoos** [comment]
(Oh, I thought I can reopen... should I create a new issue to track this?)

**Comment by jcollins-g** [comment]
This looks like some kind of different edge case.  Thanks for pasting the log information into the bug, it helps a great deal!

**Comment by jcollins-g** [comment]
This is what @scheglov warned me about in a previous PR; a bug where we assume `TypeParameterType.bound` is an InterfaceType.  Sadly it looks like it hits bugs in the real world.
