### ISSUE TITLE
Canonical URL calculation is off for top-level functions

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2122]
dartdoc: `0.30.0+1`

example top-level function:
- source: https://github.com/dart-lang/pana/blob/master/lib/src/utils.dart#L191-L209
- documentation: https://pub.dartlang.org/documentation/pana/0.12.2/pana/prettyJson.html
arguments: `--rel-canonical-prefix https://pub.dartlang.org/documentation/pana/0.12.2`

expected content in HTML:
- `<link rel="canonical" href="https://pub.dartlang.org/documentation/pana/0.12.2/pana/prettyJson.html">`

actual content in HTML:
- `<link rel="canonical" href="https://pub.dartlang.org/documentation/pana/0.12.2/../pana/prettyJson.html">`

(note the `/../` segment between `/0.12.2/` and `/pana/`)

**Comment by isoos** [comment]
Not only for top-level ones, but other files too, e.g.:

```
<link rel="canonical" href="https://pub.dev/documentation/pana/0.12.2/models/LicenseFile/LicenseFile.html">
```
vs
```
<link rel="canonical" href="https://pub.dev/documentation/pana/0.12.2/../../models/LicenseFile/LicenseFile.html">
```

**Comment by jcollins-g** [comment]
This seems only to impact pub, but they are an important customer.  Maybe there is some bad interaction with the --rel-canonical-prefix flag.

**Comment by jcollins-g** [comment]
@isoos Does the --use-base-href flag makes any difference?

**Comment by isoos** [comment]
> Does the --use-base-href flag makes any difference?

It does: the canonical URL is good, and it brings back the `<base>` tag. Should we use that? (Is that the replacement of `--hosted-url`?)

**Comment by jcollins-g** [comment]
We should consider it a temporary fix until we can figure out what's wrong with the URL generation.  Future versions of dartdoc can't rely on base href because markdown can't work well with it.

**Comment by jdkoren** [comment]
I actually removed `--hosted-url` because it wasn't being used anywhere in the code or templates.

I think I know what's happening, but it may take a bit to figure out a fix. In the meantime, you can use `--use-base-href` to restore the original behavior, and it should give you the expected content.

**Comment by isoos** [comment]
The patch for the canonical URL is not too bad in our code, so I'd rather wait for a future release to get this fixed (not in a hurry with that), than going back and forth with the `<base>` changes again (as I've verified the new version without it on the staging site).

**Comment by jcollins-g** [comment]
leaving as P1 since there is a workaround.
