### ISSUE TITLE
dartdoc over Flutter project is trying to parse all the Flutter source files.

### ISSUE THREAD

**Issue by limonadev** [dart-lang/dartdoc#2141]
I am trying to generate docs for a Flutter app. When I go inside de app directory, and run `dartdoc`, the command first parse my `lib/` folder (which is ok!) but then tryies to parse the Flutter source files (shows lines like `parsing /opt/Flutter/...`, for every Flutter source file). Is there any form to specificate that dartdoc only works over the actual folder?

**Comment by jcollins-g** [comment]
We should just squelch the parsing messages outside the package the person is documenting.  We still have to parse them but it's confusing to people, especially considering we have bugs in this area like #1949.

**Comment by limonadev** [comment]
I will let dartdoc parse all the files then. Thank you so much for the help!

**Comment by tbarbugli** [comment]
@jcollins-g on my tiny Flutter package it takes `dartdoc` ~90s to run parsing and doc generation

```
flutter pub global run dartdoc:dartdoc --exclude 'dart:async,dart:collection,dart:convert,dart:core,dart:developer,dart:io,dart:isolate,dart:math,dart:typed_data,dart:ui,dart:ffi,dart:html,dart:js,dart:js_util'
```

**Comment by abdelrahmanemam91** [comment]
@limonadev please can you tell me how did you generated the docs for your project as all my attempts to generate docs it generate docs for the dart sdk.

**Comment by limonadev** [comment]
@abdelrahmanemam91 I just went into the root of my project folder and run the dartdoc command. The command first documented my code but after that, it documented the Flutter SDK also. It took a few minutes but at the end, it created the documentation without problems
