### ISSUE TITLE
dartdoc_options exclude ignored

### ISSUE THREAD

**Issue by tbarbugli** [dart-lang/dartdoc#2155]
On a Flutter package, when I exclude packages via cmd line flag I get the expected behavior, if I move that list to options the exclude is ignored.

```yaml
dartdoc:
  exclude: ["dart:async", "dart:collection", "dart:convert", "dart:core", "dart:developer", "dart:io", "dart:isolate", "dart:math", "dart:typed_data", "dart:ui", "dart:ffi", "dart:html", "dart:js", "dart:js_util"]
```

I tried adding some other option to the file just to be sure it was actually used by dartdoc and I can see it is actually used and other options work fine.

**Comment by jcollins-g** [comment]
Exclude specified in the dartdoc options are context sensitive and only operate on libraries defined with your package, but given the level of user confusion on this it should be better documented that this can not be used to work around #1949.
