### ISSUE TITLE
test/experiment_options_test.dart relies on "bogus" features defined by analyzer package

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/dartdoc#2156]
The test `experiment_options_test.dart` relies on the presence of two "bogus" entries in the analyzer's `ExperimentStatus.knownFeatures` map.  These entries were not intended to be kept around in the long term; they were created solely to illustrate the file format while it was being developed.  We should change the dartdoc test so that it doesn't require them.  This could be accomplished, for example, by making use of the analyzer's `overrideKnownFeatures` method.

Making this change would allow us to address analyzer technical debt issue https://github.com/dart-lang/sdk/issues/40860.

**Comment by scheglov** [comment]
This was fixed.
