### ISSUE TITLE
Show in API docs at what dart version a feature was introduced

### ISSUE THREAD

**Issue by erf** [dart-lang/dartdoc#2160]
I think it would be a good idea to note in the API docs, at what dart lang version a spesific feature was introduced. I think this would be make it easier to spesify dart version in your `pubspec.yaml`, based on a feature or link to the correct documentation where this feature was introduced.

E.g like [this feature](https://api.dart.dev/stable/2.6.1/dart-core/List/operator_plus.html), a note at the bottom or at the top-right could note the version when it was first introduced. 

I commented regarding this feature in #1513, where the `@Since` property was mentioned, and that it had this information, but apparently it was internal, so it could not be used to generate this information ( i assume ). Before my comment, the last comment on that issue was in 2017, so not sure about the status, and i thought i'd create a new issue to spark a conversation. Please feel free to close this issue, if it is a duplicate.

**Comment by erf** [comment]
Closed in favor of https://github.com/dart-lang/sdk/issues/40963

**Comment by jcollins-g** [comment]
Thanks for trying to reduce bug duplication, but to track adding part of the feature to dartdoc having a bug here is a good idea.

**Comment by jcollins-g** [comment]
Oh, and we already have a dartdoc bug for this.  Closing in favor of #1513.
