### ISSUE TITLE
dartdoc crashes on an empty stagehand console package

### ISSUE THREAD

**Issue by mobileink** [dart-lang/dartdoc#2163]
Am I doing something wrong?

$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "macos_x64"
$ dartdoc --version
dartdoc version: 0.29.1
$ stagehand console-full
$ pub get
$ dart bin/main.dart
Hello world: 42!
$ dartdoc

```
jUnhandled exception:
Invalid argument (uri): Unknown package: Instance of '_SimpleUri'
#0      resolveUri.<anonymous closure> (package:resource/src/resolve.dart:13:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#6      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#7      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#8      _resolvePackageUriFuture (dart:_builtin)
<asynchronous suspension>
#9      Isolate.resolvePackageUri (dart:isolate-patch/isolate_patch.dart:352:16)
#10     resolveUri (package:resource/src/resolve.dart:11:20)
#11     PackageLoader.readAsBytes (package:resource/src/package_loader.dart:27:33)
#12     loadAsBytes (package:dartdoc/src/html/resource_loader.dart:32:45)
#13     loadAsString (package:dartdoc/src/html/resource_loader.dart:20:21)
#14     _DefaultTemplatesLoader.loadPartials (package:dartdoc/src/html/templates.dart:106:33)
#15     _loadPartials (package:dartdoc/src/html/templates.dart:76:40)
#16     Templates._create (package:dartdoc/src/html/templates.dart:195:26)
#17     Templates.createDefault (package:dartdoc/src/html/templates.dart:165:12)
#18     HtmlGenerator.create (package:dartdoc/src/html/html_generator.dart:68:35)
#19     initGenerators (package:dartdoc/src/html/html_generator.dart:163:25)
#20     Dartdoc.withDefaultGenerators (package:dartdoc/dartdoc.dart:67:40)
#21     main (file:///b/s/w/ir/cache/builder/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:91:23)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by jcollins-g** [comment]
@mobileink Can you reveal more about the contents of the package you are documenting?  At least the contents of pubspec.yaml, but any source files would be helpful too.

**Comment by mobileink** [comment]
dartdoc crashes on a simple app generated by stagehand, as my bug reported
indicated.  Can we start with that?

**Comment by jcollins-g** [comment]
I didn't know what stagehand was so didn't understand it was part of your repro case.  Now that I know it generates packages it should be simple enough to reproduce the problem....

However, it works fine for me... so I'm not sure what is wrong here.  Perhaps a different version of stagehand?
```
jcollins-macbookpro2:x5 jcollins$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "macos_x64"
jcollins-macbookpro2:x5 jcollins$ dartdoc --version
dartdoc version: 0.29.1
jcollins-macbookpro2:x5 jcollins$ pub global activate stagehand
Resolving dependencies... (1.4s)
+ args 1.6.0
+ async 2.4.1
+ charcode 1.1.3
+ collection 1.14.12
+ http 0.12.0+4
+ http_parser 3.1.4
+ meta 1.1.8
+ path 1.6.4
+ pedantic 1.9.0
+ source_span 1.7.0
+ stagehand 3.3.7
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.1.6
+ usage 3.4.1
Precompiling executables... (1.1s)
Precompiled stagehand:stagehand.
Installed executable stagehand.
Activated stagehand 3.3.7.
jcollins-macbookpro2:x5 jcollins$ stagehand console-full
Creating console-full application `x5`:
  /Users/jcollins/dart/x5/.gitignore
  /Users/jcollins/dart/x5/CHANGELOG.md
  /Users/jcollins/dart/x5/README.md
  /Users/jcollins/dart/x5/analysis_options.yaml
  /Users/jcollins/dart/x5/bin/main.dart
  /Users/jcollins/dart/x5/lib/x5.dart
  /Users/jcollins/dart/x5/pubspec.yaml
  /Users/jcollins/dart/x5/test/x5_test.dart
8 files written.

--> to provision required packages, run 'pub get'
--> run your app using `dart bin/main.dart`.
jcollins-macbookpro2:x5 jcollins$ pub get
Resolving dependencies... (4.1s)
+ _fe_analyzer_shared 1.0.3
+ analyzer 0.39.4
+ args 1.6.0
+ async 2.4.1
+ boolean_selector 2.0.0
+ charcode 1.1.3
+ collection 1.14.12
+ convert 2.1.1
+ coverage 0.13.9
+ crypto 2.1.4
+ csslib 0.16.1
+ glob 1.2.0
+ html 0.14.0+3
+ http 0.12.0+4
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ io 0.3.3
+ js 0.6.1+1
+ logging 0.11.4
+ matcher 0.12.6
+ meta 1.1.8
+ mime 0.9.6+3
+ multi_server_socket 1.0.2
+ node_interop 1.0.3
+ node_io 1.0.1+2
+ node_preamble 1.4.8
+ package_config 1.9.2
+ path 1.6.4
+ pedantic 1.9.0
+ pool 1.4.0
+ pub_semver 1.4.4
+ shelf 0.7.5
+ shelf_packages_handler 2.0.0
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_map_stack_trace 2.0.0
+ source_maps 0.10.9
+ source_span 1.7.0
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ test 1.14.2
+ test_api 0.2.15
+ test_core 0.3.3
+ typed_data 1.1.6
+ vm_service 4.0.0
+ watcher 0.9.7+14
+ web_socket_channel 1.1.0
+ webkit_inspection_protocol 0.5.0+1
+ yaml 2.2.0
Changed 51 dependencies!
Precompiling executables... (8.2s)
Precompiled test:test.
jcollins-macbookpro2:x5 jcollins$ dart bin/main.dart
Hello world: 42!
jcollins-macbookpro2:x5 jcollins$ dartdoc
Documenting x5...
parsing /Users/jcollins/dart/x5/lib/x5.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/core/core.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/collection/collection.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/internal/internal.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/async/async.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/convert/convert.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/typed_data/typed_data.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/math/math.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/developer/developer.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/isolate/isolate.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/ffi/ffi.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/html/dart2js/html_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/html/html_common/html_common_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/web_gl/dart2js/web_gl_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/native_typed_data.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/interceptors.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/shared/embedded_names.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/js_helper.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/foreign_helper.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/js_names.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/rti.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/shared/recipe_syntax.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/js_util/dart2js/js_util_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/html/html_common/metadata.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/indexed_db/dart2js/indexed_db_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/svg/dart2js/svg_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/web_audio/dart2js/web_audio_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/web_sql/dart2js/web_sql_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_http/http.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/io/io.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/js/dart2js/js_dart2js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/js/_js.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/mirrors/mirrors.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/html/dartium/nativewrappers.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/cli/cli.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/wasm/wasm.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/js_primitives.dart...
parsing /Users/jcollins/dart/all_sdks/2.7.1/lib/_internal/js_runtime/lib/shared/async_await_error_codes.dart...
Initialized dartdoc with 38 libraries in 15.1 seconds
documenting x5
Generating docs for library x5 from package:x5/x5.dart...
Validating docs...
no issues found
Documented 1 public library in 0.4 seconds
Success! Docs generated into /Users/jcollins/dart/x5/doc/api
jcollins-macbookpro2:x5 jcollins$
```

**Comment by mobileink** [comment]
On Wed, Mar 25, 2020 at 11:33 AM Janice Collins <notifications@github.com>
wrote:

> I didn't know what stagehand was so didn't understand it was part of your
> repro case. Now that I know it generates packages it should be simple
> enough to reproduce the problem....
>
> However, it works fine for me... so I'm not sure what is wrong here.
> Perhaps a different version of stagehand?
>
Below is my output to match yours.  An obvious place to start would be to
fix the broken error message "Invalid argument (uri): Unknown package:
Instance of '_SimpleUri'' to make it print the URI.

Thanks,

Gregg

$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "macos_x64"
Sparky-2.local:~/tmp/stagehand
$ dartdoc --version
dartdoc version: 0.29.1
Sparky-2.local:~/tmp/stagehand
$ stagehand --version
stagehand version: 3.3.7
Sparky-2.local:~/tmp/stagehand
$ stagehand console-full
Creating console-full application `stagehand`:
  /Users/gar/tmp/stagehand/.gitignore
  /Users/gar/tmp/stagehand/CHANGELOG.md
  /Users/gar/tmp/stagehand/README.md
  /Users/gar/tmp/stagehand/analysis_options.yaml
  /Users/gar/tmp/stagehand/bin/main.dart
  /Users/gar/tmp/stagehand/lib/stagehand.dart
  /Users/gar/tmp/stagehand/pubspec.yaml
  /Users/gar/tmp/stagehand/test/stagehand_test.dart
8 files written.

--> to provision required packages, run 'pub get'
--> run your app using `dart bin/main.dart`.
Sparky-2.local:~/tmp/stagehand
$ pub get
Resolving dependencies... (2.5s)
+ _fe_analyzer_shared 1.0.3
+ analyzer 0.39.4
+ args 1.6.0
+ async 2.4.1
+ boolean_selector 2.0.0
+ charcode 1.1.3
+ collection 1.14.12
+ convert 2.1.1
+ coverage 0.13.9
+ crypto 2.1.4
+ csslib 0.16.1
+ glob 1.2.0
+ html 0.14.0+3
+ http 0.12.0+4
+ http_multi_server 2.2.0
+ http_parser 3.1.4
+ io 0.3.3
+ js 0.6.1+1
+ logging 0.11.4
+ matcher 0.12.6
+ meta 1.1.8
+ mime 0.9.6+3
+ multi_server_socket 1.0.2
+ node_interop 1.0.3
+ node_io 1.0.1+2
+ node_preamble 1.4.8
+ package_config 1.9.3
+ path 1.6.4
+ pedantic 1.9.0
+ pool 1.4.0
+ pub_semver 1.4.4
+ shelf 0.7.5
+ shelf_packages_handler 2.0.0
+ shelf_static 0.2.8
+ shelf_web_socket 0.2.3
+ source_map_stack_trace 2.0.0
+ source_maps 0.10.9
+ source_span 1.7.0
+ stack_trace 1.9.3
+ stream_channel 2.0.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ test 1.14.2
+ test_api 0.2.15
+ test_core 0.3.3
+ typed_data 1.1.6
+ vm_service 4.0.0
+ watcher 0.9.7+14
+ web_socket_channel 1.1.0
+ webkit_inspection_protocol 0.5.0+1
+ yaml 2.2.0
Changed 51 dependencies!
Precompiling executables... (12.6s)
Precompiled test:test.
Sparky-2.local:~/tmp/stagehand
$ dart bin/main.dart
Hello world: 42!
Sparky-2.local:~/tmp/stagehand
$ dartdoc
Unhandled exception:
Invalid argument (uri): Unknown package: Instance of '_SimpleUri'
#0      resolveUri.<anonymous closure>
(package:resource/src/resolve.dart:13:9)
#1      _RootZone.runUnary (dart:async/zone.dart:1381:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#3      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:680:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#6      _AsyncAwaitCompleter.complete
(dart:async-patch/async_patch.dart:32:15)
#7      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#8      _resolvePackageUriFuture (dart:_builtin)
<asynchronous suspension>
#9      Isolate.resolvePackageUri
(dart:isolate-patch/isolate_patch.dart:352:16)
#10     resolveUri (package:resource/src/resolve.dart:11:20)
#11     PackageLoader.readAsBytes
(package:resource/src/package_loader.dart:27:33)
#12     loadAsBytes (package:dartdoc/src/html/resource_loader.dart:32:45)
#13     loadAsString (package:dartdoc/src/html/resource_loader.dart:20:21)
#14     _DefaultTemplatesLoader.loadPartials
(package:dartdoc/src/html/templates.dart:106:33)
#15     _loadPartials (package:dartdoc/src/html/templates.dart:76:40)
#16     Templates._create (package:dartdoc/src/html/templates.dart:195:26)
#17     Templates.createDefault
(package:dartdoc/src/html/templates.dart:165:12)
#18     HtmlGenerator.create
(package:dartdoc/src/html/html_generator.dart:68:35)
#19     initGenerators (package:dartdoc/src/html/html_generator.dart:163:25)
#20     Dartdoc.withDefaultGenerators (package:dartdoc/dartdoc.dart:67:40)
#21     main
(file:///b/s/w/ir/cache/builder/sdk/third_party/pkg/dartdoc/bin/dartdoc.dart:91:23)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:305:32)
#23     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:174:12)
Sparky-2.local:~/tmp/stagehand
$

**Comment by jcollins-g** [comment]
To be honest this bug is not likely to receive much attention unless I can reproduce it as I don't have a lot of time to work on dartdoc right now.  PRs are welcome however if you want to take a look.

I would recommend trying pub global activate dartdoc to get the latest version of dartdoc and trying that  -- while I can't reproduce your bug even with the exact same version, it's at least worth a try to see if things improve.

If possible I'll try and dig a little deeper next week.

**Comment by mobileink** [comment]
After upgrading to dart 2.7.2, dartdoc 0.29.1 seems to work.

Thanks,

gregg
