### ISSUE TITLE
allow dartdoc to document unforked NNBD SDK

### ISSUE THREAD

**Issue by liamappelbe** [dart-lang/dartdoc#2166]
We're moving towards unforking the Dart NNBD SDK (ideally this week), but one of the blockers is that dartdoc needs to be updated to be able to document opted in code.

I think all that needs to be updated is that a couple of files need to be updated to handle the new `NeverElementImpl` from the analyzer API. This new element is very similar to `DynamicElementImpl`.

I had a go at doing this in the SDK's local copy of  dartdoc, and was able to get it working by adding a `NeverType` class to the model directory that's essentially the same as `Dynamic`, updating `ModelElement.from` to handle `ElementKind.NEVER` similarly to how it handles `ElementKind.DYNAMIC`, and then just adding `|| ElementKind.NEVER` basically everywhere else `ElementKind.DYNAMIC` is referenced.

We need to get this fixed ASAP, so if this sounds like a good approach I'd be happy to send a PR with what I've got.

**Comment by devoncarew** [comment]
@jcollins-g is OOO today; sending a PR would be great. If she's not back tomorrow we can find an alternative reviewer.

**Comment by mit-mit** [comment]
@Levi-Lesches would you mind filing a new issue for that? The current tracker here is the right one. Thanks!

**Comment by Levi-Lesches** [comment]
Done -- #2232
