### ISSUE TITLE
Using {@youtube} it throughs error like, requests to the server have been blocked by an extension

### ISSUE THREAD

**Issue by Yuvaraj-Gajaraj** [dart-lang/dartdoc#2172]
While using {@youtube} tag with the youtube video link it is not working properly. It through error like
**Requests to the server have been blocked by an extension.** While generate the API documentation locally using `dartdoc` command then it is working perfectly, but while publishing package it is not working properly. 

**Tag With URL**
 `{@youtube 560 315 https://www.youtube.com/watch?v=DL0Ix1lnC4w}`

**Image**
![image](https://user-images.githubusercontent.com/61863686/78656454-0bdb8080-78e5-11ea-83d0-1771f0bec848.png)

**Comment by jcollins-g** [comment]
Can you give an example page on pub where it is not working?

**Comment by jcollins-g** [comment]
@Yuvaraj-Gajaraj, please reopen if you are still having this issue or have more information.
