### ISSUE TITLE
Request: linked, fully qualified annotations for a ModelElement

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#219]
Currently, our annotations are just String names. But consider this case:

```
@MyAnnotation('some value')
class Foo ...
```

Request is to have a getter on ModelElement that returns all "fully qualified" annotations. Instead of `MyAnnotation`, I'd like to display `MyAnnotation('some value')` in the docs.

Basically, I want to reconstruct the entire annotation. We also need to make it linked. For example, I'd like to click on MyAnnotation and be taken to that class.

After a quick glance, this doesn't look trivial. So I need @keertip's help :)

**Comment by sethladd** [comment]
@keertip rocked this PR https://github.com/dart-lang/dartdoc/pull/223

**Comment by keertip** [comment]
@sethladd, not quite done yet! Have to get the linking in :)

**Comment by keertip** [comment]
working in it now.

**Comment by keertip** [comment]
#225
