### ISSUE TITLE
error: unresolved doc reference [ByteStream]

### ISSUE THREAD

**Issue by ishaileshmishra** [dart-lang/dartdoc#2198]
In documentation inherited from base_client.BaseClient.send:

**Comment by jcollins-g** [comment]
Hi @ishaileshmishra , thanks for filing an issue.  Can you give more context as to what you're trying to do?  For example, what the contents of the documentation comment are for base_client.BaseClient.send and what you expect ByteStream to link to, and as much of the output of dartdoc that you can share.

**Comment by ishaileshmishra** [comment]
Scenario: 
1. take a class that extends abstract class that implements the concrete function
2. dartdoc tries to take doc reference from the super class

Example in my case:

```
class HttpClient extends http.BaseClient {

@override
  Future<http.StreamedResponse> send(http.BaseRequest request) {
    return _client.send(request);
  }

}
```

**Comment by jcollins-g** [comment]
This is a more general problem with how to handle warnings in docs the user didn't create but are imported.  We should be able to do this better.

**Comment by srawlins** [comment]
Sorry for the delay here @ishaileshmishra . I'm closing this as stale, but if you experience this, please feel free to re-open. I just need a complete reproduction, with imports, etc. Thanks!
