### ISSUE TITLE
Add html tags at specific place.

### ISSUE THREAD

**Issue by ishaileshmishra** [dart-lang/dartdoc#2201]
I have a scenario to adding the Html content inside <head> tag after just next to <title> tag:

Example

```
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1, user-scalable=no">
  <meta name="description" content="API docs for the Sphere class from the calculus library, for the Dart programming language.">
  <title>Asset class - sphere library - Dart API</title>

  **<!-- I have to add html here  -->**
  
<base href="..">
  <link href="https://fonts.googleapis.com/css?family=Source+Code+Pro:500,400i,400,300|Source+Sans+Pro:400,300,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="static-assets/github.css">
  <link rel="stylesheet" href="static-assets/styles.css">
  <link rel="icon" href="static-assets/favicon.png">
  <!-- header placeholder -->
</head>
```

**Comment by jcollins-g** [comment]
@ishaileshmishra Thanks for filing a feature request.  Does the existing `--header` functionality not work?  That will place HTML at the header placeholder, still inside `<head>`.  Flutter uses this to adjust style.

**Comment by ishaileshmishra** [comment]
@jcollins-g I am not familiar with this --header feature. could you please provide the link of implementation so I can check if it solves the problem.

**Comment by jcollins-g** [comment]
@ishaileshmishra 

See the README for documentation on `--header`.  A very complex example is used in building the Flutter documentation, here: https://github.com/flutter/flutter/blob/7f400af35a0716efc86f5b9401dcbedc501c2ed7/dev/tools/dartdoc.dart#L136

**Comment by jcollins-g** [comment]
Sorry, the README doesn't actually have that.  But dartdoc --help does.

**Comment by jcollins-g** [comment]
@ishaileshmishra Please let me know if you have further questions on this and/or reopen the issue.
