### ISSUE TITLE
Implementation section drops semi-colons for late fields

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2202]
When NNBD is enabled we're losing semicolons for fields, for some reason.

![Screen Shot 2020-05-06 at 2 40 15 PM](https://user-images.githubusercontent.com/14116827/81319148-17d17400-9044-11ea-9d22-4e0747e34d05.png)

**Comment by mit-mit** [comment]
@jcollins-g how is this progressing?

**Comment by devoncarew** [comment]
cc @srawlins

**Comment by srawlins** [comment]
I can prioritize this for September.

**Comment by franklinyow** [comment]
Any update?

**Comment by srawlins** [comment]
No update

**Comment by mit-mit** [comment]
Moving to P1; getting beta done is our highest feature priority at the moment

**Comment by srawlins** [comment]
Do we know why this issue is in the Beta epic?

**Comment by mit-mit** [comment]
Looks like that's where jcollins tagged it when it was filed. Is the only impact here that `;` is missing in the Implementation section? If so, I'm happy to more this back to P2 and punt to the stable milestone.

**Comment by jcollins-g** [comment]
I think putting things on the Beta milestone was at one point "the place we punted things to".  AFAIK the semicolon is the only impact.

**Comment by mit-mit** [comment]
Got it, updated
