### ISSUE TITLE
method signature text does not align correctly when wrapped

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#221]
the alignment of the text is not right when it wraps.

![screen shot 2015-02-18 at 3 45 30 pm](https://cloud.githubusercontent.com/assets/2192312/6259261/6394cfc4-b785-11e4-81dd-4e5d0fb11b58.png)

**Comment by sethladd** [comment]
Good catch! Thanks for the report

**Comment by sethladd** [comment]
Covered in PR https://github.com/dart-lang/dartdoc/pull/233
