### ISSUE TITLE
dartdoc should allow nnbd ? and ! inside comment references

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2212]
I expect people will write things like `[Object?]` and possibly even `[fieldName!]` to refer to elements in comment references.  Support this similarly to how we used to strip out 'new' and other extraneous information.

**Comment by mit-mit** [comment]
@jcollins-g how is this progressing?

**Comment by devoncarew** [comment]
cc @srawlins

**Comment by srawlins** [comment]
I can prioritize this for September.

**Comment by srawlins** [comment]
Fixed by https://github.com/dart-lang/dartdoc/pull/2328
