### ISSUE TITLE
is there such way to generate a tree sidebar by file path?

### ISSUE THREAD

**Issue by super-yolin** [dart-lang/dartdoc#2218]
I want to generate a sidebar with pages and widgets categories

what should I do?

**Comment by jcollins-g** [comment]
Theoretically that might be possible with custom templates, but that's beyond the scope of a bug report.  Dartdoc uses mustache for its templating system.

If you want to build such an option, we might consider including it via flag but it would be a massive change.  Can you describe more about what you're trying to achieve?

**Comment by super-yolin** [comment]
Thank you so much for listening.

This is what i want 👇🏻

## Coments
```dart

/// {@menu businessPage}
/// {@nickname 购物车}
class ShoppingCart ...

/// {@menu baseWidget}
/// {@nickname 块标题}
class BlockTitle ...

/// {@menu businessWidget}
/// {@nickname 商品标题}
class ProductTitle ...

```


## Sidebar Menu
* business page
  * 购物车
* base widget
  * 块标题
* business widget
  * 商品标题

**Comment by jcollins-g** [comment]
@super-yolin It sounds like you want dartdoc to support alternative names for symbols for different languages.  A "nickname" inline doesn't seem scalable to the many languages that exist, but some way of referencing symbols for additional information out of band seems like a good idea.  The Category support in dartdoc (https://github.com/dart-lang/dartdoc#categories) should allow you to tag symbols and have dartdoc organize them into separate pages for you.
