### ISSUE TITLE
Synthetic configuration option flutterRoot from <internal>

### ISSUE THREAD

**Issue by akifarhan** [dart-lang/dartdoc#2229]
Error when generating dartdoc from flutter project.

```
dartdoc failed: Synthetic configuration option flutterRoot from <internal>, computed as PATH, resolves to missing path: PATH.
```

**Comment by jcollins-g** [comment]
@akifarhan 

Hi, that looks like your FLUTTER_ROOT variable might be set to something invalid, like the string 'PATH'.  Can you check that environment variable and try again?

**Comment by akifarhan** [comment]
I set my FLUTTER ROOT to `$HOME/development/flutter/bin/flutter"`? Is it correct?

**Comment by akifarhan** [comment]
Okay my bad. I shouldve set it to root -- `$HOME/development/flutter`

**Comment by akifarhan** [comment]
Thank you @jcollins-g
