### ISSUE TITLE
Dartdoc doesn't handle nnbd return type for Map.[]

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/dartdoc#2232]
Despite handling the return type for a static function properly (for example, documenting  [`int.tryParse`](https://api.dart.dev/dev/2.9.0-13.0.dev/dart-core/int/tryParse.html) as `int?`), it got the documentation for [`Map.[]`](https://api.dart.dev/dev/2.9.0-13.0.dev/dart-core/Map/operator_get.html) as `V` instead of `V?`, despite the code snippet clearly showing otherwise. Perhaps it's an operator thing?

**Comment by mit-mit** [comment]
cc @jcollins-g

**Comment by jcollins-g** [comment]
verified fixed with #2227
