### ISSUE TITLE
Dartdoc doesn't support null safety `required` keyword

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/dartdoc#2247]
Thanks @hixie for noticing this!

An example of the bad output can be seen here: https://master-api.flutter.dev/flutter/dart-ui/Rect/Rect.fromCenter.html

**Comment by srawlins** [comment]
I see the following text at that link:

```none
Rect.fromCenter(
{required Offset center,
required double width,
required double height}
)
```

Does it look like this has been fixed?
