### ISSUE TITLE
Require @nodoc to be on the last line of a doc comment

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#2256]
Right now, dartdoc respects `@nodoc` and `<nodoc>` anywhere in a doc comment.

Checking for this string anywhere in a doc comment appears in profiling to take a lot of time. I think it makes perfect sense to require that it be on the last line, and that we don't respect `<nodoc>`.

It's a breaking change, but internal searching shows that all cases are on the last line. If any code does not have it on the last line, it can easily be changed in said code and a new package published.

**Comment by devoncarew** [comment]
> Checking for this string anywhere in a doc comment appears in profiling to take a lot of time

Hmm, that's somewhat surprising. Is there a polynomic algorithm somewhere - are we doing something like checking each comment n^2 times, where n is the number of documented symbols in a package?

**Comment by devoncarew** [comment]
I have no issues with restricting when we recognize nodoc, just curious why this is showing up as a performance issue.

**Comment by srawlins** [comment]
I may not be great at profiling. But String.indexOf showed up, mostly called by String.contains, mostly when checking for `@nodoc`.

**Comment by srawlins** [comment]
After testing this idea, it doesn't seem to change performance at all. Additionally, I've found a few other directives. I didn't know we had so many. Probably not worth it to require this change.
