### ISSUE TITLE
Paragraph breaks don't render correctly for enum dartdocs

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dartdoc#2268]
e.g. https://master-api.flutter.dev/flutter/rendering/CrossAxisAlignment-class.html

The source code is:

```dart
  /// Place the children along the cross axis such that their baselines match.
  ///
  /// Because baselines are always horizontal, this alignment is intended for
  /// horizontal main axes. If the main axis is vertical, then this value is
  /// treated like [start].
  ///
  /// For horizontal main axes, if the minimum height constraint passed to the
  /// flex layout exceeds the intrinsic height of the cross axis, children will
  /// be aligned as close to the top as they can be while honoring the baseline
  /// alignment. In other words, the extra space will be below all the children.
  ///
  /// Children who report no baseline will be top-aligned.
```

The resulting HTML looks like this:

![Screen Shot 2020-07-15 at 1 27 10 PM](https://user-images.githubusercontent.com/15253456/87592564-f07bd080-c69e-11ea-9c9b-e27f1723e87f.png)

It should look like this:

![Screen Shot 2020-07-15 at 1 27 10 PM](https://user-images.githubusercontent.com/15253456/87593586-849a6780-c6a0-11ea-8526-1cae0caf84e3.png)

**Comment by jdkoren** [comment]
Interesting, I wonder if that has to do with the doc content being inside of a `<dd>` tag
