### ISSUE TITLE
`index.json` does not mention packages or package names anywhere

### ISSUE THREAD

**Issue by jdkoren** [dart-lang/dartdoc#2270]
Perhaps this is working as intended, but I notice that packages / package names are not mentioned anywhere in the generated `index.json` (used for the search index). I'd like to use this file as an input to other tools, and discovered the lack of package names in the process.

**Comment by jdkoren** [comment]
Would it be problematic if we added `"packageName": "${e.package.name}"` for each entry in the index? This would not add new entries, but would let us know which package an element is found in. I made a pull request for that, but happy to explore other ideas.

**Comment by srawlins** [comment]
I don't think this would be problematic.
