### ISSUE TITLE
 Invalid argument(s): join(null, "bin", "cache", "dart-sdk"): part 0 was null, but part 1 was not.

### ISSUE THREAD

**Issue by rajat-girnar** [dart-lang/dartdoc#2279]
while we generating doc this error will come.And I set dart-SDK path ,flutter-SDK path but is not working

**Comment by srawlins** [comment]
Thanks for filing this issue! Would you mind sharing the command you used to run dartdoc? I guess I'm mostly interested in seeing the Dart SDK path and Flutter SDK path.

**Comment by rajat-girnar** [comment]
Command for Dartdoc : **dartdoc**
Dart-Sdk Path :  **export PATH=/home/rajat/Documents/sdk/flutter/bin/cache/dart-sdk/bin/:$PATH**
Flutter-SDK Path:  **export PATH=/home/rajat/Documents/sdk/flutter/bin/:$PATH** 
@srawlins  please check this

**Comment by Quwaysim** [comment]
I'm having the same issue

**Comment by sakebook** [comment]
I tried this and it solved the problem.

https://github.com/dart-lang/dartdoc/issues/1705

**Comment by sidrao2006** [comment]
Duplicate of #1705
