### ISSUE TITLE
Documenting flutter app fails with dartdoc failed: Unknown type NeverElementImpl on dartdoc v0.29.1

### ISSUE THREAD

**Issue by Vbbab** [dart-lang/dartdoc#2280]
The issue occurs when creating a Flutter application (e.g. from Android Studio), then attempting to document it using `dartdoc`. After a bit of analysis, `dartdoc` throws the error `dartdoc failed: Unknown type NeverElementImpl`. Attatched is a full dump of `dartdoc`'s output.

Here is [dartdoc.txt](https://github.com/dart-lang/dartdoc/files/5011441/dartdoc.txt)

**Comment by srawlins** [comment]
This version of dartdoc is quite old. Recent versions of Dart or Flutter should ship with a newer version.

**Comment by jcollins-g** [comment]
@Vbbab As @srawlins indicated, the version you're referencing is very old.  You must have at least version `0.30.3` to support the analyzer's representation of the `Never` type (the exception you reported), and we recommend using the latest version available via `pub global activate dartdoc` -- currently `0.34.0`.

If you can reproduce the problem on a newer version, please reopen the issue.
