### ISSUE TITLE
Not processing some tool directives inside templates

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#2281]
Commit https://github.com/dart-lang/dartdoc/commit/6d5396c2b4bc415ab9cb3d8212b87ecffd90a272 created a new bug where doc comments which are not prefetched are processed with `processCommentWithoutTools` , in which the behavior changed to _process templates_ but still not process _tools_.

**Comment by srawlins** [comment]
This should be fixed before 0.32.3 is published.

cc @goderbauer

**Comment by goderbauer** [comment]
The problem was discovered when trying out https://github.com/dart-lang/dartdoc/commit/6d5396c2b4bc415ab9cb3d8212b87ecffd90a272 with Flutter: https://github.com/flutter/flutter/pull/62622
