### ISSUE TITLE
Travis builds fail to build docs for self... apparently

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#229]
The travis builds have been saying this for a while:

```
  failed: docs not generated
        : testDartdoc (file:///home/travis/build/dart-lang/dartdoc/tool/grind.dart:30:46)
```

1) Why does it say failed? :)
2) Why doesn't the build break?

Does this indicate a real issue or a misconfigured build?

**Comment by keertip** [comment]
#257
