### ISSUE TITLE
Implementers section missing on RestorableValue.

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2290]
https://master-api.flutter.dev/flutter/widgets/RestorableInt-class.html says:

```
Inheritance
Object > ChangeNotifier > RestorableProperty<int> > RestorableValue<int> > RestorableNum<int> > RestorableInt
```

Click on `RestorableNum`, you get https://master-api.flutter.dev/flutter/widgets/RestorableNum-class.html:

```
Inheritance
Object > ChangeNotifier > RestorableProperty<T> > RestorableValue<T> > RestorableNum
Implementers
RestorableDouble, RestorableInt
```

Click on `RestorableValue`, you get https://master-api.flutter.dev/flutter/widgets/RestorableValue-class.html:

```
Inheritance
Object > ChangeNotifier > RestorableProperty<T> > RestorableValue
```

...with no "Implementers" section!

**Comment by Hixie** [comment]
Oh, it's probably because there's a private class between RestorableValue and RestorableNum in the inheritance hierarchy.

**Comment by srawlins** [comment]
I think the solution is to treat any intermediate private classes as invisible "proxies", and continue to the public ones.

So if

* A implements B, and
* C implements _D implements B, and
* E implements _F implements _G implements B,

then the page for B should list, as implementors, A (as it would today), C (skipping over _D), and E (skipping over _F and _G). Classes which implement A, C, and E are not shown (it is only a list of immediate implementors), but the links are there to follow.

**Comment by srawlins** [comment]
f5985ce7143385512f63e51e264eb3710d6a525c seems to have exacerbated this.
