### ISSUE TITLE
Investigate the persistent failure in the flutter CI bot

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#2302]
See here for an example failure:

https://travis-ci.org/github/dart-lang/dartdoc/builds/718426662

```
...
flutter-docs: Precompiled grinder:_boot.
flutter-docs: Precompiled grinder:_boot.
flutter-docs: Precompiled grinder:_boot.
flutter-docs: Precompiled grinder:grinder.
flutter-docs: Precompiled grinder:init.
flutter-docs: Precompiled coverage:format_coverage.
flutter-docs: Precompiled coverage:format_coverage.
flutter-docs: Precompiled coverage:run_and_collect.
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by devoncarew** [comment]
Possibly a dup of https://github.com/dart-lang/dartdoc/issues/2233 ?

**Comment by jcollins-g** [comment]
looking at this and similar hangs in the CI I think it is a deadlock in MultiFutureTracker, probably due to a change in how Future.next() is executed.  It's extremely hard to tell just by inspection though -- I'll poke at it a bit.

**Comment by jcollins-g** [comment]
from Future.then:  "If this future is already completed, the callback will not be called immediately, but will be scheduled in a later microtask.".  MultiFutureTracker depends on the callback being called immediately after the completion of the Future in order not to deadlock.  PR coming up.

**Comment by jcollins-g** [comment]
I'm still working on the deadlock and it isn't the only problem.  We are also impacted by https://github.com/dart-lang/sdk/issues/43487 as our coverage runs require passing special flags to the Dart VM.
