### ISSUE TITLE
Investigate other windows CIs

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#2304]
We're not really maintaining our windows CI (currently appveyor based). We should investigate other windows CI systems (travis, github actions, ...).

https://github.com/dart-lang/dartdoc/blob/master/appveyor.yml

**Comment by parlough** [comment]
Fixed by move to GitHub Actions in https://github.com/dart-lang/dartdoc/commit/b956fa37782d473e3bda652f9d75a5e47b5b3987
