### ISSUE TITLE
Implement external and abstract variables

### ISSUE THREAD

**Issue by eernstg** [dart-lang/dartdoc#2310]
Cf. the [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/abstract-external-fields/implementation-plan.md), the addition of external and abstract variables to Dart may require some updates.

**Comment by srawlins** [comment]
Currently dartdoc only indicates an abstract class or an abstract method via _very_ muted text in the title:

* https://pub.dev/documentation/analyzer/0.39.17/dart_element_element/Element-class.html
* https://pub.dev/documentation/analyzer/0.39.17/dart_element_element/Element/accept.html

I don't think "external" methods are indicated in any way. 😕 

* https://api.dart.dev/stable/2.9.2/dart-collection/HashMap/HashMap.html

So I think to complete this feature, I will annotate abstract fields in the same way that abstract classes and methods are now. I don't think there is any work to be done for external fields or variables.
