### ISSUE TITLE
Now the generated documents are sorted by alphabet. I want to generate documents in the order of code writing. How to do this

### ISSUE THREAD

**Issue by c1avie** [dart-lang/dartdoc#2317]
![image](https://user-images.githubusercontent.com/2912208/91117927-69b90b00-e6c2-11ea-8c69-4571b1c5fa26.png)

**Comment by srawlins** [comment]
Thanks for reporting this issue. The only sorting available today is alphabetical. There is an existing issue for the idea, https://github.com/dart-lang/dartdoc/issues/1551.

**Comment by c1avie** [comment]
How to get rid of alphabetic sorting in dartdoc_options.yaml？

**Comment by srawlins** [comment]
The only sorting available today is alphabetical.
