### ISSUE TITLE
Wrong name used to access the index field of enumeration constants

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/dartdoc#2318]
In at least one place:
```
new ModelElement.fromPropertyInducingElement (package:dartdoc/src/model/model_element.dart:203:65)
```
this package is assuming that every enumeration constant has a field whose name is the same as the name of the constant and whose value is the index of the constant. That isn't true; the field is named `index`. We need to fix the analyzer to stop producing a representation of such a field, but we can't do so until this package stops depending on the existence of that field.

The easiest way to test that all such locations have been fixed might be to update the version of `analyzer` being used by `dartdoc` to stop producing the invalid field. The code that produces the field is, as of this writing, at `pkg/analyzer/lib/src/dart/element/element.dart:1778`.

**Comment by srawlins** [comment]
Thanks for filing this, @bwilkerson .

If I try to change that case on line 203 from:

```dart
var index = e.computeConstantValue().getField(e.name).toIntValue();
```

to

```dart
var index = e.computeConstantValue().getField('index').toIntValue();
```

I get a null pointer exception:

```none
  NoSuchMethodError: The method 'toIntValue' was called on null.                                                                                                     
  Receiver: null                                                                                                                                                     
  Tried calling: toIntValue()                                                                                                                                        
  dart:core                                             Null.toIntValue                                                                                              
  package:dartdoc/src/model/model_element.dart 203:66   new ModelElement.fromPropertyInducingElement
```

Are we sure that analyzer's enum constant values contain that `index` getter, and that it contains a value?

**Comment by scheglov** [comment]
Was fixed https://github.com/dart-lang/dartdoc/pull/2865
