### ISSUE TITLE
dartdoc help output is hard to read

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/dartdoc#2350]
`dartdoc --help` prints it's output in a very very narrow column, which is unaffected by the console width:

<img width="1207" alt="Screenshot 2020-09-16 at 11 33 33" src="https://user-images.githubusercontent.com/13644170/93319719-7ee01000-f810-11ea-812b-8ad2df783416.png">

I'd expect the output to be wrapped to fit in the width of the terminal, not a preset (very small) hardcoded width.

We have an API for getting the terminal width: https://api.dart.dev/stable/2.9.1/dart-io/Stdout/terminalColumns.html
For a similar change we made recently, see https://dart-review.googlesource.com/c/sdk/+/158400.

**Comment by devoncarew** [comment]
Good catch! This was addressed ~12 days ago in the dartdoc repo (https://github.com/dart-lang/dartdoc/pull/2333). Sam has brought the latest into the sdk repo recently. It may or may not have made the cut for whatever version you were testing.

@mit-mit, can you include the dart version you were using? cc @srawlins

**Comment by mit-mit** [comment]
I'm running `pub global run dartdoc --help`

**Comment by mit-mit** [comment]
But I had an old activated version. I updated it, and it's working now! Closing.
