### ISSUE TITLE
Exclude file patterns

### ISSUE THREAD

**Issue by aloisdeniel** [dart-lang/dartdoc#2355]
Is there any way to exclude files from generation ?

I would like to ignore all output classes generated by tools ([freezed](https://github.com/rrousselGit/freezed/issues/259) in my case) : `*.freezed.dart` files.

**Comment by rrousselGit** [comment]
Maybe another idea is to ignore elements that start with $, as it seems that this is the convention used by code-generators.

**Comment by jcollins-g** [comment]
@rrousselGit would #2369 solve your issue?

**Comment by jcollins-g** [comment]
Closing, assuming #2369 is sufficient for this problem unless otherwise indicated.
