### ISSUE TITLE
Cannot install dartdoc

### ISSUE THREAD

**Issue by Vbbab** [dart-lang/dartdoc#2363]
The Dart SDK from [the website instructions](https://dart.dev/get-dart) ships with a rather old version of `dartdoc`. However, upon running `pub global activate dartdoc` to try to upgrade, during `Precompiling executables...` stage, `pub` fails, complaining about an unknown method `runZonedGuarded`.

Below is the full dump.
```
Failed to precompile dartdoc:bin\dartdoc:
../../Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.34.0/lib/dartdoc.dart:499:5: Error: The method 'runZonedGuarded' isn't defined for the class 'Dartdoc'.
 - 'Dartdoc' is from 'package:dartdoc/dartdoc.dart' ('../../Pub/Cache/hosted/pub.dartlang.org/dartdoc-0.34.0/lib/dartdoc.dart').
Try correcting the name to the name of an existing method, or defining a method named 'runZonedGuarded'.
    runZonedGuarded(
    ^^^^^^^^^^^^^^^
```

**Comment by jcollins-g** [comment]
@Vbbab which version of the Dart SDK are you using?

**Comment by Vbbab** [comment]
```
Dart VM version: 2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "windows_x64"
```

Installed via the website's instructions using `chocolatey`.

**Comment by jcollins-g** [comment]
@Vbbab Hi, via chocolatey you should be able to install this package:  https://chocolatey.org/packages/dart-sdk/2.9.3.  If you have used chocolatey before to install Dart, you might need to run `choco upgrade dart-sdk`.

**Comment by Vbbab** [comment]
Alright, thanks!

**Comment by Vbbab** [comment]
Also, seems that `dart-sdk` 2.9.3 conflicts with the `sass` package??
