### ISSUE TITLE
For methods or functions in the core SDK marked as async, state that they return a Future

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#237]
After talking to Gilad, the decision was made to not explicitly document that a function/method was marked as async. Instead, document that it returns a Future.

Let's test that we do the right thing for the SDK and package docs.

**Comment by sethladd** [comment]
Hi @keertip when you have a moment, can you look at what it will take to ask the Analyzer if a method was marked as async and then have our ModelFunction and Method objects state they return a Future?

Thanks!!

**Comment by sethladd** [comment]
Is this possible with the analyzer API?

We'll have to do something similar with async*

**Comment by keertip** [comment]
Yes, we can do this.

**Comment by sethladd** [comment]
![screen shot 2015-03-01 at 1 08 46 pm](https://cloud.githubusercontent.com/assets/5479/6432815/1f5fd474-c014-11e4-8930-8c6e4aa153b9.png)

**Comment by keertip** [comment]
Looks like the sdk libraries have to move to using async. Test when the change has been made.

**Comment by sethladd** [comment]
We do this.

![screen shot 2015-07-17 at 2 58 55 pm](https://cloud.githubusercontent.com/assets/5479/8758033/5f7e7bf4-2c94-11e5-8307-110c43454140.png)
