### ISSUE TITLE
Error class in Flutter dartdocs reference classes that aren't in the documentation

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2382]
https://master-api.flutter.dev/flutter/dart-core/Error-class.html
If you click on FuchsiaRemoteConnectionError, RpcFormatError, SshCommandError, and maybe others, in the "Implementors" list, you end up at a 404 page. I think those packages aren't supposed to be included in the documentation generation?

**Comment by jcollins-g** [comment]
tagging @srawlins as he's been in this area

**Comment by jcollins-g** [comment]
This may be related to some fixes we made to include more things in the Implementors list.  The original bug may have been hiding that we weren't correctly keeping track of what we weren't supposed to be documenting.

**Comment by srawlins** [comment]
Yeah very likely related to my work to improve the Implementors section.

**Comment by jcollins-g** [comment]
Actually, the implementors is only one piece of the bug and not even the biggest part.  Dartdoc is assuming "remote" documentation for packages in Flutter that are excluded via the command line.  This is wrong and may lead to many more errors.

**Comment by jcollins-g** [comment]
Even worse those errors can't be found with the link checker because the link checker skips over remote links.  So, for dartdoc, this is P0.
