### ISSUE TITLE
Doc request: how to run newer dartdoc in flutter context

### ISSUE THREAD

**Issue by srp7474** [dart-lang/dartdoc#2385]
I am writing a Flutter package I need to publish. I too am experiencing issues like issue #2382 plus other crashes plus strange errors like ```error: unresolved doc reference [RenderTable.debugDescribeChildren]```

The version I am running is 0.32.4 and Flutter 1.21.1 on a windows machine.

I realize it is more efficient for all for me to have  your latest code on which to report issues with (0.35.0)

Please point me to doc (I looked very hard) on how to do this.  Perhaps it is not advisable as the flutter package might have been baked in  with 0.32.4.

I tried installing dart using choocolaty but there too I could not figure out how to upgrade to the new dartdoc version.  Also the version installed had no idea how to document the Flutter package.  Obviously the Flutter context passes a lot of parameters to dartdoc under the covers,

Thanks, Steve

**Comment by jcollins-g** [comment]
`pub global activate dartdoc` is the recommended way to get the latest version of dartdoc on all platforms.  If you're using Flutter, be sure to use the `pub` that comes with the version of Dart that is embedded in the Flutter SDK.  All this will depend on your path being set correctly.
