### ISSUE TITLE
dartdoc version management woes. reports wrong version

### ISSUE THREAD

**Issue by srp7474** [dart-lang/dartdoc#2390]
Thanks for the help on upgrading dartdoc.

I ran on my Windows 7 machine
```C:\tools\dart-sdk\bin>pub global activate dartdoc```

and got (I ran it twice) 

```Package dartdoc is currently active at version 0.35.0.```

and a dump of dependent packages
```
Resolving dependencies...
+ _fe_analyzer_shared 11.0.0
+ analyzer 0.40.4
+ args 1.6.0
+ async 2.4.2
+ charcode 1.1.3
+ cli_util 0.2.0
+ collection 1.14.13
+ convert 2.1.1
+ crypto 2.1.5
+ csslib 0.16.2
+ dartdoc 0.35.0
+ glob 1.2.0
+ html 0.14.0+4
+ js 0.6.2
+ logging 0.11.4
+ markdown 2.1.8 (3.0.0 available)
+ meta 1.2.3
+ mustache 1.1.1
+ node_interop 1.1.1
+ node_io 1.1.1
+ package_config 1.9.3
+ path 1.7.0
+ pedantic 1.9.2
+ pub_semver 1.4.4
+ source_span 1.7.0
+ string_scanner 1.0.5
+ term_glyph 1.1.0
+ typed_data 1.2.0
+ watcher 0.9.7+15
+ yaml 2.2.1
Precompiling executables...
Precompiled dartdoc:dartdoc.
Installed executable dartdoc.
Activated dartdoc 0.35.0.
```

yet when I run

```
C:\tools\dart-sdk\bin>dartdoc --version
running C:\tools\dart-sdk\bin\dart against C:\tools\dart-sdk\bin
dartdoc version: 0.32.4
```
 The version has not changed.  Flutter is in the path.  So is the version number wrong or what.

I added the `running` line to the batch file to make sure that is what I was executing.

Thanks,
Steve

**Comment by jcollins-g** [comment]
Your path does not include the directory where pub has installed the package, or if it has the path, it is not in front of the SDK path.   This is part of installing the dart SDK.  If you can't adjust the path for some reason, "pub global run dartdoc" will work.

**Comment by srp7474** [comment]
@jcollins-g Thanks Janice.  How do I find out where pub has installed the package.  I would prefer to update the path. The `pub global run dartdoc` did work.
