### ISSUE TITLE
Members with lots of parameters wrap poorly in the index views

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2408]
e.g. https://master-api.flutter.dev/flutter/material/TabBar-class.html

The constructor looks like this:

```
Constructors
TabBar({Key? key, required List<
   Widget> tabs, TabController? controller, bool isScrollable: false, Color? indicatorColor, double indicatorWeight: 2.0, EdgeInsetsGeometry indicatorPadding: EdgeInsets.zero, Decoration? indicator, TabBarIndicatorSize? indicatorSize, Color? labelColor, TextStyle? labelStyle, EdgeInsetsGeometry? labelPadding, Color? unselectedLabelColor, TextStyle? unselectedLabelStyle, DragStartBehavior dragStartBehavior: DragStartBehavior.start, MouseCursor? mouseCursor, ValueChanged<int
   >? onTap, ScrollPhysics? physics})
Creates a material design tab bar. [...]
const
```

**Comment by jcollins-g** [comment]
Looks like our breaks are not set up properly?  This could be an issue on smaller screens / mobile too even for smaller sets of parameters, so setting to P2.

**Comment by mleonhard** [comment]
#2620 has an extreme example and screenshots.

Let's rename this issue to an action.  Suggestion: "Add line breaks to large param lists for readability."

**Comment by jamesderlin** [comment]
This issue shouldn't be about adding line-breaks, it should be about making the text wrappable.
