### ISSUE TITLE
move null safety notification to the sidebar and remove from individual symbols

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2409]
As @mit-mit mentioned,  move the null safety tag out of individual titles.

Filing separately as this doesn't seem P1/blocking to me.

<img width="898" alt="Screenshot 2020-10-22 at 21 05 14" src="https://user-images.githubusercontent.com/13644170/96918333-72ec0b80-14aa-11eb-886c-d7d116c4dc49.png">

_Originally posted by @mit-mit in https://github.com/dart-lang/dartdoc/issues/2403#issuecomment-714700519_

**Comment by parlough** [comment]
Superseded by https://github.com/dart-lang/dartdoc/issues/3294
