### ISSUE TITLE
NPE: importedExportedLibraries was called on null

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#2426]
Affected version: `0.36.2`
Original report: https://github.com/dart-lang/pub-dev/issues/4238

To reproduce:
- Download `flutter_instagram_stories` from [here](https://storage.googleapis.com/pub-packages/packages/flutter_instagram_stories-0.1.5%2B4.tar.gz).
- Run `dartdoc` without any extra parameters (but with Flutter in path or `FLUTTER_ROOT` set).

Also affected packages: `fid_widgets`, `typeahead`.

````
NoSuchMethodError: The getter 'importedExportedLibraries' was called on null.
Receiver: null
Tried calling: importedExportedLibraries
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Library.importedExportedLibraries (package:dartdoc/src/model/library.dart:272:47)
#2      Library.packageImportedExportedLibraries.<anonymous closure> (package:dartdoc/src/model/library.dart:253:52)
#3      Iterable.forEach (dart:core/iterable.dart:283:30)
#4      Library.packageImportedExportedLibraries (package:dartdoc/src/model/library.dart:252:12)
#5      _MarkdownCommentReference._reducePreferLibrariesInLocalImportExportGraph.<anonymous closure> (package:dartdoc/src/markdown_processor.dart:531:24)
#6      SetMixin.any (dart:collection/set.dart:190:15)
#7      _MarkdownCommentReference._reducePreferLibrariesInLocalImportExportGraph (package:dartdoc/src/markdown_processor.dart:530:17)
#8      _MarkdownCommentReference.computeReferredElement (package:dartdoc/src/markdown_processor.dart:471:21)
#9      _getMatchingLinkElement (package:dartdoc/src/markdown_processor.dart:240:12)
#10     _makeLinkNode (package:dartdoc/src/markdown_processor.dart:855:16)
#11     new MarkdownDocument.withElementLinkResolver.linkResolver (package:dartdoc/src/markdown_processor.dart:950:14)
````

**Comment by CaptainIRS** [comment]
The problem seems to occur when imports use a non-standard URI

#### Minimal Example with same error:

> **A.dart**
```dart
import 'subdirectory//B.dart';

/// Doc comment about [x]
class A {
  int x;
}
```

> **subdirectory/B.dart**
```dart
class B {}
```

**Comment by jcollins-g** [comment]
confirmed.

**Comment by jcollins-g** [comment]
Root of the issue is that Dart and therefore the analyzer treats the same file on disk differently based on how it is referenced -- there can be two separate "libraries" even if the URIs resolve to the same file.  Dartdoc will have to pretend that these references refer to the same library in order to get not only non-crashing, but sane looking results.   We might consider emitting a lint/info as well when users do this.

**Comment by jcollins-g** [comment]
This problem probably surfaced as a result of recent bugfixes where we traverse the import/export graph more correctly.
