### ISSUE TITLE
Topics are not sorted alphabetically or overridable by categoryOrder

### ISSUE THREAD

**Issue by timsneath** [dart-lang/dartdoc#2438]
See for example: 
https://win32.pub/topics/user32-topic.html

This makes the page unusable as a reference, since you can't scan. This feels like a regression, but I'm not certain :( 

Repro:
Page is built using `dartdoc --enable-experiment=non-nullable` on WSL. 

Source `dartdoc_options.yaml`:
https://github.com/timsneath/win32/blob/master/dartdoc_options.yaml

```bash
$ dartdoc --version
dartdoc version: 0.36.2
```

**Comment by jcollins-g** [comment]
Topics and the functions contained within them all seem to be unsorted for some reason.

**Comment by timsneath** [comment]
This is awesome -- the [link](https://win32.pub/topics/user32-topic.html) now contains sensible results with APIs ordered correctly. One side-effect however is that the `categoryOrder` option used to determine the ordering of the left hand navbar is no longer respected:

```yaml
  categoryOrder: ["kernel32", "user32", "gdi32", "shell32", "ole32", "oleaut32", "comctl32", "comdlg32", "shcore", "psapi", "version", "advapi32", "bthprops", "powrprof", "dxva2", "winmm", "com", "winrt", "examples"]
```

**Comment by jcollins-g** [comment]
@timsneath Oof, that was not intended -- categoryOrder should be respected and override the sort order.  I'll look into it.

**Comment by srawlins** [comment]
I fixed `categoryOrder` recently. Please re-open if it doesn't seem fixed on latest dartdoc.
