### ISSUE TITLE
sdk-analyzer test is broken

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2462]
Looks like migration of _fe_analyzer_shared broke our analysis test?

**Comment by parlough** [comment]
I think it should be fine now, can you trying running the tests again?

**Comment by jcollins-g** [comment]
@parlough Tried, but your fix is so new I have had to clear the Travis caches.  Going to spin them all again once the cache is populated.

**Comment by parlough** [comment]
Thanks for fixing this :)
