### ISSUE TITLE
Inherited methods are no longer italics in the right sidebar (regression)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2472]
Contrast the right sidebar in these two:
https://api.flutter.dev/flutter/rendering/RenderClipOval-class.html
https://master-api.flutter.dev/flutter/rendering/RenderClipOval-class.html

The methods that are inherited are italics in the old sidebar, and look exactly like overridden methods in the new sidebar. I noticed this in particular because now noSuchMethod looks like it's overridden by everyone and part of every API.

**Comment by parlough** [comment]
For reference, I believe this was caused by https://github.com/dart-lang/dartdoc/pull/2444, I'll submit a PR for this later today or tomorrow.
