### ISSUE TITLE
Can't type slash in the search field

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/dartdoc#2483]
Because `/` is a shortcut the jumps focus to the search field.

It's probably best to test if `document.activeElement` is a `input` or `textarea` tag before stealing focus and calling `e.preventDefault()`.

https://github.com/dart-lang/dartdoc/blob/29db6210948e341c2f6b94d9e8ff62563f18f062/lib/resources/script.js#L193-L198

**Comment by jonasfj** [comment]
side note: the shortcut is nice, we're looking into adding a similar thing on pub.dev

**Comment by parlough** [comment]
I'm making some other changes to this handling so I can take this.
