### ISSUE TITLE
Implemented types are obscured by intermediate private types

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2485]
Similar to #1623, implemented types only show directly implemented types and don't currently take into account that indirectly implemented types may not be exposed.

from @natebosch:

Another place I notices is that `Queue` doesn't show it implements `Iterable` because of the not-exposed `EfficientLengthIterable` class, but shows all the iterable methods as inherited.

_Originally posted by @natebosch in https://github.com/dart-lang/dartdoc/issues/1623#issuecomment-761203704_

**Comment by jcollins-g** [comment]
#2495 fixes most of this, however type parameters are not properly converted across.

**Comment by srawlins** [comment]
Forking that last bug into a new issue. https://github.com/dart-lang/dartdoc/issues/2997
