### ISSUE TITLE
Add generic type aliases to dartdoc

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2499]
There is now sufficient implementation in top of tree analyzer that we can do this.

**Comment by jcollins-g** [comment]
Landing this is blocked on #2500, which is in itself blocked on getting build, glob, and dart_style working well with the new analyzer.  In a private branch however most of the implementation is complete.

See also https://github.com/dart-lang/sdk/issues/44960.

**Comment by parlough** [comment]
@jcollins-g If you want to open a draft PR with the in progress changes, I'd be happy to take a preliminary look!

**Comment by jcollins-g** [comment]
I will be swinging back around to this feature shortly.
