### ISSUE TITLE
dartdoc needs to play nicely with null-safe analyzer

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2500]
The new null-safe analyzer at SDK head causes dartdoc's infrastructure to break, and we need to update our dependencies to be compatible with it once the new version of analyzer is published.

**Comment by parlough** [comment]
I'm quite excited =]

**Comment by jcollins-g** [comment]
Also, this is a prerequisite for actually migrating dartdoc's code, but does not include that work.  That'll be the next bug :-)
