### ISSUE TITLE
Allow generic function types as type arguments

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2517]
Blocks dart-lang/sdk#44922.

Implement dart-lang/language#496 for dartdoc once analyzer support is available.

**Comment by jcollins-g** [comment]
Blocked by dart-lang/sdk#44929.

**Comment by leafpetersen** [comment]
How's this looking?

**Comment by jcollins-g** [comment]
This is crashing with current published analyzer.  It does not crash, but has some obvious errors/omissions particularly in type bounds for generated documentation at head.

**Comment by franklinyow** [comment]
Any update?

**Comment by devoncarew** [comment]
@jcollins-g - FYI, the likely branch point for the next beta release (the first with this language feature enabled) is on or around May 18th; this is the last bit of work left for the small language features release.

**Comment by jcollins-g** [comment]
@devoncarew is that May 18th date still accurate?

**Comment by devoncarew** [comment]
No - it'll be closer to June 4 (https://github.com/dart-lang/sdk/milestone/92).
