### ISSUE TITLE
dartdoc 0.39.0 failed because it tries to invoke nullabilitySuffix on a null

### ISSUE THREAD

**Issue by hoylen** [dart-lang/dartdoc#2531]
The dartdoc program throws a NoSuchMethodError because it tries to invoke nullabilitySuffix on a null.

This is from dartdoc version 0.39.0 that comes with dart-2.12.0-259.14.beta.

```
% dartdoc
Documenting ssh_key...
-
dartdoc failed: NoSuchMethodError: The getter 'nullabilitySuffix' was called on null.
Receiver: null
Tried calling: nullabilitySuffix
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54:5)
#1      SubtypeHelper.isSubtypeOf (package:analyzer/src/dart/element/subtype.dart:51:29)
#2      TypeSystemImpl.isSubtypeOf2 (package:analyzer/src/dart/element/type_system.dart:1162:27)
#3      TypeSystemImpl.isSubtypeOf (package:analyzer/src/dart/element/type_system.dart:1158:12)
#4      TypeSystemImpl._refineNumericInvocationContextNullSafe (package:analyzer/src/dart/element/type_system.dart:1713:11)
#5      TypeSystemImpl.refineNumericInvocationContext (package:analyzer/src/dart/element/type_system.dart:1402:14)
#6      ResolverVisitor.visitArgumentList (package:analyzer/src/generated/resolver.dart:862:24)
#7      InvocationInferenceHelper._resolveArguments (package:analyzer/src/dart/resolver/invocation_inference_helper.dart:326:15)
...
```

To reproduce the problem, clone the "null-safety" branch of the ssh_key repository and run dartdoc on it:

https://github.com/hoylen/ssh_key/tree/fa4833d7dfe92e2873d0443c65802cba8eca06e6

```
git clone --single-branch --branch null-safety https://github.com/hoylen/ssh_key.git
cd ssh_key
pub get
dartdoc
```

Note: once this bug has been fixed and I can generate that documentation, that branch will be merged into master and deleted. So if the branch is not present, it means the bug has been fixed.

I was using:

* Dart SDK version: 2.12.0-259.14.beta (beta) (Wed Feb 17 10:18:35 2021 +0100) on "macos_x64"
* macOS

**Comment by jcollins-g** [comment]
This looks like an analysis bug of some sort.  Investigating.

**Comment by jcollins-g** [comment]
This is not an issue at head.   Presumably this has been fixed somewhere along the line.  A publish of dartdoc will solve this problem; I'll get to that.

**Comment by jcollins-g** [comment]
a trickier bit will be finding the issue and backporting it into beta, should that be necessary.

**Comment by hoylen** [comment]
Thanks Janice. I'll wait for the next dart-sdk beta release.

**Comment by jcollins-g** [comment]
Closing.  Use `pub global activate dartdoc` to get version 0.40.0 which does not have this problem.

**Comment by bsutton** [comment]
This problem is happening on pub.dev.

https://pub.dev/packages/dcli/score

**Comment by mschwartz** [comment]
I get this error after doing the pub global activate dartdoc

Looks like dartdoc 0.42.0

**Comment by jcollins-g** [comment]
@mschwartz All reports of this for newer versions have been linked to incorrect PATH settings or other problems.  Be certain you are running the version of dartdoc you installed.

**Comment by mschwartz** [comment]
I am using the version for windows along with JetBrains 
IDE.  Not sure if the IDE installed a second copy.

I am running the command from the terminal built into the IDE.
