### ISSUE TITLE
remove dartdoc's dependency on dart:mirrors

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#2580]
We're planning on remove dartdoc's dependency on dart:mirrors (in favor of a codegen replacement for package:mustache - codename `'mustachio'`). This issue is to track this work, so that any downstream work items can be aware.

cc @srawlins @jcollins-g @a-siva

**Comment by srawlins** [comment]
This is related to https://github.com/dart-lang/dartdoc/issues/2335; the final codegen solution will be a simple translation from the HTML and Markdown templates into a library with many `StringBuffer.write` calls.

**Comment by devoncarew** [comment]
I believe this is complete now (cc @a-siva).
