### ISSUE TITLE
generate a link to the source code

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/dartdoc#2587]
for each entry of documentation it would be nice to have a way to view their source code directly

the link to the source could be displayed near the title

![image](https://user-images.githubusercontent.com/39104740/112325047-691e3c80-8cc4-11eb-9f23-3a4d36a481e0.png)

the same could be added to the bottom bar and would lead to the tree root

![image](https://user-images.githubusercontent.com/39104740/112325178-83f0b100-8cc4-11eb-91b8-845056a98ade.png)

**Comment by jcollins-g** [comment]
This is already implemented.  See linkToSource under https://github.com/dart-lang/dartdoc#dartdoc_optionsyaml-fields, and note the example in dartdoc's own dartdoc_options.yaml.

https://github.com/dart-lang/dartdoc/blob/8b911bc6f9eeb33804b0dfdf4b6e9e9d64c74c8b/dartdoc_options.yaml#L4

It looks like this option is not permitted by pub.dev, however.  Perhaps @isoos could investigating allowing this?  Or possibly autogenerating it?   One problem is that we don't want the pub site to link to arbitrary user defined web pages.

**Comment by isoos** [comment]
Linking to the source on pub.dev would make sense if we had a source code view of the package archive (and in that case pub.dev would override the option to link to the pub-dev-provided sources. I think it is a legitimate feature request, but knowing the current backlog of things, it may not be a priority for the team in the next few months.

**Comment by nt4f04uNd** [comment]
> Linking to the source on pub.dev would make sense if we had a source code view of the package archive (and in that case pub.dev would override the option to link to the pub-dev-provided sources

i am not sure what this means, but just wanted to say that we have a `repository` entry in `pubspec.yaml` and imo this would be logical to generate source links from the package tree taking to account only this entry and ignore custom `linkToSource`

> it may not be a priority for the team in the next few months

that's understandable and totally fine to me

**Comment by isoos** [comment]
> upd: hmm, however we need to point to the exact commit, so that is not quite valid

Exactly. Also, even if you had the commit, there is a non-null chance that git history gets rewritten, or repository is closed down.

**Comment by nt4f04uNd** [comment]
if git history is rewritten, this is not a problem at least for github, because commits continue living unattached, instead of being deleted

imo pub.dev generally should not care about this (as it already does for links on the package homepage - i saw a lot of packages with invalid links)

**Comment by isoos** [comment]
> imo pub.dev generally should not care about this (as it already does for links on the package homepage - i saw a lot of packages with invalid links)

It is bad for the user experience, and this is a good reason to care about it. That's one of the reasons why pub.dev checks the existence of such URLs, and gives full score only if they are all valid and serving content.

**Comment by parlough** [comment]
I agree that it should likely be hosted separately. The most prominent example I can think of is `docs.rs` which hosts the code alongside the docs, rather than the package website.

I have a feeling this may be the more appropriate direction, as then we can include inline source links within dartdoc and include them in more places.

For example [here](https://docs.rs/hashbrown/0.11.2/hashbrown/struct.HashMap.html#method.clear) you have a link to hosted source code for each documentation member.

**Comment by parlough** [comment]
```dart
void main() {
[hi](https://docs.rs/hashbrown/0.11.2/src/hashbrown/lib.rs.html)
}
