### ISSUE TITLE
Make long argument lists readable

### ISSUE THREAD

**Issue by mleonhard** [dart-lang/dartdoc#2620]
Flutter [`MaterialApp `](https://api.flutter.dev/flutter/material/MaterialApp-class.html) contains two constructors with many optional parameters.  The parameters appear as a giant blob of text more than two screens wide.  It requires HORIZONTAL SCROLLING to see all of the parameters.

This makes searching and reading the docs extremely slow.  Also, [CTRL-F searching is unusable in Flutter docs](https://github.com/dart-lang/dartdoc/issues/2131).

Let's reformat parameter lists the way Dart itself formats them: one per line.

# Screenshots
Taken with Safari 14.0.3.

![Screen Shot 2021-04-21 at 01 09 53](https://user-images.githubusercontent.com/520739/115520282-d9c26580-a23e-11eb-874b-53306dec94f7.png)
![Screen Shot 2021-04-21 at 01 10 09](https://user-images.githubusercontent.com/520739/115520294-de871980-a23e-11eb-817c-0dedc23d6a4c.png)

**Comment by CaptainIRS** [comment]
Related issue: #2408

**Comment by mleonhard** [comment]
Closing as duplicate.
