### ISSUE TITLE
Type aliases are not well documented

### ISSUE THREAD

**Issue by timsneath** [dart-lang/dartdoc#2638]
New feature in Dart 2.13, presumably needs some special handling in dartdoc.

See for example the type aliases here:
https://pub.dev/documentation/winmd/1.0.0-pre.12/winmd/winmd-library.html#typedefs

dartdoc seems to treat these as a method that returns a dynamic type, rather than an alias for another type.

**Comment by jcollins-g** [comment]
@timsneath @isoos  For this to work properly on pub.dev, the pub site must be using 2.13 to generate docs:

https://github.com/dart-lang/pub-dev/blob/master/pkg/pub_dartdoc/mono_pkg.yaml#L3

Output from dartdoc 0.42.0 using the proper SDK version:

![Screen Shot 2021-05-10 at 8 43 31 AM](https://user-images.githubusercontent.com/14116827/117686579-db12ee00-b16b-11eb-8aec-e1f1aec71682.png)

**Comment by devoncarew** [comment]
> Perhaps that is the underlying problem here -- we should try and sync the two?

That sounds likely; perhaps mention in https://github.com/dart-lang/pub-dev/issues/4790 ?

**Comment by isoos** [comment]
An update has been deployed to pub.dev and now type aliases are generated as expected.
