### ISSUE TITLE
[bug] dartdoc failed: fatal error: unable to locate the input directory at ...

### ISSUE THREAD

**Issue by GroovinChip** [dart-lang/dartdoc#2639]
(I'm opening this issue because Google search actually resulted in the message that there aren't any good results for my search.)

Running dartdoc for my flutter package results in the following error:

```
dartdoc failed: fatal error: unable to locate the input directory at /private/var/folders/fj/0h13f7s11pv3n8s7wkd9v68m0000gn/T/pana.1620525748371.P5JaNQ/hosted/pub.dartlang.org/meta-1.3.0/lib..
```

I am using the latest version of dartdoc (0.42.0) and am on the latest stable version of Flutter.

<details>
<summary>
Here's my `flutter doctor -v` output:
</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale en-US)
    • Flutter version 2.0.6 at /Users/groov/development/flutter
    • Framework revision 1d9032c7e1 (9 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/groov/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.3 20E232 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
</details>

**Comment by jcollins-g** [comment]
Have you tried running `flutter pub cache repair` followed by `flutter pub get`?

**Comment by GroovinChip** [comment]
```
Resolving dependencies...
+ _fe_analyzer_shared 21.0.0
+ analyzer 1.5.0
+ args 2.1.0
+ async 2.6.1
+ charcode 1.2.0
+ cli_util 0.3.0
+ collection 1.15.0
+ convert 3.0.0
+ crypto 3.0.1
+ csslib 0.17.0
+ dartdoc 0.42.0
+ file 6.1.0
+ glob 2.0.1
+ html 0.15.0
+ logging 1.0.1
+ markdown 4.0.0
+ meta 1.3.0
+ package_config 2.0.0
+ path 1.8.0
+ pedantic 1.11.0
+ pub_semver 2.0.0
+ source_span 1.8.1
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ watcher 1.0.0
+ yaml 3.1.0
Precompiling executables...
Precompiled dartdoc:dartdoc.
Installed executable dartdoc.
Activated dartdoc 0.42.0.
```

**Comment by GroovinChip** [comment]
It has started working again. Not sure why, but I'm closing this issue since the problem is gone.

**Comment by xanmankey** [comment]
I'm having the same issue. Here's what I've tried:
- ```flutter pub cache repair```
- ```dartdoc```: failed
- ```flutter pub get```
- ```dartdoc```: failed
- ```flutter global pub deactivate dartdoc```
- ```flutter global pub activate dartdoc```
- ```dartdoc```: failed

The error message is:
```dartdoc 6.3.0 (/home/xanmankey/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-3.1.2.snapshot) failed: fatal error: unable to locate the input directory at /home/xanmankey/Programming/App/SwipeSwap/SwipeSwapFrontend/swipeswap/lib/models..```

My code in /lib structured as follows:
├── home.dart
├── main.dart
├── matching.dart
├── models.dart
├── order.dart
├── providers.dart
├── services.dart
├── src
│   ├── models
│   │   ├── order_model.dart
│   │   ├── seller_model.dart
│   │   └── user_model.dart
│   ├── provider
│   │   ├── order_provider.dart
│   │   ├── screen_provider.dart
│   │   ├── seller_provider.dart
│   │   └── user_provider.dart
│   ├── screens
│   │   ├── home
│   │   │   ├── profile.dart
│   │   │   ├── seller.dart
│   │   │   └── swaps.dart
│   │   ├── matching
│   │   │   ├── matchFound.dart
│   │   │   ├── matching.dart
│   │   │   └── noMatchFound.dart
│   │   ├── order
│   │   │   ├── order.dart
│   │   │   └── orders.dart
│   │   └── welcome
│   │       ├── welcome.dart
│   │       └── wrapper.dart
│   ├── services
│   │   ├── auth.dart
│   │   └── firebase_options.dart
│   ├── utils
│   │   ├── bottom_nav_bar.dart
│   │   ├── constants.dart
│   │   └── order_card.dart
│   └── widgets
│       ├── dining_court.dart
│       ├── item.dart
│       └── logout_button.dart
├── utils.dart
├── welcome.dart
└── widgets.dart

I also have a dartdoc_options.yaml file in the root project directory as follows:

```yaml
dartdoc:
  # categories:
  #   "Screens":
  #     markdown: doc/Screens.md
  #     name: Screens
  exclude: ["lib/src/**"]
  nodoc: ["lib/src/**"]
  # categoryOrder: ["Screens"]
```

The files directly inside of lib are library files and the files inside of src are exported in the library files (makes the documentation a little bit neater IMO). I also wanted to categorize all of the directories under the screens directory into sub-libraries, but I wasn't sure how to do that. Just building my documentation comes first though! If you have any idea or could provide any suggestions, I would greatly appreciate it!
