### ISSUE TITLE
Implement constructor tear-offs in dartdoc

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#2655]
Depends on dart-lang/sdk#46020.

We can add to dartdoc's internal reference scheme for unnamed constructor tearoffs based on the specification, here:  https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md.   Specifically, allowing comment references to use `[C.new]` for unnamed constructor tearoffs will simplify some things in the new reference lookup code.

[Edit by eernstg on Jul 8th: Updated link to feature spec.]

**Comment by jcollins-g** [comment]
Unblocking as it should be possible to begin development, and not crash for simple uses now.

**Comment by devoncarew** [comment]
@jcollins-g - is this generally on track for early October?

**Comment by jcollins-g** [comment]
yes.
