### ISSUE TITLE
Adapt to FunctionType changes - no element and typeArguments

### ISSUE THREAD

**Issue by scheglov** [dart-lang/dartdoc#2662]
See https://dart-review.googlesource.com/c/sdk/+/201520

`FunctionType` is not really a `ParameterizedType`, in contrast to `InterfaceType` there are no `typeArguments`.

I tried to do update dartdoc myself, but I don't understand this are of code well enough.

FWIW, presubmit in google3 is mostly green.
https://test.corp.google.com/ui#id=OCL:376069083:BASE:376079831:1622095079317:8501e410

**Comment by jcollins-g** [comment]
this is now fixed in dartdoc 0.45.0

**Comment by scheglov** [comment]
Thank you, my CL is now green :-)
