### ISSUE TITLE
extension docs "on" line points to extension

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2697]
e.g. https://master-api.flutter.dev/flutter/flutter_test/TestBasicMessageChannelExtension.html

The "on" after the doc text points to the same page. I'm assuming it should say "on BasicMessageChannel" and point to that?

**Comment by lrhn** [comment]
Came here to say the same thing; https://pub.dev/documentation/ffi/latest/ffi/StringUtf8Pointer.html

**Comment by jcollins-g** [comment]
This looks like it is fixed in head, can only reproduce in the v0.45.0 tag.  My guess is @srawlins fixed a problem in template resolution as part of the AOT template work.
