### ISSUE TITLE
Dartdoc fails to execute with an unhandled exception

### ISSUE THREAD

**Issue by Riktam-Santra** [dart-lang/dartdoc#2723]
I was creating a usual package to handle data from an api, but on running to dartdoc, the tool seemed to failed as soon as I started it with an Unhandled Exception.

The command output was as follows:

`Unhandled exception:
Invalid argument (uri): Unknown package: Instance of '_SimpleUri'
#0      ResourceLoader.resolveResourceUri.<anonymous closure> (package:dartdoc/src/generator/resource_loader.dart:41:11)
<asynchronous suspension>
#1      ResourceLoader.getResourceFile (package:dartdoc/src/generator/resource_loader.dart:31:15)
<asynchronous suspension>
#2      _DefaultTemplatesLoader.loadTemplate (package:dartdoc/src/generator/templates.dart:168:24)
<asynchronous suspension>
#3      Templates._create (package:dartdoc/src/generator/templates.dart:265:25)
<asynchronous suspension>
#4      initHtmlGenerator (package:dartdoc/src/generator/html_generator.dart:22:19)
<asynchronous suspension>
#5      Dartdoc.fromContext (package:dartdoc/dartdoc.dart:149:21)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg/dartdoc/bin/dartdoc.dart:24:9)
<asynchronous suspension>`

Dart SDK info:
`Dart SDK version: 2.13.3 (stable) (Wed Jun 9 12:44:44 2021 +0200) on "windows_x64"`

**Comment by jcollins-g** [comment]
@Riktam-Santra Does the package analyze correctly with `dart analyze`?  This is required for dartdoc to function properly, although it should not just throw an exception but suggest this if there is an unknown package exception.

**Comment by Riktam-Santra** [comment]
Never mind, I seemed to have fixed it finally after reinstalling flutter. I had installed dart doc using `pub global activate dartdoc` which didn't seem to work and was giving me a dartdoc not found error and therefore I tried adding the directory manually to the system path which gave the output above, I reinstalled flutter and removed the path entry and now it is working fine.
