### ISSUE TITLE
sdk docs index.html missing info

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#275]
Missing this info

![screen shot 2015-03-16 at 9 04 45 am](https://cloud.githubusercontent.com/assets/2192312/6670392/8f09e0dc-cbbb-11e4-95d4-d9ca4a8aba3c.png)

@sethladd, where is this info located?

**Comment by sethladd** [comment]
Not exactly sure. @kwalrath might know.

Try grepping our SVN repo? :)

**Comment by kwalrath** [comment]
https://code.google.com/p/dart/wiki/WritingApiDocumentation#Choosing_which_file_to_edit said where it was, but it isn't there any more.

**Comment by keertip** [comment]
@kwalrath, who would know?

**Comment by alan-knight** [comment]
It got inlined into the docgen sources at pkg/docgen/lib/src/generator.dart, because that's the only way it would be available to docgen running as a snapshot.

**Comment by sethladd** [comment]
whoa, no kidding.

**Comment by kwalrath** [comment]
I've updated the [wiki page](https://code.google.com/p/dart/wiki/WritingApiDocumentation?ts=1426886145&updated=WritingApiDocumentation#Choosing_which_file_to_edit) to point to [pkg/docgen/lib/src/generator.dart](https://code.google.com/p/dart/source/browse/branches/bleeding_edge/dart/pkg/docgen/lib/src/generator.dart).

**Comment by keertip** [comment]
fixed with #312
