### ISSUE TITLE
sdk docs: doc comment resolve refs 

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#282]
Looks like links are not resolved in certain cases dart:collection

![screen shot 2015-03-16 at 12 45 29 pm](https://cloud.githubusercontent.com/assets/2192312/6674997/eaf32948-cbda-11e4-89cb-dcdd996b5949.png)

**Comment by keertip** [comment]
This turned out to be an analyzer issue. Have a cl out to fix that. Now for it to land and be pushed out to pub. Rev version of analyzer once the fix has been published.

**Comment by sethladd** [comment]
Awesome, thanks for tracking that down!
