### ISSUE TITLE
Doc coverage/quality reporting

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dartdoc#284]
'twould be awesome to have detailed reporting on doc coverage/quality ala [inchjs](http://trivelop.de/inchjs/).

Reasons to build this into dartdoc rather than as a separate tool:

* Code reuse.
* Speed.  Doc generation and quality gathering can be done simultaneously similar to how test coverage and test results can be calculated from a single run of the unit tests.
* easier integration into dartdocs.org

dartdocs.org could provide a url to access the doc quality page, and also a badge that people could include in their READMEs, and maybe directly integrate it into pub.dartlang.org as well.

Another part would be [linter support](https://github.com/dart-lang/linter/issues/62) so that editors can flag and link to undocumented (or poorly documented) things in the source to make them easy to fix.

**Comment by sethladd** [comment]
Indeed! We have something like that here: http://google.github.io/dart-shapeshift/

We would LOVE if someone integrated it with the new dartdoc.

Patches welcome

**Comment by pq** [comment]
:+1: 

I've been thinking about this vis a vis linting.  For my edification, how do we specify public API?  Are we limiting ourselves to everything in `lib/` (minus `lib/src`)?  Do we look at `bin`?

**Comment by keertip** [comment]
We don't look at bin, just lib/ (minus lib/src).

**Comment by pq** [comment]
Actually, it's more nuanced I think.  It looks like you also process explicitly exported members.

Look at the docs for `barback` for example:

http://www.dartdocs.org/documentation/barback/0.15.2+4/index.html#barback/barback

And now notice that much of that is in fact exported from `lib/src`:

https://github.com/dart-lang/barback/blob/master/lib/barback.dart

(Thanks to @munificent for the salient example!)

**Comment by sethladd** [comment]
This would be cool, but we're unlikely to get to this. If anyone is interested, please reopen and take a shot at it!
