### ISSUE TITLE
Devdocs.io integration

### ISSUE THREAD

**Issue by xxgreg** [dart-lang/dartdoc#286]
I'm not sure what the scope of the dartdoc tool is - or if this is the right place to file this bug.

If you're planning on allowing search and offline use, then take a look at devdocs.io. It provides a slick offline searchable, auto-updating version of the MDN docs.

It would also be great to have html/css/js/postgresql docs searchable from the same site used for Dart docs.

https://devdocs.io
https://chrome.google.com/webstore/detail/devdocs/mnfehgbmkapmjnhcnbodoamcioleeooe?hl=en

**Comment by kasperpeulen** [comment]
Or maybe add dart to devdocs. Dash (another offline documentation tool) also has dart support.

**Comment by xxgreg** [comment]
I guess dartdoc could have a flag to output to a machine readable format such as json. This would make it easy to integrate with any third party doc tools.

**Comment by keertip** [comment]
dartdoc will be able to output in machine readable format, that is planned see #6.

**Comment by sethladd** [comment]
Integration with systems such as devdocs.io sounds great. It's unclear what needs to happen, though. If someone wants to take this on, we'd love it.

**Comment by sethladd** [comment]
Would love it if someone takes a shot at implementing. We're unlikely to get to this any time soon, so I'm going to close. But please reopen or comment if you want to implement this. Thanks!
