### ISSUE TITLE
Dartdoc_options.yaml options

### ISSUE THREAD

**Issue by rahul-readwhere** [dart-lang/dartdoc#2860]
Can anyone suggest me a proper example for generating doc with sections on the left menu but couldn't find any relevant solution.

**Comment by srawlins** [comment]
@rahul-readwhere can you elaborate on your desired functionality? I don't think dartdoc (including dartdoc_options.yaml) supports a flag that changes the layout of the HTML.

**Comment by bwilkerson** [comment]
Without clarification we can't work on this. I'm going to close it as stale. We can re-open if there's a response to the question.
