### ISSUE TITLE
move away from auto-running `pub get`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#2862]
We should move away from auto-running `pub get` when the dartdoc tool is invoked. This doesn't match the other dart related tools (analyze, format, test, fix, ...). In addition, the logic for dartdoc is too restrictive - it'll try and run pub in a project that doesn't use it - that has a hard-coded package_config.json file above the current directory for instance (like the dart-lang/sdk `pkg/` directories for instance).

**Comment by spydon** [comment]
Would this also solve the `pubspec.yaml has changed since the pubspec.lock file was generated, please run "flutter pub get" again.` error? Which is common if you run for example [Melos](https://github.com/invertase/melos).

**Comment by srawlins** [comment]
Hmm possibly? If dartdoc was running `pub get` at unexpected times.

**Comment by spydon** [comment]
After a bit more investigation I don't think it is related, it is related to this https://github.com/dart-lang/pub/pull/3215

**Comment by srawlins** [comment]
@devoncarew implemented this.
