### ISSUE TITLE
Problem with links to dart:xxx libs in breadcrums 

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dartdoc#287]
Not sure this is the right place to report this.

Open
https://ci.directcode.org/guestAuth/repository/download/Dart_SdkDocs/.lastSuccessful/dart_async/Future/catchError.html
Click `dart:async library` in the middle of the breadcrumb
the link is `dart:async/index.html` and `dart:` is recognized as protocol.

**Comment by kaendfinger** [comment]
Trying to fix this now

**Comment by sethladd** [comment]
Thanks for the report! And the fix!
