### ISSUE TITLE
Generating page of TODOs with dartdoc

### ISSUE THREAD

**Issue by MarcBritton** [dart-lang/dartdoc#2944]
We have a bunch of TODO comments in our dart/flutter code. Is there any way to generate a a single page of TODOs from our code base using dartdoc? These TODOs are scattered across our code base, it'd be nice to have one html page containing them all to share with other people.

I thought this might be possible because the dart analyzer is aware of TODOs, but I couldn't see an option for this in dartdoc.

Thanks!

**Comment by srawlins** [comment]
There is currently no way to do this.

Since dartdoc only concerns itself with doc comments (`///`), it would not be the appropriate tool to surface TODO comments (`//` comments).

**Comment by MarcBritton** [comment]
Thanks for letting me know.
