### ISSUE TITLE
Add Support for Pub Global and Snapshotting

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/dartdoc#297]
I am willing to implement support for Pub Global and Snapshotting. This can be done by adding a transformer that inlines the templates and resources into the code itself before compilation.

**Comment by kaendfinger** [comment]
cc @sethladd @keertip

**Comment by sethladd** [comment]
I think we're going to get a "real" solution for this. So hold off on this.

cc @iposva

**Comment by kaendfinger** [comment]
Ok :)

**Comment by sethladd** [comment]
We probably won't have a solution in time for 1.10. So we do need a hack/work-around in the meantime.

Should we use grinder to put all templates and resources into a .dart script?

**Comment by kaendfinger** [comment]
Yes that would help.

**Comment by sethladd** [comment]
Help wanted! :)

**Comment by sethladd** [comment]
Blocked on https://code.google.com/p/dart/issues/detail?id=21020

We could implement the workaround (encode all resources as strings) but that's less than ideal: we would need to run the encoder every time we touch our resources. We we do a lot, as we're constantly tweaking the CSS files.

**Comment by sethladd** [comment]
I've started a workaround.

**Comment by kaendfinger** [comment]
Awesome.

**Comment by sethladd** [comment]
WIP https://github.com/dart-lang/dartdoc/pull/362

See lib/resource_loader.dart

**Comment by sethladd** [comment]
Here's a shot at it: https://github.com/dart-lang/dartdoc/blob/warning-on-snapshot/lib/resource_loader.dart

Handles loading a package: resource, under the following scenarios:

* Just running via the Dart VM
* Running via pub run + HTTP + source rewriting to HTTP URIs for imports
* Running via snapshot in global_package directory (this was the tough one)

Does not handle:

* Respecting package-root, it currently just looks for a package/ dir in most scenarios
* Listing resources in a directory (because HTTP can't do that)
* Probably a billion small details

**Comment by sethladd** [comment]
Next up: change the logic in html_generator to get the files via resource_loader (instead of directly via the file system) and then test test test.

Help Wanted with this part, if someone is interested.

**Comment by kaendfinger** [comment]
I'll see what I can do :)

**Comment by sethladd** [comment]
Picking this up again. Will look at loading dartdoc's resources with the resource_loader

**Comment by sethladd** [comment]
OK, I have a version that might work. Starting test.

**Comment by sethladd** [comment]
The code is merged! Need to test from pub global activate now.

**Comment by kaendfinger** [comment]
Great :) I'll test it out

**Comment by sethladd** [comment]
Coolness! Just tested and it seems to work when installed via global activating snapshot.
