### ISSUE TITLE
Missing git tag for 5.1.0 release

### ISSUE THREAD

**Issue by Cliabhach** [dart-lang/dartdoc#3022]
Hi! First off, I want to thank you for `dartdoc`, it's been super useful.

I'm filing this issue because of an inconsistency I see on GitHub. The current [CHANGELOG.md](https://github.com/dart-lang/dartdoc/blob/f4bda6c/CHANGELOG.md) on the `master` branch has entries for 5.0.0, 5.0.1, and 5.1.0. However, there's [no 5.1.0 tag](https://github.com/dart-lang/dartdoc/tree/v5.1.0) and the most recent GitHub Release is [4.1.0](https://github.com/dart-lang/dartdoc/releases/tag/v4.1.0).

I can't be 100% certain, but I think the missing git tag may be why [pub.dev's version history](https://pub.dev/packages/dartdoc/versions) is missing an entry for 5.1.0.

**Comment by srawlins** [comment]
Sorry for the delayed response.

Publishing is not tied to a git tag. The git tag is done for other purposes, like tracking commits.

To answer your question, dartdoc 5.1.0 has not been published yet. Normally I use a 'dev' version number between publishes, and I'm surprised the version on master is not "5.1.0-dev". Maybe I messed that up. In any case, I intend to cut a release today or tomorrow.

**Comment by Cliabhach** [comment]
Ah, I see! Thanks for clarifying.

**Comment by srawlins** [comment]
Just released 5.1.0
