### ISSUE TITLE
URL-based search broken

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/dartdoc#3024]
Implemented in #1126, this feature allows you to add `?search=query` to the URL and will redirect you to the page that most closely matches `query`, as if you had typed it in the search bar and pressed Enter. This feature allows Chrome to search through a Dartdocs through the address bar. 

For some reason, this code appears to be broken now. Loading both https://api.dart.dev/stable/2.16.2/index.html?search=string and https://api.flutter.dev/?search=string do not redirect as they used to and instead the search bar shows `Failed to initialize search`, and the console shows `Could not activate search functionality`. The last time this feature worked was on https://api.dart.dev/stable/2.12.4/index.html?search=string (it stopped working at 2.13.0). It appears that commit a33ec963eb5b9aa91b4da8e39df908be70a2892e changed a lot of how the search JS is generated, so perhaps this will be fixed, just wanted to point some attention to it.

**Comment by parlough** [comment]
This was caused by me not passing the search index into `findMatches` at: https://github.com/dart-lang/dartdoc/blob/73e397cb6930fa1dbfb3b47b3d84934866b761bd/lib/resources/script.js#L469

It doesn't look like the new script supports the url based search yet either though.
