### ISSUE TITLE
Legacy [:code:] references no longer recognized

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dartdoc#303]
The documentation for `bool.toString()` references e.g. [:true:] and [:"true":].  It is supported by the old dartdoc:

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.bool#id_toString

But in the new dartdoc

https://ci.directcode.org/guestAuth/repository/download/Dart_SdkDocs/.lastSuccessful/dart_core/bool/toString.html

the escape sequences are not recognized:

Returns [:"true":] if the receiver is [:true:], or [:"false":] if the receiver is [:false:].

Probably those docs should just be updated to reference e.g. `` `true` `` and `` `"true"` ``, but I wanted to confirm that here first before filing a bug on dartbug.com.

**Comment by keertip** [comment]
Think we need to verify whether the old style is still supported. Looking at https://www.dartlang.org/articles/doc-comment-guidelines/#inline-styles specifies both the styles. 

@sethladd , @Sfshaza

**Comment by sethladd** [comment]
How common are the `[:"true":]`in our existing dartdocs ? Should we just change it in the source, instead of adding this support to the new dartdoc ?

**Comment by kaendfinger** [comment]
@sethladd Very common. I see them quite a bit.

**Comment by sethladd** [comment]
Thanks for confirming. Let's support it. Patches welcome!

**Comment by kaendfinger** [comment]
I'll take it.

**Comment by sethladd** [comment]
Thanks!
