### ISSUE TITLE
up/down arrow keys in search doesn't work any more (regression)

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#3052]
STEPS TO REPRODUCE
1. Go to master-api.flutter or api.dart.dev/dev
2. Tab three times to focus the search field
3. Type "e"
4. Press the down arrow

EXPECTED RESULTS
It highlights the first result

ACTUAL RESULTS
Nothing happens when you press the down arrow

This is a regression; it works fine on stable (api.flutter.dev or api.dart.dev/stable).

Maybe caused by https://github.com/dart-lang/dartdoc/pull/3016 ? cc @devoncarew

**Comment by devoncarew** [comment]
> Maybe caused by #3016 ? cc @devoncarew

Ah, yup, I would expect so. I'll take a look.

**Comment by devoncarew** [comment]
Or - @keertip - when will your intern come online? This might be a good issue for them - in-line with their starter project?

**Comment by keertip** [comment]
Intern will be starting next week.

**Comment by justinmc** [comment]
Also pressing the enter key used to select the first option but now it's broken too.

**Comment by keertip** [comment]
@klr981

**Comment by srawlins** [comment]
@klr981 fixed this. 🎉 

Release coming soon.
