### ISSUE TITLE
Markdown Generator

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/dartdoc#307]
I'm considering making a generator that makes markdown documentation files. This would be nice if I wanted to store my docs in my repo.

**Comment by sethladd** [comment]
sounds good to me. We could really use a machine output, hopefully backwards compatible with what dartdocgen emits.

**Comment by kaendfinger** [comment]
I'll do that as well.

**Comment by sethladd** [comment]
Closing as we're unlikely to get to this, but please do reopen or comment if someone would like to implement this. Thanks!
