### ISSUE TITLE
Single Page App design with static files

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#3079]
In order to solve **output size** issues (https://github.com/dart-lang/dartdoc/issues/2995), **performance** issues (https://github.com/dart-lang/dartdoc/issues/2799, https://github.com/dart-lang/dartdoc/issues/2998), and in order to enable some desired front-end features (\[citation needed]), we can convert generated docs into a rough Single Page App design.

Typically a single page app would have a web server at the backend which is generating JSON responses to update the contents of the page, but we can carry out the minimum amount of work by just dumping slightly different HTML files, and incorporating some JS to request them and insert HTML snippets into the DOM.

## Background

The long and short of our performance and output size problems come from this fact:

> A library with a class with _n_ members will generate _O(n)_ files, each of which has a sidebar of length _O(n)_, resulting in a total of _O(n<sup>2</sup>)_ bytes.

## Design

In a green field design, we could re-imagine dartdoc to instead dump out one or many JSON files which would be served to a JS app and drawn into the page. But in this design, I take all of our existing code which generates one HTML file for every element, and make only small changes.

### Generation

Today, for each element, we generate an HTML file with the following 5 sections in its body:

1. a header
2. a left sidebar
3. a right sidebar
4. a main body
5. a footer

The blocks with incredible amounts of duplication are the two sidebars. The footer may also be perfectly duplicated across every file, but probably doesn't represent a lot of bytes.

In this design, for each element, we instead generate an HTML file with the following 2-3  filled sections:

1. a header
2. a main body
3. (probably _not_ the footer; but removing it can be done separately)

The other sections will be present but empty (or near enough; there are some breadcrumbs for mobile at the top of some sidebars)

The HTML will look something like:

```html
<html>
    <head>...</head>
    <body>
        <header>...</header>
        <main>...</main>
        <sidebar-left><!-- intentionally empty --></sidebar-left>
        <sidebar-right><!-- intentionally empty --></sidebar-right>
        <footer><!-- maybe empty --></footer>
    </body>
</html>
```

Additionally, we generate a few more files (apologies, https://github.com/dart-lang/dartdoc/issues/1272):

* For every library, we generate a **library sidebar**, which will be displayed on the library's page, and on the page of every element exported from that library.
* For every "container" (class, mixin, enum, extension), we generate a **container sidebar**, which will be displayed on the container's page, and on the page of every element in the container (fields, methods, ...).

### Initial page load

This new design requires that docs be served from an HTTP file server. The dartdoc package uses the dhttpd package in it's grinder scripts. Python's httpd module works fine as well. Whatever currently serves docs for pub.dev, api.dart.dev, and api.flutter.dev, will also work fine.

When a page is loaded initially, the browser will fill in the DOM just as it does today, except the sidebars will be empty. On load, some JS will read a data property of some tag (body?) for the left sidebar, build a URL for the HTML file for the desired sidebar, and request it. It then inserts the sidebar into its proper place in the DOM. The JS will do the same for the right sidebar.

### Linking

As an optimization, to reduce page load (typical SPA optimization): we can add click handlers in the JS for all links destined for other pages within the same doc site.

When a link to another page in the same site is clicked (like a doc comment reference, or a type in a signature, or a member with a class, ...):

1. the JS intercepts it and instead requests the URL (the same HTML file destination) asynchronously,
2. parses the HTML response,
3. pushes the new location via the JS Navigation API
5. replaces the current `<header>` section with that of the response
6. replaces the current `<main>` section with that of the response
7. replaces the `<title>` tag (other stuff in `<head>`?)
8. requests the new page's left sidebar and right sidebar
9. replaces the left sidebar with the new one, and the right sidebar with the new one

**Comment by Levi-Lesches** [comment]
Two questions: 
1. Would an `<iframe>` of the sidebar be simpler? The link to the iframe's `src` can be generated as part of the regular process.
2. Would this affect SEO? I suppose not, since the class/enum/etc's main page will still have all its members, and each member gets its own page to link to.

**Comment by srawlins** [comment]
> 1. Would an <iframe> of the sidebar be simpler? The link to the iframe's src can be generated as part of the regular process.

Definitely. I think it reduces or removes any ability to do JS in there.

> 2. Would this affect SEO? I suppose not, since the class/enum/etc's main page will still have all its members, and each member gets its page to link to.

I don't think so.

> 3. Does this make https://github.com/dart-lang/dartdoc/issues/1272 unacceptably worse? It's still O(n) files, but an extra two files for every container is still a lot. On the other hand, it produces shorter files.

I don't think so. Just a little worse.

**Comment by srawlins** [comment]
CC @jcollins-g we talked about this design yesterday.

**Comment by jcollins-g** [comment]
> ### Linking
> The JS needs to also add click handlers for all links destined for other pages within the same doc site.

Why does the JS need to handle links destined for other pages?   Is this an optimization? 

As discussed offline, I think this aligns well with [Reducing dartdoc generated file footprint](https://docs.google.com/document/d/1zG_xIshD7Y2bPV2YMrTQ4mrpd8SbC9rH-RcRij39cqc).  The impacts of the two problems are multiplicative and dartdoc output could get quite small if we implement both of them.

**Comment by srawlins** [comment]
> Why does the JS need to handle links destined for other pages? Is this an optimization?

I need to correct that. I realized that's a bad design because it wouldn't support things like "Right click -> Copy link destination." and in implementing, it was easier to just make links point to the right place, statically, and every click is a full reload.

**Comment by jonasfj** [comment]
> I realized that's a bad design because it wouldn't support things like "Right click -> Copy link destination."

It could be made to work. But it's a nin-trivial pain to do -- and testing it is difficult.

Same with history management, it's also doable, just mildly painful.

Serving plain HTML has a lot going for it.

**Comment by Levi-Lesches** [comment]
@srawlins I'm really impressed by the sidebars PR, but it broke my docs :(
Here's what the sidebars should look like
![image](https://github.com/dart-lang/dartdoc/assets/20747538/1981cffe-9d65-4b2f-aeda-88535ae9ea18)
And here's what a method/property/constructor page actually looks like:
![image](https://github.com/dart-lang/dartdoc/assets/20747538/c9595798-d693-4ee2-b62e-f059a2871a93)

Clearly the `ProtoSocket-class-sidebar.html` file exists and loads fine, but I noticed the constructor/method/property pages don't even request it!
Here are the network requests for the `ProtoSocket` page: 
![image](https://github.com/dart-lang/dartdoc/assets/20747538/433128c2-517d-4e0f-a7a6-4f7733aa8410)
And here are the requests for the `init` method: 
![image](https://github.com/dart-lang/dartdoc/assets/20747538/f77b04e8-d349-45a1-aba3-dfbda5b5772e)

Here's the code for the `main-content` on the `ProtoSocket` page: 
```html
<div id="dartdoc-main-content" class="main-content" data-above-sidebar="burt_network/burt_network-library-sidebar.html" data-below-sidebar="burt_network/ProtoSocket-class-sidebar.html">
```
And here's the code for the `init` method: 
```html
<div id="dartdoc-main-content" class="main-content" data-above-sidebar="burt_network/ProtoSocket-class-sidebar.html" data-below-sidebar="">
```
When I edit the HTML to put the sidebar on the right as well, it loads... but only on the right side. My repository is [here](https://github.com/BinghamtonRover/Dart-Networking), feel free to ask for more info.

**Comment by srawlins** [comment]
Thanks for the report, @Levi-Lesches could you open an issue for what you're seeing?

**Comment by Levi-Lesches** [comment]
Filed #3467

**Comment by srawlins** [comment]
Forgot to close this when I shipped it :D
