### ISSUE TITLE
Method documentation does not show whether the method is static or not

### ISSUE THREAD

**Issue by osa1** [dart-lang/dartdoc#3108]
Consider https://api.dart.dev/stable/2.17.6/dart-core/Object/hashAll.html

There is no mentions in the header ("hashAll method") or in the type signature that the method is static.

I need to look at the implementation, or see if the method name is in "STATIC METHODS" menu on the left.

It would be easier if the header said "hashAll static method".

**Comment by srawlins** [comment]
Good catch. How has this been like this for so long? 🤣
