### ISSUE TITLE
Dark mode tweaks

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#3116]
After trying out Dark mode locally, @mit-mit has some good suggestions:

* [ ] the colors look a bit off compared to our standard colors on other sites; can we update the color palette to match?
* [ ] the dark/light toggle takes up a lot of space. could it just be a single icon button that toggles between a filled sun and a hollow sun?

**Comment by srawlins** [comment]
@parlough do you have links for the color scheme of other Dart or Flutter properties for Dark mode?

**Comment by srawlins** [comment]
@klr981 What do you think of the single icon toggle idea? No rush to implement.

**Comment by keertip** [comment]
@srawlins , @mit-mit, the colors were taken for the Dart pad palette.

**Comment by parlough** [comment]
DartPad is currently the only other site with a proper dark mode: https://github.com/dart-lang/dart-pad/blob/master/lib/scss/colors.scss

I'm not aware of any well-defined color scheme, but @johnpryan may have referenced one when working on the current DartPad design.

The homepage styles for dart.dev may be a useful reference as well: https://github.com/dart-lang/site-www/blob/main/src/_sass/_dash.scss

**Comment by johnpryan** [comment]
The design resources recently moved over to Figma. I'll forward the link to this group.

**Comment by mit-mit** [comment]
@keertip @klr981 was my comment above useful to explain the issue i'm seeing?

**Comment by klr981** [comment]
@mit-mit I am able to change the background color for the code and the docs. 

For the code itself it can't be changed as easily to look like the second screenshot you sent. Since the docs only have some of the code parts specified, this will mean only some things can be changed to a specific color others things would have the same color even if it is not the same type.
