### ISSUE TITLE
fonts with 300 weight are hard to read in dark mode 

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dartdoc#3137]
Using 300 weight:

![Screen Shot 2022-08-30 at 11 06 46 AM](https://user-images.githubusercontent.com/1145719/187511074-cb96972e-eb67-4f1b-b45e-a811ca3de54e.png)

Using 400 weight:

![Screen Shot 2022-08-30 at 11 05 33 AM](https://user-images.githubusercontent.com/1145719/187511079-6e751dc2-b4d6-4c7f-a3f7-aaf3dfca5e5c.png)

**Comment by srawlins** [comment]
ooh I agree. Thanks for reporting!

@parlough are you interested?

(Side note: I wish we had _any_ UI/web/screenshot tests, :( )

**Comment by parlough** [comment]
I guess the point was to distinguish inherited members from those that are not. Is the italic name enough here to distinguish them?

There is the related question of hiding/minimizing them in the first place: https://github.com/dart-lang/dartdoc/issues/2057
