### ISSUE TITLE
dartdoc 6.1.0 generates invalid HTML

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#3146]
Discovered by the HTML validation tests in https://github.com/dart-lang/pub-dev/pull/6031:

```
  <div class="features"><span class=" @<a href="https://pub.dev/documentation/json_annotation/1.2.0/json_annotation/JsonKey-class.html">JsonKey</a>(includeIfNull: false)">@<a href="https://pub.dev/documentation/json_annotation/1.2.0/json_annotation/JsonKey-class.html">JsonKey</a>(includeIfNull: false)</span><span class="feature final">final</span></div>
```

This is generating docs on [`pana` `0.12.2`](https://pub.dev/packages/pana/versions/0.12.2.tar.gz) with pub.dev's [command line arguments](https://github.com/dart-lang/pub-dev/blob/master/app/lib/dartdoc/dartdoc_runner.dart#L136-L145), notably:
```
--rel-canonical-prefix $canonicalUrl
--no-validate-links
--sanitize-html
```

I'm not sure where to look in the templates, but the regression happened between 6.0.1 and 6.1.0.

**Comment by srawlins** [comment]
Thanks for the clear repro!
