### ISSUE TITLE
Dark Mode broken on https://master-api.flutter.dev/

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dartdoc#3170]
This is what it looks like when I trigger dark mode on https://master-api.flutter.dev/:

![Screen Shot 2022-09-19 at 11 27 56 AM](https://user-images.githubusercontent.com/1227763/191089166-c5555e0f-260e-4e1d-ad3b-063c0b8d19c0.png)

**Comment by parlough** [comment]
Flutter's custom [doc style overrides](https://github.com/flutter/flutter/blob/master/dev/docs/assets/overrides.css) will need to be modified to adapt to the [dark mode changes](https://github.com/dart-lang/dartdoc/commit/d3eaea627e5acadd278bd966ee644112a101a1b1).

\cc @gspencergoog

**Comment by gspencergoog** [comment]
Ahh.  What has to change?  Does the CSS just need to reference `light-theme` and `dark-theme` and have versions for both for any style attribute that includes colors?

**Comment by dnfield** [comment]
Flutter bug: https://github.com/flutter/flutter/issues/111941

**Comment by parlough** [comment]
Looks like you already got to fixing this in https://github.com/flutter/flutter/pull/112023. Thanks!

**Comment by gspencergoog** [comment]
Yep, all fixed.
