### ISSUE TITLE
Search results dropdown should only use one line per result

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#3171]
I've been using the new Search experience in dartdoc for a few days now and I think we can improve it further with some small changes. Because each entry in the drop-down takes four lines and three font styles plus a big box, it's relatively hard to scan the results and there are very few results on the screen at a time.
 
<img width="532" alt="" src="https://user-images.githubusercontent.com/551196/191115424-bbb68901-87b9-4aec-8309-147f37166e54.png">

I think this could be improved by using only one line per result with fewer words overall, more like a typical autocomplete UI, for example more like what GitHub does when you type `@` (but with the class and member names, and maybe library names, rather than people's identities, of course!).

<img width="189" alt="" src="https://user-images.githubusercontent.com/551196/191115777-f53f7c89-bcee-4d15-a745-e0ae621984e6.png">

**Comment by srawlins** [comment]
I agree. Great suggestion.
