### ISSUE TITLE
"Enter" to see full search results doesn't work

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#3172]
If I press enter after typing in a search term with many results, I get a UI that says to press Enter to get all the results.

<img width="518" alt="" src="https://user-images.githubusercontent.com/551196/191116527-c4c400d4-a5f7-4db6-86f7-1a1273fe28d9.png">

However, nothing happens when I press enter.

**Comment by kevmoo** [comment]
Reproduces on https://api.dart.dev/be/187340/index.html?

**Comment by kevmoo** [comment]
Sadly, this seems unfixed. For reasons I do not understand!

**Comment by Hixie** [comment]
FWIW, this doesn't work on https://master-api.flutter.dev/ as far as I can tell. I don't know what version of dartdoc that's on though, maybe we just haven't rolled far enough yet?

**Comment by kevmoo** [comment]
It's on latest – 6.1.2 – it IS working on https://api.dart.dev/be/

Wondering if the JS is copied or modified with Flutter...

**Comment by devoncarew** [comment]
We have a regular (semi-automated) process to roll the latest dartdoc into the dart sdk. My most recent knowledge here (which may be out of date) is that it's a manual process to roll the latest dartdoc into flutter.

**Comment by devoncarew** [comment]
Ah; last updated (by @kevmoo) ~15 days ago: https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh.

**Comment by kevmoo** [comment]
...but there was ALSO some concern that the way flutter rolls dartdoc is non-standard. maybe the JS files are different than what's in the package, etc.

**Comment by srawlins** [comment]
It's also weird that https://master-api.flutter.dev/search.html does not load. That could be related, as that is what pressing Enter will load.

**Comment by Hixie** [comment]
This is not working on the Flutter API docs. Any chance we could reopen the issue and make it a high priority? We're about to have a significant branch cut.

cc @itsjustkevin @gspencergoog

**Comment by kevmoo** [comment]
Yeah, we need this fixed. @keertip @srawlins @jacob314

**Comment by itsjustkevin** [comment]
FYI @atsansone @MaryaBelanger
