### ISSUE TITLE
Not clear which library search results are from

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#3175]
Searching for [State] returns results that appear to all be from the "widgets library": it says "widgets library", then "State class", then "State class", then "State constructor", then "BackgroundFetchClickEvent". The latter is actually from dart:html and has nothing to do with the others, but there is no clear separation between them to indicate that they are unrelated. The next result is back to being from the Flutter package which further confused the issue.

<img width="501" alt="" src="https://user-images.githubusercontent.com/551196/191123410-7daaaf6c-e09b-43e3-8c02-fe8cfba494df.png">

One could imagine fixing this in conjunction with https://github.com/dart-lang/dartdoc/issues/3171 by having every result be of the form "Class.member (library) description..." or some such, as in:

* `State` class (`widgets`) The logic and internal state for a Statef...
* `State` constructor (`widgets`)
* `BackgroundFetchClickEvent.state` (`dart:html`) 
* `PrimaryPointerGestureRecognizer.state` (`gestures`) The cur...

**Comment by srawlins** [comment]
Fixed with your suggestions here: https://github.com/dart-lang/dartdoc/pull/3181.

I'll close this, but after another round of dartdoc bump and push to master-api, of course please re-open or open new bugs with the new UX.
