### ISSUE TITLE
JS errors when searching API

### ISSUE THREAD

**Issue by dnfield** [dart-lang/dartdoc#3178]
go to https://api.dart.dev/dev/2.19.0-216.0.dev/index.html

Open the console

Start typing in the API search box

observe JS errors

```
js_helper.dart:1124 Uncaught RangeError (start): Invalid value: Not in inclusive range 0..1: 6
    at Object.b (js_helper.dart:1124:37)
    at Object.b6 (errors.dart:358:7)
    at b_.l (js_string.dart:155:22)
    at b_.F (js_string.dart:153:10)
    at iz.$2 (search.dart:382:36)
    at ip.$2 (search.dart:424:5)
    at ip.$1 (search.dart:406:3)
    at ii.$1 (search.dart:443:5)
    at no (js_helper.dart:1836:14)
    at HTMLInputElement.<anonymous> (js_helper.dart:1868:1)
```

![image](https://user-images.githubusercontent.com/8620741/191159306-6945bd5b-7fa9-4725-a4c1-98b1fa8602b5.png)

Also observable on https://master-api.flutter.dev

@kevmoo @srawlins fyi

**Comment by kevmoo** [comment]
CC @keertip

**Comment by kevmoo** [comment]
Also CC @srawlins

**Comment by keertip** [comment]
I am able to reproduce the problem, now trying to figure out the problem. Looks like the exception does not occur all the time.

**Comment by srawlins** [comment]
Have you made progress on this one @keertip ? I haven't looked at it.

**Comment by keertip** [comment]
Meant to update. I can reproduce on the site, but not seeing the exceptions when running locally.

**Comment by keertip** [comment]
Will wait for a new version of dartdoc and check again to reproduce

**Comment by srawlins** [comment]
CC @keertip this has been re-worked at least one more time recently. May be fixed.

**Comment by kevmoo** [comment]
Just looked at https://master-api.flutter.dev/ – I think @srawlins got it fixed!
