### ISSUE TITLE
The slash search shortcut does not work any more

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/dartdoc#3180]
I can't tell if it was intentionally removed or regressed. This shortcut was super-useful when quickly looking up docs without having to tab multiple times or reach for the mouse.

**Comment by srawlins** [comment]
Can you elaborate? I'm not sure what feature you are talking about.

**Comment by kevmoo** [comment]
I know `/` would send focus to the search box in gmail. 

I just tried this on https://api.flutter.dev/ and https://api.dart.dev/stable/2.18.1/index.html – which are NOT on the latest dartdoc and `/` doesn't work here.

I dig this as a feature request. Not sure if it's a regression, though!
