### ISSUE TITLE
use colors from the material design pallete

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#319]

**Comment by sethladd** [comment]
For now:

```
Palette generated by Material Palette - materialpalette.com/cyan/teal

.dark-primary-color    { background: #0097A7; }
.default-primary-color { background: #00BCD4; }
.light-primary-color   { background: #B2EBF2; }
.text-primary-color    { color: #FFFFFF; }
.accent-color          { background: #009688; }
.primary-text-color    { color: #212121; }
.secondary-text-color  { color: #727272; }
.divider-color         { border-color: #B6B6B6; }
```

**Comment by sethladd** [comment]
![screen shot 2015-04-02 at 8 23 36 pm](https://cloud.githubusercontent.com/assets/5479/6977617/5087bb7c-d976-11e4-88b9-152755cba847.png)

**Comment by sethladd** [comment]
cc @lukechurch @keertip 

Covered in PR https://github.com/dart-lang/dartdoc/pull/320

**Comment by keertip** [comment]
Looking good! Thanks!

**Comment by sethladd** [comment]
Code blocks are also 80 characters, and scroll along the x axis.

**Comment by jaumard** [comment]
Is there a way to customize this ? would be nice for doc that are embedded in website to have the same color palette
