### ISSUE TITLE
enum documentation has weird constructor-like calls interspersed

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#3201]
https://master-api.flutter.dev/flutter/dart-ui/BoxHeightStyle.html
...has a few lines that just say `BoxHeightStyle()` spread throughout the docs in a way that doesn't have any context.

**Comment by srawlins** [comment]
Interesting bug, as it is rendering differently at https://api.flutter.dev/flutter/dart-ui/BoxHeightStyle.html...

I'm not a huge fan of that display either; I think it is only interesting for enhanced enums with constructor type parameters or parameters.

**Comment by Hixie** [comment]
Oh it's supposed to be the value, I see. Wow I really had no idea what it was! :-)
I wonder if instead of `includeLineSpacingTop → const [BoxHeightStyle](https://api.flutter.dev/flutter/dart-ui/BoxHeightStyle.html)` at the top, it would be `includeLineSpacingTop → const [BoxHeightStyle](https://api.flutter.dev/flutter/dart-ui/BoxHeightStyle.html)(3)`...

**Comment by Hixie** [comment]
This fix does not seem to have propagated to the Flutter API docs. Any chance we could reopen the issue? We're about to have a significant branch cut and while this isn't the most critical problem by far, it's a noticeable regression.

cc @itsjustkevin @gspencergoog

**Comment by parlough** [comment]
It seems at least this issue can be fixed by bumping to [dartdoc 6.1.3](https://pub.dev/packages/dartdoc/changelog#613) as the fix for this was included in that release: https://github.com/flutter/flutter/pull/116474

**Comment by itsjustkevin** [comment]
FYI @atsansone @MaryaBelanger
