### ISSUE TITLE
Arrow keys do not iterate through search suggestions in order

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dartdoc#3204]
In this video I am hitting the down arrow key every time to move the highlight. The highlight does not move in the order I would have expected:

https://user-images.githubusercontent.com/1227763/193352809-c153e39d-596f-4d65-8360-2233b179da87.mov

**Comment by srawlins** [comment]
Thanks for the report. Turns out dartdoc search had all these features people used! I had no idea.

**Comment by Hixie** [comment]
This is not working on the Flutter API docs. Any chance we could make it a high priority? We're about to have a significant branch cut, and this is a quite confusing and very visible behavior in a flagship area of the product.

cc @itsjustkevin @gspencergoog

**Comment by itsjustkevin** [comment]
FYI @atsansone @MaryaBelanger
