### ISSUE TITLE
Does not generate the categories

### ISSUE THREAD

**Issue by LucasMatheusDev** [dart-lang/dartdoc#3219]
I'm documenting my code as the flutter documentation instructed, but the categories are not generated in index.html

it will generate the `categories.Json` file but nothing appears on the site

My Doc :  
![issue](https://user-images.githubusercontent.com/81427844/195187743-ddf7118d-b740-42cd-ab6a-06c8b82ed42e.png)

Web Page of Doc : 
![Captura de tela 2022-10-11 170212](https://user-images.githubusercontent.com/81427844/195187771-d3299cd4-a1e1-4b52-9cb0-7c53614bbff8.png)

## Steps :
- Create the class to be documented;

- Add category markup @Category(['Atuh', 'Register]) on top of the class

- Create test documentation using three slashes, for example:
/// documentation test for class
/// {@category Auth}

- Run `dart doc .`

- Open generated` index.htm`l file in the folder **doc/api/**

**Comment by srawlins** [comment]
Thanks for filing a bug report. Please post the steps you undertook in order to generate your docs with categories.

**Comment by LucasMatheusDev** [comment]
> Thanks for filing a bug report. Please post the steps you undertook in order to generate your docs with categories.

Hello friend @srawlins , I'm sorry I forgot to put the steps, I updated the comment with the steps I did.

Thanks in advance for the help 😊

**Comment by srawlins** [comment]
I suspect you need to add `categories` to your `dartdoc_options.yaml`: https://github.com/dart-lang/dartdoc#dartdoc_optionsyaml

**Comment by LucasMatheusDev** [comment]
Thank you. Adding the `dartdoc_options.yaml` solved it for me
