### ISSUE TITLE
Codeblock in --format=md Generates HTML

### ISSUE THREAD

**Issue by AlexAntonides** [dart-lang/dartdoc#3237]
When I use the `dartdoc --format=md` command on the following example,

```dart
/// A class that uses a markdown example.
///
/// ```dart
/// Foo.example()
/// ```
class Foo {
    [...]
}
```

The following "markdown" is generated:
```markdown
# Foo
<p>A class that uses a markdown example.</p>
<pre class="language-dart"><code class="language-dart">Foo.example()
</code></pre>
```

This however is just a mix between Markdown and HTML. I understand that some markdown renderers are capable of rendering HTML, I'd rather have the markdown format generate actual markdown instead, like the following result:
```markdown
# Foo
A class that uses a markdown example.
'''dart
Foo.example()
'''
```

**Comment by kallentu** [comment]
Format flag no longer exists, closing.
https://github.com/dart-lang/dartdoc/commit/4317b06bcc2c4c250b8d4e45147a3a07c21af0df
