### ISSUE TITLE
Could not find order to  generate markdown documentation with dartdoc 6.1.2

### ISSUE THREAD

**Issue by Geio-Guo** [dart-lang/dartdoc#3241]
I used to generate markdown documentation  with order --format md in dartdoc 5.1.2. However, I could not find any order to generate markdown documentation when I update dartdoc to version 6.1.2.

**Comment by srawlins** [comment]
Can you please show the command you use and the error that dartdoc prints?

**Comment by Geio-Guo** [comment]
dart doc --format=md

**Comment by Geio-Guo** [comment]
I had tried these commands and get just one error:
command  like this:
dart doc --format=md
dart doc --format md
dart doc . --format=md

**Comment by srawlins** [comment]
Oh sorry, yes `dart doc` has fewer options. I recommend using the package directly with `dart pub global activate dartdoc` and `dart pub global run dartdoc`.

**Comment by Geio-Guo** [comment]
I had run your command but get this error:
`dartdoc 6.1.2 (/root/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-2.18.2.snapshot) failed: Top level package requires Flutter but FLUTTER_ROOT environment variable not set.`

**Comment by Geio-Guo** [comment]
It is so sad that I get this error when I set flutter root env 
`/root/.pub-cache/bin/dartdoc: 行 18:  7522 已杀死               dart "/root/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-2.18.2.snapshot"`

**Comment by srawlins** [comment]
I think there is a flutter equivalent of `dart pub global run dartdoc` but I don't know what it is 😁 .

**Comment by Geio-Guo** [comment]
So is there any other way that can  generate markdown documentation 🤔

**Comment by pq** [comment]
@srawlins

**Comment by srawlins** [comment]
Not that I know of, sorry.
