### ISSUE TITLE
Text  not aligned when one line documentation wraps

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#326]
![screen shot 2015-04-03 at 1 06 43 pm](https://cloud.githubusercontent.com/assets/2192312/6988064/67c0851c-da02-11e4-86b0-09d88ae2c90a.png)

**Comment by sethladd** [comment]
Fixed!

![screen shot 2015-04-07 at 1 27 38 pm](https://cloud.githubusercontent.com/assets/5479/7032777/d92dad22-dd29-11e4-94d4-a9848cf7baac.png)
