### ISSUE TITLE
Release 6.1.4

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#3262]
We need to release dartdoc 6.1.4 which has a fix for #3172, for flutter.

CC @kevmoo @itsjustkevin

**Comment by srawlins** [comment]
+1; @itsjustkevin @kevmoo I'm not sure on the Flutter release timeline. But #3204 is the other bug fix I'd hope to get into this release.

**Comment by parlough** [comment]
@srawlins Are you working on #3204? If so, I don't want to work on it unnecessarily. 

The search code is pretty complicated. One thing to note, is that it seems https://github.com/dart-lang/dartdoc/pull/3181 which caused the issue also partially broke the results as elements that are not enclosed (perhaps just libraries?) will no longer be displayed.

**Comment by itsjustkevin** [comment]
@srawlins we plan to release a beta this week with hotfixes to follow every week.

**Comment by srawlins** [comment]
I have not and I am out today. I... hope I'll be back tomorrow, so I won't claim it.

**Comment by srawlins** [comment]
I'm back; I've released v6.1.4 so that flutter can test @parlough 's fix for the enter key in search. Will release 6.1.5 with more fixes ASAP.
