### ISSUE TITLE
annotations appears twice

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#3265]
e.g. https://master-api.flutter.dev/flutter/painting/Decoration/lerpFrom.html:

![2022-12-06-164445_904x369_scrot](https://user-images.githubusercontent.com/551196/206059731-b628ef70-ae3d-4f9d-b4bd-29126ce886f3.png)

**Comment by srawlins** [comment]
Widget.createElement looks pretty wild too. https://master-api.flutter.dev/flutter/widgets/Widget/createElement.html

This might be only for functions. The bug does not happen in mockito's [deferToDefaultResponse](https://pub.dev/documentation/mockito/latest/mockito/Mock/deferToDefaultResponse-constant.html), but does happen in observable's [observed](https://pub.dev/documentation/observable/latest/observable/Observable/observed.html).

**Comment by srawlins** [comment]
Note that this bug is already live at api.flutter.dev: https://api.flutter.dev/flutter/widgets/Widget/createElement.html

Still haven't found what caused the regression.

**Comment by srawlins** [comment]
This bug seems to have been introduced before 66e11fdcafe50b23aceecae7c0f5de16b92ccf67 (2022-01-16). I'm not going to search back before then.

**Comment by parlough** [comment]
I guess it's likely https://github.com/dart-lang/dartdoc/pull/2600 or related changes which includes annotations as features, which are [rendered](https://github.com/dart-lang/dartdoc/blob/master/lib/templates/html/method.html#L11), but annotations are still [rendered as well](https://github.com/dart-lang/dartdoc/blob/master/lib/templates/html/_callable_multiline.html#L4). 

I'm not sure the intended distinction between features and annotations, but I guess it makes sense for annotations to be rendered above the element description.

**Comment by srawlins** [comment]
Yeah I'm making a change which effectively does that, and adding testing, haha.

**Comment by srawlins** [comment]
Another screenshot of the broken code for posterity: 

<img width="575" alt="Screen Shot 2022-12-13 at 10 25 24 AM" src="https://user-images.githubusercontent.com/103167/207414936-eb3225a3-6ce0-4ca2-ac90-940adec8b097.png">

 found at https://pub.dev/documentation/observable/latest/observable/Observable/observed.html

**Comment by srawlins** [comment]
If Flutter is keen on having this fix, it is found in dartdoc 6.1.5, cc @goderbauer @gspencergoog
