### ISSUE TITLE
Failed to run dart doc with a newly published package on pub.dev 

### ISSUE THREAD

**Issue by iamwalter** [dart-lang/dartdoc#3289]
After publishing a package, I noticed pub.dev does not want to generate documentation. See the error logs at https://pub.dev/packages/azure_app_config/score for details.

Locally the command `dart doc` is running fine, I have Dart SDK version: 2.18.6 (stable) on "macos_arm64"

It seems some dependencies are incorrect? Below is the stack trace:

```
stdout: MSG : Resolving dependencies...
MSG :   _fe_analyzer_shared 52.0.0
    |   analyzer 5.4.0
    |   args 2.3.1
    |   async 2.10.0
    |   build 2.3.1
    |   build_config 1.1.1
    |   checked_yaml 2.0.2
    |   collection 1.17.0
    |   convert 3.1.1
    |   crypto 3.0.2
    |   dart_style 2.2.4
    |   dio 4.0.6
    |   file 6.1.4
    |   freezed 2.3.2
    |   freezed_annotation 2.2.0
    |   glob 2.1.1
    |   http_parser 4.0.2
    |   json_annotation 4.7.0
    |   logging 1.1.0
    |   meta 1.8.0
    |   package_config 2.1.0
    |   path 1.8.3
    |   pub_semver 2.1.3
    |   pubspec_parse 1.2.1
    |   source_gen 1.2.6
    |   source_span 1.9.1
    |   string_scanner 1.2.0
    |   term_glyph 1.2.1
    |   typed_data 1.3.1
    |   watcher 1.0.2
    |   yaml 3.1.1
MSG : No dependencies changed.

stderr: FINE: Pub 2.18.6
SLVR: fact: azure_app_config is 0.9.0
SLVR: derived: azure_app_config
SLVR: fact: azure_app_config depends on crypto ^3.0.2
SLVR: fact: azure_app_config depends on dio ^4.0.6
SLVR: fact: azure_app_config depends on freezed ^2.2.0
SLVR: fact: azure_app_config depends on freezed_annotation ^2.2.0
SLVR: fact: azure_app_config depends on json_annotation ^4.7.0
SLVR: fact: azure_app_config depends on meta ^1.8.0
SLVR:   selecting azure_app_config
SLVR:   derived: meta ^1.8.0
SLVR:   derived: json_annotation ^4.7.0
SLVR:   derived: freezed_annotation ^2.2.0
SLVR:   derived: freezed ^2.2.0
SLVR:   derived: dio ^4.0.6
SLVR:   derived: crypto ^3.0.2
IO  : Get versions from https://pub.dartlang.org/api/packages/crypto.
IO  : Get versions from https://pub.dartlang.org/api/packages/dio.
IO  : Get versions from https://pub.dartlang.org/api/packages/freezed.
IO  : Get versions from https://pub.dartlang.org/api/packages/freezed_annotation.
[...]
    |   "generator": "pub",
    |   "generatorVersion": "2.18.6"
    | }
RangeError (start): Invalid value: Not in inclusive range 0..4998: 5000
#0      RangeError.checkValidRange (dart:core/errors.dart:358:7)
#1      _StringBase.substring (dart:core-patch/string_patch.dart:400:27)
#2      _limit (package:pub/src/log.dart:344:16)
#3      dumpTranscriptToFile (package:pub/src/log.dart:377:22)
#4      PubCommand.run (package:pub/src/command.dart:231:13)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#6      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:18)
<asynchronous suspension>
#7      runDartdev (package:dartdev/dartdev.dart:66:16)
<asynchronous suspension>
#8      main (file:///b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

Thanks for the help!

**Comment by srawlins** [comment]
CC @isoos could this be a bug for pub.dev? Or maybe the SDK? I don't even know what `package:pub` is...

**Comment by isoos** [comment]
This looks like a bug at version resolution. /cc @sigurdm @jonasfj - I think `pub` shouldn't throw exception on strange input - although not sure where the strange part is coming from. Also: the dependencies were resolved for `pana` analysis, so maybe this was a fluke?

**Comment by iamwalter** [comment]
@srawlins  @isoos Thanks for the input. I'll upload an updated version of the package tomorrow or the day after and report back.

**Comment by isoos** [comment]
@iamwalter: Note: usually there is no need to upload new versions (for the sake of triggering analysis), as we periodically re-analyze packages. I'm not sure how often such `dartdoc` failures would be re-tried, but there are other triggers that would re-run the analysis.

**Comment by sigurdm** [comment]
This looks like a bug in the logging code itself :(

Not sure what went down here - we'll have to try investigating.

**Comment by iamwalter** [comment]
I uploaded a new version to pub - the analysis is not working, still. Guess it was not a fluke. :(

**Comment by iamwalter** [comment]
@sigurdm Does this mean that it this issue will be resolved automatically, as soon as pub.dev updates?

**Comment by sigurdm** [comment]
Yes - we periodically regenerate all documentation, and everytime we deploy a new version - so you should not have to take any action.

**Comment by sigurdm** [comment]
But just that the logging bug is fixed doesn't mean that this issue is fixed. Only that with a newer dart we would get the actual trace of what is going on (hopefully).

**Comment by iamwalter** [comment]
@sigurdm 

I [fixed](https://github.com/iamwalter/azure_app_config/commit/328f8220e0e3335c8bf2a1d6339e703ddb749f3d) the issue by moving 'freezed' to a dev_dependency!
