### ISSUE TITLE
push to pub

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#33]
Is it too early to push a version to pub? This would make it much easier for people to dogfood (via `pub global activate`).

**Comment by sethladd** [comment]
Not quite yet. We can make this a goal for end of month.

You can install packages from git via pub global if you're really motivated :)

**Comment by sethladd** [comment]
We'll have to also put a tombstone on https://pub.dartlang.org/packages/docgen

**Comment by sethladd** [comment]
We have the name: https://pub.dartlang.org/packages/dartdoc

**Comment by kevmoo** [comment]
Done? @sethladd @devoncarew

**Comment by keertip** [comment]
Yes, we do have it on pub.
