### ISSUE TITLE
Missing links for annotations in dartdoc 6.1.5

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/dartdoc#3314]
Details here: https://github.com/dart-lang/pub-dev/pull/6264

**Comment by srawlins** [comment]
The solution is to upgrade to Dart 2.19.0, correct?

**Comment by sigurdm** [comment]
cc @isoos

**Comment by isoos** [comment]
Oh, it wasn't clear for me that this is the solution for the issue. I'll do the upgrade and check if everything is fixed.

**Comment by srawlins** [comment]
Sorry about that. I think 🤞 that this should correct the cross-package links.

**Comment by isoos** [comment]
Unfortunately the annotation link is still removed:
https://github.com/dart-lang/pub-dev/pull/6385/files#diff-bd6aeb626b9f4f0cae06298cde69525441a9d5f8e336b6ea8f69df3481b893b3L177

**Comment by srawlins** [comment]
Actually, that diff is expected. It is not just the _link_ for the annotation that is missing, but the text as well. See https://github.com/dart-lang/dartdoc/pull/3268, a fix for https://github.com/dart-lang/dartdoc/issues/3265. The `@JsonKey` annotation is removed from the class file, where it once was listed in the "features" of the, for example, `version` field. But it should still be listed on the `version` field's page.

As per the fix, you can see that `@protected` is found in https://master-api.flutter.dev/flutter/painting/Decoration/lerpFrom.html, but no longer on the class page at https://master-api.flutter.dev/flutter/painting/Decoration-class.html.

**Comment by isoos** [comment]
Ah, okay, makes sense. I'll go ahead with the version upgrade then.

**Comment by isoos** [comment]
(we may close this issue, but I don't have the permission for it)
