### ISSUE TITLE
Starting with Flutter

### ISSUE THREAD

**Issue by thestrutpole** [dart-lang/dartdoc#3318]
I'm new to flutter. I'm trying to use the 'flutter pub run build_runner build' command to generate json serializers usingjson annotation @JsonSerializable(). When I run the command  then error is displayed several times:
...\flutter\bin\cache\pkg\sky_engine\lib\ui\compositing.dart:131:26 - This requires the 'super-parameters' language feature to be enabled.
> flutter doctor
[√] Flutter (Channel stable, 3.7.0, on Microsoft Windows [Version 10.0.16299.1087]
...
No issues found!
> flutter --version
Flutter 3.7.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b06b8b2710 (9 days ago) • 2023-01-23 16:55:55 -0800
Engine • revision b24591ed32
Tools • Dart 2.19.0 • DevTools 2.20.1

I added 
  - use_super_parameters
to the lint rules in the analysis_options.yml file on my project directory with no joy.

Please recommend how to solve this problem

**Comment by parlough** [comment]
Hi, thanks for filing an issue. This is the repository for [`dartdoc`](https://dart.dev/tools/dart-doc), a tool for generating HTML/Markdown documentation of your Dart code. For Flutter questions, I recommend reaching out on their help forums, such as StackOverflow, the /r/FlutterDev Discord, etc. You can find more links to Flutter community resources on the Flutter [community page](https://flutter.dev/community#community-grid).

As for this particular issue, super parameters were added in Dart 2.17, so your project needs a [language version](https://dart.dev/guides/language/evolution#language-versioning) of at least 2.17 to support code in Flutter that uses super parameters. To accomplish this, make sure the [SDK constraint](https://dart.dev/tools/pub/pubspec#sdk-constraints) in your `pubspec.yaml`, starts with `>= 2.17.0` or greater

**Comment by srawlins** [comment]
Thanks for the quick response, @parlough . Closing for now.
