### ISSUE TITLE
typo in search UI

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#3326]
There's a typo in the code applying css styles to the seach UI:

```
web/search.dart:        ..classes.add('seach-options')
```

I didn't correct it however as I don't see any css values for `seach-options` or `search-options`, so am not sure what the best fix is (correct the typo? remove applying the style? correct to a newer css style name?).

**Comment by srawlins** [comment]
Odd. Probably dead code. @parlough cleaned up a lot of CSS rules recently, but I don't see `search-options` in that change. https://github.com/dart-lang/dartdoc/commit/ed56883d7b3c31aea3faa27232c3bffc2c97aaa4

**Comment by parlough** [comment]
Looks like it was added unused in https://github.com/dart-lang/dartdoc/pull/3129. Seems safe to remove.
