### ISSUE TITLE
[Sealed class] dartdoc implementation

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/dartdoc#3328]

**Comment by jcollins-g** [comment]
This should be a simple matter of marking sealed classes as sealed in dartdoc's output, but will double check to make sure.

**Comment by jcollins-g** [comment]
#3354 adds most of this.   It should be closed out with the rest of the class modifiers once support for inferred modifiers are complete.

**Comment by jcollins-g** [comment]
Closing; inferred modifiers are complete.
