### ISSUE TITLE
Remove first line of docs from main doc body

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#333]
We show the first line in the header. No need to show it twice.

![screen shot 2015-04-07 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/5479/7035151/c80d7688-dd3a-11e4-9fd2-fbabed8976f7.png)

**Comment by keertip** [comment]
We should remove the first line from the header. Removing it from the doc body can lead to lost info - when doc has references etc.

**Comment by sethladd** [comment]
hm, good point. We can see what it looks like if we remove from the header. Having two lines in the header works really well. It tells me the name and what it is.

**Comment by keertip** [comment]
If we are going the route of adding icons , maybe we could try to make use of the same to indicate what it is?

**Comment by sethladd** [comment]
We know what type of thing it is (class, property, etc), but the sub-header tells the user what the intention of the thing is.

We can experiment here.

**Comment by sethladd** [comment]
I don't think we're going to do this anymore.
