### ISSUE TITLE
Running with --dry-run masks warnings from --validate-links

### ISSUE THREAD

**Issue by mkorbel1** [dart-lang/dartdoc#3330]
Running `dart doc --validate-links --dry-run` when warnings related to `--validate-links` are present will mask those warnings.  They are only visible if `--dry-run` is omitted.

Additionally, I can't get any of the `--validate-links` warnings to print out, just the count of the number of warnings, which is pretty frustrating to debug.  I'm not sure if the two are related.

Running on Dart version 2.19.2:
```
$ dart --version
Dart SDK version: 2.19.2 (stable) (Unknown timestamp) on "linux_x64"
```

**Comment by srawlins** [comment]
Good catch. That combo of flags should not be allowed.

**Comment by srawlins** [comment]
> Additionally, I can't get any of the --validate-links warnings to print out

Would you mind filing a separate issue for this? Thanks!

**Comment by mkorbel1** [comment]
> That combo of flags should not be allowed.

Why not?  My use case is checking that there's no documentation issues as part of CI.  I'd like to include warnings caught by `--validate-links` in my CI, but without actually needing to generate (and keep) all the documentation lying around.

Speaking of, these other issues are relevant for this use case as well:
https://github.com/dart-lang/dartdoc/issues/2846
https://github.com/dart-lang/dartdoc/issues/2907
https://github.com/dart-lang/dartdoc/issues/1959


> Would you mind filing a separate issue for this? Thanks!

Sure, filed here: https://github.com/dart-lang/dartdoc/issues/3331

**Comment by srawlins** [comment]
The `--validate-links` feature is just a generic links checker on the generated output. If you like, we could keep this as a feature request that links can be validated in a dry run. But I'll prepare you I don't think we can implement that in the foreseeable future.

**Comment by mkorbel1** [comment]
Ah, ok, thanks for clarifying.  I guess my real "feature request" is to make it really easy to use `dartdoc` in CI with as many quality checks as possible.

Ignoring/deleting the `doc/api/` directory feels like an acceptable workaround for now, but yes some sort of indication that you can't run those two flags together would be helpful!

**Comment by jcollins-g** [comment]
https://dart-review.googlesource.com/c/sdk/+/282811 should prevent users from using both flags at once under this circumstance.

**Comment by mit-mit** [comment]
@jcollins-g given this is technically a small breaking change (CI jobs that used to pass both flags will break), I think we should mention this in the CHANGELOG.md file
