### ISSUE TITLE
Search result order from search results page is inconsistent with the search dropdown list

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dartdoc#3341]
For example, searching api.dart.dev for `Future`:

![image](https://user-images.githubusercontent.com/17391434/219901496-e0cacc1e-00f3-4478-8433-48d298825a65.png)

The results from the search dropdown list in the upper-right seem to be ordered by some heuristic for "relevance". The `Future` class itself rightfully is the first result.

In contrast, the results from https://api.dart.dev/stable/2.19.2/search.html?q=future are in some other order that seems less sensible.  Why is the order inconsistent?  The link to the `Future` class now is the third result.

Additionally, the search dropdown list shows snippets that provide more context, whereas the search results page is very bare.

Finally, I'll point out that despite claims of "27 results", there are not 27 results listed.  I presume that it's counting multiple occurrences of the search term within each linked document, but this isn't what I'd expect from the `Press "Enter" key to see all 27 results` message in the dropdown list.

(Note that isn't quite the same as https://github.com/dart-lang/dartdoc/issues/3176, which more about what the ideal search order should be.)

**Comment by srawlins** [comment]
You're not seeing _any_ results on the main page. There is no order. The text you're seeing is the categorization of the (non-existent) results. I think this is fixed with https://github.com/dart-lang/dartdoc/pull/3285. Maybe not. It'd be good to know what version of dartdoc was used to generate (the present content at) https://api.dart.dev/stable/2.19.2/search.html?q=future

**Comment by srawlins** [comment]
Also see https://github.com/dart-lang/dartdoc/issues/3308.

**Comment by jamesderlin** [comment]
This looks fixed in the Dart 3.0.0 documentation.
