### ISSUE TITLE
Stopping Material children / descendants from being included in Docs

### ISSUE THREAD

**Issue by codingiswhyicry** [dart-lang/dartdoc#3343]
I'm using DartDoc to document a massive design system package, and on export, Flutter children are being included in the documentation as 'within' the design system. I marked the export statement for 'material.dart' as @nodoc in my main library file, but it didn't seem to do anything. My end goal is just to document the most top-level objects in the file structure, and not their descendants / children. 

Apologies if this is already resolved, I've been searching through the docs / Google for a couple of hours now and haven't been able to make a lot of progress on this. If someone could point me in the right direction, it would be very much appreciated. Thanks! :-) 

<img width="1440" alt="Screen Shot 2023-02-18 at 10 15 08 PM" src="https://user-images.githubusercontent.com/10201992/219932278-d231a0e9-2652-4e99-9a46-f136d853e470.png">

**Comment by codingiswhyicry** [comment]
The relevant dart-doc-options file: https://github.com/Astra-Labs/Aureus/blob/v.0.0.0.1/Package/dartdoc_options.yaml 
The library file in question with @nodoc: https://github.com/Astra-Labs/Aureus/blob/v.0.0.0.1/Package/lib/aureus.dart

**Comment by jcollins-g** [comment]
The library referenced reexports the material and google_fonts libraries, which is why they are included (by linking to Flutter docs if `--link-to-remote` is true).  This creates an API surface for Flutter libraries within your package which is why dartdoc documents it.  I would suggest avoiding this by not reexporting libraries across packages (simply, drop the export statements and have your users import both Flutter and aureus).  This makes it clearer both in docs and to users of the API where objects are coming from.

However, assuming you've considered that and really want or need to do this instead, you are correct that `@nodoc` does not apply in this way to export statements.  This would have to be a feature addition.

**Comment by codingiswhyicry** [comment]
That makes sense, thank you for your time:-) I think I'll just remove the export for now, but it would be awesome if in the long term something could be added for this, if there's enough demand for it. 

Our goal is to be a mediator for the entire UI layer so whoever uses our design system would only be responsible for logic code & custom components, but it's not a hill I'll die on.

**Comment by codingiswhyicry** [comment]
Also, in case any future developers run into this thread: I got around this issue by having to import my own package into the items that were apart of the package, and then importing the material library and manually marking it as no doc on every file. 

Any export / import of a package I didn't want documented within a library file led to bad results / circular references that caused remote docs to be included, so I removed the export statements of packages I didn't want documentation for in my main package file. Pretty hacky solution, but it works. 

<img width="443" alt="Screen Shot 2023-02-21 at 2 42 46 AM" src="https://user-images.githubusercontent.com/10201992/220323244-f583f32b-e6fa-433b-9aab-f4e0e5a79598.png">

**Comment by jcollins-g** [comment]
FYI, simply `import`ing a Flutter library should not result in generating Flutter documentation inside your package as that doesn't add it to the API surface.  If for some reason it does, that's a more serious bug.

I understand the idea of wanting to create a mediation layer as that seems nice for users as then they only have to have a single import statement.   But do consider that if Flutter decides to add names to their library that conflict with names in your `aureus` library, it's likely to start becoming a maintainability problem.  Namespace conflicts will then be forced to be resolved in your mediation layer with `show` / `hide`, and if the user wants to override whatever choices you make, they'll have to have `show`/`hide` as well.  We've considered before making dartdoc complain loudly when it sees cross-package reexports.  Ordinarily, adding something to the namespace of a library is not considered a breaking change.  A cross-package unconditional reexport risks breaking that assumption.

**Comment by codingiswhyicry** [comment]
Ah, thank you for letting me know about the above. I may have misread the docs. 

And definitely heard on the maintainability problem. We're trying to balance being friendly to new developers with that, but you make a lot of strong points and I think separating them without a mediation layer is the right call. Thanks :-)
