### ISSUE TITLE
Members exported in a library must show up as being library-native

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#335]
See the `path` package.

`PathException` should be in the `path` library

**Comment by keertip** [comment]
fixed in #341

**Comment by kevmoo** [comment]
This doesn't seem to work.

Run it over https://github.com/dart-lang/angular2_build/tree/master/angular2

The `angular2` library is empty. I tried it with dartdoc HEAD @ https://github.com/dart-lang/dartdoc/commit/f8fdec86da5a1ce82f61944f8841821ee1bdbd6e

**Comment by keertip** [comment]
fixed #424
