### ISSUE TITLE
There no longer seems to be a way to list valid warnings

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dartdoc#3361]
[The dartdoc README.md](https://pub.dev/packages/dartdoc) says in several places:

> See the lists of valid warnings in the command line help for `--errors`, `--warnings`, and `--ignore`.

However, `--errors`, `--warnings`, and `--ignore` are rejected by `dart doc`:

```
$ dart doc --warnings
Could not find an option named "warnings".

Usage: dart doc [arguments] [<directory>]
-h, --help                  Print this usage information.
-o, --output=<directory>    Configure the output directory.
                            (defaults to "doc/api")
    --validate-links        Display warnings for broken links.
    --dry-run               Try to generate the docs without saving them.

Run "dart help" to see global options.
```
If users are supposed to be pass `--errors`, `--warnings`, and `--ignore` as options for a different command, then the exact command should be specified.  Presumably this used to work with the old `dartdoc` command?

**Comment by jcollins-g** [comment]
This still works when running dartdoc.dart directly.  README.md should be updated to indicate this, but we could also consider exposing more control over warnings via dartdev.

**Comment by jamesderlin** [comment]
The top-level `dart` tool should allow passing through those options then, which I suppose means that this should be moved to dart-lang/sdk?
