### ISSUE TITLE
[Question] Log the warnings

### ISSUE THREAD

**Issue by HeySreelal** [dart-lang/dartdoc#3391]
I've run Dart doc and the results included this line:

`Found 7 warnings and 0 errors.`

But, no matter what flag I pass I'm not logged with the actual warnings that are occurring.

I tried dart doc --verbose, I tried to use the dartdoc globally and used `--verbose-warnings`, and `--warnings`. No useful information was found. 

Is there a way that I can get logs on where in my code actually that warning appears?

**Comment by jamesderlin** [comment]
Also see https://github.com/dart-lang/dartdoc/issues/3331.

Warnings are kind of useless if there's no way to see what they are.

**Comment by srawlins** [comment]
Sorry for the extreme delay!

I have seen this once before, and I think I worked around it somehow, but I've lost the knowledge. IIRC, the warnings were about broken links or orphaned files or something... But yes, super frustrating that they are counted, but not printed.

If you have a reproduction, we can look into it. (Or the next time I can repro it myself I can investigate properly.)

**Comment by HeySreelal** [comment]
Hi @srawlins, I've tried to reproduce the issue with no success. Also, found the warnings are now being logged to the console. Which pretty much sounds like we can close this issue. Thanks again!
