### ISSUE TITLE
Link a class that is used to initialize a constant

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#343]
![screen shot 2015-04-10 at 4 33 31 pm](https://cloud.githubusercontent.com/assets/5479/7099038/596ae492-df9f-11e4-8f90-4f192bf15ee3.png)

Notice how "ConstantClass" is not linked.

Thanks!

**Comment by keertip** [comment]
#371

**Comment by sethladd** [comment]
Very cool! Except, maybe I didn't merge correctly

![screen shot 2015-04-13 at 3 20 53 pm](https://cloud.githubusercontent.com/assets/5479/7126737/aa061bf8-e1f0-11e4-8b5c-9049a38ff208.png)

**Comment by sethladd** [comment]
Fixed in my branch.
