### ISSUE TITLE
First class functions are missing generic type parameters in API

### ISSUE THREAD

**Issue by nshahan** [dart-lang/dartdoc#3452]
I noticed this when looking at the docs for package:dart_internal. For example look at [extractIterableTypeArgument](https://pub.dev/documentation/dart_internal/latest/extract_type_arguments/extractIterableTypeArgument.html)

Notice how in the signature at the top the function parameter is displayed in the old format and is missing its generic type parameter:
```dart
extractIterableTypeArgument(Iterable iterable, Object? extract()) → Object?
```

While in the implementation you can see the newer function type syntax and the type parameter:
```dart
Object? extractIterableTypeArgument(
        Iterable iterable, Object? Function<T>() extract) =>
    internal.extractTypeArguments<Iterable>(iterable, extract);
```

This issue appears on the main API page as well:
https://pub.dev/documentation/dart_internal/latest/extract_type_arguments/extract_type_arguments-library.html

**Comment by srawlins** [comment]
Whoa yikes, great catch.
