### ISSUE TITLE
Remove grinder dependency

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#3455]
In moving this to the SDK repo, we can either add grinder to the SDK's deps, or remove our dependency on grinder. I'm happy to just rewrite the grinder tasks as package:args commands.

**Comment by parlough** [comment]
Seems like switching to `package:args` would be the most reliable long term.

**Comment by srawlins** [comment]
There are currently 36 tasks:

1. [ ] `analyze`, depends on `analyzeTestPackages`, which can be replaced with `dart analyze .`.
2. [ ] `analyzeTestPackages`, no deps, which can be replaced by running `dart analyze` in the `testing/test_package` and `testing/test_package_experiments` packages.
3. [ ] `checkFormat`, no deps, which can be replaced by running `dart format -o none bin lib test tool web`.
4. [ ] `presubmit`, depends on `analyze`, `checkFormat`, `checkBuild`, `tryPublish`, `test`, does nothing else.
5. [ ] `buildbot`, depends on `presubmit`, `test`, `testDartdoc`, does nothing else.
6. [ ] `buildbotNoPublish`, depends on `analyze`, `checkFormat`, `checkBuild`, `test`, `testDartdoc`, does nothing else.
7. [ ] `buildSdkDocs`, no deps, does real work.
8. [ ] `compareSdkWarnings`, no deps, does real work.
9. [ ] `testWithAnalyzerSdk`, no deps, runs grinder tasks with SDK's copy of analyzer at HEAD.
10. [ ] `buildTestExperimentsPackageDocs`, depends on `clean`, runs dartdoc in `testing/test_package_experiments` package.
11. [ ] `buildTestPackageDocs`, depends on `clean`, runs dartdoc in `testing/test_package` package.
12. [ ] `buildTestPackageDocsMd`, depends on `clean`, runs dartdoc the `testing/test_package` package with `--format md`.
13. [ ] `serveTestPackageDocs`, depends on `buildTestPackageDocs`, and serves the docs.
14. [ ] `serveTestPackageDocsMd`, depends on `buildTestPackageDocsMd`, and serves the docs.
15. [ ] `serveSdkDocs`, depends on `buildSdkDocs`, and serves them.
16. [ ] `compareFlutterWarnings`, no deps, and does real work.
17. [ ] `serveFlutterDocs`, depends on `buildFlutterDocs`, and serves them.
18. [ ] `serveLanguageTestDocs`, depends on `buildLanguageTestDocs`, and serves them.
19. [ ] `buildLanguageTestDocs`, no deps, does real work.
20. [ ] `validateFlutterDocs`, depends on `buildFlutterDocs`, `testDartdocFlutterPlugin`, does nothing else.
21. [ ] `buildFlutterDocs`, no deps, does real work.
22. [ ] `buildPubPackage`, no deps, does real work.
23. [ ] `servePubPackage`, depends on `buildPubPackage`.
24. [ ] `checkChangelogHasVersion`, no deps, checks the CHANGELOG.
25. [ ] `build`, depends on `clean` and `buildWeb`, can be replaced with `dart run tool/mustachio/builder.dart`, and edit `dartdoc_options.yaml`.
26. [ ] `buildWeb`, no deps, can be replaced with `dart compile js --output=lib/resources/docs.dart.js web/docs.dart -O4`, and compile a signature
27. [ ] `checkBuild`, no deps, verifies generated files are up-to-date.
28. [ ] `tryPublish`, depends on `checkChangelogHasVersion`, can be replaced with `dart pub publish -n`
29. [ ] `test`, depends on `analyzeTestPackages`, can be replaced with `dart --enable-asserts run test`
30. [ ] `clean`, no deps, deletes files,
31. [ ] `testDartdoc`, 
32. [ ] `testDartdocRemote`,
33. [ ] `serveDartdocFlutterPluginDocs`
34. [ ] `buildDartdocFlutterPluginDocs`
35. [ ] `testDartdocFlutterPlugin`
36. [ ] `validateSdkDocs`
