### ISSUE TITLE
Dart Doc Failed on Windows

### ISSUE THREAD

**Issue by yangsfang** [dart-lang/dartdoc#3493]
Attempting to document Flutter on Windows. 

Steps:

1. Install Flutter on Windows (I used 3.7.12)
2. cd into `%FLUTTER_ROOT%\packages\flutter` which contains the flutter source code
3. `flutter pub get`
4. `dart doc`

Error:

```
dartdoc 6.1.5 (/X:/flutter/packages/flutter/dartdev) failed: Command executables must exist. The file "x:\flutter\bin\cache\dart-sdk\bin\dart" does not exist for tool snippet..
```

This is because on Windows the executable files have extensions. `dart.exe` exists in that directory but isn't picked up by [the check](https://github.com/dart-lang/dartdoc/blob/v6.1.4/lib/src/dartdoc_options.dart#L214).

Copied `dart.exe` to `dart` in `x:\flutter\bin\cache\dart-sdk\bin`. There is another error:

```
dartdoc 6.1.5 (/X:/flutter/packages/flutter/dartdev) failed: Non-Dart commands must be executable. The file "x:\flutter\bin\cache\dart-sdk\bin\dart" for tool snippet does not have execute permission..
```

It seems the [permission check code](https://github.com/dart-lang/dartdoc/blob/v6.1.4/lib/src/dartdoc_options.dart#L222) does not understand Windows permissions. (my executing user does have read and execute permission to that file).

Is generating flutter docs on Windows supported?

**Comment by srawlins** [comment]
To separate out a general "can I generate docs for some package on Windows?" from "can I generate _the Flutter API docs_ on Windows?", can you try the script that the Flutter team uses to generate the Flutter API docs?

It is this script here: https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh

If that script _is_ supposed to be runnable on Windows, like with Linux-on-Windows or Cygwin or something, they should have instructions. Either way, this is probably a question for the Flutter team, or for StackOverflow.

**Comment by yangsfang** [comment]
> To separate out a general "can I generate docs for some package on Windows?" from "can I generate _the Flutter API docs_ on Windows?", 

Indeed I'm trying to do the latter - generating _the Flutter API docs_ on Windows. 

I understand from https://github.com/dart-lang/dartdoc/issues/2161#issuecomment-602838219 that the snippet tool is only relevant for generating Flutter/Dart documentation, and it appears this code path is only utilized in that case.

> can you try the script that the Flutter team uses to generate the Flutter API docs?
> 
> It is this script here: https://github.com/flutter/flutter/blob/master/dev/bots/docs.sh
> 
> If that script _is_ supposed to be runnable on Windows, like with Linux-on-Windows or Cygwin or something, they should have instructions. Either way, this is probably a question for the Flutter team, or for StackOverflow.

I understand that the Flutter team has some script to perform doc generation for their own purpose. And they may have expectations on what environment they want to run their script on to generate their doc. I briefly looked at the script and I do not believe that script will be useful on my environment. (They expect a Linux environment such as the Windows Subsystem for Linux, and that is not what I'm doing) 

With the above said, it is still unclear whether the Flutter team does intend to support people generating the docs on Windows without a Linux like environment, in addition to what they are already doing for their own purpose with the script above. But that question should indeed be addressed to the Flutter team.

My remaining question is - I've determined the offending code was written with a Linux-like environment in mind and resides in this repository. Is it of interest at all to make that part of the code cross platform? Or would that depend on the answer to whether Windows should be supported for generating Flutter API docs from Flutter team?

**Comment by srawlins** [comment]
> My remaining question is - I've determined the offending code was written with a Linux-like environment in mind and resides in this repository. Is it of interest at all to make that part of the code cross platform? Or would that depend on the answer to whether Windows should be supported for generating Flutter API docs from Flutter team?

Good questions. It is mostly a matter of priority. We do some testing on Windows in our CI, so that devs can generate docs for their own packages locally. But we don't test Flutter's doc generation script on Windows. We wouldn't want to land a fix blindly, so we'd want to test it, etc. It probably won't be a high priority task and would require some effort.

**Comment by yangsfang** [comment]
Ack. Considering that we have not cleared the question of whether the end goal here is supported, and I cannot imagine too many people being interesting in doing this, this is low priority. 

It seems like it wouldn't be wise to pursue a fix in the official repo, given the potential time investment. 

I'm closing this bug as won't fix.

**Comment by yangsfang** [comment]
Just want to give the workaround here for anyone interested in hacking it for their purpose (although it won't be merged into the official repo for reasons stated above):

https://github.com/dart-lang/dartdoc/blob/f2bb6e92aa4fa76a409f301773d5be6bfda897dc/lib/src/dartdoc_options.dart#L213

Add the following lines above.

```dart 
if (Platform.isWindows) {
  executable = executable + '.exe';
}
```

https://github.com/dart-lang/dartdoc/blob/f2bb6e92aa4fa76a409f301773d5be6bfda897dc/lib/src/io_utils.dart#L65

Add the following lines above.
```dart
if (io.Platform.isWindows) {
  return mode != 0;
}
```

Then run at the project root run `dart <path to dartdoc cloned repo>/lib/dartdoc.dart .`.
