### ISSUE TITLE
Documentation contains out of date information

### ISSUE THREAD

**Issue by dgagnon** [dart-lang/dartdoc#3494]
See https://pub.dev/packages/dartdoc:
```
Auto including dependencies 
If --auto-include-dependencies flag is provided, dartdoc tries to automatically add all the used libraries, even from other packages, to the list of the documented libraries.
```

This is one of many such example.  There are many issues currently linked to this in both dartdoc and sdk repo.  The root caused seems to be the transition to "dart doc" which was done without exposing the same functionality as before, but was not declared as a breaking change.

**Comment by srawlins** [comment]
Good catch! Thanks for reporting.

**Comment by dgagnon** [comment]
@srawlins I see this is being tagged as a P3.  Based on the published definitions, I would expect this to receive a P2 at the minimum, considering it impacts every new and a lot of old users.  Moreover, this issue has been raised over a year ago.

**Comment by srawlins** [comment]
We don't have hard rules about the prioritization. But generally, an issue that only affects a user who is trying to run `dart doc` themselves is low priority, as very (very) few users do this. Issues affecting the generated documentation of a package is much higher priority.

Age doesn't really factor into priority.

**Comment by dgagnon** [comment]
Thanks for taking the time to reply.

The documentation for dart mention dart docs as the recommended method for documenting code:  https://dart.dev/effective-dart/documentation  

We would like to have HTML documentation in our internal developer portal.  As there are no mention of this being available primarily for package maintainer, nor there is another method of generating internal documentation from dart code, we are having some difficulty understanding what is the recommended approach for dart/flutter applications.

What would you recommend we do differently to avoid pulling in all dependencies when generating the documentation ?

**Comment by srawlins** [comment]
> we are having some difficulty understanding what is the recommended approach for dart/flutter applications.

`dart doc` is probably the recommended approach. Or, _would be_ the recommended approach, but as you note, we don't have a formal recommendation.

> What would you recommend we do differently to avoid pulling in all dependencies when generating the documentation ?

You shouldn't have to do anything differently. `dart doc` should not generate documentation for dependencies.

**Comment by dgagnon** [comment]
Thank you, this was helpful.  Turns out dart doc reads the `.fvm/flutter_sdk` folder in the project when there is one.  We resolved it with the nodoc configuration option.  This now prevents dartdoc from generating documentation for all installed libraries.

dartdoc_options.yaml:  
```yaml
nodoc: [ '.fvm/flutter_sdk/**/*']
```
