### ISSUE TITLE
Fatal error: unable to locate the input directory

### ISSUE THREAD

**Issue by xanmankey** [dart-lang/dartdoc#3504]
I'm having the same issue as https://github.com/dart-lang/dartdoc/issues/2639#issue-881632230. Here's what I've tried:
- ```flutter pub cache repair```
- ```dartdoc```: failed
- ```flutter pub get```
- ```dartdoc```: failed
- ```flutter global pub deactivate dartdoc```
- ```flutter global pub activate dartdoc```
- ```dartdoc```: failed

The error message is:
```dartdoc 6.3.0 (/home/xanmankey/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart-3.1.2.snapshot) failed: fatal error: unable to locate the input directory at /home/xanmankey/Programming/App/SwipeSwap/SwipeSwapFrontend/swipeswap/lib/models..```

My code in /lib structured as follows:
├── home.dart
├── main.dart
├── matching.dart
├── models.dart
├── order.dart
├── providers.dart
├── services.dart
├── src
│   ├── models
│   │   ├── order_model.dart
│   │   ├── seller_model.dart
│   │   └── user_model.dart
│   ├── provider
│   │   ├── order_provider.dart
│   │   ├── screen_provider.dart
│   │   ├── seller_provider.dart
│   │   └── user_provider.dart
│   ├── screens
│   │   ├── home
│   │   │   ├── profile.dart
│   │   │   ├── seller.dart
│   │   │   └── swaps.dart
│   │   ├── matching
│   │   │   ├── matchFound.dart
│   │   │   ├── matching.dart
│   │   │   └── noMatchFound.dart
│   │   ├── order
│   │   │   ├── order.dart
│   │   │   └── orders.dart
│   │   └── welcome
│   │       ├── welcome.dart
│   │       └── wrapper.dart
│   ├── services
│   │   ├── auth.dart
│   │   └── firebase_options.dart
│   ├── utils
│   │   ├── bottom_nav_bar.dart
│   │   ├── constants.dart
│   │   └── order_card.dart
│   └── widgets
│       ├── dining_court.dart
│       ├── item.dart
│       └── logout_button.dart
├── utils.dart
├── welcome.dart
└── widgets.dart

I also have a dartdoc_options.yaml file in the root project directory as follows:

```yaml
dartdoc:
  # categories:
  #   "Screens":
  #     markdown: doc/Screens.md
  #     name: Screens
  exclude: ["lib/src/**"]
  nodoc: ["lib/src/**"]
  # categoryOrder: ["Screens"]
```

The files directly inside of lib are library files and the files inside of src are exported in the library files (makes the documentation a little bit neater IMO). I also wanted to categorize all of the directories under the screens directory into sub-libraries, but I wasn't sure how to do that. Just building my documentation comes first though! If you have any idea or could provide any suggestions, I would greatly appreciate it!

**Comment by srawlins** [comment]
Sorry to hear you're seeing this crash. Can you paste the full stack trace?

**Comment by xanmankey** [comment]
I would if I knew how... I tried running ```dartdoc --no-quiet``` in both the vscode terminal and the ubuntu terminal, but it didn't seem to change the output at all. The specified error message is all that I'm getting in terms of output. Is there a different way to log in a more verbose manner or dartdoc log files somewhere that I can provide?

**Comment by srawlins** [comment]
😦 that's certainly annoying. I'm not sure why the stack trace is being swallowed. I don't usually run dartdoc with just `dartdoc`. What about `dart run dartdoc` or `dart pub global run dartdoc`? I forget the incantation these days.

**Comment by srawlins** [comment]
I found where it is being swallowed, in `lib/src/dartdoc.dart`. I can send a PR to fix that.

I don't have high hopes that the stack will be illuminating though. Is there a way I can reproduce this locally?

**Comment by xanmankey** [comment]
Running ```flutter pub global run dartdoc``` worked as intended, so the issue was likely related to my usage of the command. I assumed ```dartdoc``` would be the intended way to run the command, but it seems to function differently when run standalone as opposed to when run by flutter or dart. Thanks for the suggestion!
