### ISSUE TITLE
[proposal] Release dartdoc 7.0.0, update to it in SDK DEPS, propose cherry pick update to 3.2 `beta`

### ISSUE THREAD

**Issue by parlough** [dart-lang/dartdoc#3514]
Primarily to get the fixes for https://github.com/dart-lang/pub-dev/issues/7058 and similar issues in: https://github.com/dart-lang/dartdoc/pull/3507 and https://github.com/dart-lang/dartdoc/pull/3510

These issues impact Dart 3.1, but I don't think it's worth cherry-picking back to 3.1 as the fixes would likely need to be separated from other recent dartdoc changes.

**Comment by srawlins** [comment]
We vet a release in Google internal before tagging the pub package version. So I like the idea of bumping in dart-lang/sdk, then Google internal, then bumping to 7.0.0, release, and propose a cherry-pick for Dart 3.2.

**Comment by parlough** [comment]
Sounds great to me :)

**Comment by parlough** [comment]
I'm going to close this as the release was made and incorporated into the SDK. Thank you!

A separate cherry-pick request issue can be made against the SDK repository if you think it's safe enough.
