### ISSUE TITLE
Mark anything as deprecated as obviously deprecated

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#355]

**Comment by seaneagan** [comment]
What about de-prioritizing all deprecated members to the bottom of a given section (methods, properties, etc.), ignoring source and alphabetical order?

**Comment by sethladd** [comment]
maaaybe ? not a bad idea. Make it happen! :)

**Comment by sethladd** [comment]
It would not be a bad thing to open a new issue for pushing deprecated members down to the bottom of the list.
