### ISSUE TITLE
Documentation for functions in `enum`s are linked but not generated

### ISSUE THREAD

**Issue by mkorbel1** [dart-lang/dartdoc#3584]
If you define an `enum` with a function in it, then the documentation page for that `enum` will have a link to a documentation page about that function (and even the doc comment for the function), however the page for the function will be missing.

In addition, since the target of the link is missing, `--validate-links` will trigger a warning.  This was annoying to debug because of #3331.  I had to run this repo in debug mode and add `print` statements to figure out what was missing since I didn't know what the warning was.

To reproduce, create an `enum` with a `static` function in it, for example:
```dart
enum MyEnum {
  a,
  b,
  c;

  /// Says hello!
  static void myFunction() {
    print("hello");
  }
}
```

The generated documentation will include `MyEnum` and a link to `myFunction`, as expected, however the link (circled) will be dead because the doc page for `myFunction` is not generated.

![image](https://github.com/dart-lang/dartdoc/assets/75506197/7bb46f95-773f-49ca-9b72-05b01f518ce4)

**Comment by srawlins** [comment]
Sorry for the extreme delay (dartdoc has fallen through the gaps in our triage process). I think there is a sizeable blind spot here with enhanced enums. I noticed that dartdoc's Enum doesn't inherit from Class, but it really probably should.
