### ISSUE TITLE
`static` methods are listed as mixins in documentation search results

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/dartdoc#3588]
For example: https://api.dart.dev/stable/3.2.0/search.html?q=tryparse

![image](https://github.com/dart-lang/dartdoc/assets/17391434/8ee91919-bba8-4188-ae3a-fa6c56c5ebb5)

None of the classes with `tryParse` `static` methods is a mixin class.  Clicking on any of those search results does correctly show "tryParse static method" in the breadcrumbs and in the main heading:

![image](https://github.com/dart-lang/dartdoc/assets/17391434/926d7629-79ee-4fa0-9d74-2d43be13fc00)

I observe this when searching for other `static` methods too.

**Comment by srawlins** [comment]
This appears to be fixed at dartdoc HEAD.

**Comment by srawlins** [comment]
And this is fixed at 8c103397734f4dba75915e40c734a88e29a35f26. This is the commit that is going to be cherry-picked into Dart 3.2.x. I'll close with that; watch for a Dart 3.2.x.
