### ISSUE TITLE
Add in-page nav for major sections

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#359]
For a class or library with lots and lots of stuff, it might be hard to jump to a particular section. Assumption: a user wants to see *just* the methods or *just* the properties.

Add an in-page nav or menu that helps a user jump down to a section.

**Comment by devoncarew** [comment]
I'll take a look at the in-page nav.

**Comment by devoncarew** [comment]
This line: `<base href="{{htmlBase}}">` is making the inter-page nav very interesting.

**Comment by sethladd** [comment]
Sorry about that.

**Comment by devoncarew** [comment]
> I don't think we underline the words in the tabs, on hover. Looks like we should bold on hover.
> Also, I think we should put a border at the bottom of the selected tab.
> Check out http://www.getmdl.io/started/index.html
