### ISSUE TITLE
Dartdoc generates docs for library in `lib/src`

### ISSUE THREAD

**Issue by robertbastian** [dart-lang/dartdoc#3590]
See the docs here: https://icu4x-pr-artifacts.storage.googleapis.com/gha/81185cffa2efc81a06f9f311f7e74055da81bd52/ffi/dart/index.html

Generated from the code here:
https://github.com/unicode-org/icu4x/tree/81185cffa2efc81a06f9f311f7e74055da81bd52/ffi/capi/dart/package

The library `lib/src/lib.g.dart` is not part of the public API, yet it appears in the docs.

**Comment by srawlins** [comment]
I cannot reproduce this behavior. With both Dart 3.0 and Dart at HEAD (recent), when I:

1. `git clone git@github.com:unicode-org/icu4x.git`
2. `cd icu4x/`
3. `dart pub get`
4. `dart doc`
5. Open the generated docs in a browser. I only see the 'icu' library.

**Comment by robertbastian** [comment]
With "from the package" I meant from `ffi/capi/dart/package`. This is the invocation: https://github.com/unicode-org/icu4x/blob/26af7358c6aec5cebdaa909b597a3e2928080043/.github/workflows/artifacts-build.yml#L158-L162

**Comment by srawlins** [comment]
Ah yeah, that's what I meant. Sorry. Have you run `dart pub get`? What version of Dart are you runnnig?

**Comment by robertbastian** [comment]
I have not run `dart pub get`. I'm running 3.1.5, and CI is running whatever the `dart-lang/setup-dart@v1` installs.

**Comment by srawlins** [comment]
I imagine `dart doc` does not recognize the package as a Dart package without a package config. The package config is generated by `dart pub get`, at `.dart_tool/package_config.json`.

I'm not sure how to configure the `setup-dart` GitHub Action code, but I see that `dart pub get` is explicitly called in, for example, the [markdown](https://github.com/dart-lang/markdown/blob/master/.github/workflows/test-package.yml#L31) CI code.

> Does dart pub get change things outside the repo?

Yes, it downloads files into the pub cache, which by default is at `$HOME/.pub-cache`.

**Comment by srawlins** [comment]
It's intentional. We use the [package config specification](https://github.com/dart-lang/language/blob/main/accepted/2.8/language-versioning/package-config-file-v2.md), and the `.dart_tool/package_config.json` file to tell dartdoc and the analyzer how to resolve `package:` URIs, and where the package root of a package is. It could be pragmatic to just guess based on the presence of a pubspec.yaml file, if there was a compelling reason to locate a package without a package config file.

**Comment by robertbastian** [comment]
Is it documented anywhere that I have to run `dart pub get` before `dart doc`? Why doesn't `dart doc` run it if it needs it?

**Comment by srawlins** [comment]
I'm not sure if it is documented anywhere. It could run it itself.

**Comment by priyanuj-gogoi** [comment]
> Is it documented anywhere that I have to run `dart pub get` before `dart doc`?

Yes

*“To generate documentation, you must first run [dart pub get](https://dart.dev/tools/pub/cmd/pub-get) and your package must pass [dart analyze](https://dart.dev/tools/dart-analyze) without errors.”* – dart.dev ([source](https://dart.dev/tools/dart-doc))
