### ISSUE TITLE
Are there any options for showing an image in a comment for a private repository?

### ISSUE THREAD

**Issue by atreeon** [dart-lang/dartdoc#3597]
I want to link to and show an image in IntellJ Idea popup when I hover over a class nane.  An image is referenced and is displayed in the Intellij Idea documentation popup when I reference an external publicly available image.  Unfortunately my repo is private and if I link to the image in a private repo the image doesn't link correctly.

It doesn't seem to work on a local relatively linked image either (image1, image2 in the examples below).  I'm not completely sure but github seems to support this https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#images.

Another option that works is just a md style link as per the last option but of course that doesn't show when I hover over a class definition.

Ideally I'd like the image to show in Intellij Idea when I hover over a class definition.  Is there a way to get the images to show for relative links perhaps or private repos?

```
/// ![image1 image in same file location](x.png)
///
/// ![image2 relative link](../../../x.png)
///
/// ![image3 link with token as a macro](https://raw.githubusercontent.com/atreeon/xyz/abc/x.png?token={@macro token})
///
/// ![image4 link with a token, this works](https://raw.githubusercontent.com/atreeon/xyz/abc/x.png?token=QWERTY)
///
/// ![image5 private repo link](https://raw.githubusercontent.com/atreeon/xyz/abc/x.png?raw=true)
///
/// ![image6 private repo link](https://github.com/atreeon/xyz/blob/abc/x.png?raw=true)
///
/// https://github.com/atreeon/xyz/blob/abc/x.png?raw=true
```

**Comment by srawlins** [comment]
I don't believe so. @jwren could maybe point you to where you could make that request.

**Comment by jwren** [comment]
Closing this issue, opening on the Dart Plugin here: https://youtrack.jetbrains.com/issue/IDEA-340708/Can-images-be-displayed-in-hovers-in-dartdoc
