### ISSUE TITLE
Topic links with spaces show 404

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/dartdoc#3654]
The link for a topic with a space character no longer works. For example, https://pub.dev/documentation/go_router/latest/topics/Get%20started-topic.html

Steps to reproduce:
1. Go to https://pub.dev/documentation/go_router/latest/
2. Click on "Get started"
3. Observe 404

**Comment by parlough** [comment]
I don't think anything has changed in dartdoc recently that could have caused this.

Perhaps something on pub.dev? https://github.com/dart-lang/pub-dev/commit/d7462ad952057c9c723202bf6ce08d3d749e1345

\cc @isoos 

Maybe dartdoc should replace spaces with hyphens though? Not sure.

**Comment by isoos** [comment]
Hm, this may be the culprit, we need to enable spaces too: https://github.com/dart-lang/pub-dev/pull/7449
(Although it would be really great if dartdoc could generate dashes instead, I don't really like `%20` in URLs).

**Comment by johnpryan** [comment]
It's also a common practice to use `+` instead of `%20`

**Comment by parlough** [comment]
Ah, if `+` is a common practice, that makes sense to me. Good idea!

A fix landed for pub.dev in https://github.com/dart-lang/pub-dev/commit/d32ab0b863d742685cb5d842950a7af01f2bab25, so this should be fixed automatically after their next deploy when the docs are regenerated next.

But this still sounds like something that's valuable to consider, just lower priority :)

**Comment by johnpryan** [comment]
That fix makes sense to me. I prefer `%20` since it aligns with [rfc1738](http://www.faqs.org/rfcs/rfc1738.html).
