### ISSUE TITLE
In "implementers" list, include `extension type` implementers along with classes and mixins

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#3656]
See `TypeData` - https://api.dart.dev/main/4ddc4a9e8d1a13aa50bac280669e4334e39a0b57/dart-typed_data/TypedData-class.html

You see all of the implementers.

See `JSTypedArray` - https://api.dart.dev/main/4ddc4a9e8d1a13aa50bac280669e4334e39a0b57/dart-js_interop/JSTypedArray-extension-type.html

```dart
/// The Javascript `Int8Array`.
@JS('Int8Array')
extension type JSInt8Array._(JSInt8ArrayRepType _jsInt8Array)
    implements JSTypedArray {}
```

I'd expect to see `implementers`, too!

**Comment by srawlins** [comment]
BTW we do have tests that this works so... something fishy :D

**Comment by srawlins** [comment]
Wait no, you lost me. Why do you expect to see `implementers` on the page for `extension type JSInt8Array`? Who implements `JSInt8Array`? Is that even legal?

**Comment by parlough** [comment]
I think Kevin means the page for `JSTypedArray` should show that `JSInt8Array` implements it.

**Comment by srawlins** [comment]
OK. We can add that feature.

**Comment by kevmoo** [comment]
Looking at https://api.dart.dev/main/b4574904f9cd0d6f7147950c02ee2447569d0be9/dart-js_interop/JSTypedArray-extension-type.html

Which corresponds to https://github.com/dart-lang/sdk/commit/b4574904f9cd0d6f7147950c02ee2447569d0be9

Which includes https://github.com/dart-lang/sdk/commit/7c223d8312e2c672252d5c81a17c2d0da36dc517

Which syncs dartdoc to include https://github.com/dart-lang/dartdoc/compare/7e171fc..7a9df65

It doesn't seem this is fixed!

**Comment by srawlins** [comment]
Ah, I think it's that JSTypedArray is also an extension type. Can fix.
