### ISSUE TITLE
issues rolling into google3

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#3680]
There are one or more issues rolling the latest dartdoc into google3:

```
Target of URI doesn't exist. #uri_does_not_exist

import 'package:dartdoc/src/render/renderer_factory.dart';
```

I'll pause the roll into the sdk; we should roll dartdoc into google3 and then unpause the sdk roll.

**Comment by srawlins** [comment]
I was able to land a dartdoc bump, https://github.com/dart-lang/sdk/commit/7359dedd68ce1d7b6c7bb94c4a79d3325122fdb1, with some changes to google3, so I think we're good here.
