### ISSUE TITLE
libraries aren't sorted correctly in the latest pkg:googleapis

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#3744]
Compare the left library list in

https://pub.dev/documentation/googleapis/11.4.0/
https://pub.dev/documentation/googleapis/12.0.0/
https://pub.dev/documentation/googleapis/13.1.0/

The 13.1.0 are sorted incorrectly. I'm guessing it's due to the `name` being blank in all of these so we're just sorting on the hashcode, which ends up being...random?

https://github.com/dart-lang/dartdoc/blob/28d0dabbcce6e19cb62daea2db7d5d3d87017dfa/lib/src/model/nameable.dart#L97-L104

**Comment by srawlins** [comment]
I think I fixed this, but I don't know when. They looks sorted well in the latest docs.
