### ISSUE TITLE
Where does one get the SDK's README for the docs?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#376]
The dartdoc README uses a fake path to the SDK's library readme.

Assuming I have a .zip of the Dart SDK, where do I find the SDK's lib README for the doc generation?

(I wanted to setup a grinder task to generate the SDK docs)

Thanks!

**Comment by sethladd** [comment]
Opened https://code.google.com/p/dart/issues/detail?id=23203 to add the readme to the SDK, and then we can update our README with instructions.

**Comment by keertip** [comment]
Starting 1.11, the Dart SDK zip will have the api_readme.md file in the lib directory.

**Comment by sethladd** [comment]
Fixed for 1.11!
