### ISSUE TITLE
Dartdoc 8.0.11 complains about "[this]" on extension types

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#3818]
See [this GitHub actions run](https://github.com/sass/dart-sass/actions/runs/9849486609/job/27193224758?pr=2251), which is full of errors like:

```
error: unresolved doc reference [this]
    from sass.SassApiValue.assertSelector: (file:///home/runner/work/dart-sass/dart-sass/lib/src/value.dart:443:16)
  error: unresolved doc reference [this]
    from sass.SassApiValue.assertSimpleSelector: (file:///home/runner/work/dart-sass/dart-sass/lib/src/value.dart:467:1[8](https://github.com/sass/dart-sass/actions/runs/9849486609/job/27193224758?pr=2251#step:4:9))
  error: unresolved doc reference [this]
    from sass.SassApiValue.assertCompoundSelector: (file:///home/runner/work/dart-sass/dart-sass/lib/src/value.dart:4[9](https://github.com/sass/dart-sass/actions/runs/9849486609/job/27193224758?pr=2251#step:4:10)2:20)
  error: unresolved doc reference [this]
    from sass.SassApiValue.assertComplexSelector: (file:///home/runner/work/dart-sass/dart-sass/lib/src/value.dart:517:19)
```

for code that worked with previous versions of Dartdoc. Note that [the current documentation](https://pub.dev/documentation/sass_api/latest/sass/SassApiValue/assertSelector.html) correctly renders `[this]` as a link to the extension type.

**Comment by ntkme** [comment]
The change was mentioned here: https://github.com/dart-lang/dartdoc/blob/main/CHANGELOG.md#8010

> Remove support for `[this]` as a comment reference. Referring to the
  containing element can be written as `this [Foo]`, and referring to 'this'
  can just be written as `` `this` ``. (#3765)

However, it definitely feels wrong to introduce a breaking change in a patch release.

**Comment by srawlins** [comment]
Yes, sorry. It is intentional. Apologies that it wasn't made in a major version bump. A few more breaking changes should be coming (I guess mainly removing deprecated support), which should be bundled into a 9.0.0 release.

**Comment by srawlins** [comment]
Sorry again, but I'll close this as it is intentional.
