### ISSUE TITLE
Alert blocks do not render on pub.dev generated docs

### ISSUE THREAD

**Issue by JaffaKetchup** [dart-lang/dartdoc#3819]
Not sure if this is the best place for the issue, please transfer if necessary.

When generating locally, the markdown alert blocks appear correctly:

![image](https://github.com/user-attachments/assets/4016bd60-2a4b-4050-9263-c4a1bc59382e)

However, in the [generated documentation](https://pub.dev/documentation/flutter_map_tile_caching/latest/flutter_map_tile_caching/FMTCStore-class.html) for a pub.dev package, the blocks do not render:

![image](https://github.com/user-attachments/assets/4abde9e0-6196-4789-b77c-ac42d3a91d7b)

**Comment by parlough** [comment]
\cc @isoos I know pub.dev manually replicates some of dartdoc's styles, is this just something missing from that?

**Comment by isoos** [comment]
We do support them, so this seems to be a bug. Was there any change in the output format or styles that dardoc is using? We've just released a new site version with `dartdoc 8.0.10`...

**Comment by isoos** [comment]
I've found the culprit: `pub.dev` executes `dartdoc` with the `--sanitize-html` flag, and when that is on, the sanitization removes the alert block's `div` and related styles.

**Comment by srawlins** [comment]
Fixed by https://github.com/dart-lang/dartdoc/pull/3820
