### ISSUE TITLE
Broken links for class members main body vs sidebar

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#3828]
See https://github.com/dart-lang/web/issues/274

From @vsmenon 

If I go here:

https://pub.dev/documentation/web/latest/web/Node-extension-type.html

and click on appendChild under METHODS on the right, I get a 404 error.

Not sure if this is a general bug with extension types.

From @kevmoo 

Weird!

https://pub.dev/documentation/web/latest/web/Node/appendChild.html in the
main body
https://pub.dev/documentation/web/web/Node/appendChild.html on the sidebar

**Comment by kevmoo** [comment]
CC @srawlins

**Comment by srawlins** [comment]
I can reproduce this with local testing. Fix coming.
