### ISSUE TITLE
Try new analyzer flag: parseFunctionBodies

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#383]
Analyzer just landed option for `parseFunctionBodies`, which might speed things up for us, from https://code.google.com/p/dart/source/detail?r=45119

Need analyzer 0.24.4

**Comment by keertip** [comment]
#395

**Comment by keertip** [comment]
On my machine this change has reduced sdk doc gen from 55 secs to 37 secs.

**Comment by sethladd** [comment]
I'll take it! :)  thanks for integrating this.
