### ISSUE TITLE
package:collection's classes are missing "Implemented types"

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#3850]
See [DelegatingIterable](https://pub.dev/documentation/collection/1.19.0/collection/DelegatingIterable-class.html), which indirectly implements Iterable:

```dart
class DelegatingIterable<E> extends _DelegatingIterableBase<E> { ... }
abstract class _DelegatingIterableBase<E> implements Iterable<E> { ... }
```

vs [DelegatingList](https://pub.dev/documentation/collection/1.19.0/collection/DelegatingList-class.html), which directly implements List:

```dart
class DelegatingList<E> extends _DelegatingIterableBase<E> implements List<E> { ... }
abstract class _DelegatingIterableBase<E> implements Iterable<E> { ... }
```

It should be displayed that `DelegatingIterable` implements `Iterable`, even though it is indirect.

**Comment by srawlins** [comment]
@kevmoo if you have a minute, I'd love your opinion.

The issue is that `DelegatingIterable` _extends_ (not _implements_) `_DelegatingIterableBase`, which then _implements_ `Iterable`. I really think this is 100% beside any point; it's an implementation detail. From the consumer's perspective, `DelegatingIterable` implements `Iterable`, and we should document it as such.

**Comment by kevmoo** [comment]
Great question, @srawlins 

My gut here: there should always be a path to all implemented interfaces. But I think it's fine if the route is indirect.

Might be worth seeing what other platforms do: C#, Java, etc

**Comment by srawlins** [comment]
Fixed; I forget when.
