### ISSUE TITLE
Some property pages in the collection package's docs have duplicated content

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#3851]
But not all...

E.g. look at [DelegatingList.length](https://pub.dev/documentation/collection/1.19.0/collection/DelegatingList/length.html). Yikes.

But [DelegatingList.reversed](https://pub.dev/documentation/collection/1.19.0/collection/DelegatingList/reversed.html) is ok. And all methods I can find seem ok, like [DelegatingList.clear()](https://pub.dev/documentation/collection/1.19.0/collection/DelegatingList/clear.html).

**Comment by srawlins** [comment]
OK, I get it. The page is split into "getter" information (docs, attributes, implementation) and "setter" implementation.

api.dart.dev has style with a border between the two, and a much larger margin (e.g. [here](https://api.dart.dev/stable/3.5.1/dart-core/List/length.html)).

@isoos would this be a bug for pub.dev? I guess just keeping stylesheets in sync?

**Comment by isoos** [comment]
@srawlins: I'm not aware of any CSS rule that pub.dev would do to hide that border.

For the dartdoc pages we mostly use the default dartdoc rules and extra CSS files and merge them into one. This is the entry point for compilation:
https://github.com/dart-lang/pub-dev/blob/master/pkg/web_css/lib/dartdoc.scss

There are a few additional rules, but I don't think these are related. In the long term we want to make the styles more uniform between dartdoc pages and regular pub.dev, but it is not yet decided on how we want to approach that.

**Comment by srawlins** [comment]
Ah it's because the style is applied to `section#setter`. dartdoc's `styles.css` contains:

```
section#setter {
  border-top: 1px solid #ddd;
```

But pages on pub have `<div id="setter"`, _not_ `<section id="setter"`. :/ Is this just old? Or does pub rewrite `<section id="setter"`?

* api.dart.dev - _section_ tag - e.g. [List.length](https://api.dart.dev/stable/3.5.1/dart-core/List/length.html)
* pub.dev - _div_ tag - e.g. [DegatingList.length](https://pub.dev/documentation/collection/1.19.0/collection/DelegatingList/length.html)

**Comment by isoos** [comment]
It is possible that we rewrite `<section>` to `<div>` (or rather when rendering we are rendering a slightly different HTML so that it passes a strict sanitization rule). Would it be possible to drop the `section` part from the CSS rule? As the `id` is unique, it wouldn't add much there.
