### ISSUE TITLE
Regression or bug with pub.dev: "failed to load sidebar"

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dartdoc#3859]
Generated dartdocs on pub.dev say:

```
Failed to load sidebar. Visit dart.dev for help troubleshooting.
```

Example: https://pub.dev/documentation/pxl/0.1.0-alpha/pxl/IntPixels-class.html.

**Comment by curiouslaw** [comment]
Add more information on this. This happen on level 4 doc (e.g., `go_router package >  documentation > go_router.dart > GoRoute class`) But not level 2 / 3 doc(e.g., level 3 doc: `go_router package >  documentation > go_router.dart`)

**Comment by srawlins** [comment]
That's unpleasant... thanks for the report!

**Comment by srawlins** [comment]
I can reproduce this locally with `pxl-0.1.0-alpha`. Added some debugging and found there is a child of `Abgr8888` who's `enclosingElement` (`Abgr8888`) has a `href` value of `null`.

**Comment by srawlins** [comment]
Some export issue; `Abgr8888`'s enclosing element is the 'format' library, which does not have an 'href', I guess because it is declared in `lib/src`, but it is exported by `lib/pxl.dart` so...

**Comment by matanlurey** [comment]
Probably worth mentioning this: I see this all over pub.dev (not specific to Pxl).

https://pub.dev/documentation/sector/0.4.0-alpha+2/topics/Grids-topic.html

**Comment by srawlins** [comment]
Yeah probably a wide-ranging regression. I can reproduce this at version 8.0.14 (latest released), but I cannot reproduce at 8.0.13. This was probably introduced with d629e1eacccf11338413d2581818cc9c84f340d9 or maybe 0577ca1d20388bc13ed132bea587991766e3d431.

CC @isoos @sigurdm @jonasfj. I'm prioritizing a fix and release for this bug. You could revert pub to use dartdoc 8.0.13, but maybe I would get out a release before all the docs on pub could be regenerated. So I'll leave that in your hands. I'll keep this issue up-to-date with my progress.

**Comment by isoos** [comment]
What's the expected time for a new release? If it is out tomorrow, we can just roll forward as we have a planned deployment on Thursday.

**Comment by matanlurey** [comment]
Btw not to pile on but it appears search is broken on pub.dev for potentially similar reasons.

**Comment by srawlins** [comment]
Yeah the bug affects / is caused by broken search.

> What's the expected time for a new release?

I'm hoping to have a fix mailed out in a few hours. Published to pub just after that.

**Comment by jonasfj** [comment]
> I'm prioritizing a fix and release for this bug. You could revert pub to use dartdoc 8.0.13, but maybe I would get out a release before all the docs on pub could be regenerated.

Each time we bump `dartdoc`, SDK versions, pana used in analysis and documentation generation we make a new runtimeVersion, we could migrate traffic back to the previous runtimeVersion.

But if we have a fix ready, I think we should just ship new release tomorrow. It doesn't appear as though everything is affected.
