### ISSUE TITLE
Regression: Categories duplicate symbols

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dartdoc#3860]
Two links:

- https://pub.dev/documentation/pxl/0.1.0-alpha/pxl/pxl-library.html
- https://pub.dev/documentation/pxl/0.1.0-alpha/topics/Buffers-topic.html

Former is not a topic/category, and WAI.

Latter is, and duplicates all of the exported symbols:

<img width="138" alt="Screenshot 2024-08-31 at 2 15 56 PM" src="https://github.com/user-attachments/assets/56343ab2-1d00-4ec7-9e04-469e5ac3312f">

**Comment by srawlins** [comment]
I suspect this is another effect of deduplicating exported elements; I believe there is a 'Buffer' class both from the private library in which it is declared, and another from the exporting library.
