### ISSUE TITLE
Top right search bar not functioning correctly

### ISSUE THREAD

**Issue by curiouslaw** [dart-lang/dartdoc#3861]
In the top right search bar, I got this buggy behaviours:
1. When the bar is empty, it always showing hint text of `Loading screen...`
2. When I type search query and click enter, it won't show the result page, but it will refresh the page instead
3. When I make the browser width smaller, the search bar won't resize it's width correctly

Interestingly, all these buggy behaviours don't happen in freezed [documentation page](https://pub.dev/documentation/freezed/latest/builder/freezed.html), where it only consist of one method

*might be related with https://github.com/dart-lang/dartdoc/issues/3859

**Comment by srawlins** [comment]
Thanks for the report; on what pages do you see this buggy behavior?

**Comment by curiouslaw** [comment]
No worries. I think this happens in almost all of the pub.dev API reference page (e.g., for flutter_bloc [documentation page](https://pub.dev/documentation/flutter_bloc/latest/)).

The [freezed documentation page](https://pub.dev/documentation/freezed/latest/builder/freezed.html) with one method which I mention before is a rare exception.
