### ISSUE TITLE
`@template` on extension don't work

### ISSUE THREAD

**Issue by dickermoshe** [dart-lang/dartdoc#3888]
A template tag placed within an extension doesn't get picked up and can't be used elsewhere:
As you can see here, the `baz` macro doesn't work, because it was declared in the extension
```dart
class Foo {
  /// {@macro baz}
  ///
  /// {@macro pink}
  ///
  ///
  ///
  ///
  ///
  ///
  ///
  void bar() {}

  /// {@template pink}
  /// this works
  /// {@endtemplate}
  void pink() {}
}

extension on Foo {
  /// {@template baz}
  /// This does not work
  /// {@endtemplate}
  void baz() {}
}
```

<img width="442" alt="image" src="https://github.com/user-attachments/assets/284d1c54-894c-465d-aa4c-11fc0713264c">

**Comment by srawlins** [comment]
Thanks for the narrow repo and bug report!

**Comment by dickermoshe** [comment]
@srawlins When building a site, the template works 
<img width="950" alt="image" src="https://github.com/user-attachments/assets/a194aadc-e6d5-4525-9a98-e26b38e414de">

I guess this is an issue with the extension

**Comment by dickermoshe** [comment]
Opened this: https://github.com/Dart-Code/Dart-Code/issues/5284

**Comment by DanTup** [comment]
This is actually an SDK issue. I didn't realise it was raised here too and worked on a fix https://dart-review.googlesource.com/c/sdk/+/386840 - hope I didn't duplicate any effort if you were looking at this @srawlins!

**Comment by srawlins** [comment]
I've been sick so no wasted time on my side 😅 . Thanks Danny and @dickermoshe for following up!
