### ISSUE TITLE
Search on https://api.dart.dev/dev doesn't work

### ISSUE THREAD

**Issue by mkustermann** [dart-lang/dartdoc#3889]
The search field on https://api.dart.dev/dev doesn't work. It doesn't register the mouse click and one cannot enter text into it. Note this is specific to `/dev` and `/stable` seems to work.

In the console it shows an error
```
js_helper.dart:1198 Uncaught Error: TypeError: null: type 'minified:aM' is not a subtype of type 'String'
    at Object.a (js_helper.dart:1198:19)
    at Object.fz (rti.dart:1654:3)
    at cM.hD (search.dart:143:29)
    at ae.C (iterable.dart:425:29)
    at an.m (iterable.dart:354:5)
    at Object.hM (core_patch.dart:367:5)
    at Object.eW (core_patch.dart:348:39)
    at iterable.dart:224:7
    at dR.a (async_patch.dart:303:19)
    at dR.$2 (async_patch.dart:328:23)
```

/cc @devoncarew do you know who can take a look at this?

**Comment by devoncarew** [comment]
I assume the stacktrace is coming from dartdoc's embedded web app; cc @srawlins.

Sam, we may also consider less name mangling for the compiled web app? I'm not sure what the size tradeoff is.

**Comment by parlough** [comment]
@srawlins Was this fixed by https://github.com/dart-lang/dartdoc/pull/3877? Search seems to work on api.dart.dev/main.

**Comment by srawlins** [comment]
I think so. I wish I could see when each `dev/` docs was built and with what version of dartdoc, but I don't know how.

**Comment by parlough** [comment]
> I wish I could see when each dev/ docs was built and with what version of dartdoc

Perhaps there is a more direct way (or we should add one), but the footer does include the SDK version (currently 3.6.0-270.0.dev) which the DEPS file specifies dartdoc at 8100ccf1c1b8a462fd08adcc0cfd8db0f941f44a which doesn't include that fix.

**Comment by srawlins** [comment]
Today it seems to work. Can someone else confirm? (In case it it just some pages)
