### ISSUE TITLE
Why is my image not responsive on gh-pages but is on pub.dev docs??

### ISSUE THREAD

**Issue by ArnavK-09** [dart-lang/dartdoc#3904]
## gh-pages

![Screenshot_2024-10-11-00-07-13-47_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/6970e2cc-721d-4604-8e69-0cf0112ebb71)

## pub.dev hosted docs

![Screenshot_2024-10-11-00-07-40-95_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/53efbea0-336d-4faf-9309-48332e06abd7)

**Comment by srawlins** [comment]
@ArnavK-09 thanks for filing an issue. We'd need to see your markdown source in order to know why. 🤷

**Comment by ArnavK-09** [comment]
> @ArnavK-09 thanks for filing an issue. We'd need to see your markdown source in order to know why. 🤷

### here's topmost part of my [readme](https://github.com/ArnavK-09/mdb_dart/tree/main?tab=readme-ov-file#-minds-dart-) 


```markdown
<h1 align="center">🎯 Minds Dart 🎯</h1>
<br />
<p align="center">
    <img alt="hero" width="450" src="https://cdn.prod.website-files.com/62a8755be8bcc86e6307def8/634af4c76088703e4422ed06_Mindsdb%20white%20logo%20prev-p-500.jpg" />
</p>
<br /><br />
<p align="center">
<a href="https://pub.dev/packages/mdb_dart">
<img alt="pub verion" src="https://img.shields.io/pub/v/mdb_dart.svg">
</a>
    <a href="https://pub.dev/packages/mdb_dart">
<img alt="repo size" src="https://img.shields.io/github/repo-size/ArnavK-09/mdb_dart?color=green">
        </a>    <a href="https://github.com/ArnavK-09/mdb_dart/releases">
<img alt="repo release" src="https://img.shields.io/github/v/release/ArnavK-09/mdb_dart">   </a> 
      <a href="https://github.com/ArnavK-09/mdb_dart/actions/workflows/tests.yaml">
<img alt="Tests" src="https://github.com/ArnavK-09/mdb_dart/actions/workflows/tests.yaml/badge.svg"> </a> 
          <a href="https://github.com/ArnavK-09/mdb_dart/blob/main/LICENSE">
<img alt="license" src="https://img.shields.io/badge/License-Mozilla%20Public%20License%202.0-orange.svg"> </a> 
</p>

> [!NOTE]
>
> A powerful and intuitive **Dart SDK** for interacting with the **Minds AI API**. Seamlessly integrate machine learning capabilities into your Dart applications!
```

**Comment by ArnavK-09** [comment]
i notices this styling is missing from my github pages hosted docs, but present on pub.docs, do i need to change anything in dart doc cmd [action](https://github.com/ArnavK-09/mdb_dart/blob/main/.github/workflows/docs.yaml)??


```css
.markdown-body img {
  max-width: 100%;
  box-sizing: content-box;
}```

**Comment by srawlins** [comment]
I'm not sure why pub.dev applies a `.markdown-body` style. But if GitHub doesn't, there is nothing we can do about that. You might be able to apply styles inline in an `img` tag with `style=` but I'm not sure.

**Comment by ArnavK-09** [comment]
ohk, thanks, i think i should abandon ghpages and use pub only for docs!
thanks mate
