### ISSUE TITLE
Extensions on nullable class are missing from generated docs

### ISSUE THREAD

**Issue by loic-sharma** [dart-lang/dartdoc#3907]
# Summary
If an extension is on `T?`, dart doc will not include it on `T`’s API reference. Follow-up to https://github.com/dart-lang/dartdoc/issues/2021

# Repro

See: https://github.com/loic-sharma/static_extension_on_nullable

Create a library with an extension methods on `Widget` and `Widget?`:

```dart
class Widget {}

extension NullableDecorators on Widget? {
  Widget padding() => Widget();
}

extension Decorators on Widget {
  Widget expanded() => Widget();
}
```

## Expected result

`dart doc` includes both the `.padding` and `.expanded` extension methods on the `Widget` class.

## Actual result

The `.padding` extension method is missing:

![image](https://github.com/user-attachments/assets/9a4ece02-16d4-4833-bc5b-dbe2c300a508)

**Comment by srawlins** [comment]
Good catch!
