### ISSUE TITLE
Function types with multiple args shouldn't be split across multiple lines

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#392]
![screen shot 2015-04-14 at 4 22 55 pm](https://cloud.githubusercontent.com/assets/5479/7149458/7ec952b6-e2c2-11e4-86c0-0d3e3e63e80d.png)

**Comment by sethladd** [comment]
taking a look at this one now

**Comment by sethladd** [comment]
Once https://github.com/dart-lang/dartdoc/issues/403 lands, I can then play with the formatting of this part.

**Comment by sethladd** [comment]
PR https://github.com/dart-lang/dartdoc/pull/404 fixes this. Thanks @polux !

**Comment by polux** [comment]
Ahah, didn't mean to fix this. Glad I did by accident :)
