### ISSUE TITLE
Broken links on dev after the change to remove index.html pages

### ISSUE THREAD

**Issue by athomas** [dart-lang/dartdoc#3933]
Links on https://api.dart.dev/dev/latest/dart-core/ are broken.

Example `BigInt` (note the extra dart-core): https://api.dart.dev/dev/latest/dart-core/dart-core/BigInt-class.html.

The backend bucket serving the site is configured with a main page suffix which is likely the reason for the broken links:
https://cloud.google.com/storage/docs/hosting-static-website#specialty-pages

How is this meant to be working? Should the loadbalancer serve the `index.html` when it gets a request for `https://api.dart.dev/dev/latest/dart-core/`? Would that work for older pages as well?

Note: it's likely infeasible to add special rules for versions in the load balancer so we'd have to find some config/dartdoc output combination that makes all stable versions work or do a data migration of the old content.

/cc @kevmoo @srawlins

**Comment by srawlins** [comment]
This was surprising as I thought we had sorted this out 😅 . I bisected down to 4d461298345722c92f7f54b3a58c9ee3250d6bc9 as the culprit commit. Will work on a fix.
