### ISSUE TITLE
The generated library URLs need an ending slash

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#3936]
The documentation URLs for libraries generated by 8.3.0 are missing an ending slash. When hosted, this breaks the sidebar and all relative links, as the base-uri reference is one directory up.

To fix that, the hosting needs to redirect from `/library-x` to `/library-x/`, and that is one extra request (extra latency) that could have been spared with the ending slash.

Related note: The change of the library URLs (#3895) is breaking pub.dev in multiple ways. We should explore how we could define a somewhat future-proof way to prevent or mitigate such disruptions. (We should also prevent situations where we need the beta SDK to analyze or generate sources for packages requiring the same beta SDK, but that's another discussion.)

**Comment by srawlins** [comment]
I tested the new URLs only with serving the HTML files on disk via the `dhttpd` package, which I think behaves like vanilla Apache, and loads `/index.html` if it is available. But I guess this is not universal behavior. We can instead link to `library-x/`.

Thanks for the report, @isoos
