### ISSUE TITLE
Automate publishing of package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#398]
Need to also bump version in library and the pubspec.yaml

**Comment by sethladd** [comment]
Might use https://github.com/seaneagan/den for this, but not sure it has everything I need. I opened a bunch of bugs and questions.

**Comment by sethladd** [comment]
den does have a way to bump for the build (+1 on the build number)

**Comment by seaneagan** [comment]
http://www.dartdocs.org/documentation/den_api/0.1.0/index.html#den_api/den_api.Pubspec@id_bump

`(await Pubspec.load()).bump(ReleaseType.build)` should do the trick :).

**Comment by sethladd** [comment]
nice

**Comment by sethladd** [comment]
Will work on this now.

**Comment by sethladd** [comment]
PR https://github.com/dart-lang/dartdoc/pull/436

cc @keertip @devoncarew for FYI

**Comment by sethladd** [comment]
Yay!

Thanks to @seaneagan for den.
