### ISSUE TITLE
Performance regression when building core SDK docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#400]
On my machine, it used to take ~50 seconds. Now it's taking ~130 seconds.

**Comment by keertip** [comment]
@sethladd  how are you running it? This is with master?

**Comment by sethladd** [comment]
Yup. Turns out, that we do need `analyzeFunctionBodies` turned on, so we can get the sources for the methods/functions.

Regardless, I saw the regression after I updated and that property was set to false.

I'm going to keep a very close eye on the performance. The Travis builds are recording the SDK doc generation times now.

**Comment by sethladd** [comment]
I think this was triggered by `element.node.toSource()`. I removed that and times went back down to "normal".

**Comment by sethladd** [comment]
Closing for now.
