### ISSUE TITLE
Display source for functions and methods

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#403]
What else should we show source for?

This would be for the dedicated pages, not the class or library "index" pages.

**Comment by sethladd** [comment]
Check it out. I use dart formatter to make the source look pretty :)

**Comment by sethladd** [comment]
![screen shot 2015-04-16 at 5 30 32 pm](https://cloud.githubusercontent.com/assets/5479/7194104/496140e6-e45e-11e4-8967-7dd44888c4f8.png)

**Comment by sethladd** [comment]
Blocked by https://github.com/dart-lang/dartdoc/issues/405

**Comment by sethladd** [comment]
Making progress:

![screen shot 2015-07-21 at 3 22 14 pm](https://cloud.githubusercontent.com/assets/5479/8813969/70bf57d2-2fbc-11e5-8b68-3f46030d82f7.png)

**Comment by sethladd** [comment]
Dupe of https://github.com/dart-lang/dartdoc/issues/11

**Comment by polux** [comment]
Wow, looks awesome!
