### ISSUE TITLE
Libraries do not have their source set

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#405]
This returns null:

```
      String eSource =
          (source != null) ? source.substring(e.node.offset, e.node.end) : null;
```

Looks like the source is not set for the library.

**Comment by keertip** [comment]
#410 fixes it for all packages, except SDK.

**Comment by sethladd** [comment]
Closing. We no longer pass source into constructors.

**Comment by polux** [comment]
Does it mean there won't be a source link in the generated doc?

**Comment by sethladd** [comment]
Not immediately. We'd love some help on this.

**Comment by polux** [comment]
Could you please quickly point me to what is blocking so I know where to look if I want to help? Or is it just that you deprioritized this feature but there's nothing preventing from doing it?

**Comment by polux** [comment]
By "quickly" I mean "don't spend too much time on it" not "do it fast" :) Feel free to tell me you don't have time right now.

**Comment by keertip** [comment]
This is not on our priority list right now, there is nothing blocking it.

**Comment by polux** [comment]
Thanks!

**Comment by sethladd** [comment]
If you can help with this feature, we'll be happy to reopen and assign to you.

When we looked at implementing it "for real", we saw a lot of refactoring around how we create new Library instances. tldr: we create too many instances, all over the place. To get this source code feature correct, you'd probably also want to create a registry of Library instances, such that there is a single Library instance for a library from the analyzer.

If you can do that, you'll not only deliver "display source code" but also significantly clean up the code :)

**Comment by polux** [comment]
I can't promise anything, it'll depend on my free time. But if I have some I'll give it a try and reopen this issue. Thank you for explaining what needs to be done!
