### ISSUE TITLE
Display enum with lots of values nicely

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#407]
![screen shot 2015-04-17 at 2 47 43 pm](https://cloud.githubusercontent.com/assets/2192312/7211574/ea659d04-e510-11e4-9d41-88f59028d3a6.png)

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
Replaced by https://github.com/dart-lang/dartdoc/issues/421
