### ISSUE TITLE
generic parameters on argument types should be visible

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#408]
```dart
foo(List<int> items)
```

The docs should show `List<int>` instead `List<E>`

Example input
![screen shot 2015-04-19 at 2 25 42 pm](https://cloud.githubusercontent.com/assets/17034/7221443/1d19ecd8-e6a0-11e4-92be-d2b0c2a7255c.png)

Example output
![screen shot 2015-04-19 at 2 25 37 pm](https://cloud.githubusercontent.com/assets/17034/7221444/21f0ecc0-e6a0-11e4-9588-cabe8c13464e.png)

**Comment by sethladd** [comment]
@keertip can you take a look at this one?

**Comment by keertip** [comment]
Yes, will take a look.

**Comment by keertip** [comment]
Have not been able to figure out why this is happening - looks like the analyzer is unable to resolve the reference to Binding - the parameter is assigned a dynamic type.  Need to look into it some more.

**Comment by sethladd** [comment]
IIR there's a difference between Types and Elements. The type of a thing isn't always what we want... we sometimes want the the thing the developer said in the code. Analyzer folks might have more insight here.

Thanks for taking a look!

**Comment by keertip** [comment]
Talking to the Analyzer folks :) Trying to figure out why it is not being resolved in this particular case.

**Comment by sethladd** [comment]
Any news here from the analyzer folks? Is there an analyzer bug that we can follow?

**Comment by keertip** [comment]
Will take another look.

**Comment by keertip** [comment]
The method signature has changed, and dartdoc does the right thing now. 

Closing for now, reopen if you see this issue again.
