### ISSUE TITLE
Optional positional arguments should be shown in brackets

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#409]
Input
![screen shot 2015-04-19 at 2 25 42 pm](https://cloud.githubusercontent.com/assets/17034/7221451/4bae10a6-e6a0-11e4-8ca2-07e538ec5c73.png)

Output
![screen shot 2015-04-19 at 2 25 37 pm](https://cloud.githubusercontent.com/assets/17034/7221449/49f64e9a-e6a0-11e4-8176-0d4603efe5a6.png)

Expect to see brackets around the last two arguments.

**Comment by keertip** [comment]
#429
