### ISSUE TITLE
Property type - readonly etc is different on library page and property page

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#411]
![screen shot 2015-04-20 at 9 07 38 am](https://cloud.githubusercontent.com/assets/2192312/7234555/d03e03ca-e73c-11e4-8031-8e3db6360554.png)

![screen shot 2015-04-20 at 9 07 55 am](https://cloud.githubusercontent.com/assets/2192312/7234564/d696fad8-e73c-11e4-956d-edd169911580.png)

**Comment by sethladd** [comment]
I'll take this one

**Comment by sethladd** [comment]
Handled in PR https://github.com/dart-lang/dartdoc/pull/434
