### ISSUE TITLE
Add obvious marker for items in index pages

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#412]
To better distinguish methods, functions, etc.

**Comment by sethladd** [comment]
![screen shot 2015-04-20 at 6 30 38 pm](https://cloud.githubusercontent.com/assets/5479/7244105/46453e3c-e78b-11e4-8492-3175f5b120a7.png)


What about something like this?

(ignore the poor font in the circle, imagine that was Roboto)

**Comment by sethladd** [comment]
cc @devoncarew @keertip

**Comment by sethladd** [comment]
With the font fixed.

![screen shot 2015-04-20 at 6 59 17 pm](https://cloud.githubusercontent.com/assets/5479/7244368/4cc51b3e-e78f-11e4-8fdc-c5bdc9602322.png)

**Comment by sethladd** [comment]
cc @kevmoo for thoughts

**Comment by kevmoo** [comment]
Better, I think. I think this will just take a bit of user education.

**Comment by devoncarew** [comment]
It'll definitely help identify what they are. And I like the increased indent the image gives the line items; it helps group the functions together under the "Function" category.

It would be great to have some a/b/c comparisons with some other ways of displaying class functions/members.

**Comment by sethladd** [comment]
Material Design really likes keylines (vertical alignment). It's a happy accident that the function names are indented under the header Function. Our design won't do indention to indicate grouping.

I will try this technique for the other listing on this index page.

**Comment by sethladd** [comment]
No longer planned... but we could do something in the future. (also, this worked was stalled due to a bug in chrome)
