### ISSUE TITLE
Remove the generation date

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#414]
I see this at the bottom of the docs: `Generated on: April 20 2015`. You should consider removing this. It's nice for the docs to be stable - that the exact same output will be generated for the same input files. This won't be the case if you stamp the files with a time/date.

**Comment by sethladd** [comment]
Hm, perhaps a pubspec version number is sufficient here.

**Comment by sethladd** [comment]
Removed! https://github.com/dart-lang/dartdoc/pull/420
