### ISSUE TITLE
Remove the Suggestions and Comments link

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#415]
Doesn't go anywhere...

![screen shot 2015-04-20 at 1 38 31 pm](https://cloud.githubusercontent.com/assets/1269969/7239953/71b7b794-e762-11e4-8f07-79cd65f62c4b.png)

**Comment by sethladd** [comment]
Good catch. Now that we're open on github, we can link there.

However, I think we're going to remove this link. It's confusing... comments for the API? comments for the library? for the dartdoc output?

**Comment by sethladd** [comment]
Done and done! https://github.com/dart-lang/dartdoc/pull/420
