### ISSUE TITLE
consider removing the subtitle line

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#416]
![screen shot 2015-04-20 at 1 40 48 pm](https://cloud.githubusercontent.com/assets/1269969/7240005/d002fd54-e762-11e4-9a57-5063729bfc86.png)

The `Welcome to the Dart API...` line doesn't add much; I think just having the large title looks better,

**Comment by sethladd** [comment]
The one-line descriptions for the libraries works well in the header, in general.

We could change the one-line description for the core libraries, though. Please open a bug on the core SDK.

I don't think we want to special-case this in the dartdoc tool, though.

Thanks for the report, though!
