### ISSUE TITLE
increase line height for code blocks

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#417]
The general text font is a tiny bit too small. It's 14px; 11pt reads better (at least on my mac).

Also, the code font looks squished:

![screen shot 2015-04-20 at 1 42 20 pm](https://cloud.githubusercontent.com/assets/1269969/7240036/138d1b90-e763-11e4-8344-36c82e25402f.png)

consider removing the override from the bootstrap defaults, and adding a 4px rounded border to soften things a bit.

**Comment by sethladd** [comment]
14px is what material design seems to recommend.

We can increase the line height for code blocks.

**Comment by sethladd** [comment]
Can you define "squished" ?

**Comment by devoncarew** [comment]
squished:

![screen shot 2015-04-20 at 1 42 20 pm](https://cloud.githubusercontent.com/assets/1269969/7240720/08cadb5c-e768-11e4-9872-7bf3d72b3c8c.png)

vs unsquished:

![screen shot 2015-04-20 at 2 18 24 pm](https://cloud.githubusercontent.com/assets/1269969/7240716/00c39c5a-e768-11e4-941f-664d46624a63.png)

The line height is a bit too small, and the font just looks squished vertically.

**Comment by devoncarew** [comment]
It's easier to see if you toggle between the two in devtools.

**Comment by sethladd** [comment]
I agree, line height can be increased for code blocks.

**Comment by devoncarew** [comment]
I removed this guy: https://github.com/dart-lang/dartdoc/blob/master/lib/resources/styles.css#L78. The fallback (in bootstrap I think) looks good.

**Comment by sethladd** [comment]
Source code pro is the "new standard". Will increase the line height and re-evaluate.

**Comment by sethladd** [comment]
Increased to 1.4 line height. Let's give this a shot. https://github.com/dart-lang/dartdoc/pull/419
