### ISSUE TITLE
sdk docs h1 incorrect

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#423]
The docs for the SDK say `Dart API Reference package` at the top of the page; it shouldn't say "package".

**Comment by sethladd** [comment]
Good catch. I guess we'll have to special case this one.

**Comment by sethladd** [comment]
Package is no longer appended.

![screen shot 2015-04-22 at 1 52 09 pm](https://cloud.githubusercontent.com/assets/5479/7285060/b7ec5c34-e8f6-11e4-9f02-a5a1255fcc77.png)

**Comment by sethladd** [comment]
(ignore the 'dartdoc' underneath the title. I didn't set the README)

**Comment by sethladd** [comment]
PR at https://github.com/dart-lang/dartdoc/pull/430
