### ISSUE TITLE
Option to sort elements alphabetically in the UI

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#425]
https://github.com/dart-lang/dartdoc/issues/197

If a dev wants their code to follow code order, great.

Most devs don't think about it.

Most doc users want items sorted.

**Comment by sethladd** [comment]
Talking to Kevin, the use case is: "I'm looking for a name that I think exists. I want to jump to the list where I think the name might be, to validate if the name exists"

**Comment by sethladd** [comment]
Renamed issue to make it an option. We want to default to lexical ordering. The developer might have had a reason to order the code in a certain way.

Let the UI re-order, as an opt-in behavior by the user.

**Comment by seaneagan** [comment]
+1 for alphabetic by default, makes it easier to find stuff.

**Comment by seaneagan** [comment]
Another reasons, you really can't do full source order anyways, since members are broken down into sections (constructors, methods, properties).

**Comment by sethladd** [comment]
We're unlikely to make this an option. Names are alphabetized now.

**Comment by kevmoo** [comment]
Wonderful! :metal:
