### ISSUE TITLE
Omit <dynamic> from generics

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#454]
If we have a generic that is just `Iterable<dynamic>`, we can omit the `<dynamic>` part for brevity.

From the Map docs:

![screen shot 2015-05-05 at 8 27 32 pm](https://cloud.githubusercontent.com/assets/5479/7487095/4e5881ca-f365-11e4-928b-34cd98a0d52c.png)

**Comment by keertip** [comment]
fixed in #458
