### ISSUE TITLE
links using @link annotation not resolved

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#457]
Some docs use @link for links. dartdoc should resolve them, and if that is not possible, at least not show the annotation in the generated docs.

![screen shot 2015-05-07 at 8 27 09 am](https://cloud.githubusercontent.com/assets/2192312/7519688/744d253e-f496-11e4-9672-8ced7371f85b.png)

**Comment by sethladd** [comment]
This is news to me. :( Where did they come from? That's not a dart doc thing, is it?

**Comment by keertip** [comment]
Yes, it's not a dartdoc thing. It's in the angular 2 package.

**Comment by sethladd** [comment]
I'm not sure we need to resolve these yet. If we start resolving them, we're implicitly supporting them. Until there's a lot of evidence that they are widely used, this feels like a low priority.

**Comment by sethladd** [comment]
We don't plan on doing anything special here.
