### ISSUE TITLE
strange styles on home page (ie. README.md)

### ISSUE THREAD

**Issue by a14n** [dart-lang/dartdoc#463]
The styles of the titles on the `docs/index.html` page looks strange. For instance the `font-size` are not ordered and some padding/margin are really small :

- h1 has a computed `font-size: 24px`
- h2 has a computed `font-size: 20px`
- h3 has a computed `font-size: 24px`
- h4 has a computed `font-size: 18px`

Test done with `dartdoc-0.0.1+10` on [dart-ghpages-generator](https://github.com/a14n/dart-ghpages-generator).

**Comment by sethladd** [comment]
Thanks for the report! Could you please take a screenshot?

**Comment by a14n** [comment]
On the screenshot, `Usage` is `<h2>` and `Running it` is `<h3>` but the `<h2>` is smaller.

![capture du 2015-05-12 17 50 35](https://cloud.githubusercontent.com/assets/1206632/7591663/79f64b7c-f8cf-11e4-8d00-f05549298f08.png)

**Comment by sethladd** [comment]
Ah, gotcha! Good catch. The header tags inside markdown need to be tweaked. Thanks!

**Comment by sethladd** [comment]
taking a look

**Comment by sethladd** [comment]
A little bit better:

![screen shot 2015-05-13 at 2 47 51 pm](https://cloud.githubusercontent.com/assets/5479/7621876/120776fc-f97f-11e4-9695-ede3544db88d.png)

**Comment by sethladd** [comment]
PR https://github.com/dart-lang/dartdoc/pull/467

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by a14n** [comment]
Thanks, it's better for `font-size`.

The titles are still not really visible at first look. Is it possible to add some spaces over and/or under `<h>` and increase their `font-weight` ? Something like the titles on  https://www.dartlang.org/tools/pub/cmd/ .

**Comment by sethladd** [comment]
We could add some padding to the headers, sure.
