### ISSUE TITLE
Please widen the dependency on logging

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dartdoc#464]
I added the package to my project and logging got downgraded from 0.11.1 to 0.9.3

**Comment by zoechi** [comment]
I just saw in the README that I don't need to add it to my project but instead global activate it. Note to self "read README first" ;-). Maybe you want to widen it anyway otherwise just close.

**Comment by sethladd** [comment]
We should probably upgrade logging anyway. I'll take a look.

But yes, you shouldn't have to directly depend on dartdoc. :)

**Comment by sethladd** [comment]
Covered in https://github.com/dart-lang/dartdoc/pull/466
