### ISSUE TITLE
members of exported libraries are shown like part of the exporting library

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dartdoc#465]
```
library bwu_docker;

export 'src/remote_api.dart';
export 'src/data_structures.dart';
```
In the generated docs it looks like the members of library `remote_api` and `data_structures` are members of library `remote_api`.

Is this intentional?

**Comment by sethladd** [comment]
Thanks for the report. Yes, it's intentional. When library A exports library B, a consumer of A will see all of B's names.

cc @kevmoo

**Comment by kevmoo** [comment]
Yup. @zoechi do you have another expectation?

**Comment by zoechi** [comment]
I admit I expected them to be presented like they are organized in the source files with their original library name. I  guess I just need to get familiar with the way dartdog presents the classes.

**Comment by sethladd** [comment]
We're trying to provide a more logical view of your code. Another example of this: the way we display properties in dartdoc is a logical view.
