### ISSUE TITLE
The --sdk-docs is an option, not a flag 

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#468]
If you use --sdk-docs, you want ONLY sdk-docs. If you omit the arg from the command line, that's the same as saying --no-sdk-docs.

**Comment by sethladd** [comment]
PR is https://github.com/dart-lang/dartdoc/pull/469

**Comment by keertip** [comment]
@sethladd  Yes, and "option" in the `ArgParser` was just an implementation detail. The flag did just what you wanted. Now `dartdoc` is expecting a value after `--sdk-docs`, was that your intention?

**Comment by sethladd** [comment]
Doh! Sorry. Fixing.

**Comment by sethladd** [comment]
Fixed! https://github.com/dart-lang/dartdoc/pull/471

**Comment by keertip** [comment]
Thanks!
