### ISSUE TITLE
dartdoc doesn't generate if there's a `docs` directory present

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#472]
The first time dartdoc is run, it generates into `docs`. The 2nd time, it fails with the message `Warning: output directory exists: docs`. I'd want it to run the same each time; it should just generate into `docs` whether or not the directory is initially present.

dartdoc version: 0.0.1+10

**Comment by sethladd** [comment]
I disagree. What if you manually created the output directory, and manually put some files in there. And then you run dartdoc and it overwrites your files. :(

Perhaps we could add a --overwrite option?

Closing for now. We've chosen the safer option. But maybe this was the wrong assumption. Are there examples of tools that overwrite files by default?

**Comment by devoncarew** [comment]
It'd want the runs to be idempotent. It should do the same thing on the same input. The fact that dartdoc changes the state enough that it can't run the 2nd time is non-intuitive.

**Comment by sethladd** [comment]
But what if it didn't create that output directory in the first place? Let's say that you created a docs/ dir and put an index.html file in there. And then you ran our tool and it overwrote your index.html.

**Comment by a14n** [comment]
BTW the [documentation section in the Pub Package Layout Conventions](https://www.dartlang.org/tools/pub/package-layout.html#documentation) encourages to put the generated doc under `doc` :

>Instead, this is for tutorials, guides, and other hand-authored documentation _in addition to_ generated API references.

It could be worth to standardize the place to find the generated API ref.

**Comment by sethladd** [comment]
Not a bad idea! Maybe generate into apidoc ?

**Comment by seaneagan** [comment]
But it's bad practice to commit / publish generated docs, right?  I think we'd need to at least co-encourage adding `apidoc` to .gitignore.

**Comment by seaneagan** [comment]
Also, an alternative to `apidoc` could be `doc/api` or `doc/gen`.

**Comment by a14n** [comment]
@seaneagan I wondered the same thing. But what will append when a langage breaking change makes that dartdoc cannot generate the api doc for old code ?

**Comment by a14n** [comment]
+1 for `doc/api`

**Comment by sethladd** [comment]
Where we put it is one question.

I'm still curious about the root issue: should dartdoc overwrite files, or should it warn the user if the directory it's trying to write into isn't empty?

**Comment by a14n** [comment]
Overwriting files is fine here because the generated directory should stay sync with the sources. Doing changes in the generated api doc looks really strange.

**Comment by sethladd** [comment]
But remember, you can do this: `dartdoc --output=some_dir` ... would you want dartdoc to warn you if the some_dir already exists and has files in it?

**Comment by a14n** [comment]
It's similar to `pub build --output=some_existing_dir`. Although I don't know what pub will do.

**Comment by a14n** [comment]
A quick test with `pub build` confirms it overwrites the directory.

**Comment by sethladd** [comment]
If I'm the only one that doesn't want my tools to overwrite the directory, then I'll accept that and we can change dartdoc. This isn't one of the sacred things :)

**Comment by sethladd** [comment]
Pull requests welcome!

**Comment by sethladd** [comment]
We now generate docs into docs/ even if docs/ exists. :)
