### ISSUE TITLE
font seems too small

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#473]
The paragraph font for my generated docs is:

```
font-family: Roboto, sans-serif;
font-size: 14px;
```

It seems too small when I'm reading it. This was for the docs that corresponded to my readme.

Somewhat related, the color for the paragraph font is inconsistent with text for the library summary. The readme color is rgb(177, 177, 177) and the library summary (in a `dd` element) is rgb(51, 51, 51).

![screen shot 2015-05-14 at 1 26 14 pm](https://cloud.githubusercontent.com/assets/1269969/7641177/d786ff7a-fa3c-11e4-8b8d-67a5a8a3d434.png)

vs:

![screen shot 2015-05-14 at 1 26 22 pm](https://cloud.githubusercontent.com/assets/1269969/7641181/dddd5f90-fa3c-11e4-8d1c-5defd377f732.png)

**Comment by sethladd** [comment]
I think Devon embiggened it.

@devoncarew can we close this?

**Comment by devoncarew** [comment]
Yup, they're slightly bigger now, and consistent.
