### ISSUE TITLE
method summaries look odd

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#474]
![screen shot 2015-05-14 at 1 27 47 pm](https://cloud.githubusercontent.com/assets/1269969/7641205/12a6b410-fa3d-11e4-9f5b-65d2f04aaf29.png)

The `()`'s are orphaned.

**Comment by sethladd** [comment]
I guess in the cases where a constructor doesn't have args, we could omit the empty parens. We could move the parens up to the previous line, too.

**Comment by keertip** [comment]
Moving the parens up to previous line would work.

**Comment by sethladd** [comment]
Would like to try a few things here.

**Comment by sethladd** [comment]
Making empty parens a bit nicer.

https://github.com/dart-lang/dartdoc/pull/575

![screen shot 2015-06-11 at 3 57 52 pm](https://cloud.githubusercontent.com/assets/5479/8108787/e4e15310-1052-11e5-9833-85c3cc33cc0a.png)

**Comment by sethladd** [comment]
In the meantime, if you want the signature next to the name, it'll look like this:

![screen shot 2015-06-11 at 4 03 43 pm](https://cloud.githubusercontent.com/assets/5479/8108875/8adea650-1053-11e5-82c8-60baec0e890b.png)
![screen shot 2015-06-11 at 4 03 34 pm](https://cloud.githubusercontent.com/assets/5479/8108876/8ae3fc72-1053-11e5-9b63-4111bdea8cb7.png)

**Comment by keertip** [comment]
@sethladd, prefer having all the params on one line rather than the split.

**Comment by sethladd** [comment]
Sure, we can do that. Help me understand what you like about it?

**Comment by sethladd** [comment]
Started

**Comment by sethladd** [comment]
With the PR, it now looks like:

![screen shot 2015-06-12 at 2 12 53 pm](https://cloud.githubusercontent.com/assets/5479/8129808/2af806d6-110d-11e5-935b-b34ce09bb7f1.png)

**Comment by sethladd** [comment]
CL https://chromiumcodereview.appspot.com/1184733002/

**Comment by sethladd** [comment]
Fixed!
