### ISSUE TITLE
so many files

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#475]
So very many files; each one of my ctors - with no args and no dartdoc - generate into their own file.

**Comment by sethladd** [comment]
Yes. We made a choice to allow for each "named thing" to get a file. This gives us lots of space to put more examples and comments.

Not sure how this impacts you. Can you clarify?

Other doc systems do this. See MDN, for example. And the PHP docs.

**Comment by sethladd** [comment]
This one is by design. We want to allow for a comments system, which will thrive if each "thing" is a page.

A single page per "thing" also gives us a lot more room for:

* examples
* metadata
* comments
* future expansion
