### ISSUE TITLE
Add git tags for the published versions

### ISSUE THREAD

**Issue by a14n** [dart-lang/dartdoc#482]
On [the tags page](https://github.com/dart-lang/dartdoc/tags) we should see the tags corresponding to [the versions on pub](https://pub.dartlang.org/packages/dartdoc).

```
git tag v0.0.1+10 $sha
git push origin --tags
```

**Comment by sethladd** [comment]
probably true. There's a grinder task that tries to be the release workflow. Can you help update that or create a new grinder task that can do all the things we want to do when releasing, including pushing to pub? That would be a big help.

**Comment by seaneagan** [comment]
I think eventually it can look like:

```dart
@Task
publish(String releaseType) {
  new PubApp.global('den').run[['bump', releaseType];
  Pub.publish();
}
```

but first we'll need:

https://github.com/seaneagan/unscripted/issues/21
https://github.com/google/grinder.dart/issues/116
https://github.com/google/grinder.dart/issues/203

**Comment by sethladd** [comment]
Thanks for the analysis. Please land those patches so we can automate the whole thing :)

**Comment by keertip** [comment]
We have a manual process for now. Can automate when all the necessary bits are in place.
