### ISSUE TITLE
sketch of 3rd party doc generators

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#483]
I'd like to be able to use a 3rd party backend to dartdoc. Here's a sketch of how it could work:

    dartdoc --generator=dartdoc_xmlgen

Dartdoc would check the pub cache for a `dartdoc_xmlgen` package. It could do a pub global activate of `dartdoc_xmlgen` if it wasn't already installed. It would then parse the source files, create the in-memory model, and hand the model off to the backend (along with info about where the out directory is) in order to generate the doc files.  Not sure in this scenario if `dartdoc_xmlgen` is an isolate based plugin mechanism or involves some codegen in order to bootstrap dartdoc+dartdoc_xmlgen.

**Comment by sethladd** [comment]
Neat!

Can you allow someone to pass in multiple generators?

We should try isolates first... and see if the perf of serializing the entire model is acceptable.

**Comment by devoncarew** [comment]
> Can you allow someone to pass in multiple generators?

Hmm, maybe, but they could also just run the tool a few times.

**Comment by sethladd** [comment]
But then I need to spin up the analyzer a few times. :(

**Comment by bwilkerson** [comment]
Another use for plugins! Perhaps analyzer won't be the only trail-blazer in this area. Let's make sure we coordinate; no point in both teams learning the same lessons twice.

**Comment by sethladd** [comment]
There's already a plugins package here: https://pub.dartlang.org/packages/plugins

**Comment by keertip** [comment]
If we can use the plugin model, that would be the way to go!

**Comment by bwilkerson** [comment]
Note that the package Seth referenced is not the same as the one we're using for analyzer. It solves a different part of the extensible software space. As I understand it, it allows the host application (dartdoc in this case) to run a package's main method in a separate isolate and provides a (slightly) higher-level interface for passing data between the isolates. I say "slightly" because it assumes that all data is arbitrary maps.

**Comment by keertip** [comment]
We would like to have support for 3rd party generators so as to make it easy to use the work done in dartdoc. But for now this is not high on our priority list.

**Comment by sethladd** [comment]
This would be very cool, but it's not on our radar. Please reopen or comment if you intend to work on it.
