### ISSUE TITLE
The "Inherited" tag is shown on a separate line for methods

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#487]
For methods the inherited tag is shown on a separate line and breaks up the continuity of the method name and signature. It gets quite difficult to figure out that this is a method. 

![screen shot 2015-05-15 at 11 34 05 am](https://cloud.githubusercontent.com/assets/2192312/7659445/ccb3e922-faf6-11e4-9f12-f33f0294cd5f.png)

**Comment by sethladd** [comment]
Good catch! Will do.
