### ISSUE TITLE
dartdoc should fail to generate docs if any analysis errors

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#489]
It should probably (possibly?) still generate docs, but should warn the user at the end that there were analysis errors encountered:

```
"4 analysis errors and 123 warnings encountered!"
```

**Comment by keertip** [comment]
Like it! That would help the user understand why docs were not generated or why generated docs are missing information.

**Comment by sethladd** [comment]
Curious. Why would docs not be generated if there are analysis warnings?

**Comment by sethladd** [comment]
I'm not sure we want to print out "X errors encountered", unless that was the reason the docs weren't generated. If I'm generating docs, I'm probably not concerned that there are warnings in the code. And if there are warnings in the code, I might be frustrated if you don't tell me what those warnings are.

Currently, I think we should only display feedback that prevented the docs from being generated. If the docs were generated, don't tell me how many warnings my code has.

**Comment by devoncarew** [comment]
The analyzer is pretty tolerant of errors in the code - it'll generate ASTs even if there are semantic or syntactical errors. I guess it's not warnings I'm concerned about so much as errors. The generated docs may not be complete. We'll still generate documentation, but won't warn that there were errors that could mean that the documentation is potentially incorrect.

I guess the question is, should we generate if there are analysis errors or fail with an `exit(1)`. And if we do generate w/ errors, should we warn the user that the generated documentation may be incomplete.

**Comment by keertip** [comment]
If we do generate docs when there are errors in analysis, we should inform the user that the documentation is most likely to be incomplete and why. This helps the user know the cause instead of assuming dartdoc is not working right.

**Comment by sethladd** [comment]
Errors? Fail to generate.

Warnings? Generate. (this assumes that warnings don't affect the semantics of the code, and the docs will be correct in the face of any warnings)
