### ISSUE TITLE
Generate docs into doc/api

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#493]
@devoncarew @keertip this seems like a good idea as the default place to put the generated API docs. Thoughts?

**Comment by a14n** [comment]
Did you mean `doc/api` ?

**Comment by devoncarew** [comment]
`doc/api` sounds good. It's unlikely to conflict with user written documentation, and uses the `doc` dir which pub likes.

**Comment by sethladd** [comment]
doc/api , yes :)

**Comment by keertip** [comment]
#497
