### ISSUE TITLE
introduce an abstract ClassMember element

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#494]
This would let clients of the `model.dart` API know when they had a member of a class and look up the parent `Class`.

```
abstract class ClassMember extends ModelElement {
  Class get clazz;
}
```

Probably the parent of `Field`, `Method`, and `Constructor`.

**Comment by sethladd** [comment]
:+1:

**Comment by sethladd** [comment]
We should do this, but going to close to help keep our bug database clean-ish. If you plan to do this near-term, please do reopen.
