### ISSUE TITLE
API inconsistent in model.dart

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#495]
In `model.dart`, the Library class uses get methods while the Class class uses getters. So, `Library.getConstants()` vs `Class.constants`. The API should probably be normalized.

**Comment by keertip** [comment]
Yes, it should be consistent. Will  fix.

**Comment by sethladd** [comment]
Yes! It's one of those... we'll get to it, we promise. Patches welcome!  (and we prefer getters)

**Comment by keertip** [comment]
#503
