### ISSUE TITLE
the rendering for the dart:core Deprecated annotation is dodgy

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#496]
![screen shot 2015-05-18 at 12 57 23 pm](https://cloud.githubusercontent.com/assets/1269969/7690632/32568cf6-fd6a-11e4-9036-976923c7efe2.png)

**Comment by sethladd** [comment]
Taking a look now.

**Comment by sethladd** [comment]
PR https://github.com/dart-lang/dartdoc/pull/518
