### ISSUE TITLE
Parse `Deprecated.expires` as markdown

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/dartdoc#500]
In grinder we've been using the String argument to Deprecated to inform about the new API that is replacing the deprecated one.  For example:

```
@Deprecated('Use `Test` instead')
class Tests ...
```

It would be nice if we could instead do:

```
@Deprecated('Use [Test] instead')
class Tests ...
```

and have `[Test]` actually link to the `Test` class.

It's unfortunate the the argument is called `expires`, something more generic like `message` would have been better), but since it's just a positional argument at the call site, only dartdoc itself really needs to care about the fact that it's exposed as `expires`.

**Comment by seaneagan** [comment]
See also http://dartbug.com/23489

**Comment by zoechi** [comment]
+1

**Comment by sethladd** [comment]
This seems like a reasonable special case. sgtm

Patches welcome!

**Comment by sethladd** [comment]
Love the suggestion, but we're unlikely to get to this any time soon. Please comment or reopen if you'd like to work on this.
