### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/dartdoc#502]
It's not uncommon for projects to include diagrams/images in a repo that are referenced in the readme for clarity, but currently those images are not copied over to `doc/api/` with the rest of the static assets.

Are there any plans to support this use case?

**Comment by sethladd** [comment]
where would dartdoc get the images from?

**Comment by evanweible-wf** [comment]
In the use case I'm talking about, the images would be included in the repo, so it'd be a simple copy.

For example:
```
- repo/
  |- images/
  |  \- example.png
  \- README.md
```

**README.md:**
```md
![example](/images/example.png)
```

If dartdoc could parse that relative URL, it could copy `images/example.png` to `doc/api/images/example.png` and it should just work thanks to the `<base href=".">` in `doc/api/index.html`.

**Comment by evanweible-wf** [comment]
I guess that example is specific to the README.md, but the same pattern would work with doc comments:

**lib/example.dart**
```dart
/// ![example](/images/example.png)
class Example {}
```

If the url was actually relative `../images/example.png`, the path resolving wouldn't be hard. If it's `/images/example.png` like the example above, it would require mapping `/` to the project root. Maybe it's not even worth supporting that use case - just allow relative paths.

**Comment by sethladd** [comment]
Is the proposal for dartdoc to parse all comments, look for image URLs in markdown, resolve the URIs, and copy those files over to doc/api ?

I wonder if we could put the images into doc/ and refer to them from there.

**Comment by evanweible-wf** [comment]
I like that idea a lot better :smile:. Would have to serve from the `doc/` instead of `doc/api` though. That's fine locally, but I don't know what the plan is for hosted docs. Will that work?

**Comment by sethladd** [comment]
Another option is to default to copy doc/images/* into doc/api/*

**Comment by evanweible-wf** [comment]
I'm trying to think of a way to support GitHub and the docs, since the readme would be used in both places. If the readme has a link to `doc/images/example.png` and that image get's copied into `doc/api/images/example.png`, the doc image would be broken.

I guess I could keep images in `images/` and add a build step to copy `images/*` to `doc/images/` and always reference as `/images/file.png`, but that feels like it should be unnecessary.

Side note: are images in the readme supported on pub.dartlang.org?

**Comment by seaneagan** [comment]
readme is also displayed on pub.dartlang.org, so would want it to work there as well

**Comment by sethladd** [comment]
We could just leave this as an exercise to the developer... their taskrunner (e.g. grinder) could generate the docs with dartdoc, and then copy image from wherever they want into doc/api.

**Comment by evanweible-wf** [comment]
I'm perfectly fine with that, but I don't see how that translates to automatic doc generation when publishing to pub. Will that process be changing?

**Comment by seaneagan** [comment]
Another thing to keep in mind is that images add to the size of your package when it's downloaded, so maybe best not to include it in the same branch of your repo anyways?  I've put doc images into my gh-pages branch before because of this.

**Comment by evanweible-wf** [comment]
@seaneagan That's a good point. Maybe the best solution is keep the documentation simple and link to github pages/external source for more details.
