### ISSUE TITLE
Many libs from the web (web_sql, etc) don't have one-line docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#505]
![screen shot 2015-05-23 at 10 29 06 am](https://cloud.githubusercontent.com/assets/5479/7785129/a6a13032-0136-11e5-9f2f-76284d89df76.png)

**Comment by sethladd** [comment]
cc @keertip

**Comment by sethladd** [comment]
Is this a bug in dartdoc or do those libraries not have one-liners?

(They have one-liners on api.dartlang.org...)

**Comment by keertip** [comment]
There are two versions of the these libraries in the sdk - dart2js and dartium. The dart2js libraries have documentation while the dartium ones don't. Looks like dartdoc is using the dartium libs to generate the docs while docgen is using the dart2js ones.

**Comment by alan-knight** [comment]
Yeah, there's a long-standing bug about the discrepancies between the two. Somewhere on my list is revisiting the way the docs are handled, but it's been buried pretty deep under just fixing things that are actually broken.

**Comment by sethladd** [comment]
@alan-knight what are the canonical dart:html definitions? I suspect it's dart2js.

Can we get dartdoc to look at dart2js's copy of the libs?

Thanks for the analysis, @keertip !

**Comment by alan-knight** [comment]
Ah, if only it were that simple. I believe, although I'm going on fuzzy memories here, that in some cases Dartium has better docs. Docgen uses dart2js mirrors, so it has no choice but to use dart2js. Original bug is https://code.google.com/p/dart/issues/detail?id=10991 (marked stale because of dartdoc work :-)

**Comment by keertip** [comment]
Will change dartdoc to use the dart2js versions of the libraries. At least it will be consistent with the current docs.

**Comment by sethladd** [comment]
In this case, I don't think we should special-case dartdoc. We'll be left with the same bug that has existed for (literally) years... docs displayed by analysis server (and thus, editors) will be different than the docs we display in api.dartlang.org.

**Comment by sethladd** [comment]
Not clear why, but libraries.dart points to dartium's dart:html. That copy doesn't have all the docs.

In order to ensure that analyzer in all cases is looking at the same dart:html, we'll continue to look at whatever dart:html is the default in libraries.dart.

We hope that dartium's copy of dart:html is updated with more docs, or libraries.dart points to dart2js as the default. Either way will fix the ultimate issue.
