### ISSUE TITLE
Tests for [new Constructor] format ?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#516]
A quick grep through the SDK shows:

```
~/Code/dart/sdk/sdk/lib[master] $ grep -rnw . -e '\[new'
./_internal/pub/lib/src/barback/transformer_id.dart:74:  /// [new TransformerId.parse].
./_internal/pub/lib/src/pubspec.dart:33:  /// This will be null if this was created using [new Pubspec] or [new


./_internal/pub/lib/src/utils.dart:93:/// Like [new Future], but avoids around issue 11911 by using [new Future.value]

./_internal/pub/lib/src/utils.dart:856:  // Using [new Future] adds an asynchronous operation that works around the


./core/uri.dart:878:   * This method takes the same parameters as the [new Uri] constructor,
```

(edited for false positives)

That's not a lot of cases. But, there may not be another way to link to a constructor.

Just double checking that we want to support this form. If so:

* We'll need to add some tests
* We'll document it on https://www.dartlang.org/articles/doc-comment-guidelines/

**Comment by sethladd** [comment]
@keertip @devoncarew any thoughts?

I think we should support `[new Constructor]` but I can be convinced otherwise.

**Comment by keertip** [comment]
Did a quick test. The analyzer does resolve the reference to `[new Future]`, so dartdoc can support this use use. Will check to see if changes, if any are needed in dartdoc.

**Comment by sethladd** [comment]
Just checked, and it's mentioned on the doc page. So I think all we need is a few tests.

**Comment by sethladd** [comment]
Should we add a test for a named constructor, too?

**Comment by keertip** [comment]
Yes, will do.

**Comment by keertip** [comment]
#525, #528
