### ISSUE TITLE
References to elements from another library are not linked right

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#529]
Consider the case for references to `Future` in the documentation for `dart:io`. The link that is generated points to `Future` in `dart:io` library instead of `dart:async`

**Comment by sethladd** [comment]
Good catch.

**Comment by keertip** [comment]
#536

**Comment by sethladd** [comment]
Is this something we can test for so we don't regress?

**Comment by keertip** [comment]
#540
