### ISSUE TITLE
Only run tests once, not twice, in Travis

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#539]
We're running the tests twice in Travis... once with and once without coverage.

Let's get to a single run of the tests, collecting coverage.

**Comment by devoncarew** [comment]
We need to make sure that the `dart_coverage` tool fails on test failures, but not on coverage capture or upload failures (which happen more frequently than they should).

**Comment by sethladd** [comment]
@kevmoo drops the knowledge on us.

1) run tests w/ --coverage_dir set

2) likely fork/hack coveralls to have a mode that does report, but takes in a directory (with coverage results) instead of a process to run

**Comment by sethladd** [comment]
PR is up: https://github.com/duse-io/dart-coveralls/pull/40

**Comment by sethladd** [comment]
I was informed that --coverage_dir is deprecated.

Instead, we should use Chris's tool here: https://github.com/dart-lang/coverage

**Comment by kevmoo** [comment]
@sethladd Who told you that?

It's so freakin easy to use coverage_dir. I'd love to argue that we keep it...

**Comment by sethladd** [comment]
PR is up in the coveralls plugin: https://github.com/duse-io/dart-coveralls/pull/42

Once that lands, we can run the tests a single time in our build.

**Comment by sethladd** [comment]
PR has been merged. Need to take another look at this.

**Comment by sethladd** [comment]
This is fixed. We run the tests, and capture coverage, in one go.

**Comment by sethladd** [comment]
Looks like tests are still being run twice during the build.
