### ISSUE TITLE
Copy the design from polymer docs

### ISSUE THREAD

**Issue by gmosx** [dart-lang/dartdoc#547]
http://polymer.github.io/polymer/

**Comment by sethladd** [comment]
We're pretty close to this. What exactly works for you with polymer's design?

**Comment by gmosx** [comment]
Polymer's version just looks professional (like the rest of the polymer
site). The current dartdoc template is not as good, dart-lang.org just
sucks.

On Mon, Jun 1, 2015 at 6:36 PM, Seth Ladd <notifications@github.com> wrote:

> We're pretty close to this. What exactly works for you with polymer's
> design?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartdoc/issues/547#issuecomment-107589161>.
>



-- 
http://www.gmosx.com

**Comment by sethladd** [comment]
Sorry to hear you don't think the current template is not as good. We will continue to strive to make our docs look professional. Please let us know if there are other specific things you like about other doc sites.
