### ISSUE TITLE
converting dart:async to dart_async, but could conflict with real dart_async

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#552]
We might need to come up with a new scheme for directories. Not sure...

Consider the case where a project might merge the SDK docs with their project's docs. If their project includes dart_sync as a library name (unlikely, but could happen), it could then conflict with the dart_async directory generated due to the SDK.

Would dartdoc ever create the SDK docs along with a project's docs?

Should our directory structure for generated docs be globally consistent? At least between packages hosted on pub and the core SDK?

If you saw:

api.dartlang.org/dart_async

and

dartdocs.org/dart_async

Would you be confused?

**Comment by sethladd** [comment]
cc @keertip @devoncarew

**Comment by devoncarew** [comment]
You could either live with the (probably pretty small) change of a name collision, or convert the `:` into a char that's a legal file system char but not a legal dart id char (e.g., `-`).

**Comment by sethladd** [comment]
dashes work for me! Thanks for the suggestion.

**Comment by sethladd** [comment]
Working on this now.

**Comment by sethladd** [comment]
PR https://github.com/dart-lang/dartdoc/pull/553

**Comment by sethladd** [comment]
`:` and `.` are now `-`

Bonus, URLs look nicer, too! (subjective, I know :)

**Comment by keertip** [comment]
Awesome! Thanks for looking at this.
