### ISSUE TITLE
Allow a user to insert arbitrary HTML to header or footer of generated docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#56]
In order to allow a user to insert their own CSS or analytics snippet, we can allow them to add arbitrary HTML into the header or footer of each generated HTML page.

**Comment by keertip** [comment]
@sethladd, would it make sense to have a config file local to the user to specify these values and dartdoc will pick it up if available while generating the docs.

**Comment by sethladd** [comment]
Required are the necessary command-line args. A "nice to have" is a config file. But if we turn on command-line args, then people can script it however they want.

**Comment by keertip** [comment]
#328
