### ISSUE TITLE
add flag to silence messages while generating docs

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#562]
On build bots it would be nice not to have the slew of messages while generation

**Comment by sethladd** [comment]
should we just go ahead and switch over to using the logging package?

**Comment by sethladd** [comment]
of course, we can send everything to dev/null during a build :)

**Comment by keertip** [comment]
Tried that, works on the mac, but did not work on linux.

**Comment by sethladd** [comment]
Curious, what was the full command?

**Comment by keertip** [comment]
figured out how to get redirection to dev/null working on linux.
