### ISSUE TITLE
dartdoc warnings aren't actionable

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#572]
```
WARNING: ModelFunction loadAsBytes contains unknown doc reference [Uint8List]
```

They should contain the file and line of the issue so users can locate the problem in the source.

We might want to print them all out at the end of the run as well, instead of in with the `generating` progress.

**Comment by sethladd** [comment]
+1

**Comment by devoncarew** [comment]
Also, they are duplicated. We print out one when doing the element's summary (on its parent page), and again when doing the element's detail page:

```
generating docs for library resource_loader.dart…
WARNING: ModelFunction loadAsBytes contains unknown doc reference [Uint8List]
WARNING: ModelFunction loadAsBytes contains unknown doc reference [Uint8List]
```

We should probably move the warning logic out of the markdown conversion code and into a separate phase. It would also be easier to get character positions then as well.
