### ISSUE TITLE
Make it easier to jump around the page

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#576]
Some pages are very long. Make it easier to jump from one section to another.

**Comment by sethladd** [comment]
Here's one idea:

![screen shot 2015-06-11 at 4 16 38 pm](https://cloud.githubusercontent.com/assets/5479/8109133/79ccd52e-1055-11e5-924a-f0a6a0f6ea61.png)

**Comment by keertip** [comment]
So a top nav bar instead of one on the right/left?

**Comment by sethladd** [comment]
We could do a left-nav, but it's a bit of a space waster, as there could be a bunch of whitespace unused.

Regardless, definitely open for mocks for alternatives!

**Comment by keertip** [comment]
Top nav bar would also work, as long as it is obvious to users.

**Comment by sethladd** [comment]
Dupe of https://github.com/dart-lang/dartdoc/issues/359
