### ISSUE TITLE
push built docs to firebase automatically on each build

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#578]
So that we know what the current output looks like.

**Comment by keertip** [comment]
There is a firebase instance at https://dartdoc-sdk-docs.firebaseapp.com/ which could be used.

**Comment by sethladd** [comment]
How does this affect build/test times?

**Comment by devoncarew** [comment]
It's about 10-15 seconds on the stable non-sdk docs bot.

We could move it over to the sdk generating bot, or create a bot just for this task. I'm not sure how to have a specialized bot however. It seems like you get additional travis bots by sharding your build.

**Comment by sethladd** [comment]
10-15 sec seems reasonable enough.

If we really want to get smart, we'd chain it... IFF we have a successful build, return TESTS PASSED and then spawn a new bot just to upload. But I don't think there's a chaining mechanism?

In any case, thanks for setting this up!
