### ISSUE TITLE
summarize library members on markdown block boundaries (was: summarize library members on sentence boundaries?)

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#582]
This method summary ends mid-sentence:

![screen shot 2015-06-11 at 4 27 44 pm](https://cloud.githubusercontent.com/assets/1269969/8120688/fdb61048-1056-11e5-8ec7-39c0d2efa87c.png)

It might be nicer to end it on a sentence boundary. So just show the first sentence?

Or, since the docs are in markdown, we could end it on the first paragraph (the first blank line).

**Comment by keertip** [comment]
Initially we were showing just the first sentence. Not sure why it was changed. @sethladd ?

**Comment by sethladd** [comment]
Very very early we tried to show the first sentence. However, that got hard to detect (how to tell when the sentence ends?). So then we started using the first block, as defined by the docs themselves. A block is the first "paragraph".

If we can come up with a good algorithm to detect end of sentence, we should use it.

**Comment by devoncarew** [comment]
> Note that Dart Style for docs says the first block or paragraph should be a short one-line sentence.

Then +1 to using the first markdown block. It's much more reliable to parse and if people are following the dartdoc style guide they'll get good docs.

**Comment by sethladd** [comment]
I think we can close this. We do create a one-liner based on the first block, as markdown defines it (which is really the first paragraph). The first paragraph should be a single sentence.

Please re-open if we should do something differently.
