### ISSUE TITLE
Track down issue with test on Windows... is it a real bug?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#587]
Tracking issue to find root cause for https://github.com/dart-lang/dartdoc/pull/586

Also, is this a real issue on windows?

**Comment by keertip** [comment]
Looking at the generated docs for test package on Windows, the link to class in another library is  correct and works. This is the same link that is in used in the test. So not sure why the test is failing.

**Comment by sethladd** [comment]
Hi @keertip can you take a minute to see if this is a real issue? I can't remember if we silenced a test on the windows bots, and if we need to check into that before releasing. Thanks!

**Comment by keertip** [comment]
Last time I looked, the failure was in finding the library for the class, the test could not find the library in the package and so no link was generated.

**Comment by sethladd** [comment]
No action here. Closing. Feel free to reopen if it shows up again.
