### ISSUE TITLE
Support generating docs for new dart: libraries

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#599]
Dart embedders can add new dart: libraries. The analyzer added a `--url-mappings` command-line arg to map a dart: lib to some definition.

It would be really useful if dartdoc could pass the --url-mappings through to the analyzer.

**Comment by abarth** [comment]
I'm going to try to fix this issue.

**Comment by abarth** [comment]
With that pull request (and some tweaks to Sky), I was able to generate docs for Sky.
