### ISSUE TITLE
Use docs.md before using readme.md for the docs homepage

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#602]
Many (most) projects use the readme for both project status (build and health status) _and_ external docs for how to use the project. Including it in static docs could be surprising, esp. since the readme will often contain links to live status info (travis build info, code coverage info, ...).

![screen shot 2015-06-20 at 2 08 42 pm](https://cloud.githubusercontent.com/assets/1269969/8269228/2dd5fc88-1756-11e5-982d-28ac89ebd93f.png)

Thoughts on not generating docs based on the readme, but instead having the landing page based on the rollup of libraries in the package?

@keertip @sethladd

**Comment by devoncarew** [comment]
Or pull from `docs.md` or `package.md` in preference to readme.md.

**Comment by keertip** [comment]
The current docs does not show the status info on the package landing page, though it does pull the `readme.md` file. 

![screen shot 2015-06-22 at 9 52 00 am](https://cloud.githubusercontent.com/assets/2192312/8287388/6c9afc7e-18c4-11e5-82e9-e70159a2fd23.png)


![screen shot 2015-06-22 at 9 53 37 am](https://cloud.githubusercontent.com/assets/2192312/8287413/9622eade-18c4-11e5-94f4-c0f4395d3221.png)

 Maybe we should be doing the same?

**Comment by sethladd** [comment]
I'm not sure we can ask package authors to add another .md file to their package, just for the API docs.

However, if we first look for docs.md, and if that doesn't exist, use readme.md, that would work for me.

**Comment by sethladd** [comment]
We can do this if we find a good number of projects would use this.
