### ISSUE TITLE
additional style, layout, and generation changes

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#605]
As a follow-up to https://github.com/dart-lang/dartdoc/pull/604, here are some thoughts about other doc generation changes (some already tracked in other issues):

### header
- [ ] the header repeats a lot of information - things that are displayed immediately before and after it
- [ ] the scrolling header needs fixes
- [ ] we should have a local section nav in the sub-header
- [ ] only the top header should be fixed to the page
- [ ] the subheader should use a material design card look

### also
- [ ] we need a left nav, to help provide context about where the user is
- [ ] there is a bug about exported libraries - we don't generate the correct links to exported classes. They expect to be found in a library that we may not have generated docs for.
- [ ] consts should show their types
- [ ] where to put `Inherits`?
- [ ] including the readme.md will pull in some things that we won't want in static documentation (instead, pull from ‘docs.md’ if it exists?)
- [ ] we need to sort the members lexically (esp. for larger libraries like `dart:html`)
- [ ] say “class foo”, “library bar” instead of “foo class”, “bar library”?
- [ ] have a circle icon for the first letter of the type? in the sub-header?
- [ ] function / method name summaries should end in ‘()’
- [ ] we should have material design icons where appropriate (nav menu, overflow menu, search)
- [ ] deprecated properties don’t show as deprecated
- [ ] constants should sort before classes

### warnings
- [ ] improve the dartdoc warnings - they should show the file location they're from
- [x] add a warning when we encounter an undocumented library
- [ ] either fix the warning generator, or the dartdoc code in `resource_loader.dart`:
```
generating docs for library resource_loader.dart…
WARNING: ModelFunction loadAsBytes contains unknown doc reference [Uint8List]
WARNING: ModelFunction loadAsBytes contains unknown doc reference [Uint8List]
```

**Comment by sethladd** [comment]
Hi @devoncarew what should we do with this issue?

**Comment by devoncarew** [comment]
We can close this -

**Comment by sethladd** [comment]
To be clear, lots of good ideas here. Just wondering how to make progress. We could split out the big impact changes into different tickets.
