### ISSUE TITLE
exported libraries have broken links

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#609]
See the link for `Package` on this page: https://dartdoc.firebaseapp.com/dartdoc.generator/Generator_class.html

It works from this page however: https://dartdoc.firebaseapp.com/dartdoc/index.html

So, `Package` from the private `dartdoc.models` library is exported by the public `dartdoc` library. We generate a summary of it in the dartdoc library page, and a detail page for it as well, in the dartdoc dir. `dartdoc.generator` has a reference to it, but it thinks that is lives in the `dartdoc.models` package (which it does).

Some possible fixes:

- from `dartdoc.generator`, don't create a hyperlink for `Package`. Just treat it like a regular reference to a symbol we're not generating docs for
- in `dartdoc`, create an entry in the overview for `Package`. But generate the detail page for it in `dartdoc.models`. This would be a synthetic library that would contain all the `dartdoc.models` symbols that had been exported from other libraries.

Any other ideas or options? I like the 2nd one - it handles the case well where a class is exported by more than one library.

**Comment by sethladd** [comment]
Looks like this one can be closed?
