### ISSUE TITLE
it'd be useful to know who implements a given class

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#615]
It'd be useful to know who implements a given class. We show who extends now, but not who implements.

**Comment by sethladd** [comment]
good call!

**Comment by sethladd** [comment]
We have "implemented by"... is that what you are looking for?

![screen shot 2015-07-10 at 3 07 24 pm](https://cloud.githubusercontent.com/assets/5479/8629955/613f8fa2-2715-11e5-8cba-824a0b3a1dfc.png)

**Comment by devoncarew** [comment]
Yup, that was it - didn't realize we had it.

**Comment by sethladd** [comment]
My favorite kinds of bugs. The already fixed kind.
