### ISSUE TITLE
use the new resource loading API

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#619]
Is it available for consumption yet?

**Comment by sethladd** [comment]
Doesn't look like it. https://github.com/dart-lang/sdk/commit/f8ce36df557af9028ef72612a43e9942d6f16585 seems to be the last commit that I noticed?

Here's the latest source: https://github.com/dart-lang/sdk/blob/master/runtime/lib/core_patch.dart

cc @iposva-google who might have an update?

**Comment by sethladd** [comment]
Blocked on https://github.com/dart-lang/sdk/issues/21020

**Comment by sethladd** [comment]
We're "weapons free" now, Resource landed in latest bleeding edge of Dart SDK.

**Comment by sethladd** [comment]
Thanks!
