### ISSUE TITLE
intra-page nav

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#621]
Related to https://github.com/dart-lang/dartdoc/issues/359, but this item covers seeing element siblings and navigating to parent elements.

Probably implemented as a material design side nav toggle, with a hotdog button in the toolbar.

**Comment by sethladd** [comment]
I think this is a P1. We want to do something here before release.

**Comment by sethladd** [comment]
In progress:

![screen shot 2015-07-13 at 7 35 55 pm](https://cloud.githubusercontent.com/assets/5479/8665229/741981fe-2996-11e5-8d66-b92e6631f699.png)
![screen shot 2015-07-13 at 7 35 47 pm](https://cloud.githubusercontent.com/assets/5479/8665230/742ec0fa-2996-11e5-88cc-319b03f6f97e.png)

**Comment by sethladd** [comment]
WIP: CL https://chromiumcodereview.appspot.com/1230573003

**Comment by devoncarew** [comment]
Cool! I think we'd want to borrow one of the material design colors for our page for the selected item color. And we probably need some padding between the menu and the header.

**Comment by sethladd** [comment]
Lots of style tweaks to come, for sure.

**Comment by sethladd** [comment]
![screen shot 2015-07-14 at 9 58 33 am](https://cloud.githubusercontent.com/assets/5479/8679341/fb2a8c2e-2a0e-11e5-9edb-f39bd7b71658.png)

A little progress.

**Comment by sethladd** [comment]
Better:

![screen shot 2015-07-14 at 12 57 12 pm](https://cloud.githubusercontent.com/assets/5479/8683464/e09a5952-2a27-11e5-8fde-897f07c03ccc.png)

**Comment by sethladd** [comment]
Mobile: 

![screen shot 2015-07-14 at 12 57 35 pm](https://cloud.githubusercontent.com/assets/5479/8683468/eccdb732-2a27-11e5-8ca3-76c74904adb8.png)

**Comment by sethladd** [comment]
Ready for review: https://chromiumcodereview.appspot.com/1230573003/

**Comment by devoncarew** [comment]
For mobile, I think that the navigation should display over the other content. What does it look like when the left nav is not open? The only delta from before is the addition of the hamburger button?

**Comment by sethladd** [comment]
Left-nav not open:

![screen shot 2015-07-14 at 1 09 39 pm](https://cloud.githubusercontent.com/assets/5479/8683793/9d4ef1b0-2a29-11e5-9d7b-b1a4897486f9.png)

**Comment by sethladd** [comment]
We can try to make the left-nav stick on top of content.... but I'd like to try that in another patch.

**Comment by sethladd** [comment]
Example of long list:

![screen shot 2015-07-14 at 1 28 31 pm](https://cloud.githubusercontent.com/assets/5479/8684290/6077c336-2a2c-11e5-8634-f21fab298d17.png)

**Comment by devoncarew** [comment]
Looks good!

**Comment by sethladd** [comment]
initial support landed for classes. Doing a library now. Please take a look and tweak styles if necessary.

**Comment by sethladd** [comment]
Bug: inconsistent padding/margin at top between left-hand nav and content.

![screen shot 2015-07-14 at 3 16 01 pm](https://cloud.githubusercontent.com/assets/5479/8686454/4bb26582-2a3b-11e5-95b2-cb90516d98db.png)

**Comment by sethladd** [comment]
Library looks pretty similar:

![screen shot 2015-07-14 at 3 29 45 pm](https://cloud.githubusercontent.com/assets/5479/8686676/368f835e-2a3d-11e5-8c49-77af763f66c8.png)

**Comment by sethladd** [comment]
OK, I think this is sufficiently landed. I await @devoncarew 's tweaks :)
