### ISSUE TITLE
Overloaded use of arrow in breadcrumbs nav

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#625]
We use the unicode arrow to indicate "returns", but it's also used in the breadcrumbs nav.

Can we use something different in the breadcrumbs?

![screen shot 2015-07-08 at 9 49 24 am](https://cloud.githubusercontent.com/assets/5479/8576417/b96c3d26-2556-11e5-9396-bea9a681343a.png)

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
Sounds good. We can play with bullets and other chars.

**Comment by sethladd** [comment]
What was the concern with `>` ?

**Comment by devoncarew** [comment]
Just aesthetics :) It looks a bit too much like ascii art.

I _do_ like that it makes clear a hierarchical relationship. We can move back to it if we don't get inspired by some other char.

**Comment by sethladd** [comment]
We could use an SVG for the greater than, so it doesn't look so ASCII.

Some examples:

![screen shot 2015-07-08 at 1 42 11 pm](https://cloud.githubusercontent.com/assets/5479/8581695/3ad268f2-2577-11e5-82fe-5401faf469fa.png)

![screen shot 2015-07-08 at 1 43 34 pm](https://cloud.githubusercontent.com/assets/5479/8581710/57e8a294-2577-11e5-8d2b-f38d898b5f67.png)


![screen shot 2015-07-08 at 1 44 17 pm](https://cloud.githubusercontent.com/assets/5479/8581729/7053cf20-2577-11e5-9495-a4d263f7bd22.png)

**Comment by devoncarew** [comment]
+1

We'll need svgs for the nab menu and such anyway.

**Comment by sethladd** [comment]
Link to SVG for breadcrumb: https://developers.google.com/_static/93cc29a174/images/redesign-14/breadcrumb.svg

**Comment by sethladd** [comment]
And apparently we can use a list-style-image CSS with a URL to an SVG

something like `list-style-image: url('bullet.svg');`

**Comment by sethladd** [comment]
CL https://chromiumcodereview.appspot.com/1228893005

**Comment by sethladd** [comment]
![screen shot 2015-07-09 at 11 27 28 am](https://cloud.githubusercontent.com/assets/5479/8603498/7f509d80-262d-11e5-9d7f-c5dff3650755.png)

**Comment by sethladd** [comment]
Landed!
