### ISSUE TITLE
Specific generic superclass/interface parameters aren't "filled-in"

### ISSUE THREAD

**Issue by bprosnitz** [dart-lang/dartdoc#630]
For instance, on the Uint8List page. https://api.dartlang.org/apidocs/channels/be/dartdoc-viewer/dart:typed_data.Uint8List

Uint8List implements List<int> but the method documentation still includes the generic parameter. For instance for add, there is:
void add(E value) rather than void add(int value)

**Comment by sethladd** [comment]
Thanks for the report!

We're finishing up work on a new dartdoc. This is one of the bugs we've fixed.

Here's a screenshot:

![screen shot 2015-07-09 at 11 32 34 am](https://cloud.githubusercontent.com/assets/5479/8603624/37a4c6a4-262e-11e5-95f1-5e8513b6244f.png)

I'll close this issue for now. Keep the feedback coming!
