### ISSUE TITLE
Improve visibility of property types

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#633]
The property type is very close to the property name. I wonder if we can improve this?

**Comment by sethladd** [comment]
How about this:

![screen shot 2015-07-10 at 11 39 09 am](https://cloud.githubusercontent.com/assets/5479/8626229/735476c0-26f8-11e5-9e40-3fe7dadb525e.png)

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by sethladd** [comment]
On mobile:

![screen shot 2015-07-10 at 1 38 48 pm](https://cloud.githubusercontent.com/assets/5479/8628564/038859e0-2709-11e5-8873-fe6eb80662da.png)

**Comment by sethladd** [comment]
CL https://chromiumcodereview.appspot.com/1230923007/

**Comment by devoncarew** [comment]
It seems fairly different from how we display methods and functions - it's using a different rendering style.

**Comment by sethladd** [comment]
Properties aren't functions or classes. It's the only place we have that is a name and a type. Maybe there's a better way, but I find the current way hard to read properties.

Ideas?

**Comment by sethladd** [comment]
I could use the arrow. Like "foo --> String"

**Comment by devoncarew** [comment]
foo --> String would work, and parallel how we display functions. We'd probably still need to special case constants, because of the need to display the values.

**Comment by sethladd** [comment]
Going to do the least ambitious thing here and put the type annotation first. Boring, but least surprising.

**Comment by sethladd** [comment]
CL https://chromiumcodereview.appspot.com//1230923007

Fixed in 61fed36741496

**Comment by sethladd** [comment]
It's now:

![screen shot 2015-07-10 at 2 41 18 pm](https://cloud.githubusercontent.com/assets/5479/8629624/bd1e39d0-2711-11e5-8e4b-fda3501145c0.png)
