### ISSUE TITLE
we lost the `>` separators between extends parents

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#635]
<img width="484" alt="screen shot 2015-07-10 at 1 52 56 pm" src="https://cloud.githubusercontent.com/assets/1269969/8628847/113165f8-270b-11e5-8af9-348ea13f0e47.png">

**Comment by sethladd** [comment]
I'll figure it out... thanks for the catch!

**Comment by sethladd** [comment]
Oh, hah, I think it's because the color of the > is white :)

**Comment by sethladd** [comment]
Fixed!

![screen shot 2015-07-10 at 3 27 20 pm](https://cloud.githubusercontent.com/assets/5479/8630244/2c62e81c-2718-11e5-9ae1-8063bb15a24d.png)

**Comment by sethladd** [comment]
CL https://chromiumcodereview.appspot.com/1233763002

Fixed in 87a1e1b24e66078e2b24
