### ISSUE TITLE
On mobile, show types on line above names for constants and properties

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#636]

**Comment by sethladd** [comment]
Now looks like this:

![screen shot 2015-07-10 at 2 44 44 pm](https://cloud.githubusercontent.com/assets/5479/8629675/3a0b113e-2712-11e5-9fa5-37ca58646b6d.png)

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by sethladd** [comment]
CL https://chromiumcodereview.appspot.com/1228363003

Fixed in e5d20d6bd64320f8a23067

**Comment by devoncarew** [comment]
+1, looks good!
