### ISSUE TITLE
No Dart identity visible on docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#637]
We need some of our colors and logo, somewhere/somehow, to echo back to the main Dart identity.

Perhaps showing the logo is sufficient.

**Comment by sethladd** [comment]
We have a favicon now.

**Comment by sethladd** [comment]
Now at the bottom:

![screen shot 2015-07-16 at 2 05 58 pm](https://cloud.githubusercontent.com/assets/5479/8735185/cea0b294-2bc3-11e5-9713-7600f0c9ff3b.png)

and

![screen shot 2015-07-16 at 2 09 35 pm](https://cloud.githubusercontent.com/assets/5479/8735262/5120f792-2bc4-11e5-98be-6225ea4804a2.png)

**Comment by devoncarew** [comment]
Can we make the line a bit more terse? It'll wrap now on mobile devices.

**Comment by sethladd** [comment]
Suggestions?

I really want the words "API" and "docs" for SEO.

Maybe move the CC below?

**Comment by sethladd** [comment]
What about something like

![screen shot 2015-07-16 at 3 20 09 pm](https://cloud.githubusercontent.com/assets/5479/8736541/449f5504-2bce-11e5-9ce5-cd38a6448ab9.png)

**Comment by sethladd** [comment]
Going with this for now:

![screen shot 2015-07-16 at 4 16 26 pm](https://cloud.githubusercontent.com/assets/5479/8737375/13633ac0-2bd6-11e5-8cf2-fc415ea7b5ae.png)

**Comment by sethladd** [comment]
Going with this, a little better?

![screen shot 2015-07-16 at 4 18 51 pm](https://cloud.githubusercontent.com/assets/5479/8737397/646250d2-2bd6-11e5-8c0a-fb6b4b120b5d.png)

![screen shot 2015-07-16 at 4 18 46 pm](https://cloud.githubusercontent.com/assets/5479/8737398/67304e54-2bd6-11e5-8fcd-e091f5e6971f.png)
