### ISSUE TITLE
Option: hide inherited fields / methods

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#641]
Users have asked to be able to hide inherited fields / methods / "things".

Often APIs are full of methods pulled in from super classes, but the user just wants to see "what's new". For example, HTML and Sky and other widget libraries.

**Comment by sethladd** [comment]
cc @johnmccutchan @abarth for FYI

**Comment by sethladd** [comment]
Dupes https://github.com/dart-lang/dartdoc/issues/980

**Comment by Hixie** [comment]
Bonus points if you can also show or hide those that are overriding something from the base class.

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/1010

**Comment by sethladd** [comment]
Not sure we closed this one. We just dim inherited, yes? We'd still like to add an option to hide them.

**Comment by kevmoo** [comment]
Gotcha

**Comment by Hixie** [comment]
It doesn't seem like we even dim them at this point. Maybe we're on some old version?

I'd like to see just the newly introduced members e.g. in:
http://docs.flutter.io/flutter/rendering/RenderParagraph-class.html

**Comment by kevmoo** [comment]
@Hixie We only dim/italic on the right side. In the main body, you see the *inherited* comment

**Comment by Hixie** [comment]
I don't think the "inherited" comment is enough to make this clear to readers. I think if we want to have the members always there, maybe separating inherited members from new members, e.g. by having the inherited ones in a separate later section, would really help.

Consider a page like: http://docs.flutter.io/flutter/rendering/RenderCustomMultiChildLayoutBox-class.html

This is pretty typical for Flutter docs.

BTW, it would also be useful to be able to distinguish methods that were overridden from those that are entirely new. Similarly marking the protected methods somehow would be good (we don't have any yet but we will soon be going and adding @protected annotations all over the place).

**Comment by kevmoo** [comment]
@Hixie we might-could open a new issue on this.

I went back and forth w/ @sethladd and @keertip on what's in there now.

Separate feature requests for overrides and projected would also be good, me thinks.

**Comment by sethladd** [comment]
I'd like to see if we can find a way to make inherited methods easier to recognize, when looking at the list of methods provided by a class. There's probably a better way to do it than to print "inherited" below the name.

![screen shot 2016-03-18 at 1 20 40 pm](https://cloud.githubusercontent.com/assets/5479/13891079/436cadd0-ed0c-11e5-99bd-dbb09e3b406a.png)

**Comment by devoncarew** [comment]
We could prefix the name with a up-arrow icon. Something like the icon-upload from glyphicons (http://getbootstrap.com/components/).

**Comment by sethladd** [comment]
If we can get vertical alignment correct, sounds like something we should try. Thanks!

**Comment by astashov** [comment]
Trying to figure out what needs to be done to mark this ticket as closed :)

* Use the arrow icon instead of 'inherited' for inherited methods?
* Add some sort of toggle to show/hide inherited methods. How'd that toggle look like? Where would it be placed?

I saw @kevmoo tried to implement this, but then there was no consensus on UX, and the PR was eventually closed without merging. So, what's the scope of this ticket now? @sethladd ? @devoncarew ?

Thanks!

**Comment by sethladd** [comment]
@astashov : let's avoid a toggle. Let's start with a better visual indicator. Open to ideas here. Try an icon?

(note: if you try an icon, please see how that affects page load speeds. hopefully we don't need to download an entire font just to use one icon :)

**Comment by Hixie** [comment]
Maybe sorting the inherited members after the new members?

**Comment by sethladd** [comment]
> Maybe sorting the inherited members after the new members?

Worth a shot.

**Comment by astashov** [comment]
> Maybe sorting the inherited members after the new members?

You mean the same visual indicator (`inherited`), no show/hide toggle, just place inherited members after the new members, and that's it. Right?

**Comment by Hixie** [comment]
right. Not sure if it'll be good, but it's worth a try. The problem right now is that it's not at all obvious from the docs what a subclass introduces.

**Comment by kevmoo** [comment]
Changing the sort kills me – it makes scanning much harder. My vote for better visual indicator.

...all of the right classes are in place, I think. Hopefully can be done mostly w/ CSS.

**Comment by astashov** [comment]
Guys, I need a consensus to proceed :)

**Comment by Hixie** [comment]
The problem is that there's two ways you want to scan docs:
- I know about the superclass, and I want to find out why this class is interesting
- I know nothing about the superclass, and want to learn about this class.

In the first case you don't want to see the inherited members at all, especially when there's 80 of them and only 2 new methods.

In the latter case you want to see everything in order.

This is why a toggle is attractive. It's not clear how one rendering can do both.

Also, as mentioned earlier, it would also be nice to see what methods have been overridden (this speaks to the "why is this class interesting" use case) and what methods are protected vs public (this speaks to a new pair of use cases: learning about the class to use it, vs learning about the class to implement a further subclass). I'm not sure how this interacts with the problems here.

I'm not good at UX so I'm not sure how best to address these three use cases (learn why it's special, learn how to use it, learn how to implement it). I'm happy to defer to other people if they have clear ideas for how to address the three use cases.

**Comment by devoncarew** [comment]
This may not help the consensus, but javadoc tackled this by documenting the members introduced by the class, and referencing the members that were inherited:

http://docs.oracle.com/javase/7/docs/api/java/io/OutputStream.html

**Comment by astashov** [comment]
So, what about this - I first try to just reorder the members so the inherited goes last, generate Flutter docs, publish it somewhere on S3, for example. You guys try it out, if you think we don't like it - I roll back the sorting, and add a toggle, which will show/hide the inherited members, publish it too, you try it too. Then we decide what's better. Thoughts?

**Comment by sethladd** [comment]
@astashov here's my proposal. Please give this a shot.

* reorder the list of names, such that in the inherited names at after the newly-introduced names
* for inherited names in the main body of the page, please unbold then and italicize them (similar to how the inherited names are displayed in the right-hand list)

Thank you!

**Comment by astashov** [comment]
@sethladd http://astashov.s3.amazonaws.com/dartdoc_flutter/current/index.html What do you think?

**Comment by abarth** [comment]
Looks great to me, but @sethladd's thumbs up is the one you want.

**Comment by Hixie** [comment]
The order of classes looks like it got messed up on there. :-)

**Comment by Hixie** [comment]
Looks great to me.

This is going to draw attention to https://github.com/dart-lang/dartdoc/issues/981, for what it's worth. For example, check out [RenderVirtualViewport](http://astashov.s3.amazonaws.com/dartdoc_flutter/current/rendering/RenderVirtualViewport-class.html). None of the methods listed are actually new, they're all just overrides. I think we probably will end up wanting an in-between styling that distinguishes them from "new" methods. Not sure exactly what we'll want. But that's not a problem for today.

**Comment by astashov** [comment]
> The order of classes looks like it got messed up on there.

Whoops :)

**Comment by sethladd** [comment]
Thanks! Looks good. We should also de-bold the return type on the inherited methods. In the example, I see that `int` is bolder than `hashCode`, for example. For `hashCode → int`

**Comment by astashov** [comment]
Reuploaded the fixed version to http://astashov.s3.amazonaws.com/dartdoc_flutter/current/index.html. Fixed: return type of inherited members is not nonbold too, classes order is in order again :)
