### ISSUE TITLE
New option: hide fields/methods/names marked with a specific annotation

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#642]
User has asked for a new feature to be able to hide names marked with a certain annotation. This annotation would be provided by the user.

Use case: some API designs are useful only to implementors of a framework. Other APIs are useful for consumers and developers. When an end-developer wants to use an API, they shouldn't see APIs designated for framework implementors.

Using this new feature, SDKs and toolkits could generate two sets of docs (one for implementors, and one for end-developers)

**Comment by sethladd** [comment]
cc @hixie

**Comment by sethladd** [comment]
Duped by https://github.com/dart-lang/dartdoc/issues/941

**Comment by yjbanov** [comment]
I would like to add libraries to the list of things one can hide. This is useful when a package re-exports the same symbols through multiple libraries. For example, Angular 2 exports individual features via standalone libraries as well as an all-in-one library that reexports all features for those who doesn't like to type too many imports. Currently this causes duplicates to appear in dartdoc search results (e.g. look for "Query" on [angular2 dartdocs](http://www.dartdocs.org/documentation/angular2/2.0.0-alpha.37/index.html#angular2)). We could mark the "all-in-one" libraries with something standard that `dartdoc` would know to ignore, e.g.:

```dart
// everything.dart
@undocumented
library everything;

export "feature1.dart";
export "feature2.dart";
```

```dart
// feature1.dart
library feature1;

class Foo {}
```

```dart
// feature2.dart
library feature2;

class Bar {}
```

The `@undocumented` (only using as example, we can pick a different annotation) would cause the `everything` library to be excluded and therefore `Foo` and `Bar` will appear only once in dartdocs.

**Comment by keertip** [comment]
@yjbanov , how about looking for a annotation `@nodoc` in the comments to indicate that the element and its children should not be documented. 

```dart
// everything.dart
///@nodoc
library everything;

export "feature1.dart";
export "feature2.dart";
```

```dart
// feature1.dart
library feature1;

class Foo {}
```

```dart
// feature2.dart
library feature2;

class Bar {}
```

**Comment by sethladd** [comment]
Is `@nodoc` a real annotation? If not, let's not use `@` as that would be misleading.

Is there another way we can say "nodoc" inside a comment?

**Comment by keertip** [comment]
Prefer not to use a real annotation, as that would mean an import. Open to suggestions as to what we could use.

**Comment by sethladd** [comment]
Agreed. Let's not use a real annotation, and let's not use something that looks like a real annotation (to avoid confusion.

Here is an idea:

```
// everything.dart
/// #nodoc
library everything;

export "feature1.dart";
export "feature2.dart";
```

**Comment by keertip** [comment]
How about 

```
// everything.dart
/// <nodoc>
library everything;
```
or 

```
// everything.dart
/// {nodoc}
library everything;
```
My top choice is still the `@nodoc`.  Using `@` makes it stand out from the rest of the comment, and makes it easy to figure out that it is metadata.

**Comment by sethladd** [comment]
Either of those is fine with me.

While `@nodoc` looks good, I'm concerned that it's confusing with "real" metadata.

**Comment by keertip** [comment]
Will go with `<nodoc>`
