### ISSUE TITLE
Scroll bar appears below tab nav on fake library

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#644]
![screen shot 2015-07-14 at 9 44 23 am](https://cloud.githubusercontent.com/assets/5479/8679031/055ef236-2a0d-11e5-8ece-0989d1e5d12c.png)

**Comment by devoncarew** [comment]
Hmm, it's scrollable though.

We could possibly hide the scrollbar w/ something like:

```
foo::-webkit-scrollbar { 
    display: none; 
}
```

Or use some fancy nested divs, which may be a more complex solution than we want.

**Comment by sethladd** [comment]
Scrollbar bad. Scrolling good. :)
