### ISSUE TITLE
Update pub_cache dep to 0.1.0 ?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#650]
Just got this message: `+ pub_cache 0.0.1+2 (0.1.0 available)`

Should we upgrade?

(I forget why we have this dep... ?)

**Comment by devoncarew** [comment]
0.1.0 is the same as the previous published version. You added this dep to load resources :)

**Comment by sethladd** [comment]
Ah, that's right! :)

I will bump.

**Comment by devoncarew** [comment]
fixed: https://github.com/dart-lang/dartdoc/commit/dd7cf2872603e5da37121119bed1791e616b0cba
