### ISSUE TITLE
Enhancement: Option to generate docsets

### ISSUE THREAD

**Issue by chinmaygarde** [dart-lang/dartdoc#651]
Docsets and docset feeds allow applications like [Dash](https://kapeli.com/dash) and [Zeal](http://zealdocs.org/) to index documentation. This allows editor integration as well as offline access to documentation. Would be great if dartdoc generated the same via a switch.

**Comment by sethladd** [comment]
Can you link to what the output format should be?

**Comment by chinmaygarde** [comment]
The output format is a docset bundle. The documentation for the same [is here](https://kapeli.com/docsets). Also, [This project](https://github.com/ducky427/dartdash) already seems to trying to generate the same.

**Comment by sethladd** [comment]
Ah, thanks!

**Comment by sethladd** [comment]
I don't think there are sqlite bindings for Dart. If there's a way to shell out to sqlite, we could drive that script from Dart. Unfortunately, it's not easy to access C code from Dart VM, so I'm not confident I could do it. Help wanted! :)
