### ISSUE TITLE
Package/SDK homepage needs left-nav

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#652]
We need a side-nav on the package page as well; we have it on library and class pages currently.

**Comment by sethladd** [comment]
Just listing libraries? would that be a bit redundant? (since all the package/SDK homepage has is a list of libraries)

**Comment by devoncarew** [comment]
It's more for consistency with the other pages.

We'll probably want a spacer or padding on pages w/o the nav as well. This will keep the main page content in the same location as users navigate between pages.

**Comment by sethladd** [comment]
I imagine you might add some left-nav action for navigating to peers, when viewing a page for the actual method or function.

**Comment by sethladd** [comment]
Since dogfood is moved out by a day, I can squeeze this in.

**Comment by sethladd** [comment]
![screen shot 2015-07-14 at 9 10 07 pm](https://cloud.githubusercontent.com/assets/5479/8690701/bb6ba34e-2a6c-11e5-9947-327da15648f6.png)

**Comment by sethladd** [comment]
PR https://github.com/dart-lang/dartdoc/pull/656
