### ISSUE TITLE
Implemented by on class shows duplicate classes for exported classes.

### ISSUE THREAD

**Issue by kaendfinger** [dart-lang/dartdoc#663]
The implemented by part of class documentation will show duplicate classes for a single class if it is exported by more than one library.

![Screenshot](http://cl.ly/image/2N1i0W2u0d3c/Image%202015-07-16%20at%204.43.29%20AM.png)

You can see this happening on [this page](https://iot-dsa.github.io/docs/sdks/dart/dslink.common/Node-class.html).

I suggest that the true class's library be the only one that is linked.

**Comment by sethladd** [comment]
Good catch, thanks!
