### ISSUE TITLE
Ensure dart:collection's IterableBase is linked correctly (old bug)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#67]
On https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-collection, the link to the IterableBase class currently points to https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.IterableBase, which doesn't exist. Manually navigating to https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-collection.IterableBase works.

From https://code.google.com/p/dart/issues/detail?id=21374

**Comment by keertip** [comment]
Verified.
