### ISSUE TITLE
Is top section nav still required?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#678]
We have section nav (constants, typedefs, properties, etc) in two places... in the top masthead and in the left nav.

![fake_library_-_dart_api](https://cloud.githubusercontent.com/assets/5479/8753343/ddae3408-2c6f-11e5-8493-e20ab6a42ed6.png)

Do we need both?

Thoughts?

**Comment by sethladd** [comment]
cc @keertip @devoncarew

**Comment by keertip** [comment]
No, we don't need both. Make the left nav not scroll of the screen and remove the top nav?

**Comment by devoncarew** [comment]
Is the left-nav changing to an intra-page nav? The top nav was originally intended to be an in-page nav.

**Comment by sethladd** [comment]
The left-nav headers (TYPEDEFS, PROPERTIES, etc) are intra-page.

**Comment by sethladd** [comment]
We decided yes. We'll move the top nav up to same line as breadcrumbs when the user scrolls the page.
