### ISSUE TITLE
Ensure: int.parse method signature is displayed correctly

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#68]
URL: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.int#id_parse

the signature of int.parse is messed up.  the onError param is declared as
"Function int onError(String source)".
you can declare "Function onError" or "int onError(String source)", but you can't use both syntaxes at once,
at least not in real dart code.

From https://code.google.com/p/dart/issues/detail?id=19711

**Comment by keertip** [comment]
verified - dartdoc shows "int onError(String source)"
