### ISSUE TITLE
masthead nav isn't movable in desktop

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#685]
![screen shot 2015-07-17 at 4 50 20 pm](https://cloud.githubusercontent.com/assets/5479/8759199/f46243b8-2ca3-11e5-89c5-32d52d2231b4.png)

Go to fake library in test package.

Shrink window down to ~795px wide.

(on a macbook air, at least, without retina)

Expected: click and drag the nav in the masthead

Actual: no (apparent?) way to move that nav.

Bonus points: do it without scroll bars.

(haven't tried on a phone, maybe it works there?)

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
I do see the scrolling, on mobile and desktop. You have to click in the subnav header not just the header. I can update it so the whole header scrolls when necessary.

**Comment by sethladd** [comment]
I tried clicking anywhere in the tabs (either the tabs themselves or the div containing all the tabs) and I can't "grab and drag". It's not clear how to scroll that div side to side.

**Comment by devoncarew** [comment]
Hmm, I am able to do that by clicking on the area between the tabs and dragging. I'll update so that same thing works generally in the header. I do think this is a smaller use case for desktop however, as very few pages will have subnav headers that are wide enough to need scrolling.
