### ISSUE TITLE
A read/write field isn't displaying docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#686]
Check out List.length.

Current docs:

![screen shot 2015-07-17 at 5 00 53 pm](https://cloud.githubusercontent.com/assets/5479/8759275/7342d930-2ca5-11e5-86ed-7e87edd441bf.png)

New docs:

![screen shot 2015-07-17 at 5 01 30 pm](https://cloud.githubusercontent.com/assets/5479/8759277/7cd3e660-2ca5-11e5-8ca3-f128e24a42df.png)
![screen shot 2015-07-17 at 5 01 26 pm](https://cloud.githubusercontent.com/assets/5479/8759278/7cd49d62-2ca5-11e5-9189-78db78c1b8bc.png)

**Comment by sethladd** [comment]
cc @keertip 

This is a pretty big issue that we should fix.

**Comment by keertip** [comment]
Will take a look.

**Comment by sethladd** [comment]
To help test, check out the WithGetterAndSetter class in the fake lib of test_package.

**Comment by keertip** [comment]
@sethladd,

What about the case where there is an explicit setter and getter? Do we show the combined documentation?

**Comment by sethladd** [comment]
> Do we show the combined documentation?

We should combine the docs.

**Comment by keertip** [comment]
Right now we don't. Will fix it.

**Comment by sethladd** [comment]
I'll take a look at this

**Comment by sethladd** [comment]
A little better, but not great. Docs for a getter and setters are smushed into one String.

![screen shot 2015-07-20 at 5 08 00 pm](https://cloud.githubusercontent.com/assets/5479/8790370/1078aabe-2f02-11e5-9f6b-455c766387e9.png)

I'd really like to make more of a distinction in the docs. But we can open a new issue for that.
