### ISSUE TITLE
List.reversed docs not appearing

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#688]
Not sure if this is related to https://github.com/dart-lang/dartdoc/issues/686

New docs:

![screen shot 2015-07-17 at 5 15 05 pm](https://cloud.githubusercontent.com/assets/5479/8759368/6e38be4e-2ca7-11e5-8e7c-276ff6c5faab.png)

Current docs:

![screen shot 2015-07-17 at 5 15 40 pm](https://cloud.githubusercontent.com/assets/5479/8759372/7715ef96-2ca7-11e5-900c-6f5237770921.png)

**Comment by keertip** [comment]
This was fixed in  #689.
