### ISSUE TITLE
Annotated By should be comma separated

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#692]
![screen shot 2015-07-20 at 11 04 09 am](https://cloud.githubusercontent.com/assets/5479/8783238/6efaac14-2ecf-11e5-9894-78b65116efb6.png)

**Comment by sethladd** [comment]
I'll take a look.

**Comment by devoncarew** [comment]
Just so you know, I did remove the comma, and have they just separated by whitespace and the `@` char, to parallel what annotations look like in source code. If you want to change it back to commas though, fine by me :)

**Comment by sethladd** [comment]
Oh! I could have left it, but I just fixed it. But I'll leave it as blank.
