### ISSUE TITLE
Find as you type search

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#7]
A developer should be able to "find as you type" to locate docs for classes, libraries, fields, methods, functions, statics.

**Comment by sethladd** [comment]
From https://github.com/dart-lang/dartdoc-viewer/issues/38

Prefer names on the current page, when finding answers.

**Comment by sethladd** [comment]
See also https://github.com/dart-lang/dartdoc-viewer/issues/56

**Comment by sethladd** [comment]
A user would like a shortcut key to easily access the search/find-as-you-type.

See https://github.com/dart-lang/dartdoc-viewer/issues/43

For an example, see how Google Docs works. Cmd-F opens an app-specific search box.

**Comment by sethladd** [comment]
From https://github.com/dart-lang/dartdoc-viewer/issues/66 

When searching for names, prefer definitions over mentions in text.

**Comment by sethladd** [comment]
From https://github.com/dart-lang/dartdoc-viewer/issues/102

(1) suggest should have a smarter ranking. dart:math's max is more popular than dart:html's.
(2) there needs to be some way of discovering every max function, popular or not,
like the wikipedia disambiguation pages.

**Comment by sethladd** [comment]
Thought: we can parse all of pub.dartlang.org and generate a ranking of most used SDK APIs to help better inform ranking.

**Comment by sethladd** [comment]
See also https://github.com/dart-lang/dartdoc-viewer/issues/83

if I type something like "Node.remove" in the search box, it would be nice if dart:html Node.remove was the first result. The old doc viewer supported this, and I thought DartDocViewer did too, so not sure if this is a regression or a feature request. Either way, it would be super helpful :)

**Comment by sethladd** [comment]
See also https://github.com/dart-lang/dartdoc-viewer/issues/107

A request to be able to search for doc-related annotations. In Angular's case, search for all classes marked with ng-class.

**Comment by sethladd** [comment]
Suggestions from @johnmccutchan 

Allow a developer to use modifiers in search, e.g.:

`extends:Element`

`implements:Pattern`

`is:method`

**Comment by sethladd** [comment]
Feedback from beta is that people really want this. Bumping up.

**Comment by sethladd** [comment]
Started with https://github.com/dart-lang/dartdoc/pull/799

**Comment by sethladd** [comment]
By default, the search box does this on mobile:

![screen shot 2015-08-10 at 10 14 58 am](https://cloud.githubusercontent.com/assets/5479/9177840/b6339d3c-3f48-11e5-8d0a-3707095f33b0.png)

cc @devoncarew @keertip 

of course, we can change this. Thoughts?

here it is on desktop:

![screen shot 2015-08-10 at 10 15 42 am](https://cloud.githubusercontent.com/assets/5479/9177850/c5de0466-3f48-11e5-8a5d-ccbc91e36793.png)

**Comment by devoncarew** [comment]
Looks nice! I've also seen the search box replace either the entire top line or most of the top line.

**Comment by sethladd** [comment]
If it replaces the top line, we lose the "what am I looking at" signal, though.

**Comment by keertip** [comment]
Looks good!

**Comment by devoncarew** [comment]
As in, there's a little search icon on the right, clicking on it pops out the search box - covering the header. Dismissing the search would recover the space for the regular header.

**Comment by sethladd** [comment]
> As in, there's a little search icon on the right, clicking on it pops out the search box

Ah, sure, we can try that.

**Comment by sethladd** [comment]
Making progress.

![screen shot 2015-08-10 at 10 05 53 pm](https://cloud.githubusercontent.com/assets/5479/9190604/075e7980-3fac-11e5-8cbf-7f088bebdc15.png)

**Comment by polux** [comment]
Looks good!

**Comment by sethladd** [comment]
PR is ready. Will need tweaks, but I think it's enough to get feedback from real users.

**Comment by sethladd** [comment]
Testing on the core SDK, it's clear we need to rank these. Will look at the previous logic.

**Comment by sethladd** [comment]
We now have basic weighting/sorting:

![screen shot 2015-08-12 at 11 26 30 pm](https://cloud.githubusercontent.com/assets/5479/9243786/a4af8faa-4149-11e5-9cf4-4a83bf9601f4.png)
![screen shot 2015-08-12 at 11 25 43 pm](https://cloud.githubusercontent.com/assets/5479/9243785/a4ad5622-4149-11e5-80c8-f1af257f63f3.png)

**Comment by polux** [comment]
Nice! :+1:

**Comment by sethladd** [comment]
First cut of this is done. Room for improvement, so please try it out and send feedback!

**Comment by polux** [comment]
Awesome! One small gotcha: when you're done generating the doc, dartdoc writes:

    Success! Open file:///.../doc/api/index.html

But when you do this the search box is unavailable because the browser refuses to load the JSON index file. Maybe the message should mention this somehow.

**Comment by sethladd** [comment]
That's a really good point! Please open a new issue so we can address this.

**Comment by polux** [comment]
Created #819.
