### ISSUE TITLE
Don't display comments inside the actual source code

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#711]
<img width="714" alt="screen shot 2015-07-22 at 9 48 55 pm" src="https://cloud.githubusercontent.com/assets/1269969/8843292/8d81131a-30bb-11e5-996c-65da8b8568f7.png">

It seems redundant.

**Comment by sethladd** [comment]
Do you have a mock with alternative?

**Comment by devoncarew** [comment]
Just stripping off leading `\\\` or `/** ... */`.

**Comment by sethladd** [comment]
oh! I didn't understand "function's dartdoc". I thought you meant the docs above.

Yes, stripping off the docs in the source code sgtm

**Comment by sethladd** [comment]
Very nice.
