### ISSUE TITLE
exceptions show up in both the `Classes` list and the `Exceptions / Errors` list

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#712]

**Comment by sethladd** [comment]
good catch!

**Comment by sethladd** [comment]
I'll take this one.

**Comment by sethladd** [comment]
Where did you see this happen? I'm not seeing it in our test package.

![screen shot 2015-07-23 at 2 16 33 pm](https://cloud.githubusercontent.com/assets/5479/8862451/71a36e88-3145-11e5-8988-bd6ff47f1ca5.png)

**Comment by devoncarew** [comment]
When I generated docs for the SDK. Not sure which package exactly.
dart:core?

On Thu, Jul 23, 2015 at 2:16 PM, Seth Ladd <notifications@github.com> wrote:

> Where did you see this happen? I'm not seeing it in our test package.
>
> [image: screen shot 2015-07-23 at 2 16 33 pm]
> <https://cloud.githubusercontent.com/assets/5479/8862451/71a36e88-3145-11e5-8988-bd6ff47f1ca5.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dart-lang/dartdoc/issues/712#issuecomment-124242706>.
>



-- 
Devon Carew
Software Engineer
Google, Inc.

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/724
