### ISSUE TITLE
Problem with old style named constants

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dartdoc#713]
When I generate the documentation for a script:

```dart
const String TYPE_NICE = "nice";
const String TYPE_VERY_NICE = "very_nice";

/// Main function uses [TYPE_NICE] and [TYPE_VERY_NICE].
main(List<String> args) {
}
```

Then there is a problem with constant of a name `TYPE_VERY_NICE`. I found out that the reason is that when I use more than one **underscore**, the constant is written with brackets.

Output of the comment in the documentation looks like this:
Main function uses TYPE_NICE and [TYPE_VERY_NICE].

To see it you need to go to the detail of the function in the documentation.

Same problem with the old docgen: https://github.com/dart-lang/sdk/issues/23883

**Comment by sethladd** [comment]
Thanks for the report! We'll take a look.

**Comment by alan-knight** [comment]
This is probably due to the markdown parser being run first and interpreting the name as TYPE<emphasis>VERY</emphasis>NICE, or something in that vein.

**Comment by sethladd** [comment]
@alan-knight you have a good memory :)

@devoncarew this one is available if you're interested.

**Comment by sethladd** [comment]
Taking a look today.

**Comment by sethladd** [comment]
We think the issue with multiple underscores is in the markdown package. Tracking that separately here: https://github.com/dart-lang/dartdoc/issues/768

**Comment by sethladd** [comment]
I'm going to close this out because we've split this issue into two, one we've addressed now and the other we'll address in the markdown package.

Thank you so much for this report!
