### ISSUE TITLE
Referencing types for method declaration for abstract class doesn't work

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dartdoc#714]
When I generate a documentation for a method declaration in abstract class: 

```dart
abstract class SomeAbstractClass  {

  /// Gets [List] of [params].
  /// Returns [SomeClass].
  SomeClass createSomething(List params);

}
```

and then I view it in generated documentation from some subclass implementation of SomeAbstractClass, then the result is:

`Gets [List] of [params]. Returns [SomeClass].`

e.g. they remain in brackets and no type is referenced.

**It is needed to view the comment for the method from some subclass of SomeAbstractClass to see the bug.**

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
I believe this is addressed by https://github.com/dart-lang/dartdoc/pull/756
