### ISSUE TITLE
Referencing parameters from within comments is not working

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dartdoc#715]
The "old" dartdocgen supports referencing the type with a link to it.

```dart
class SomeDifferentClass {

  /// Gets [List] of [params].
  /// Returns [SomeClass].
  SomeClass createSomething(List params);
}
```

but dartdoc doesn't. The result is:

createSomething(List params) → SomeClass
Gets List of params. Returns SomeClass.

and with dartdocgen:

[SomeClass](#) [createSomething](#)([List](#) [params](#))
Gets [List](#) of [params](#). Returns [SomeClass](#).

Is this bug or feature?

**Comment by sethladd** [comment]
Thanks for the report! Will check it out.

(do you see the links in the main page for the method?)

**Comment by Janamou** [comment]
@sethladd No.
I now noticed that when I link to class which is in the same .dart file, the referencing to class works and also it works for attributes.

**Comment by keertip** [comment]
@Janamou, what did you use for testcase?. 

`dartdoc`  generates links if it can be resolved and the link points to something contained in the package. So in the above case, `List` will not be linked as it is part of the sdk,  `SomeClass` should be linked if it is part of the public api in the same package.

**Comment by maiermic** [comment]
@keertip Is it somehow possible to link to the sdk?

**Comment by keertip** [comment]
@maiermic, yes, it is possible. Feel free to open an issue if this is a feature you would like to see in `dartdoc`.

**Comment by Janamou** [comment]
@keertip ok, thanks for the explanation, makes sense.
Only thing I am now missing is linking to the parameter of the method. Old dartdocgen supports:

```dart
/// Says some [text].
void saySomething(String text) {
  ...
}
```

And then the "text" links to the parameter of the method.

Anyway possibility of linking to the types in the SDK/other library would be also great.

**Comment by sethladd** [comment]
> Only thing I am now missing is linking to the parameter of the method.

We should do this. :)  We'll check that the analyzer supports it (we get the list of names from the comments via the analyzer)

> Anyway possibility of linking to the types in the SDK/other library would be also great.

That's a long-term plan. Probably won't happen for 1.0. But would be cool to see!

Thanks for the additional details!

**Comment by sethladd** [comment]
(marking P2 only because it's not a crashing bug, and because we're not showing wrong info)

**Comment by sethladd** [comment]
Kind of addressed by https://github.com/dart-lang/dartdoc/pull/756

When https://github.com/dart-lang/dartdoc/pull/756 lands, here's what happens:

* doc references to parameters will render as `<code>`
* no links are generated, but they are made visually distinct

There wasn't much value in linking to a parameter, because the parameter is _right there_ :)
