### ISSUE TITLE
Different formatting of code in the output

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dartdoc#716]
Add this comment to some method:

```dart
/// [:ul:] `li`.
```

```ul``` and ```li``` are formatted differently in the output. The [::] uses prettifier, the `` does not.

And in the list of methods, the code is not formatted at all. It is just a text. Maybe it should be also formatted?

**Comment by sethladd** [comment]
I think I noticed that... that's for the description.

**Comment by sethladd** [comment]
I think I found the cause. Now we look like this:

![screen shot 2015-07-23 at 4 46 55 pm](https://cloud.githubusercontent.com/assets/5479/8864739/78b0a21c-315a-11e5-9d05-535276698c5e.png)

**Comment by sethladd** [comment]
Fixed! Thanks for the report.
