### ISSUE TITLE
Can't go to the detail of inherited method

### ISSUE THREAD

**Issue by Janamou** [dart-lang/dartdoc#717]
The inherited methods from external libraries are also listed but the link's `href` is missing url so it is impossible to go to the detail. 

More info: https://github.com/dart-lang/dartdoc/issues/717#issuecomment-125949643

**Comment by sethladd** [comment]
Good catch!

**Comment by sethladd** [comment]
Hi @Janamou can you please provide some detail? I'm not exactly sure what the bug is that you are describing.

**Comment by Janamou** [comment]
@sethladd 
I found out this because of the `Command` class from `args` package. But I have seen same problem with `toString()` method somewhere.

Try this code:
```dart
import "package:args/command_runner.dart";

class SuperAwesomeCommand extends Command {

}
```

Then generate documentation and go to the `SuperAwesomeCommand` class. There are 4 methods mentioned:

addSubcommand
printUsage
run
usageException

When you want to go to the detail of any of these methods, it fails.

Now I see that the reason is that the documentation doesn't know the `Command` class so it can't find the methods. Sorry about me not providing the whole info - will update the first post.

**Comment by sethladd** [comment]
Thanks @Janamou this brings up a good point.

Currently, a subclass doesn't have its own docs for its inherited methods. Those come from the super class.

But if the super class isn't in the current scope for dartdoc, and thus we didn't generate docs for the super class, we don't have any pages for the inherited methods to link to.

Probably the right decision here is to generate docs for inherited methods IFF the superclass is from a different package.

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/750
