### ISSUE TITLE
Pages support in DartDoc

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#72]
For larger projects it would be beneficial to have a way to create pages that are linked in to the larger documentation generator. This provides a way to organize the documentation and to also create documentation outside of the scope of documentation comments.

Example in doxygen
http://www.stack.nl/~dimitri/doxygen/manual/commands.html#cmdpage
And the output
http://www.stack.nl/~dimitri/doxygen/manual/examples/page/html/pages.html

Was: https://code.google.com/p/dart/issues/detail?id=8915

**Comment by keertip** [comment]
Not planned for now

**Comment by jonasfj** [comment]
We kind of have this today, it's called "categories", but it can be used to render markdown pages.
