### ISSUE TITLE
Link from class to full source code

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#73]
Was: https://code.google.com/p/dart/issues/detail?id=8860

It would be nice to have a link from a class page on api.dartlang.org to the full source file where the class is defined.

Either a link to browse source on code.google.com, or embedding the source within api.dartlang.org.

Bonus points - if it is a abstract class, if you can add a link to the private class (or classes) that implement the interface.

Docs are nice, but easily accessible open source code is even better ;)

**Comment by skybrian** [comment]
Still wanted. :-)

**Comment by sethladd** [comment]
yup! patches welcome. Remember, needs to work for 3rd party packages, the SDK, and needs to fail gracefully if you don't have public source.

**Comment by sethladd** [comment]
We're unlikely to do this any time soon. But it would be cool if someone implemented this. Please reopen or comment if you are going to work on this. Thanks!
