### ISSUE TITLE
link to identifiers in sdk on api.dartlang.org from third-party package

### ISSUE THREAD

**Issue by maiermic** [dart-lang/dartdoc#739]
Support links to identifiers (for example `List`) of the sdk. Links sould be added to types in (class-, method-, ...) signatures and in doc comments ([markup links](https://www.dartlang.org/articles/doc-comment-guidelines/#links)).

**Comment by chalin** [comment]
Any update on this? Could it be triaged and marked with a priority level, say, P1 :)

**Comment by kwalrath** [comment]
@devoncarew do we still have someone working on dartdoc?

**Comment by devoncarew** [comment]
@keertip is working on it, but it's not her main task; contributions are welcome here.

**Comment by chalin** [comment]
@devoncarew - Thanks for the update. Could we at least assign a priority level to this issue?
And maybe tag it as [help wanted](https://github.com/dart-lang/dartdoc/labels/help%20wanted) too?

**Comment by jcollins-g** [comment]
Is this a request for external linkage to api.dartlang.org, or a request for auto-include-dependencies to do this?

**Comment by kwalrath** [comment]
The former, I think.

I believe it's a request for externally generated API doc that uses SDK classes to link to the SDK doc, by default. E.g. if an external package (say, [args](https://www.dartdocs.org/documentation/args/0.13.7/index.html)) has a property that's a Map (say, [commands](https://www.dartdocs.org/documentation/args/0.13.7/args/ArgParser/commands.html)), most people would want to be able to click Map and get to https://api.dartlang.org/stable/dart-core/Map-class.html.

Options might be to (1) not generate those links or (2) link to a particular version of the SDK API docs. These links should probably have different default formatting from links inside the same package.

**Comment by jcollins-g** [comment]
OK.  #1368 addressed the latter, the former is definitely on my radar though.  Going to adjust the title of the issue to be more clear.

**Comment by jcollins-g** [comment]
#1524 should make this much easier.  Dartdoc now has some elementary package-boundary awareness that we can use to determine whether alternate hyperlinks should be generated, so it's now just a matter of implementing the generation.
