### ISSUE TITLE
Instruct analyzer to ignore all HTML

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#760]
I don't believe we have any requirement for the analyzer to try to analyze the HTML in our project. I assume this speeds things up, if we ignore `*.html`

**Comment by sethladd** [comment]
@devoncarew is this easy for you to do?

**Comment by devoncarew** [comment]
I think this is taken care of by this file:

https://github.com/dart-lang/dartdoc/blob/master/.analysis_options#L6

@johnmccutchan committed a change will will make sure that our top-level pubspec file can affect exclusions in all sub-dirs. If you're seeing html files being analyzed in the dartdoc project, you're probably running into that. The fix will be in the next dev sdk.

Re: having the analyzer ignore generated docs in general, that seems like a good idea. It already ignores `build/` explicitly. Adding `doc/api/` would make sense as well.

**Comment by sethladd** [comment]
Can we also ignore lib/templates ?

**Comment by sethladd** [comment]
:+1:
