### ISSUE TITLE
dartdoc does not understand sdk_ext

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/dartdoc#763]
sky uses the new sdk_ext feature of the analysis server to define dart:sky.  Unfortunately dartdoc doesn't seem to understand this?

 - create a pubspec.yaml:
```
name: docdemo
dependencies:
  sky: any
```

- create a lib/main.dart:
```
import 'dart:sky';

class Test {
    Color color;
}
```

 - `pub get`
 -  `dartdoc`

Generating documentation for 'docdemo' into /src/docdemo/doc/api/

parsing lib/main.dart...
Parsed 1 file in 3.2 seconds.

[error] Target of URI does not exist: 'dart:sky' at lib/main.dart, line 1.
Generation failed: encountered 1 analysis error.

@abarth

**Comment by keertip** [comment]
@eseidelGoogle, try running `dartdoc` with `--url-mapping` option

**Comment by eseidelGoogle** [comment]
Thats how we handle it today:
https://github.com/domokit/sky_engine/blob/master/sky/tools/skydoc.py

But that should no longer be necessary with the recent analyzer changes is my understanding?

**Comment by keertip** [comment]
Looked at the sdk_ext support in analyzer, have to add code to  `dartdoc` to use that.

**Comment by sethladd** [comment]
Thanks for the report!

**Comment by keertip** [comment]
Looked at this a bit more, there is some logic to initialize package uris and the sdk extensions. This should be in analyzer package instead of analyzer_cli, so that dartdoc  and other tools can make use of it. Will do that, and then dartdoc gets the sdk extensions for free.

**Comment by sethladd** [comment]
Fixed with https://github.com/dart-lang/dartdoc/pull/805

Thanks for the report!
