### ISSUE TITLE
--package-root does not appear to work

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/dartdoc#766]
Here is an example package:
http://filebin.ca/2B2DDfWYrFNu/docdemo.zip

Here is a diff version of that zip:
```
diff --git a/packages/test b/packages/test
new file mode 120000
index 0000000..187d1b6
--- /dev/null
+++ b/packages/test
@@ -0,0 +1 @@
+../test/lib
\ No newline at end of file
diff --git a/test/lib/one.dart b/test/lib/one.dart
new file mode 100644
index 0000000..e4aa859
--- /dev/null
+++ b/test/lib/one.dart
@@ -0,0 +1,4 @@
+import 'packages:test/two.dart';
+
+class One {
+}
diff --git a/test/lib/two.dart b/test/lib/two.dart
new file mode 100644
index 0000000..a5a8403
--- /dev/null
+++ b/test/lib/two.dart
@@ -0,0 +1,2 @@
+class Two {
+}
diff --git a/test/pubspec.yaml b/test/pubspec.yaml
new file mode 100644
index 0000000..b327536
--- /dev/null
+++ b/test/pubspec.yaml
@@ -0,0 +1 @@
+name: test
```
(Note that in the above diff packages/test is a symlink, that's just the way git diff represents it.)

Now attempt to run dartdoc:

```
%dartdoc --input test
Generating documentation for 'test' into /src/docdemo/doc/api/

parsing test/lib/two.dart...
parsing test/lib/one.dart...
Parsed 2 files in 3.0 seconds.

[error] Target of URI does not exist: 'packages:test/two.dart' at /src/docdemo/test/lib/one.dart, line 1.
Generation failed: encountered 1 analysis error.
```

Now try with a --package-root:
```
dartdoc --input test --package-root packages
Generating documentation for 'test' into /src/docdemo/doc/api/

parsing test/lib/two.dart...
parsing test/lib/one.dart...
Parsed 2 files in 3.0 seconds.

[error] Target of URI does not exist: 'packages:test/two.dart' at /src/docdemo/test/lib/one.dart, line 1.
Generation failed: encountered 1 analysis error.
```

It appears the package-root is just being ignored.

**Comment by eseidelGoogle** [comment]
This is the one bug in dartdoc I can't easily work around at the moment.  Short of actually doing a pub get inside the sky package before running dartdoc.

**Comment by keertip** [comment]
Will take a look.

**Comment by keertip** [comment]
@eseidelGoogle, are you passing in the complete path to the directory for package root?

**Comment by eseidel** [comment]
I tried both a relative and absolute path.  "--package-root /src/docdemo/packages" as well as "--package-root packages" when running inside the docdemo directory.  I also tried with and without a = separating package-root and the value.  I didn't try debugging dartdoc itself.

**Comment by keertip** [comment]
How are you running dartdoc? from source? pub global run?

**Comment by eseidel** [comment]
Pub global activate dartdoc
Dartdoc

**Comment by keertip** [comment]
@eseidelGoogle , see that it is 'packages:test/two.dart', should be 'package:test/two.dart'

**Comment by eseidel** [comment]
Apologies. This was an attempt at making a reduction for an error we're
experiencing with the larger sky package.  I'll fix my reduction and see if
I can still reproduce.

**Comment by eseidelGoogle** [comment]
Sigh. My repo was definitely busted.  This can be closed.  I'll figure out what the actual bug is.

**Comment by sethladd** [comment]
No worries. Keep the feedback coming.
