### ISSUE TITLE
Doc references with prefixes do not resolve

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#767]
Considering this code:

```
library foo;

String foo = 'hi';
```

and

```
library bar;

import 'foo.dart' as foo;

/// Testing [foo.foo]
class Bar {

}
```

Expected: the `Testing` comment should have a link to `foo`

Actual: no link is generated. Our current logic can't handle a prefixed name inside of a doc reference.

**Comment by sethladd** [comment]
For now, we wrap prefixed names inside a `<code>` block, inside of a link.

**Comment by sethladd** [comment]
@keertip is this something we should support?

**Comment by keertip** [comment]
The doc reference resolution is done by the analyzer and dartdoc uses that information to generate the links. So if the analyzer cannot resolve the link, not much dartdoc can do there.

**Comment by jcollins-g** [comment]
Replaced with #1402
