### ISSUE TITLE
Ensure: attributes with $ and [ ] in their names are handled

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#77]
Was https://code.google.com/p/dart/issues/detail?id=17346

In html5lib/dom.Node there's an attribute $dom_nodeType,  That confuses the minimap navigation.

Yeah, the minimap for http://www.dartdocs.org/documentation/html5lib/0.12.0/index.html#html5lib/dom.Node is not functional:

    Uncaught FormatException: Invalid character (at character 83)
    ...ocs.org/documentation/html5lib/0.12.0/index.html#html5lib/dom.Node#id_clone

Note: This is also broken for attributes with "[" in their name, e.g.: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-collection.MapBase#id_[]

**Comment by keertip** [comment]
verified.
