### ISSUE TITLE
Impossible to remove "warning: library 'one' has no documentation" for unnamed libraries

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/dartdoc#772]
This is likely tied up in Sky's pattern of using unnamed libraries (which we may need to change if we're just fighting the tools).  See https://github.com/dart-lang/sdk/issues/22836 for other discussion on the issue.

But the following library:

`test/lib/one.dart`:
```
class One {}
```

Will produce a warning:
```
generating docs for library one from one.dart...
  warning: library 'one' has no documentation
```
Which will require a `library one;` statement to solve:

```
/// Library docs!
library one;
class One{}
```

I would recommend clarifying the warning to explain that the library is unnamed and ideally make it possible to document a library w/o adding a `library name;` statement.

**Comment by sethladd** [comment]
Good catch. We're quite pragmatic about this. Agree, we should only warn if a library doesn't have docs IFF it has a name.

Thanks!

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/797

**Comment by sethladd** [comment]
We will only print a warning if the library is not anonymous and it doesn't have docs.
