### ISSUE TITLE
source code be shown with 80 chars on desktop

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#775]
Looks like we're too narrow.

![screen shot 2015-08-07 at 9 05 05 am](https://cloud.githubusercontent.com/assets/5479/9140101/8342eae8-3ce3-11e5-9898-09a6560cb95e.png)

**Comment by jakemac53** [comment]
I noticed this as well, on my computer I needed to make the max width a bit over 1400px in order to fit all 80 chars. I think the actual issue here is the 3 column layout, but switching to a 2 column layout would be a bit more radical of a change :).

**Comment by jakemac53** [comment]
Actually, I tried changing the middle column to 7 column width (from 6) and the right sidebar to 2 (from 3) in the desktop layout, and I think thats a lot better. Causes a bit of overflow in the names on the right column but you can still see enough to be useful.
