### ISSUE TITLE
Library list is on the right at the top level of the SDK, and on the left when inside a library

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#776]
Seems inconsistent.

**Comment by sethladd** [comment]
There is a method to the madness.

The nav on the right is "index for the current page"

The nav on the left is "siblings"

cc @devoncarew

**Comment by sethladd** [comment]
Thanks for the feedback, but will close for now. We might need to revisit the whole "dual nav" thing, but it's not on the immediate radar.
