### ISSUE TITLE
The link highlighting seems too subtle

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#777]
The highlighting on the names that are links doesn't seem visible enough to me on desktop. Or, to put it another way, the names of things don't stand out as much as I'd like. It's hard to scan looking for a name. And parameters that are linked aren't highlighted at all.

**Comment by sethladd** [comment]
Can you take a screenshot for us? Curious where you are looking, specifically.

**Comment by alan-knight** [comment]
![dartdoc](https://cloud.githubusercontent.com/assets/3476088/9142666/19623b20-3cf6-11e5-8e89-6bf9f7d50154.jpg)

**Comment by sethladd** [comment]
Now with more blue!

![screen shot 2015-08-08 at 8 35 49 am](https://cloud.githubusercontent.com/assets/5479/9151012/801af246-3da8-11e5-9977-dc551fef87cd.png)
