### ISSUE TITLE
The order of types of things in the index seems odd

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#778]
For libraries, Typedefs are first, which seems peculiar. Classes are last.

For classes, constants are first, constructors are between properties and methods near the bottom.

**Comment by sethladd** [comment]
cc @devoncarew  any thoughts?

I'm pretty flexible about the ordering.  @alan-knight what is your preferred order?

**Comment by alan-knight** [comment]
Hmmm, not sure. Old dartdoc did, for classes

Constructors
Methods
Static methods
Operators
Properties
Static Properties

Bob recently had a post on the subject of the style guide where he suggests ordering within a source file of roughly

static properties
properties
constructors
operators
static methods
methods

which is rather different, but I'm not sure that source ordering and doc ordering have the same use cases.

I try to think of what the most common uses are. My rationale was constructors first because that's the most likely thing someone wants to do. It's also probably a short section, so easy for someone to glance at and see the one they want without having to scroll. Second is that they have one from somewhere and want to call some operation on it, so methods next. Then static methods because you probably don't want two kinds of methods in widely different sections. I could see putting them before instance as well, as they might be a way to create instances and it's also typically a short section.  Operators should be close to methods, because they're just a special case of them. Could be before, on the short section theory.

In source code it's nice to have the fields first so you know what you're doing in the code. But there are also pathological classes with many many properties, like in dart:html. My feeling was that in usage you're slightly more likely to want to call a method than to access a property, so those went first. And there can be classes with a LOT of static properties, which you occasionally need, but could easily obscure everything else that came after them, so I put them last.

For libraries my thinking was to put properties and functions first because they tend to be very short, then classes, which is the main thing you want. Typedefs you would often get to from a link, and are probably the thing you least often look up directly on the doc page.

Lots of subjectivity, but that was my reasoning.

**Comment by skybrian** [comment]
My first impression was that typedefs should be lower, either above or below exceptions.

**Comment by sethladd** [comment]
this seems to be an area of debate. We really appreciate the feedback, but we don't plan to change it. If this issue gets a lot of feedback from users, we can certainly reopen and reorder things.
