### ISSUE TITLE
Annotations should be one per line?

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#780]
If I look at https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.1/dart-html/Element-class.html it seems odd to have

```
Annotations     @DocsEditable() @DomName('Element')
```

It seems like it would be better to have each annotation on its own line.

**Comment by sethladd** [comment]
Can I ask, what do we gain from using multiple lines? (can you go into what's difficult about the way we have it?)

of course, easy to change, but curious about this one...

**Comment by alan-knight** [comment]
Basically that's how they'd look in source, and also more complicated annotations can be a bit tricky to parse mentally, so having them one per line seems easier to take in.

For a typedef like https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.1/dart-html/MidiSuccessCallback.html if the annotations were one per line rather than comma separated it would actually be valid Dart syntax.

**Comment by sethladd** [comment]
This is an easy change. I think we can do it. Can't guarantee we'll get to it soon, but let's keep it open.

Patches welcome!
