### ISSUE TITLE
Continued lines are not indented on the detail page

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#781]
See e.g. https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.1/dart-html/Element/dragStartEvent.html

where it kind of looks like it's two declarations at the start because the second line isn't indented.

**Comment by sethladd** [comment]
Thanks! Good catch.

![dragstartevent_constant_-_element_class_-_dart_html_library_-_dart_api](https://cloud.githubusercontent.com/assets/5479/9141313/9e62e7f2-3cec-11e5-83bc-690b9ab393f7.png)

**Comment by srawlins** [comment]
Looks like `text-indent` is what we want here. `text-indent: hanging` is not supported yet, so I would recommend:

```css
{
    text-indent: -17px;
    padding-left: 17px;
}
```

on `.multi-line-signature`. Looks pretty good.

**Comment by devoncarew** [comment]
Should be addressed by this: https://github.com/dart-lang/dartdoc/pull/956
