### ISSUE TITLE
Code font seems odd

### ISSUE THREAD

**Issue by alan-knight** [dart-lang/dartdoc#783]
e.g. in https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.1/dart-html/Element/dragStartEvent.html what does it mean that "dragstart" is in bold and fixed width. It's backtick-quoted in the source comment, so it presumably is how we're showing code, but it isn't obvious in the display that that's code, it just kind of looks bold.

**Comment by sethladd** [comment]
Can you suggest an alternative here? We are assuming that fixed-width fonts mean "code" to developers.

You're right, `dragstart` is "code" as the author of the doc comment intended. We used a fixed-width font to signify that.

**Comment by alan-knight** [comment]
Well, I like the way github is `doing` it. The fixed-width font doesn't look bold, and there's a very light grey background on the text that makes it stand out a bit more. And it's consistent with how they display larger blocks

```
  of source code with {
    stuff
  }
```

It also seems slightly smaller, I'm not sure I like that, but it's ok.

**Comment by sethladd** [comment]
gotcha. Thanks! We'll consider this as we tweak styles.

cc @munificent

**Comment by sethladd** [comment]
I'll take a crack at this.

**Comment by sethladd** [comment]
@alan-knight would you expect to have inlined code spans be syntax highlighted?

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/798

**Comment by sethladd** [comment]
cc @devoncarew
