### ISSUE TITLE
Load 1.12-dev for Appveyor builds, re-enable

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#795]
or scoop

**Comment by sethladd** [comment]
Does appveyor need to use a package manager? could we just download a .zip and unzip it?

**Comment by devoncarew** [comment]
Yes, but it's nice to consume a windows package manager, to try and promote having a good windows dart distro...

**Comment by sethladd** [comment]
cc @daftspaniel

**Comment by sethladd** [comment]
Thinking about this more, we shouldn't not be testing on 1.12 + windows just because chocolatey doesn't have 1.12-dev. We don't want to release dartdoc 1.0 without it being tested on windows.

Can we side-load 1.12-dev for now? Not testing on windows scares me.

**Comment by daftspaniel** [comment]
The plan is to create a dart-sdk-dev package once the main packages are semi-automated. Probably going to be a month+ before that happens though.
