### ISSUE TITLE
Ensure: do not show that class X inherits from private class _Y

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#80]
Was: https://code.google.com/p/dart/issues/detail?id=6998

If X inherits from private class _Y, the fact that its members come from _Y is an implementation detail.

I'd argue we should not show any inheritance info for these members -- make them appear as if they were defined in X.

**Comment by sethladd** [comment]
Taking a look.

**Comment by keertip** [comment]
dartdoc does not show the private class _Y, though it does mark the methods/properties as inherited.
