### ISSUE TITLE
underlines in readme not rendered well

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#803]
Given a package with this in the readme:

```
# shrill_tree_0600

A minimal Sky project.
...
```

We see:

<img width="341" alt="screen shot 2015-08-10 at 3 41 36 pm" src="https://cloud.githubusercontent.com/assets/1269969/9186081/91f3c770-3f76-11e5-94df-5bca0df2c77b.png">

**Comment by sethladd** [comment]
same problem that affects pub.dartlang.org. 

See https://github.com/dart-lang/markdown/issues/41

cc @munificent 

Thanks for the report!

**Comment by sethladd** [comment]
@munificent fixed this in markdown, and @keertip updated our dep. Should be fixed!

Thanks all!
