### ISSUE TITLE
Provide a hint where text is hidden behind a link in the overview

### ISSUE THREAD

**Issue by herhut-ggl** [dart-lang/dartdoc#808]
It should be more visible that clicking on a field/method in the class overview leads to more text.

I find it confusing is that when you look at a class like in

../dart-mirrors/MirrorsUsed-class.html

it is non-obvious that there is more text for a property if you click on it. Maybe we can add a little visual clue, like a 'more >>' or just three '...'?

**Comment by herhut-ggl** [comment]
I don't think this has been fixed. I was asking for a visual clue that clicking on the property reveals documentation beyond the one-liner. So maybe adding an ellipsis that forwards to the full text after the one-liner.

**Comment by devoncarew** [comment]
I think our fix wasn't sufficient; we show ellipses if the first paragraph of text runs over, but not if there's a 2nd paragraph (which is not shown in the summary).

**Comment by sethladd** [comment]
Thanks for the report. We can definitely improve this.

**Comment by sethladd** [comment]
We do this now:

![screen shot 2015-08-21 at 3 54 45 pm](https://cloud.githubusercontent.com/assets/5479/9420668/0048a782-481d-11e5-964e-19f1b89b23d8.png)

**Comment by sethladd** [comment]
Will see if users notice this. Can try something else if it doesn't work.
