### ISSUE TITLE
our page header color is too saturated

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#811]
<img width="208" alt="screen shot 2015-08-11 at 1 55 58 am" src="https://cloud.githubusercontent.com/assets/1269969/9194086/81930a9c-3fcd-11e5-9d11-c2fba432ee48.png">

I'd like to find a material design color w/ less saturation.

**Comment by sethladd** [comment]
I really like the blue. I know we've been back and forth on this. The previous color was too muddy, and it didn't match Dart's identity color scheme. We also had reports that the link colors in the page were too muted, so we needed a masthead color that matched the new more contrasty link colors.

**Comment by devoncarew** [comment]
For comparison, here's the color from dartlang's masthead:

<img width="148" alt="screen shot 2015-08-11 at 8 14 19 am" src="https://cloud.githubusercontent.com/assets/1269969/9201299/15500a36-4001-11e5-86e4-827aac189d4e.png">

**Comment by sethladd** [comment]
I'll take it! :)

**Comment by sethladd** [comment]
How's this:

![screen shot 2015-08-24 at 12 49 42 pm](https://cloud.githubusercontent.com/assets/5479/9450629/a0a2b752-4a5e-11e5-8be5-c782bcd0ec1e.png)
