### ISSUE TITLE
Should constants use an arrow and type on the right?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#813]
![screen shot 2015-08-11 at 10 18 41 pm](https://cloud.githubusercontent.com/assets/5479/9217002/f8221708-4076-11e5-8a2c-1e180f9a5efd.png)

We put the type annotation on the right for properties.

cc @munificent

**Comment by munificent** [comment]
I was thinking about that too. I'm all in favor of it.

**Comment by seaneagan** [comment]
Agree since constants are just a special kind of property. But it might be a bit hard to read with the value literals e.g. `APRIL → int = 4`.  Maybe move the value to the next line and get rid of `const` (which is redundant since the section is already labeled "Constants")?:

```
APRIL → int
= 4
```
