### ISSUE TITLE
fails to run after global activation: could not resolve a package location

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#816]
Running dartdoc 0.5.0 after a pub global activate:

```
~/tmp/docs $ dartdoc --sdk-docs
Generating documentation for 'Dart SDK' into /Users/sethladd/tmp/docs/doc/api/

Parsed 18 files in 9.3 seconds.

Unhandled exception:
Could not resolve a package location for base at file:///Users/sethladd/.pub-cache/global_packages/dartdoc/bin/dartdoc.dart.snapshot
#0      _handlePackagesReply (dart:_builtin:416)
#1      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by devoncarew** [comment]
I note that local activations work (pub global activate --source=path .), but hosted activations fail.

**Comment by devoncarew** [comment]
This exception is a little mysterious for me. We shouldn't bubble through any of the exceptions from the Resource class; those should be caught, ignored, and the older resource loading code called.

My only guess here is that the `Resource` ctor is throwing an exception - something we're not taking into account. If that's the case I'm not sure when the code invoking the ctor isn't on the stack.

**Comment by devoncarew** [comment]
Fixed. We have to try the older method before we try the newer resource api. The newer api gets very unhappy w/o a `.packages` file or similar.

**Comment by sethladd** [comment]
Thanks for looking into this!

I was confused by the exception, too. I was surprised I didn't see more of a stack trace from my application.
