### ISSUE TITLE
Comment for properties of a class are duplicated

### ISSUE THREAD

**Issue by Javier-Esteban** [dart-lang/dartdoc#818]
I don't know if it's a bug or my mistake.....
I have a class with a property, and I comment the property, for example:
class car{
///Color of the car
String color;
}

Then, in the documentation generated, by clicking in the property the documentation looks like this:
String color 
read / write 

Color of the car

Color of the car

Why do I get the comment twice?

**Comment by sethladd** [comment]
Thanks! That's probably a bug on our end.

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/821
