### ISSUE TITLE
Misleading message after doc generation

### ISSUE THREAD

**Issue by polux** [dart-lang/dartdoc#819]
When you're done generating the doc, dartdoc writes:

    Success! Open file:///.../doc/api/index.html

But when you do this the search box is unavailable because the browser refuses to load the JSON index file. Maybe the message should mention this somehow. Maybe it could say something like "run python -m SimpleHttpClient in .../doc/ and point you browser to http://localhost:8000/api", which would work for most users. Or there could be `dartdoc serve` command.

**Comment by sethladd** [comment]
Thanks! We should fix this. Patches welcome :)

**Comment by polux** [comment]
Opps, sorry for closing the issue by mistake, reopened.

Instead of embedding we could just tell users to run any server if they want to use the search box, and give a commandline example using `simple_http_server`.

**Comment by sethladd** [comment]
See also https://github.com/dart-lang/dartdoc/issues/854
