### ISSUE TITLE
Ensure: dartdoc can handle analyzer's "Element" and ElementLocator class

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#82]
was: https://code.google.com/p/dart/issues/detail?id=19044

I see http://www.dartdocs.org/documentation/analyzer/0.22.4/index.html with the text

```
Instances of the class ElementLocator locate the analyzer/engine-element.Element associated with a given AstNode.
```

and the return types on the methods (of Element) don't have links.

See screenshot:

![screen shot 2015-01-12 at 12 30 35 pm](https://cloud.githubusercontent.com/assets/5479/5710433/d443161e-9a56-11e4-82d4-10e21a108cd6.png)

**Comment by keertip** [comment]
This is not a bug. The library containing the `Element` class is not visible to users of the `analyzer` library, and is not documented. Hence no links.
