### ISSUE TITLE
https://dartdoc.firebaseapp.com/ isn't updated

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#824]
Any clues as to why?

We link to this from the README... if we don't guarantee that https://dartdoc.firebaseapp.com/ will be up to date, let's unlink from the README.

Thoughts?

**Comment by sethladd** [comment]
cc @devoncarew @keertip

**Comment by devoncarew** [comment]
Don't know - I'll take a look. We could also switch this to the SDK docs
link. Or remove completely. The sample link was more useful early on.

**Comment by sethladd** [comment]
Thanks. If you don't see an immediate cause, let's just remove the link.

**Comment by d2m** [comment]
not sure this is the real issue, but is suspect the firebase job bails at
    `https://github.com/dart-lang/dartdoc/blob/master/tool/grind.dart#L230`

```
@Task('Push a copy of the dartdoc docs to firebase')
firebase() {
  Map env = Platform.environment;

  if (env['FIREBASE_USER'] == null) return;
  if (env['TRAVIS_DART_VERSION'] != 'stable') return;
```

and travis-ci runs the dart dev release

**Comment by devoncarew** [comment]
Ah ha! Good catch @d2m. We changed to just building dartdoc for dev channel when we started consuming the new `Resource` API.

**Comment by d2m** [comment]
@devoncarew - Great, thanks!

**Comment by sethladd** [comment]
Thanks @d2m and @devoncarew !
