### ISSUE TITLE
Support "proxy libraries"

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/dartdoc#825]
`dartdoc` expects the something similar to the following structure:

```
└── lib
    ├── src
    │   └── part_name.dart
    └── library_name.dart
```

However if you have many public libraries in the same package, it starts to get messy. Instead I prefer the following structure;

```
└── lib
    ├── src
    │    └── library_name
    │        ├── library.dart
    │        └── part_name.dart
    └── library_name.dart
```

Where `lib/library_name.dart` only contains the following:

```dart
library proxy.library_name;

export 'src/library_name/library.dart';
```

And `lib/src/library_name/library.dart` contains:

```dart
library library_name;
// ...
```

However this makes `dartdoc` display the public API exposed from `lib/library_name.dart` as being part of the library `proxy.library_name` even though they are parts of the `library_name` library.

I've been playing around with the options to find a way to "redirect" the proxy files, or to just rename the libraries, but I couldn't find a way.

`--url-mapping` seemed promising, but I couldn't get it to work the way I wanted.

Maybe we could have a simple way to just include libraries manually?

```
--include-url=lib/src/library_name/library.dart --exclude=proxy.library_name
```

**Comment by sethladd** [comment]
Hi, thanks for the feedback!

You can include and exclude libraries (by name) but I'm not sure what the effect would be for libraries coming out of src/ directory.

We made a conscious choice to treat libraries inside of lib/src as "hidden", as per the convention semantics from a pub package layout.

We also made a conscious choice to make exported libraries appear as if they are actually part of the exporting libraries. This is because the exported names are actually visible from the exporting library. This matches what the Dart language is doing.

We highly recommend that any public library be put into lib/ directly. If they library is public and meant to be possibly imported, it belongs in lib/

You can still have a single lib/all.dart that simply exports all other public libraries.

**Comment by emilniklas** [comment]
I'm sure the reasons for your choices are good ones. I'm also aware of the whole src/ being considered private thing.

The issue is that if I had my libraries in the lib directory, then every `part` declaration would point way into my src dir:

```dart
// lib/my_component.dart
library my_package.my_component;

part 'src/my_component/my_part.dart';
part 'src/my_component/my_other_part.dart';
// ...
```

Not very elegant, I think. The other option would be to name my exported library something else.

```dart
// lib/my_component.dart
library my_package.my_component;

export 'src/my_component/library.dart';
```

```dart
// lib/src/my_component/library.dart
library my_package.my_component.internal;

part 'my_part.dart';
part 'my_other_part.dart';
```

But then I would have to use that library name in every `part of` declaration...

I just want two things:
• The library for a component of my package to be close to the parts of that library, and isolated from other components/libraries in the package.
• The library names displayed in the docs to be the same that I put in the `part of` declaration

Is this really an impossible scenario?

**Comment by sethladd** [comment]
> The library names displayed in the docs to be the same that I put in the part of declaration

Unfortunately, you won't get that if you are exporting one library through another. When you export, it's as if you're hiding an implementation detail. You don't want your users to know the details of the libraries you are exporting.

> The issue is that if I had my libraries in the lib directory, then every part declaration would point way into my src dir

This is totally legitimate and encouraged, actually :) Lots of Dart apps are written this way.

> The library for a component of my package to be close to the parts of that library, and isolated from other components/libraries in the package.

You could do this by creating sub-directories inside of lib/.

Hope that helps!

**Comment by emilniklas** [comment]
I guess I will figure out a way! Thanks!
