### ISSUE TITLE
Show parent classes in class view

### ISSUE THREAD

**Issue by emilniklas** [dart-lang/dartdoc#826]
I would be nice to have a link to the class that a class implements or extends.

**Comment by sethladd** [comment]
Hm, I thought we did that?

![screen shot 2015-08-20 at 8 52 12 am](https://cloud.githubusercontent.com/assets/5479/9388182/c452f70a-4718-11e5-9df2-8db7455bddd0.png)

Do you have a case where that is not happening?

**Comment by emilniklas** [comment]
You certainly did...
