### ISSUE TITLE
build with stable again

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#827]
Once the `Resource` API hits stable.

**Comment by devoncarew** [comment]
See https://github.com/dart-lang/dartdoc/issues/824.

**Comment by devoncarew** [comment]
Also, revert https://github.com/dart-lang/dartdoc/pull/828 when this fix lands.

**Comment by sethladd** [comment]
We can do this now. 1.12 is stable. ENGAGE THE BOT ARMY.

**Comment by sethladd** [comment]
Thanks!
