### ISSUE TITLE
Links in homepage content broken

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dartdoc#829]
If you go to https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.8/index.html and try to click on the `dart:core`, `dart:html`, or `dart:io` links in the center content section, you get a 404.

**Comment by keertip** [comment]
Ah, thanks for catching this. Those links have to be updated.

**Comment by sethladd** [comment]
Good catch, thanks!

**Comment by sethladd** [comment]
CL https://codereview.chromium.org/1299873003/

**Comment by sethladd** [comment]
CL landed. Thanks @keertip !

**Comment by sethladd** [comment]
Dupe: https://github.com/dart-lang/dartdoc/issues/844
