### ISSUE TITLE
Find as you type: exact matches should rank higher

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dartdoc#830]
When I search on "html", the top match is the "HtmlEscape" class. It seems like entities whose name is exactly "html" should be at the top?

(In this case, "dart:html" and the Html property on ContentType.)

**Comment by sethladd** [comment]
Good catch. Seems very reasonable to expect to match exact names for dart: libraries.

However, I need to double check on matching the Html property of ContentType... generally we prefer class names, and "higher level" things like libraries. But... perhaps we should score exact property names higher.

**Comment by skybrian** [comment]
The place where ranking will matter is for short, common names. (If there were a property named "item", would it should up in the search results at all?)

I also noticed that nothing shows up for single-letter searches like "x" and "y". It seems a bit surprising that we have no single-letter properties or methods.

**Comment by sethladd** [comment]
Good point. Right now, we're only searching starting at three characters. That's an artificial limit. Can bump to a single character.

**Comment by skybrian** [comment]
The number of matches might be pretty high, so for 1 and perhaps 2 letters I think it makes sense to only return exact matches.

**Comment by sethladd** [comment]
> The number of matches might be pretty high, so for 1 and perhaps 2 letters I think it makes sense to only return exact matches.

Agreed.

**Comment by sethladd** [comment]
Some improvements:

single letter exact matches:

![screen shot 2015-08-21 at 1 54 25 pm](https://cloud.githubusercontent.com/assets/5479/9418889/3495ff28-480c-11e5-87a2-a29ef859818a.png)

matching names prefixed by dart:

![screen shot 2015-08-21 at 1 55 13 pm](https://cloud.githubusercontent.com/assets/5479/9418902/4928c4f2-480c-11e5-9246-a6ecf64d9198.png)

**Comment by sethladd** [comment]
Landed some improvements. I'm sure we can do more, so please help us by opening issues specifically for other cases we can improve.
