### ISSUE TITLE
Tags in right hand nav bar of MapBase do not work

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#833]
Go to class MapBase:

https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.8/dart-collection/MapBase-class.html

then, on the right column, click on the METHODS link. I end up with a blank page that has this URL:

https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.8/#methods

In fact, this seems to be the case for the links in the right column for all classes, not just MapBase.

**Comment by sethladd** [comment]
Dupe: https://github.com/dart-lang/dartdoc/issues/835

**Comment by sethladd** [comment]
This was a poor decision decision on my part. We don't currently generate a page for inherited methods, thus we don't have a link.

Will fix.

**Comment by sethladd** [comment]
Thanks! Perhaps #835 isn't actually a dupe then. The "poor decision" comment really applies to #835.

Glad you got this one fixed :)
