### ISSUE TITLE
Inherited methods don't link to full method

### ISSUE THREAD

**Issue by rmacnak-google** [dart-lang/dartdoc#835]
E.g., in 
https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.8/dart-mirrors/InstanceMirror-class.html

The description for 'delegate' is truncated but there's no link to the full description.

**Comment by sethladd** [comment]
Closing as dupe.

Thanks for the report!

**Comment by sethladd** [comment]
Not actually a dupe. Definitely need to fix this.

**Comment by sethladd** [comment]
cc @eseidel

**Comment by sethladd** [comment]
Addressed by https://github.com/dart-lang/dartdoc/pull/867

**Comment by sethladd** [comment]
Example, with tons of links that weren't there before:

![screen shot 2015-08-27 at 11 56 32 am](https://cloud.githubusercontent.com/assets/5479/9530105/ba3eb3e0-4cb2-11e5-91ea-1fd931db8ffe.png)
