### ISSUE TITLE
Constants list is scary

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dartdoc#842]
Looking at https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.8/dart-html/Element-class.html, the list of constants is really hard to read and makes me hesitate to look at anything else on the page. (Being able to collapse the whole section would be nice, but I'll file a separate bug about that.)

Here's what the new Element page looks like:

![image](https://cloud.githubusercontent.com/assets/2164483/9398576/6e4e5bc0-475d-11e5-8b9a-ae5a0ace336b.png)

It also seems like overkill to have to go to another page to see the complete doc for a constant.

The previous treatment of constants is more readable (although I much prefer the name "Constants" to "Static Properties"!):

![image](https://cloud.githubusercontent.com/assets/2164483/9398620/bf40a0ec-475d-11e5-9f47-1dd0cdd2cbd7.png)

I'm fine with Constants being first, but (especially if they're going to be documented on separate pages) I'd really like to see a simpler, less implementation-heavy list of constants. Something like this, maybe:

## Constants
<table>
<tr>
  <td><b>abortEvent</b><br>EventStreamProvider&lt;Event></td>
  <td>Static factory designed to expose abort events to event handlers that are not necessarily...</td>
</tr>
<tr>
  <td><b>beforeCopyEvent</b><br>EventStreamProvider&lt;Event></td>
  <td> Static factory designed to expose beforecopy events to event handlers that are not necessarily...</td>
</tr>
</table>

Or this:

## Constants
<table>
<tr>
  <td>EventStreamProvider&lt;Event></td>
  <td><b>abortEvent</b> <br>
      Static factory designed to expose abort events to event handlers that are not necessarily...</td>
</tr>
<tr>
  <td>EventStreamProvider&lt;Event></td>
  <td><b>beforeCopyEvent</b><br>
      Static factory designed to expose beforecopy events to event handlers that are not necessarily...</td>
</tr>
</table>

Or even this:

## Constants
<table>
<tr>
  <td>EventStreamProvider&lt;Event><br>
         <b>abortEvent</b>
  </td>
  <td>Static factory designed to expose abort events to event handlers that are not necessarily...</td>
</tr>
<tr>
  <td>EventStreamProvider&lt;Event><br>
        <b>beforeCopyEvent</b></td>
  <td> Static factory designed to expose beforecopy events to event handlers that are not necessarily...</td>
</tr>
</table>

**Comment by alan-knight** [comment]
It is scary. It's also noticeable that it has the type declaration in front, so constants are different from non-const properties for no obvious reason.

**Comment by sethladd** [comment]
Thanks for the feedback! We felt there was real value in showing what the value of a constant is. Maybe we can show that in another way.

**Comment by alan-knight** [comment]
It's convenient when the value is 3, or 'copy'. It's less convenient when you end up with the Java-esque

EventStreamProvider<Event> beforeCopyEvent = const EventStreamProvider<Event>('beforecopy')

**Comment by sethladd** [comment]
True. But I'd like to see if we can solve this with different formats.
