### ISSUE TITLE
Allow readers to hide/collapse sections

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/dartdoc#843]
If I'm not interested in the Constants section of https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.8/dart-html/Element-class.html, for example, then I should be able to collapse it by clicking a little triangle next to the "Constants" header.

Same goes for other sections (including the description), although obviously the stuff that comes first is more likely to be collapsed. E.g., if I'm only interested in constructors, it should be easy for me to collapse every section before it (with one or more clicks) or to quick jump down to the constructor section.

**Comment by sethladd** [comment]
> to quick jump down to the constructor section.

Did you happen to see the list of nav headers in the blue masthead?

![list_class_-_dart_core_library_-_dart_api](https://cloud.githubusercontent.com/assets/5479/9414685/340b5f5c-47ef-11e5-994e-55301cb8a5ec.png)

**Comment by kwalrath** [comment]
Heh, no I didn't notice those. Maybe I'd scrolled down a little too far. But I do like having them.

But I'd still like to be able to hide all constants/methods/whatever.

**Comment by sethladd** [comment]
We don't have this on our radar, but it's not a bad idea. If someone wants to implement this, please leave a comment or reopen. Thanks!
