### ISSUE TITLE
'Loading search...' text displayed indefinitely if loaded from file:

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#854]
When the docs are loaded from the local file system (not a web server). We can't do XHR requests in this case and we get an error back trying to load the index resource. Possibly just check for the error and clear the loading text? I don't think we need to support search in this case.

<img width="248" alt="screen shot 2015-08-24 at 7 21 29 am" src="https://cloud.githubusercontent.com/assets/1269969/9442498/1732f31a-4a31-11e5-832e-e715d2ecbd3f.png">

**Comment by sethladd** [comment]
![screen shot 2015-08-24 at 12 42 17 pm](https://cloud.githubusercontent.com/assets/5479/9450470/9558e552-4a5d-11e5-9ffc-3b002b603ab1.png)

How's this?

**Comment by devoncarew** [comment]
+1. We could also consider removing the placeholder text in these situations.

**Comment by d2m** [comment]
See #894
