### ISSUE TITLE
Grinder task to ensure we're publishing master, and up to date with origin

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#855]
I accidentally published a version of dartdoc that didn't contain everything from origin/master.

I use the `grind publish` which performs other checks before publish. It should be extended to also support checking that the local master matches origin/master.

**Comment by sethladd** [comment]
cc @devoncarew @keertip FYI

**Comment by srawlins** [comment]
I don't think this has been an issue recently.
