### ISSUE TITLE
Link from mixin/abstract method to list of concrete classes it's available in

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#864]
For example, https://new-dartdocs-dot-dartlang-api.appspot.com/1.12.0-dev.5.10/dart-collection/ListMixin/fold.html

From that page, it would be pretty great to jump to a list of concrete classes where this is available (e.g., it should say "found in List, etc")

![screen shot 2015-08-26 at 1 44 49 pm](https://cloud.githubusercontent.com/assets/5479/9505715/dd933182-4bf8-11e5-82ba-0842a3b0778f.png)

**Comment by keertip** [comment]
It is not easy to get this information from the abstract method. An index of all the analyzed elements would be needed to get the info, which is not available in the analyzer.
