### ISSUE TITLE
Speed up dartdoc

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#869]
Some megamorphic calls we might be able to reduce:

![screen shot 2015-08-27 at 6 42 02 pm](https://cloud.githubusercontent.com/assets/5479/9537308/7827e880-4ceb-11e5-80d3-9da27f3e89b6.png)

**Comment by devoncarew** [comment]
Just some more data points:

https://travis-ci.org/dart-lang/dartdoc/builds/78259935

our current build takes 15-16 minutes to spit out the sdk docs.

**Comment by sethladd** [comment]
Did you happen to grab a profile?

* How much time is spent generating files?
* How much time is spent running tests, etc?
* How much time is spent uploading somewhere?

We have tons and tons of files now. To solve this, we'll need a multi-pronged approach.

* See what we can do to speed up the app. Would Isolates help? Would profiling help?
* See if there are low-hanging fruits for the build process itself.

**Comment by devoncarew** [comment]
Just from watching the build on travis (some simple spot checking) it looked like most of the time was spent building the sdk docs. There's probably a few quick changes to speed our generation time up. We're lazily computing some info; perhaps caching it the first time it's requested would do it.

**Comment by sethladd** [comment]
> There's probably a few quick changes to speed our generation time up. 

That would be awesome if there were a few quick things to do. +1 for quick wins :)

**Comment by sethladd** [comment]
@keertip is looking at generating less files, which should help.

**Comment by keertip** [comment]
addressed with #892

**Comment by sethladd** [comment]
Yay!  How much faster?

**Comment by keertip** [comment]
Takes about 2 mins on my machine.

**Comment by sethladd** [comment]
For the core SDK?  (cause that's fast! :)

**Comment by keertip** [comment]
Yes, for the core SDK.
