### ISSUE TITLE
Ensure: list what _implements_ a class

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#87]
Was https://code.google.com/p/dart/issues/detail?id=16439

'implements' is as common as 'extends'

**Comment by keertip** [comment]
dartdoc shows implements, extends and mixins.

![screen shot 2015-05-05 at 2 53 01 pm](https://cloud.githubusercontent.com/assets/2192312/7483764/8a61cd72-f336-11e4-9238-9a3c4d123543.png)

**Comment by bseib** [comment]
counter example:

What (known) classes extend the abstract class `Type

![image](https://cloud.githubusercontent.com/assets/1313561/7486039/afd78a98-f36c-11e4-91d3-d43789bf60a6.png)

**Comment by sethladd** [comment]
I'm not a total expert of this part of the spec, but classes aren't first class. The runtimeType of an instance is of type Type. A class doesn't subclass from Type.

**Comment by bseib** [comment]
Do I understand the original issue correctly?  That the generated Dart docs didn't show what known classes implement the class you're reading about?

For example, the abstract class `HashMap`:

![image](https://cloud.githubusercontent.com/assets/1313561/7486226/224e8ea2-f370-11e4-9ff9-16b2d90f6cea.png)


In the docs I can easily see that it implements `Map`, but I don't know what classes implement *it*. (And perhaps that's not what this github issue was about.)

If I grep the sdk sources, I discover that `LinkedHashMap` implements `HashMap`.

    zbox:/home/hub/bseib/git/bleeding_edge/dart/sdk/lib (master u=)$ grep -r "implements HashMap" ./*
    ./_internal/compiler/js_lib/collection_patch.dart:class _HashMap<K, V> implements HashMap<K, V> {
    ./collection/linked_hash_map.dart:abstract class LinkedHashMap<K, V> implements HashMap<K, V> {

It would be useful to see all known implementing classes in the docs. It helps one navigate and understand the relationships of the libraries at our disposal.

**Comment by sethladd** [comment]
Ah... it sounds like you're asking for "implemented by". Yes, that is useful. Looks like we have this:

![screen shot 2015-05-05 at 8 24 00 pm](https://cloud.githubusercontent.com/assets/5479/7487057/b5e7b988-f364-11e4-951e-4c4f458114b9.png)

**Comment by bseib** [comment]
Yes, where it says "Implementors" -- I'm looking for that. What's the URL for your example page? Or is this the output of a newer dartdocgen?

**Comment by sethladd** [comment]
Yes, it's the new output from the dartdoc tool (which is the tool from this repo :)
