### ISSUE TITLE
Ensure: inherited generics are clear

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#88]
Was https://code.google.com/p/dart/issues/detail?id=20167

String docs list the compareTo method as inherited from Comparable<T>, and lists the signature as

    int compareTo(T other)

which is not particularly clear, as String doesn't have a parameter T. String is listed as 

     implements Comparable<String>

so it may be that we could resolve the parameter when generating the docs. I'm not sure how common this is in non-core library code, so it might also be reasonable to special-case it.

**Comment by keertip** [comment]
Verfied. In dartdoc, the index page for `String` shows the `compareTo` method as taking a `String` parameter. The method page takes you to `Comparable.compateTo` where the parameter is `T`
