### ISSUE TITLE
If a const is just an alias, it should link to the other const

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dartdoc#880]
On the web_gl front page [1], there are a bunch of constants that are just aliases. For example:

int ACTIVE_ATTRIBUTES = RenderingContext.ACTIVE_ATTRIBUTES
const

It seems like I should be able to click on the second "ACTIVE_ATTRIBUTES" and it should take me to the other const. Similarly on the detail page [2].

[1] https://api.dartlang.org/1.12.0/dart-web_gl/dart-web_gl-library.html
[2] https://api.dartlang.org/1.12.0/dart-web_gl/ACTIVE_ATTRIBUTES.html

**Comment by seaneagan** [comment]
According to #97 it should work now, but clearly it doesn't in the docs you linked.

**Comment by sethladd** [comment]
The api.dartlang.org site needs to have its contents regenerated. It's on an older version of the docs. See https://github.com/dart-lang/api.dartlang.org/issues/42

**Comment by sethladd** [comment]
Closing out, but thanks for the feedback!
