### ISSUE TITLE
Pub readme issues

### ISSUE THREAD

**Issue by kirbyfan64** [dart-lang/dartdoc#885]
If I click the link to the contributor docs , I get a 404 not found error.

And then there's this stuff at the end:

![Image](http://s18.postimg.org/cnmjggsvd/Screenshot_2015_09_02_09_28_32.png)

**Comment by sethladd** [comment]
Thanks!

**Comment by sethladd** [comment]
cc @Sfshaza now we know we shouldn't use HTML in READMEs :)
