### ISSUE TITLE
Show where in the inheritance tree a name came from

### ISSUE THREAD

**Issue by skybrian** [dart-lang/dartdoc#887]
I was looking for the best way to determine whether a file exists. Looking at this page:
https://api.dartlang.org/133421/dart-io/File-class.html

In the right-side method listing, inherited methods aren't clickable, but there is a definition. It seems like it should link to the definition (on the same page).

The definition looks like this:

stat() → Future<FileStat>
inherited
Calls the operating system's stat() function on the path of this FileSystemEntity. Identical to FileStat.stat(...

I wanted to know which class the stat() method is inherited from, but it doesn't say. Perhaps "inherited" should be a link to the inherited method in the other class? Also, the description is cut off and I don't see any way to reveal it.

**Comment by sethladd** [comment]
That's fixed in dartdoc proper. Looks like we need to bump the SDK.

@keertip is this something you can help with?

Meanwhile, I'll clarify this issue as "show where in the inheritance tree a name came from". Would that be accurate?

**Comment by skybrian** [comment]
I'm not sure which fixes are included in "that's fixed", but it sounds okay.

**Comment by sethladd** [comment]
Oh, sorry.

> In the right-side method listing, inherited methods aren't clickable

Is fixed, I think we need to bump the version of dartdoc used by the SDK.

**Comment by keertip** [comment]
@skybrian , if you click on the method, the page that is opened is the method definition in the other class. Though not quite what you are asking for?

**Comment by skybrian** [comment]
Yes, this looks okay to me. Inherited methods are in italics and if you click on them, you can see where they came from.
