### ISSUE TITLE
FileList shows two entries for length property

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#889]
![screen shot 2015-09-02 at 3 40 22 pm](https://cloud.githubusercontent.com/assets/5479/9646481/f96dd58e-5188-11e5-9c7e-ee89d2fc8e06.png)

https://api.dartlang.org/1.12.0/dart-html/FileList-class.html

**Comment by sethladd** [comment]
fyi @keertip in case you run into this root cause

**Comment by keertip** [comment]
Yes, saw that when I was making other changes. PR coming soon!

**Comment by sethladd** [comment]
Oh, nice!!
