### ISSUE TITLE
Ensure: double's ~ and % are linked correctly

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#90]
Was https://code.google.com/p/dart/issues/detail?id=20689

Go to the int docs: https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.double

Try links for the following operators in the minimap:

"%" leads to top of the page (location says https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.double#id_%)
"-" and "unary-" lead to top of the page (location says https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core.double)
"~/" leads to dart:core library (location says https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core#id_~dart-core)
Also "~" in int leads to Dart API Reference home (location says https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-core#id_~home)

This occurs in Chrome 36 and FF 31.  I'm not sure if this is a polymer bug or dart:uri or pkg:docgen or ...

**Comment by keertip** [comment]
verified.
