### ISSUE TITLE
Display all interfaces a class transitively implements

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#901]
Right now, a class displays only the interfaces it implements directly. This means the user has to traverse through its entire inheritance tree to find everything it implements—for example, it's not clear that [`Utf8Decoder`](https://api.dartlang.org/1.12.0/dart-convert/Utf8Decoder-class.html) implements `StreamTransformer`, even though that's an important part of how it's used.

**Comment by sethladd** [comment]
thanks for the feedback!

**Comment by srawlins** [comment]
There is a breadcrumb trail of superclasses. [https://api.dart.dev/stable/2.9.0/dart-convert/Utf8Decoder-class.html] now shows StreamTransformerBase.
