### ISSUE TITLE
404 for linking from dart:io to Future

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#904]
See https://api.dartlang.org/1.12.1/dart-io/HttpClient/getUrl.html

Specifically, see the Future as return type is linked to dart-io/Future... instead of dart-async/Future...

FWIW the page was generated by dartdoc version 0.6.2

**Comment by sethladd** [comment]
BTW should we turn the link checkers on for the SDK build? It would have caught this.

cc @keertip @devoncarew

**Comment by keertip** [comment]
Generated the sdk docs locally and I still see the problem.

**Comment by sethladd** [comment]
Thanks for checking.

We don't run the link checker on the Core SDK docs, only docs from our test_package. Maybe we should run the link checker on the core SDK docs as generated by Travis, too.

**Comment by keertip** [comment]
Yes, we should. Will look at fixing the issue and then enable the checking too.

**Comment by sethladd** [comment]
Rock on!
