### ISSUE TITLE
Prefer to hide the SDK rather than the contents of the specific class

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/dartdoc#906]
In constricted width scenarios, it's probably better to hide the SDK than the structure of the currently library.

I've just been presented with this:

![image](https://cloud.githubusercontent.com/assets/2978182/9981288/40dbbb3a-5fb1-11e5-9fdd-4c10afd73aa9.png)

And found it very confusing as to why the methods that I know exist on File object are not visible in the page - the only things that are functions of the package.

I think we need to assume that users who have got to the page 'File' are interested in the details about that class over its position in the SDK. Hence prefer to hide the LHS column. 

If analytics shows that hierarchical browsing is more common than arrival from a search engine I could be persuaded that the current behaviour is correct.

**Comment by sethladd** [comment]
cc @devoncarew for his thoughts on this as he's the original designer, IIR

**Comment by keertip** [comment]
We now show the class info on RHS, so most likely this is no longer an issue?

![screenshot from 2015-12-07 09 11 11](https://cloud.githubusercontent.com/assets/2192312/11633893/9d1e4ff4-9cc2-11e5-813f-b8191d46aa80.png)
