### ISSUE TITLE
On mobile, the nav menu doesn't show up on the index page

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#908]
It does show up for the other pages, like the library pages. By nav menu, I mean the hamburger menu icon.

**Comment by devoncarew** [comment]
The primary page for sky:

<img width="243" alt="screen shot 2015-09-26 at 4 17 38 pm" src="https://cloud.githubusercontent.com/assets/1269969/10120322/314b4d6c-646a-11e5-9401-26b59a59d9ff.png">

A library page:
<img width="225" alt="screen shot 2015-09-26 at 4 17 45 pm" src="https://cloud.githubusercontent.com/assets/1269969/10120323/315f9f10-646a-11e5-9e96-88e16a217dd6.png">

From the primary page, you can't use go to the libraries using the nav menu, which you can from the library pages. I definitely feels odd.

**Comment by sethladd** [comment]
Adding to 0.7 because this is labeled a P1

**Comment by sethladd** [comment]
Just checking... is this a P1? Would we hold 0.7 for this?

**Comment by devoncarew** [comment]
Well, I wouldn't hold up a release, but it would be nice to have.
