### ISSUE TITLE
Ensure: Documentation of Converter lists dart-convert.StreamTransformer as its superclass, but it's a re-export from dart-async

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#91]
Was https://code.google.com/p/dart/issues/detail?id=20052

https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-convert.Converter lists StreamTransformer as a supertype, but the link is broken.

Similarly, https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart-async.StreamTransformer doesn't list any subtypes.

This looks like a re-export issue. dart-convert.Converter lists dart-convert.StreamTransformer as its superclass.

**Comment by keertip** [comment]
Verfied
