### ISSUE TITLE
Search should allow fully qualified name

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dartdoc#916]
On api.dartlang.org I currently can't search for "List.add". I have to search for "add" and then select the right one from the drop-down.

**Comment by sethladd** [comment]
Agreed!  Dupe of https://github.com/dart-lang/dartdoc/issues/837

**Comment by floitschG** [comment]
Sorry. Went through all open bugs, but missed that one...

**Comment by sethladd** [comment]
No problem! We'll take care of dupes if we know about them. Just happy we get feedback!
