### ISSUE TITLE
Map type is sometimes shown with only one generic argument type

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dartdoc#917]
for the invocation-class [0] the Map type for the named arguments states that it only has one generic argument. I'm guessing the second one is `dynamic`, but it's not clear.

[0] https://api.dartlang.org/1.12.1/dart-core/Invocation-class.html

**Comment by sethladd** [comment]
Good catch, thanks!

here's a direct link to the named arguments: https://api.dartlang.org/1.12.1/dart-core/Invocation/namedArguments.html

**Comment by sethladd** [comment]
Duped by https://github.com/dart-lang/dartdoc/issues/919
