### ISSUE TITLE
Missing 'dynamic' in type parameters

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dartdoc#919]
`Map<Symbol>` below should be `Map<Symbol, dynamic>`
Omit the type parameters only when all are dynamic.

https://api.dartlang.org/1.12.1/dart-core/Function/apply.html
```
dynamic apply( 
    Function function,
    List positionalArguments,
    [Map<Symbol> namedArguments]
)
```

**Comment by sethladd** [comment]
Thanks for the report! Got two of these today :)
