### ISSUE TITLE
Ensure: don't assume that package foo has a library foo

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#92]
Was https://code.google.com/p/dart/issues/detail?id=20941

docgen should not assume that lib/foo.dart exists in the foo package.

See http://www.dartdocs.org/buildlogs/b-2eb60dabc40a9a8e94c7486eeed95-startupscript.log for an example (look for "docgen")

**Comment by keertip** [comment]
This is not a problem with dartdoc. The start page is always index.html and dartdoc generates pages for all the libraries it finds in lib. There are no assumptions of the names of the dart files.
