### ISSUE TITLE
search box dropdown usability issues

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dartdoc#920]
I'm finding the search box dropdown could be better. I feel like it slows me down more than it should.

_Suggestions in italics_.

If I enter 'add' into the search box I get _some_ suggestions (10, I think)
I don't find them compelling.
List.add and Set.add are not included.

I can't get to List.add without knowing it exists, going to 'List' and then scanning the methods for 'add' (fixing https://github.com/dart-lang/dartdoc/issues/837 would help somewhat)

_Prioritize common interfaces_.

Some typed array add() methods are included (but others are not), even though they are all useless methods that throw because typed arrays are not extendable.

_Filter out or deprioritize methods that always throw_.

A single word is not sufficient for searching a big corpus. Allow multiple words 
Example: I enter "List add"
I would expect these to be high on the results:
List.add, List.addAll, ListQueue.add

The dropdown box has some physical difficulties.
There is a scroller, even though the box could easily be 2x deeper (or even 6x deeper on my big monitor). The scroller disrupts flow - I have to click on the scroller to see entries and then click back in the box to change my search

_Avoid the need to scroll unless absolutely necessary_.
_Make size of dropdown larger when the page size allows it_.

It is not clear that the presented methods are a subset of what is available.

_Have a way to see more completions_.
_Consider making the dropdown scrolling be an infinite list of all results_.
_Consider having dropdown list contain some expandable hierarchy_.

**Comment by sethladd** [comment]
Thanks for the feedback! In the meantime, don't underestimate the power of Google. Our SEO is already much much better. I'm finding I need the little search box less and less.

That said, we can of course continue to improve the little search box.

**Comment by sethladd** [comment]
https://github.com/dart-lang/dartdoc/issues/837 addresses the request to be able to search for List.length.

We don't intend to support "List add" because "List.add" should work. We want to avoid building a generalized search engine :)

> The scroller disrupts flow

You should be able to use the down arrow key. Flow is this: click in search box. Start typing. Use down arrow to move through results.

For the other feedback, we need to split into individual issues.

**Comment by sethladd** [comment]
I created individual actionable requests for the feedback we're more likely to get to. I'll close this combo-issue. Again, thanks for the feedback!
