### ISSUE TITLE
for mobile, it would be great to have the breadcrumbs show up on the top line

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#926]
For mobile, it would be great to have the breadcrumbs show up on the top line. So, just to the right of the nav menu. When the user scrolls down, we put the page title in that area. When the header is fully expanded though, it feels like it should show the breadcrumbs.

<img width="225" alt="screen shot 2015-09-26 at 4 17 45 pm" src="https://cloud.githubusercontent.com/assets/1269969/10120329/9b88f576-646a-11e5-814c-3c871f473349.png">

**Comment by jcollins-g** [comment]
I'm not sure that this is relevant anymore given the direction dartlang.org is heading wrt style.  @devoncarew agree?

**Comment by devoncarew** [comment]
agree this can be closed -
