### ISSUE TITLE
Content should hide overflow

### ISSUE THREAD

**Issue by cooler-king** [dart-lang/dartdoc#928]
Really long words can overflow the content into the right side index.

![dartdoc_overflow](https://cloud.githubusercontent.com/assets/11008367/10134708/d8bd02a6-65b5-11e5-91ea-844cd41e6512.png)

**Comment by sethladd** [comment]
Thanks!

**Comment by srawlins** [comment]
I would recommend `overflow-x: scroll` on `.main-content`, but that might be too much. You can play with it here:

* [quantity-library](http://www.dartdocs2.com/documentation/quantity/0.1.0/quantity/quantity-library.html)
* [quantity's googol](http://www.dartdocs2.com/documentation/quantity/0.1.0/quantity/googol.html)

**Comment by sethladd** [comment]
Nice! Patches welcome :)

**Comment by jcollins-g** [comment]
This was fixed at some point, overflow no longer happens.
