### ISSUE TITLE
push a new build; get the latest dartdoc into the sdk

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#929]
we should push a new build to pub, and get the latest bits into the sdk before the 1.13 cutoff.

**Comment by sethladd** [comment]
Let's a take a look at open issues and see if we can fix annoying bugs.

* https://github.com/dart-lang/dartdoc/issues/917

**Comment by sethladd** [comment]
We should also regenerate all the docs and re-upload (if only to get the canonical hrefs published)

**Comment by sethladd** [comment]
We may want to look at https://github.com/dart-lang/dartdoc/issues/943 first.

**Comment by sethladd** [comment]
0.7 is now published into pub and the SDK.
