### ISSUE TITLE
Ensure: show type parameters for generic superclass in Inherits

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#93]
Was: https://code.google.com/p/dart/issues/detail?id=16145

In https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:io.HttpServer

Expected:
Implements: Stream<HttpRequest> Extends: Object
...with 'HttpRequest' a link to the associated docs

Actual:
Implements: Stream Extends: Object

**Comment by keertip** [comment]
Verified.
