### ISSUE TITLE
Don't fail build build if docs fail, or times out, to upload to firebase

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#930]
https://travis-ci.org/dart-lang/dartdoc/jobs/82595703

failed the build :(

**Comment by devoncarew** [comment]
Unfortunately, I think this is an intermittent failure from firebase. We can either live with that or remove the upload to firebase.

**Comment by sethladd** [comment]
Can we not fail the build if the upload fails?

**Comment by devoncarew** [comment]
Yup, we can do that.

**Comment by sethladd** [comment]
Full of goodness.

**Comment by devoncarew** [comment]
https://travis-ci.org/dart-lang/dartdoc/jobs/83717609

**Comment by devoncarew** [comment]
We need to guard against upload timeouts.
