### ISSUE TITLE
Exported classes don't have any indication where they come from

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dartdoc#936]
When a class is exported, then it should be visible where that class comes from.
For example, the Rectangle class in dart:html is just a reexport from dart:math:
`export 'dart:math' show Rectangle, Point;`
Currently it is not visible that this relationship exists (which means that it is, for example, not possible to know that html.Point is assignable to math.Point).

https://api.dartlang.org/1.12.1/dart-html/Rectangle-class.html

**Comment by sethladd** [comment]
Thanks for the feedback!

**Comment by jcollins-g** [comment]
The canonicalization system in dartdoc now makes these relationships much more clear by deduping the various instances and correctly rendering inheritance; please reopen if this still isn't clear.
