### ISSUE TITLE
abstract classes and factory constructors - qualifiers not part of docs

### ISSUE THREAD

**Issue by chalin** [dart-lang/dartdoc#937]
It seems to me that **dartdoc** generated documentation doesn't indicate whether a class is `abstract` (e.g., Iterator), or am I missing something? I believe that the abstract qualifier was being output when dartdoc was in beta at some point. What was the rationale for removing it? It seems to me that it is useful to know whether a class is abstract or not.

Likewise, it would be useful to know (in the documentation) if a constructor is a `factory` or a generative constructor. Again, was there a rational for not indicating this in the documentation?

Cf. https://groups.google.com/a/dartlang.org/d/msg/misc/Hs0vyln6PfA/pZLUHB_FAwAJ

**Comment by sethladd** [comment]
re: abstract, that makes sense. We should add that.

re: factory constructor: curious, why does that matter? From a user's perspective, they don't know if it's a factory or not.

thanks for the feedback!

**Comment by chalin** [comment]
E.g., whether a superclass constructor is generative or a factory can affect how you write subclass constructors:
```dart
class P {
  P.one() {}
  factory P.two() => ...
}

class C extends P {
  C.one() : super.one(); // ok P.one() is generative
  C.two() : super.two(); // error P.two() is a factory.
}
```
Also, e.g., factory constructors can return `null`; generative constructors always return (non-null) fresh instances.

**Comment by sethladd** [comment]
> whether a superclass constructor is generative or a factory can affect how you write subclass constructors

Good point!

**Comment by chalin** [comment]
+1 for adding fix for `const` constructor qualifier too.
