### ISSUE TITLE
issues with the `implements` class summary item`

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#938]
The `Implements` class summary item doesn't hyper-link to class names, and doesn't always output text for an item. The docs for ModelElement show this:

https://dartdoc.firebaseapp.com/dartdoc/ModelElement-class.html

<img width="327" alt="screen shot 2015-10-04 at 3 43 46 am" src="https://cloud.githubusercontent.com/assets/1269969/10267452/31fb91be-6a4a-11e5-89b7-318f2eeb8521.png">

Note that there are 3 interfaces for ModelElement, but only 2 are listed, and neither are hyperlinked, even though the things in `Implemented by` just below it are.

**Comment by sethladd** [comment]
Good catch!

**Comment by keertip** [comment]
Looks like this is an issue only with the docs for dartdoc. Don't see the same problem with the test_package or the sdk docs.
