### ISSUE TITLE
Ensure: Show upper bound of type parameter in generic

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#94]
Was https://code.google.com/p/dart/issues/detail?id=16294

See https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:math.Point

Source: https://github.com/dart-lang/bleeding_edge/blob/80988a506bdf74d2e87bf0d7e1211d035c2e5624/dart/sdk/lib/math/point.dart

Actual: `Point<T> class`

Expected: `Point<T extends num> class`

**Comment by keertip** [comment]
dartdoc does not show the generic in the class information for Point. Have to check for other cases.

**Comment by keertip** [comment]
Can't check if dartdoc does the right thing here, blocked on #569
