### ISSUE TITLE
Why do you truncate the details on the *-class.html pages (and others) so aggressively?

### ISSUE THREAD

**Issue by astashov** [dart-lang/dartdoc#940]
Hi!

Why do you guys truncate the details on the *-class.html pages so aggressively? Example:
https://api.dartlang.org/1.12.1/dart-core/String-class.html

![image](https://cloud.githubusercontent.com/assets/12795/10270092/9486c08e-6aad-11e5-8d21-624c9b9eaf93.png)

E.g. I often use documentation of a class to find out some method, which will be useful for my task. So, I read through all of them, to find out what suits my needs most. Here, the method descriptions are so truncated, so I have to click to every method name, which leads me to another page, which has 3-4 lines of text more than I had on the index page. So, I have to do a lot of back-n-forth while I'm reading the class docs. That's not the perfect UX, IMHO.

What about we increase the truncation limit to some large number, like 100000 characters? It will cut the extreme cases with megabytes of documentation for some crazy method, but for most of the classess/methods with 5-10 lines of documetation it will work just fine, and will drastically increase the dartdocs UX.

What do you think?

**Comment by sethladd** [comment]
What you see is we're showing the first line (the summary). Dartdocs are typically written with a single summary line as the first paragraph.

The ellipsis was added in response to user feedback that they wanted to see that there are more docs. We're not truncating a line, though it kind of looks like we are, unfortunately.

Perhaps we can add a way to "open up" additional docs on this page. That way, if you want to see more, you can. But we default to only displaying the first line.

How does that sound?

**Comment by astashov** [comment]
> Perhaps we can add a way to "open up" additional docs on this page. That way, if you want to see more, you can. But we default to only displaying the first line.

That's better, but I still don't quite understand why not to show just everything. [Ruby](http://ruby-doc.org/core-2.2.0/String.html) does that, as well as [Java](http://docs.oracle.com/javase/7/docs/api/java/lang/String.html) for example, also the previous version of DartDocs did that. It allows you to use just regular browser's Cmd+F for searching on the page, which is a big deal :) Just curious what's the reasoning regarding that UX decistion.

Also, what about changing triple dots at the end of the first line of the docs to something else? Looks really like truncating. Something like 'show more →' or something like this.

Thanks!

**Comment by astashov** [comment]
Ping? :)

**Comment by sethladd** [comment]
I think we're interested in a mock-up for a solution. Open to ideas!

**Comment by astashov** [comment]
Umm, sorry, but what does 'a mock-up for a solution' mean :)? You mean - a PR with the implementation of that?

**Comment by sethladd** [comment]
Yup! Or, screenshots.
