### ISSUE TITLE
library docs are empty for bleeding edge docs

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#943]
Hi,

Just noticed that all libraries on the api.dartlang.org/be page are undocumented.

![screen shot 2015-10-06 at 10 54 20 am](https://cloud.githubusercontent.com/assets/5479/10317341/b3fcb876-6c18-11e5-916c-8906cbd7c4b2.png)

Bug in dartdoc, or issue with the core SDK?

FWIW the dev channel does display docs for the library: https://api.dartlang.org/1.13.0-dev.5.0/index.html

**Comment by sethladd** [comment]
cc @keertip

**Comment by keertip** [comment]
The comments are there, but not showing up in dartdoc. Not sure if this is an issue with markdown or dartdoc itself. Will take a look.

**Comment by sethladd** [comment]
Thanks for taking a look!

I wonder what we can add to the build process as checks for these kind of conditions... like a base level of tests of the docs.

**Comment by keertip** [comment]
Figured out this is due to a change made to the analyzer sources in the sdk.  opened issue https://github.com/dart-lang/sdk/issues/24514

**Comment by sethladd** [comment]
Great find!

**Comment by keertip** [comment]
fixed in be!
