### ISSUE TITLE
please show signature at top of method docs

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/dartdoc#946]
The class doc shows method signatures like
`Map.fromIterable(iterable, {K key(element), V value(element)})`
example: https://api.dartlang.org/1.12.1/dart-core/Map-class.html
but when you click on the method, it doesn't show the signature at the top.
example: https://api.dartlang.org/1.12.1/dart-core/Map/Map.fromIterable.html
Instead it shows the source code at the bottom.
(1) I don't really want to see the source code.
I mean, it's fine if I have a link to it, but I'm really here for documentation.
Source code has all kinds of distracting garbage, like the word 'factory', an equals sign,
the implementation, not to mention worse syntax highlighting and less links.
(2) The source code is often below the fold (i.e. you can't see it unless you scroll down),
it certainly is for Map.fromIterable.  I want to see the signature prominently at the top,
and in the same format as on the class summary page, e.g.
where return types are shown like -> R.

**Comment by sethladd** [comment]
cc @devoncarew 

I would agree that a formal signature at the top of the method is a useful thing.

**Comment by keertip** [comment]
@devoncarew, what do you think? It does look cleaner without the signature, but we don't want to lose out on ease of use.

**Comment by devoncarew** [comment]
For undoc'd methods it seemed like lots of duplication (esp. w/ the name already on the page in another place). Much of the same information was repeated 3 times in close proximity on the pafe. I agree that it would help for for methods that do have docs. Not sure if there's a compromise or if we should just bring back the method sig.

**Comment by sethladd** [comment]
Just ran into this issue myself. Check out https://api.dartlang.org/134069/dart-isolate/Isolate/spawnUri.html

**Comment by sethladd** [comment]
@devoncarew mind if we add it back to the top until we find something better?

**Comment by devoncarew** [comment]
Makes sense re: adding it back in.
