### ISSUE TITLE
Slashes in doc output

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#947]
Doc: https://api.dartlang.org/134062/dart-developer/Timeline-class.html

Source: https://github.com/dart-lang/sdk/blob/master/sdk/lib/developer/timeline.dart

![screen shot 2015-10-08 at 8 01 16 am](https://cloud.githubusercontent.com/assets/5479/10370236/c8a75260-6d92-11e5-82f9-4f53cb07a392.png)

Expected: no slashes in the doc output
Actual: `Start a synchronous operation labeled name. Optionally takes /// a Map of arguments. `

**Comment by sethladd** [comment]
cc @keertip

**Comment by keertip** [comment]
Looks like this is due to a change in the analyzer - it is returning the comment with whitespace before the slashes, which is why the slashes don't get stripped out.

opened issue https://github.com/dart-lang/sdk/issues/24561

**Comment by sethladd** [comment]
cc @johnmccutchan we believe we know why this is happening now
