### ISSUE TITLE
Provide better warning messages when a library lacks top level documentation

### ISSUE THREAD

**Issue by ArgentiApparatus** [dart-lang/dartdoc#949]
Currently dartdoc issues a warning if a library lacks top level documentation. E.g.

    C:\Users\...\foo> dartdoc
    Generating documentation for 'foo' into C:\Users\...\foo\doc\api\

    parsing lib\foo.dart...
    Parsed 1 file in 5.7 seconds.

    generating docs for library foo from foo.dart...
    warning: library 'foo' has no documentation
    Documented 1 library in 6.4 seconds.

    Success! Open file://C:\Users\...\foo\doc\api/index.html

It does this even if the library contains functions or classes that do have documentation. This may lead a user to conclude that dartdoc failed to find any documentation in the library and skipped it entirely.

Perhaps the warning should read 'library 'foo' has no top level documentation' ?

**Comment by devoncarew** [comment]
> 'library 'foo' has no top level documentation' 

makes sense to me!

**Comment by devoncarew** [comment]
Here's the location if you want to send a PR:

https://github.com/dart-lang/dartdoc/blob/239b0a0dae1ca8ac76deab576580205590321946/lib/src/html_generator.dart#L295

**Comment by sethladd** [comment]
I'm not sure what "top level documentation" means.

How about "Library 'foo' does not have associated doc comments" ?

**Comment by ArgentiApparatus** [comment]
This may well be an exercise in semantic hair splitting, and far too much effort expended for a single warning message, but:

To me, if library contain a class, function, constant or any other construct that is documented, than that library 'has associated doc comments'.

How does one refer to the doc comments for the library itself rather than the library and its contents?

**Comment by sethladd** [comment]
"Library 'foo' itself does not have comments"

How's that?

**Comment by keertip** [comment]
:+1:

**Comment by ArgentiApparatus** [comment]
That's good.

**Comment by sethladd** [comment]
Great! Patches welcome :)

**Comment by ArgentiApparatus** [comment]
Better warning message when library lacks documentation comments #950

**Comment by sethladd** [comment]
Thanks!
