### ISSUE TITLE
Ensure: handle one or more unnamed libraries in a package

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#95]
Assume we are generating docs for an unnamed library. Ensure all the file names and links are correct and that no assumptions are made by the tool.

Was https://code.google.com/p/dart/issues/detail?id=16769

**Comment by keertip** [comment]
verfied.

**Comment by sethladd** [comment]
Curious, did we try it with multiple anonymous libraries in one package?

**Comment by keertip** [comment]
@sethladd, missed that. Will check for multiple anonymous libraries.

**Comment by keertip** [comment]
Does not work for one than one anonymous library.

**Comment by devoncarew** [comment]
One option is to identify libraries by their path rather than their library name. The path might be more familiar to developers looking at the source, and is guaranteed to be unique and exist (unlike the library name).

**Comment by sethladd** [comment]
Could we ever document two anonymous libraries that have the same filename?

**Comment by keertip** [comment]
You cannot have two anonymous libraries with the same filename in the same directory. We should check that case where they are in different directories, though if the library is private, dartdoc does not generate docs for it.

**Comment by sethladd** [comment]
Thanks for the confirmation.
