### ISSUE TITLE
Feedback: search should make it clear if there are more results

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#955]
Specific feedback from https://github.com/dart-lang/dartdoc/issues/920

"It is not clear that the presented methods are a subset of what is available."

cc @rakudrama

**Comment by kwalrath** [comment]
Yes, please. There should be an option for a search results page. For example:

1. Go to https://www.dartdocs.org/documentation/flutter/0.0.32-dev/cupertino/cupertino-library.html. You can see there's an Animatable class there.
2. Enter Animatable in the Search box.

You're offered only a few results, all in the animation lib, not the cupertino lib. (You can't even tell that none of the results are from the current lib, though, unless you click them.)

**Comment by keertip** [comment]
With the new search experience, the user can get to all the results with a search results page. The page also there is a shows the number of results.
