### ISSUE TITLE
Allow specifying Markdown reference URLs anywhere in a Dart file

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#959]
Specifically for [html_dartium.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/dartium/html_dartium.dart), it would be great if you could specify reference urls at the bottom of the doc, like:

```dart
/**
 * [webgl-fundamentals]: http://www.html5rocks.com/en/tutorials/webgl/webgl_fundamentals/
 * [image-smoothing]: http://www.whatwg.org/specs/web-apps/current-work/multipage/the-canvas-element.html#image-smoothing
 */
```

so that any Dartdoc comment on any identifier within the file can use those reference URLs. Would this be possible?

**Comment by sethladd** [comment]
Thanks for the feedback. Why not just add these to the doc comment block that mentions the links? In other words, what problem does this fix?

**Comment by srawlins** [comment]
Thanks @sethladd, this would be useful when multiple dartdocs in one Dart file reference the same links over and over again. [html_dartium.dart](https://github.com/dart-lang/sdk/blob/master/sdk/lib/html/dartium/html_dartium.dart) shows the real use case; For example, there are no fewer than 31 methods with dartdocs that link to http://www.whatwg.org/specs/web-apps/current-work/multipage/dnd.html#dnd.

If we could specify this reference URL once (maybe at the very top, or the very bottom), these docs could really be cleaned up.

You could imagine other libraries where many methods reference the same links repeatedly.

**Comment by sethladd** [comment]
Open to ideas on how to do this. But I don't want to make a change until we learn more about how the html_*.dart files will be generated in the future.

**Comment by srawlins** [comment]
Fair enough. I'm curious as well :smile: .

I *think* this shouldn't be too hard, without knowing how this package parses doc comments: package:markdown's [`markdownToHtml()`](https://github.com/dart-lang/markdown/blob/master/lib/src/html_renderer.dart#L15..L36) convenience method shows how Markdown parsing is usually a two-pass system: first search for Reference links (`document.parseRefLinks(lines);`), and then parse the actual Markdown, with the reference URLs known. It might take a simple fix in package:markdown to, say, extract refLinks from one `Document` and inject them into another, or something. I'd be willing to do the work if we want to go forward with this.

I'll leave this here until dart-lang/sdk#23601 is resolved.

**Comment by srawlins** [comment]
OK I'll close this. The use case is very very very specific to this one use case.

In regards to @sethladd's comment:

> "... until we learn more about how the html_*.dart files will be generated in the future."

I found out that the dart:html package is generated from a `docs.json` file in the SDK, as well as a number of `.darttemplate` files. I don't think that process lends itself either way to deciding if this issue is a good idea.
