### ISSUE TITLE
Indented code blocks don't seem to be respected

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dartdoc#966]
See [ListMixin.replaceRange](https://api.dartlang.org/133561/dart-collection/ListMixin/replaceRange.html). The line starting with `List<int> list` should be a code block, but is just a paragraph. The [source](https://github.com/dart-lang/sdk/blob/master/sdk/lib/core/list.dart#L446) for this comment is:

```dart
/**
 * Removes the objects in the range [start] inclusive to [end] exclusive
 * and inserts the contents of [replacement] in its place.
 *
 *     List<int> list = [1, 2, 3, 4, 5];
 *     list.replaceRange(1, 4, [6, 7]);
 *     list.join(', '); // '1, 6, 7, 5'
 *
 * An error occurs if [start]..[end] is not a valid range for `this`.                                                                                       *
 * This method does not work on fixed-length lists, even when [replacement]
 * has the same number of elements as the replaced range. In that case use
 * [setRange] instead.
 */
```

Which seems properly formatted.

Another example is [ListMixin.asMap](https://api.dartlang.org/133561/dart-collection/ListMixin/asMap.html).

**Comment by srawlins** [comment]
I think I've figured this one out: This is only for overridden members, (like ListMixin.replaceRange, which overrides List.replaceRange): in [ModelElement.documentation](https://github.com/dart-lang/dartdoc/blob/master/lib/src/model.dart#L157..L174), we call `_rawDocs = overrideElement.documentation`, then `_rawDocs = stripComments(_rawDocs)`.

So first we're stripping comments on `List.asMap() → Map<int, E>`. Then we're stripping comments on `ListMixin.asMap() → Map<int, Int64>`, but they've already been stripped, which trims the left of every line.

**Comment by sethladd** [comment]
cc @keertip on the fix.

Is this something we want to get into 1.13?
