### ISSUE TITLE
Put constructors above properties in a class page

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#978]
When you look at a class description, for example:
   https://domokit.github.io/docs/sky/rendering/RenderBlock-class.html
...the first thing you need to know is how to create an instance of the class.

Thus, constructors should come before properties.

**Comment by sethladd** [comment]
I would agree.

cc @devoncarew any thoughts?

**Comment by devoncarew** [comment]
I'm used to ordering a class:
- static fields
- static methods
- fields
- ctors
- methods

from other languages. Dartdoc should probably mirror the order used in typical dart files. I don't know if there is one canonical ordering for members. Open to changes -

**Comment by sethladd** [comment]
The ordering in the class's text file may not be the ordering in how a user _uses_ the class. I think the docs shouldn't try to mimic source code order, especially if there's a more useful ordering when reading the docs. For example, we already alphabetize names when displaying in the docs.

**Comment by keertip** [comment]
We should do what helps the user find the info they are looking for more easily - less scroll and search.

**Comment by Hixie** [comment]
FWIW, the order in the Flutter style guide is constructor, then methods and fields grouped in whatever order makes sense, with methods roughly in the order they're likely to be executed during normal program flow.

I'm not proposing using that order. I'm not proposing using the source order. I'm just saying that when I look at this page:

   https://domokit.github.io/docs/sky/rendering/RenderBlock-class.html

...seeing two pages' worth of properties, many of which are internal details that really are only there because we don't have "protected" visibility, and many of which are inherited, is not at all useful. The thing that's most useful for dealing with that class is the constructor.

I do think grouping properties, methods, operators, constructors, etc, together makes a lot of sense. (I'd probably group "properties" separate from "properties whose type is a typedef", but that's a separate thing.) I think the current order by and large makes sense, except for constructors being second.

**Comment by kevmoo** [comment]
+1 for ctors first.

**Comment by sethladd** [comment]
Okey dokey. Help Wanted! :)

**Comment by sethladd** [comment]
Thanks!
