### ISSUE TITLE
Extraneous "///" markers in Flutter's AbstractNode.depth documentation

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#979]
Extraneous "///" markers are visible here:
   https://domokit.github.io/docs/sky/rendering/AbstractNode/depth.html

As far as I can tell, there's nothing wrong with the dartdocs in the source:
   https://github.com/flutter/engine/blob/master/sky/packages/sky/lib/src/rendering/node.dart

**Comment by keertip** [comment]
Fixed in dev 1.13-dev7.1 or use `pub global activate` to get latest version.

**Comment by Hixie** [comment]
Yup, thanks!
