### ISSUE TITLE
Class pages should have an affordance to show/hide inherited members

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#980]
When you look at this page, as a seasoned user of the rendering library:
   https://domokit.github.io/docs/sky/rendering/RenderSizeObserver-class.html
...what you really want to know is "what is special about RenderSizeObserver". It turns out, that class has two things that are special: a constructor, and a callback property. Everything else is either inherited or overridden.

It would be great if you could hide members that are just inherited. Bonus points if you can also show or hide those that are overriding something from the base class.

**Comment by sethladd** [comment]
Agreed! Dupe, will close this one. Thanks for the feedback!

**Comment by sethladd** [comment]
Agreed! Dupe, will close this one. Thanks for the feedback!
