### ISSUE TITLE
Annotate members that override members from a superclass

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#981]
It would be great if on a page like the following, members that are defined in this class but override a member from a superclass were annotated as "override", the same way inherited members are annotated as "inherited".

https://domokit.github.io/docs/sky/rendering/RenderSizeObserver-class.html

**Comment by jcollins-g** [comment]
Given that @override annotations now show up in the feature list where 'inherited' does when those are used (and it seems to be increasingly Dart-standard to use them) I'm going to drop this a bit in priority.

To be clear, I'm interpreting this as adding an "override" to the feature list under the conditions @Hixie listed and using that to replace the @override annotation.
