### ISSUE TITLE
add 0.7.3 to dart sdk

### ISSUE THREAD

**Issue by keertip** [dart-lang/dartdoc#988]
0.7.3 uses a `stack_trace 1.4.2` which is not on the bots. This and other dependent packages have to be upgraded to get `dartdoc` in the sdk.

**Comment by kevmoo** [comment]
https://github.com/dart-lang/sdk/commit/395f25502315b65ba1f9d4f5e7cd2764706ca82b
https://github.com/dart-lang/sdk/commit/439693be6a8a411b9da6c1ba90a8c43e2f2b8916

Done with these!
