### ISSUE TITLE
Fields with comments show up – weird

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#989]
https://api.dartlang.org/1.13.0-dev.7.2/dart-io/HttpServer/autoCompress.html

It's defined as a field

```
   /**
   * Whether the [HttpServer] should compress the content, if possible.
   *
   * The content can only be compressed when the response is using
   * chunked Transfer-Encoding and the incoming request has `gzip`
   * as an accepted encoding in the Accept-Encoding header.
   *
   * The default value is `false` (compression disabled).
   * To enable, set `autoCompress` to `true`.
   */
  bool autoCompress;
```

It shows up as an undocumented field plus a weird operator-looking thing on `0.7.3`

![screen shot 2015-10-22 at 12 48 27 pm](https://cloud.githubusercontent.com/assets/17034/10676494/6cca4ea0-78bb-11e5-8bfe-83450668d559.png)

Clearly a regression https://api.dartlang.org/1.12.2/dart-io/HttpServer/autoCompress.html

**Comment by sethladd** [comment]
Good catch, thanks! Sorry we didn't have a test for that.

**Comment by kevmoo** [comment]
Dart 1.12.1 + dartdoc @ 8c83c7b : fine – note, this is using the checked-in pubspec dependencies

**Comment by kevmoo** [comment]
Dart 1.12.1 + dartdoc @ 8c83c7b w/ **upgraded dependencies** analyzer 0.26.1+14 (instead of 0.26.0) – BROKEN.

Seems like this is a regression w/ the analyzer API

**Comment by keertip** [comment]
@kevmoo , thanks for the info.

**Comment by sethladd** [comment]
is there a corresponding issue on the analyzer?

**Comment by keertip** [comment]
Still investigating, but does not look like an analyzer issue.

**Comment by keertip** [comment]
Looking at https://api.dartlang.org/134467/dart-io/HttpServer-class.html#instance-properties, there is the one liner documentation comment for `autoCompress`. But does not show up in the properties page.

**Comment by kevmoo** [comment]
Look at the template for properties. It assumes getter and setter – which I think means field-only doc comments are skipped.

**Comment by keertip** [comment]
Yup, figured that out. Looking to fix it so that it works in all cases.

**Comment by sethladd** [comment]
Ah, good find.

**Comment by sethladd** [comment]
Thanks!!
