### ISSUE TITLE
Ensure: References to generic types in comments are linked correctly

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#99]
Was https://code.google.com/p/dart/issues/detail?id=16771

A comment of the form 

```
/// This can be either a [List<int>] or a [String].
```

gets parsed as a reference to #dart-core in docgen.

A workaround is to use

```
/// the somewhat awkward [List]<int>
```

or even

```
/// the even more so [List]<[int]>
```

**Comment by keertip** [comment]
The analyzer is not able to resolve references in comments with generics. Opened issue dartbug.com/23427.

**Comment by sethladd** [comment]
Blocked by https://github.com/dart-lang/sdk/issues/23427

**Comment by jcollins-g** [comment]
With exceptions noted in other bugs, this should work correctly now.
