### ISSUE TITLE
Some instance comments are ignored

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#990]
In [the shelf documentation](http://www.dartdocs.org/documentation/shelf/0.6.3%2B1/shelf/Request-class.html), there seems to be no documentation displayed for the `context`, `handlerPath`, `headers`, `method`, `protocolVersion`, `requestedUri`, or `url` fields. All of these are [well-documented](https://github.com/dart-lang/shelf/blob/master/lib/src/request.dart) in the source. It's not clear what makes these members different from the others.

Marking as P1 since randomly dropping documentation seems very bad. Also, some of these fields for shelf in particular have documentation that conveys important information about how they *shouldn't* be used, so having those docs unavailable is very bad.

**Comment by kevmoo** [comment]
Smells a bit like https://github.com/dart-lang/dartdoc/issues/989

**Comment by sethladd** [comment]
cc @keertip

**Comment by kevmoo** [comment]
Resolved with https://github.com/dart-lang/dartdoc/pull/996

**Comment by sethladd** [comment]
Thanks!!
