### ISSUE TITLE
Don't print "library has no documentation"

### ISSUE THREAD

**Issue by nex3** [dart-lang/dartdoc#998]
It's a strong pub convention for packages to have a "primary" library—a library with the same name as the package that serves as the primary entrypoint for users. It usually doesn't make sense to provide documentation for this library, since it's just (more or less) everything in the package. [Docgen handled this gracefully](http://www.dartdocs.org/documentation/json_rpc_2/1.2.0/#json_rpc_2/json_rpc_2) by simply not printing anything for undocumented libraries, but [Dartdoc prints an unsightly "*Not documented*" message](http://www.dartdocs.org/documentation/shelf/0.6.4/shelf/shelf-library.html). It should instead just not print anything, or maybe print some template text like "The primary library for $packageName."

**Comment by sethladd** [comment]
Thanks for the suggestion.

What do you mean "not printing anything for undocumented libraries" ? Do you not want to see the primary library listed at the root of the docs? Or, you just don't want to see "Not documented" ?

**Comment by nex3** [comment]
> Or, you just don't want to see "Not documented" ?

This one.

**Comment by sethladd** [comment]
Thanks!
